### ISSUE TITLE
Feature Request: Resumable Download

### ISSUE THREAD

**Issue by leeyuky9802** [abraunegg/onedrive#2898] opened 2024-10-09 15:59 UTC
### Is your feature request related to a problem? Please describe.

Yes, when downloading large files, a std.net.curl.CurlException resets the download and starts from the begining.

I carefully searched through docs and only found about resumable upload.

> Oct 09 07:54:23 nuc onedrive[1276]: Downloading file: 20241008-074458.mp4 ... done
Oct 09 07:54:11 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 100% | DONE in 00:03:20
Oct 09 07:54:00 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 95%  |  ETA    00:00:10
Oct 09 07:53:54 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 90%  |  ETA    00:00:21
Oct 09 07:53:48 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 85%  |  ETA    00:00:32
Oct 09 07:53:38 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 80%  |  ETA    00:00:42
Oct 09 07:53:24 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 75%  |  ETA    00:00:51
Oct 09 07:53:16 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 70%  |  ETA    00:01:03
Oct 09 07:53:07 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 65%  |  ETA    00:01:14
Oct 09 07:53:02 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 60%  |  ETA    00:01:28
Oct 09 07:52:56 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 55%  |  ETA    00:01:43
Oct 09 07:52:48 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 50%  |  ETA    00:01:57
Oct 09 07:52:40 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 45%  |  ETA    00:02:14
Oct 09 07:52:33 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 40%  |  ETA    00:02:33
Oct 09 07:52:26 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 35%  |  ETA    00:02:57
Oct 09 07:52:09 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 30%  |  ETA    00:03:02
Oct 09 07:51:53 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 25%  |  ETA    00:03:06
Oct 09 07:51:38 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 20%  |  ETA    00:03:08
Oct 09 07:51:24 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 15%  |  ETA    00:03:07
Oct 09 07:51:16 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 10%  |  ETA    00:03:45
Oct 09 07:51:06 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 5%   |  ETA    00:04:45
Oct 09 07:50:54 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 0%   |  ETA    --:--:--
Oct 09 07:50:51 nuc onedrive[1276]: Retrying the respective Microsoft Graph API call for Internal Thread ID rBPApbOUFZa3xCj1 (Timestamp: 2024-Oct-09 12:50:51) ...
Oct 09 07:50:49 nuc onedrive[1276]:  Next retry in approx:   2 seconds
Oct 09 07:50:49 nuc onedrive[1276]:   Line number:      786
Oct 09 07:50:49 nuc onedrive[1276]:   Calling Function: onedrive.OneDriveApi.downloadById
Oct 09 07:50:49 nuc onedrive[1276]:   Error Message:    Failure when receiving data from the peer on handle 55B8E7836230
Oct 09 07:50:49 nuc onedrive[1276]: ERROR: Encounter std.net.curl.CurlException:
Oct 09 07:48:50 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 10%  |  ETA    00:43:21
Oct 09 07:46:22 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 5%   |  ETA    00:44:39
Oct 09 07:44:03 nuc onedrive[1276]: Downloading: 20241008-074458.mp4 ... 0%   |  ETA    --:--:--

### Describe the solution you'd like

Curl set retry

### Describe alternatives you've considered

reuse local .partial files

**Comment by abraunegg** [comment] 2024-10-09 18:23
Duplicate of https://github.com/abraunegg/onedrive/issues/2576

**Closed by abraunegg** 2024-10-09 18:23 UTC
Labels: Feature Request

**Comment by abraunegg** [comment] 2024-10-09 18:26
@leeyuky9802 
>```
> Oct 09 07:50:49 nuc onedrive[1276]: Next retry in approx: 2 seconds
> Oct 09 07:50:49 nuc onedrive[1276]: Line number: 786
> Oct 09 07:50:49 nuc onedrive[1276]: Calling Function: onedrive.OneDriveApi.downloadById
> Oct 09 07:50:49 nuc onedrive[1276]: Error Message: Failure when receiving data from the peer on handle 55B8E7836230
> Oct 09 07:50:49 nuc onedrive[1276]: ERROR: Encounter std.net.curl.CurlException:
> ```

This error *also* indicates you are using a *known* broken curl version ... please read https://github.com/abraunegg/onedrive/blob/master/docs/usage.md#compatibility-with-curl very carefully and *implement* the changes on your platform which will assist with this problem.

**Comment by abraunegg** [comment] 2024-10-17 01:54
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
