### ISSUE TITLE
Feature Request: Multi-threadded synchronization 

### ISSUE THREAD

**Issue by ricperry** [abraunegg/onedrive#2716] opened 2024-05-06 14:42 UTC
### Is your feature request related to a problem? Please describe.

It's currently extremely slow to synchronize an account to a new computer. I have over 600gb and over 100,000 files that need to be downloaded. Also the bandwidth utilization is very low, as there seems to be significant processing time between each file downloaded.

### Describe the solution you'd like

Multithreadded synchronization (the way Conda can download multiple packages at a time). Also, enqueue more than 1 file at a time on initial sync.

### Describe alternatives you've considered

Gnome 46 microsoft365 account isn't working on Ubuntu 24.04 (I keep getting disconnected). I've also installed OneDriveGUI, but it doesn't seem compatible with Ubuntu 24.04 even though it's supposedly compatible with the version of onedrive (2.4.25) that I'm using.

**Comment by abraunegg** [comment] 2024-05-06 19:19
@ricperry 
This has *already* been implemented and is a duplicate of #232 

Please read:
* https://github.com/abraunegg/onedrive/issues/232
* https://github.com/abraunegg/onedrive/releases/tag/v2.5.0-rc2

>  I've also installed OneDriveGUI, but it doesn't seem compatible with Ubuntu 24.04 even though it's supposedly compatible with the version of onedrive (2.4.25) that I'm using.

Regarding the GUI - you need to raise your issue here: https://github.com/bpozdena/OneDriveGUI

There are 2 versions of the GUI. One that supports v2.4.25 - https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.0.3 and one that supports v2.5.0 - https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0rc1

**Closed by abraunegg** 2024-05-06 19:19 UTC
Labels: Feature Request

**Comment by abraunegg** [comment] 2024-05-14 01:33
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
