### ISSUE TITLE
No network connection to Microsoft OneDrive Service

### ISSUE THREAD

**Issue by Philipp0205** [abraunegg/onedrive#507] opened 2019-05-22 17:38 UTC
Hey,
everything worked perfectly until a few days ago. Then it just sopped syncing.

I tried a reinstall, now the following happens on the first start:

```
philipp@philipp:~$ onedrive
No network connection to Microsoft OneDrive Service

```
systemctl --user status onedrive.service gives following: 
```
philipp@philipp:~$ systemctl --user status onedrive.service
 onedrive.service - OneDrive Free Client
   Loaded: loaded (/usr/lib/systemd/user/onedrive.service; disabled; vendor pres
   Active: inactive (dead)
     Docs: https://github.com/abraunegg/onedrive

```

Thanks in advance!

**Comment by abraunegg** [comment] 2019-05-22 19:05
@Philipp0205 
This should be pretty clear as to why it is not working:
```
No network connection to Microsoft OneDrive Service
```

Can you test if you can login via a browser to OneDrive from your Linux system? Can you reach the service?

Have you changed your OneDrive account password? If yes, you need to stop any service, then issue a `onedrive --logout` command to re-authorise.

**Comment by Philipp0205** [comment] 2019-05-22 19:22
Ty!

nslookup does work

curl prints the folowing:

```
philipp@philipp:~$ curl https://login.microsoftonline.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

The logout command prints the no-connection-error too.

Via browser everything works fine!  I did not change the password.

**Comment by abraunegg** [comment] 2019-05-22 19:32
You have some sort of HTTPS inspection between you and Microsoft.

You have not added to your Linux system the root CA of the SSL inspection service. What this means is that your Linux system cannot validate the SSL certificate being used.

You need to fix your CA certificates on your Linux system.

**Comment by abraunegg** [comment] 2019-05-22 19:32
Closing as not a bug. local environmental issue.

**Closed by abraunegg** 2019-05-22 19:32 UTC
Labels: Answer Provided, Local Environment Issue, Not a bug
