### ISSUE TITLE
Bug: Environment variable "ONEDRIVE_NOREMOTEDELETE" not working

### ISSUE THREAD

**Issue by fthoma-coding** [abraunegg/onedrive#2470] opened 2023-08-14 15:48 UTC
### Describe the bug

I have the client running within docker (docker compose) and everything working like expected. After remove the sync directory, i have noticed, that the online content was deleted. This behavior is described at the wiki.
To disable the deletions i have added the environment variable "ONEDRIVE_NOREMOTEDELETE" and set it to 1. But after a second test i have noticed, that the deletions happend again.
To check the config, I used the environment variable "ONEDRIVE_DISPLAY_CONFIG". At the output i can see, that the environment variable "ONEDRIVE_NOREMOTEDELETE" is not used.

  test-upload:
    image: driveone/onedrive:2.4.25
    container_name: test-upload
    hostname: test-upload
    domainname: ***
    restart: unless-stopped
    environment:
        TZ: "Europe/Berlin"
        ONEDRIVE_UID: 1000
        ONEDRIVE_GID: 1000
        ONEDRIVE_NOREMOTEDELETE: 1
        ONEDRIVE_UPLOADONLY: 1
        ONEDRIVE_SINGLE_DIRECTORY: test
        ONEDRIVE_DISPLAY_CONFIG: 1
    volumes:
        - ./ondrive-config:/onedrive/conf
        - ./downloads:/onedrive/data/test

Base Args: --monitor
- We are synchronizing in upload-only mode
- Adding --upload-only
- We are printing the application running configuration at application startup
- Adding --display-running-config
- We are synchronizing in single-directory mode
- Adding --single-directory ARG
- Launching onedrive
Configuration file successfully loaded
--------------- Application Runtime Configuration ---------------
onedrive version                             = v2.4.25
Config path                                  = /onedrive/conf
...
Config option 'upload_only'                  = true
Config option 'no_remote_delete'         = false

### Operating System Details

```shell
Docker container vs docker compose
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

v2.4.25

### What is your OneDrive Application Configuration

```shell
Described at the top
```

### What is your 'curl' version

```shell
docker
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
Docker mount local volume
```

### What are all your local file system partition types

```shell
---
```

### How do you use 'onedrive'

---

### Steps to reproduce the behaviour

---

### Complete Verbose Log Output

```shell
---
```

**Comment by abraunegg** [comment] 2023-08-14 19:34
@fthoma-coding 
I am sorry but this is *not* a bug or issue.

As per the documentation: https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md

![image](https://github.com/abraunegg/onedrive/assets/4956234/e4b883b2-97de-4cf0-a2a8-237bb2c79866)

The feature you are *trying* to use was added *post* v2.4.25 release, so in order to use this Docker flag, you need to use the 'edge' Docker container. Please read: https://github.com/abraunegg/onedrive/compare/v2.4.25...master

Closing issue as not a bug.

**Closed by abraunegg** 2023-08-14 19:34 UTC
Labels: Bug

**Comment by abraunegg** [comment] 2023-08-22 01:25
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
