### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by mascreativa** [abraunegg/onedrive#607] opened 2019-07-30 17:56 UTC
Hi, I have not been able to synchronize due to connection problems with endpoint. I tried onedrive --logout a couple of times, recreating the new endpoint url

**Application and Operating System Details:**
*   OS: Linux grupodtg01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*   I'm using CLI
*   OneDrive Account Type: Personal
*   DMD or LDC compiler version: DMD64 D Compiler v2.087.0
*   Application configuration: 
```
onedrive version                    = v2.3.7-24-g8f71043
Config path                         = /home/grupodtg01/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/grupodtg01/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Sur de Chile 2010
Fotos
Imágenes
Documentos
Datos adjuntos
```
*   Curl Version: curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-2

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  execute onedrive --monitor

**Complete Verbose Log Output**
Application Log Output:
```bash
std.file.FileException@std/file.d(2028): /home/grupodtg01/OneDrive: Transport endpoint is not connected
----------------
/snap/dmd/72/bin/../import/phobos/std/file.d:272 @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x557a8b66f818]
??:? @safe uint std.file.getAttributes!(const(char)[]).getAttributes(const(char)[]) [0x557a8b6e048e]
??:? @property @safe bool std.file.isDir!(const(char)[]).isDir(const(char)[]) [0x557a8b6e03d7]
??:? @safe bool std.file.ensureDirExists!().ensureDirExists(scope const(char)[]) [0x557a8b6e0291]
??:? @safe void std.file.mkdirRecurse(scope const(char)[]) [0x557a8b6deee8]
src/main.d:271 _Dmain [0x557a8b6a2cd2]
```

**Comment by abraunegg** [comment] 2019-07-30 18:39
@mascreativa 
Please can you generate a debug log for support using the following [process](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) as this will assist with understanding what is going on.

My guess is here that there is something in regards to your local file system, and given that your using Ubuntu - something along the lines of maybe your Home directory might be encrypted. The debug log will provide some more insights however.

That the application fails because of this local issue does need to be fixed, but understanding what is going on is critical.

**Comment by abraunegg** [comment] 2019-07-30 20:13
@mascreativa 
Please can you test the following PR for resolving your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/608/head:pr608
git checkout pr608
make clean; ./configure; make;
```

This will catch the error that is generated when unable to create the local OneDrive sync directory, however why it is unable to do so - that will be a local file system issue which cannot be resolved by this client. Things to check:
* permissions
* mount permissions
* encryption

**Comment by abraunegg** [comment] 2019-07-30 23:12
Closing issue as email from user confirmed PR resolves issue

**Closed by abraunegg** 2019-07-30 23:12 UTC
Labels: Bug, Fixed, Local Environment Issue

**Comment by mascreativa** [comment] 2019-07-31 01:42
Thanks for the support, were the permissions to create Onedrive folder
