### ISSUE TITLE
Unable to exclude all files starting with dot ('.') using 'skip_file'

### ISSUE THREAD

**Issue by fonic** [abraunegg/onedrive#1091] opened 2020-10-08 13:25 UTC
### Bug Report Details ###
**Describe the bug**
I'm trying to exclude all files starting with a dot ('.') from syncing. However, onedrive refuses to start when adding `skip_file = ".*"` to the configuration. Logged error: `ERROR: Invalid skip_file entry '.*' detected`.

**Application and Operating System Details:**
*   Gentoo Linux (amd64, stable)
*   Linux Kernel 5.4.66
*   Headless
*   OneDrive version 2.4.5, package [net-misc/onedrive](https://gpo.zugaina.org/net-misc/onedrive)
*   dmd 2.087.1-r1
*   `sync_dir` is local directory (`~/OneDrive`)
*   Default config except for `skip_file = ".*"`

**To Reproduce**
1.  Add `skip_file = ".*"` to configuration
2.  Start onedrive
3.  Check log output

**Log Output**
```
2020-Oct-08 15:05:38.1198747    Notification (dbus) server not available, disabling
2020-Oct-08 15:05:38.7311767    Initializing the OneDrive API ...
2020-Oct-08 15:05:38.731361     Configuring Global Azure AD Endpoints
2020-Oct-08 15:05:38.7314052    Opening the item database ...
2020-Oct-08 15:05:38.7319824    All operations will be performed in: ~/OneDrive
2020-Oct-08 15:05:38.7320385    ERROR: Invalid skip_file entry '.*' detected
```

**Comment by abraunegg** [comment] 2020-10-08 17:43
@fonic 
This is not a bug or issue. Please re-read the [usage](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md) document, specifically:
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-the-client
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#configuration

**Comment by abraunegg** [comment] 2020-10-08 17:43
Closing issue, not a bug or issue.

**Closed by abraunegg** 2020-10-08 17:43 UTC
Labels: Not a bug

**Comment by fonic** [comment] 2020-10-09 08:53
Ok, thanks, but if you don't mind me asking: what `skip_files` settings can be used to exclude all dot files then?

**Comment by abraunegg** [comment] 2020-10-09 10:04
@fonic 
No 'skip_file' setting can be used. Please refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#skip_dotfiles

**Comment by fonic** [comment] 2020-10-09 10:06
Got it, thanks!
