### ISSUE TITLE
Monitor ends after 5 min

### ISSUE THREAD

**Issue by Drachenlaeufer** [abraunegg/onedrive#1520] opened 2021-06-22 10:21 UTC
### Bug Report Details ###
I upgraded from 2.4.11 to 2.4.12-10-g13b3709.
Before I could start "onedrive --monitor" and it did the job until I killed that process.
Now the process terminates after 5 minutes (maybe the 300s monitor_interval?).

**Application and Operating System Details:**
*   5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
*   run in xterm
*   from source via git
*   DMD64 D Compiler v2.095.1
*   OneDrive Application Version: 2.4.12-10-g13b3709
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.12-10-g13b3709
Config path                            = /home/alexander/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alexander/OneDrive
Config option 'skip_dir'               = Desktop|Documents|Pictures
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.74.0
*   Is your configured 'sync_dir' a local directory or a network mount point?
local

*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
ext4

**Comment by abraunegg** [comment] 2021-06-22 10:31
@Drachenlaeufer 
Do you have some console logging output / evidence of this 'exit' ? What is occurring when you use `--monitor --verbose` ?

This is *very* odd - and generally, will only exit from monitor in the following circumstances:
* Application crash
* Configuration using some of the developer options which are *not* documented

The 'monitor_interval' value has no bearing on application exit - it basically is a hold timer between checking the local disk / database contents & checking OneDrive online for new changes.

In fact - just to validate this - I have been running the client for the last 5 mins without issue, without exit, without problem ...

**Comment by Drachenlaeufer** [comment] 2021-06-22 11:44
"onedrive --monitor --verbose" ends just like

$ onedrive --monitor --monitor-interval 299 --verbose
(...)
Processing 48 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 01R5ZFWLN6Y2GOVW7725BZO354PWSELRRZ
$

If I reduce the interval then I get

$ onedrive --monitor --monitor-interval 75 --verbose
(... needs slightly more then 75s ...)
Processing 48 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
(...)
Sync with OneDrive is complete
(...)

So, when the process (checking files, ...) after starting needs more than monitor-interval, it continues to work, even the next repeating checks do not last that long.

Strange.

**Comment by abraunegg** [comment] 2021-06-22 20:13
@Drachenlaeufer 
This looks like that something does not like the TCP age time of idle TCP connections, and, if greater than that value - forcing the  TCP connection to be dropped - not honoring the actual TCP connection state.

It would be interesting to test all values from 75 -> 300 and see where this is breaking for you.

A couple of other things for you to try:

1. Upgrade your DMD compiler to 2.097.0
2. Replace your DMD compiler with LDC - `curl -fsS https://dlang.org/install.sh | bash -s ldc`

If you still encounter an issue, then please read this: https://github.com/abraunegg/onedrive/blob/master/docs/known-issues.md#application-stops-running-without-any-visible-reason

Perform HTTPS level debugging and determine what is going on at the HTTPS Transport layer. What does `echo $?` when the application exits as the error number?

Key points:
* Client users in Europe, connecting a MS DataCentre in Europe always seem to face this issue
* The issue points to Curl connection session being dropped by either Microsoft or your ISP or something in between

Use this then as evidence to:
* Fix your home Internet connection / router
* Get your ISP to fix their TCP connection handling
* Open a case with Microsoft

**Comment by abraunegg** [comment] 2021-06-23 22:51
@Drachenlaeufer 
Any update here regarding your investigations?

**Comment by Drachenlaeufer** [comment] 2021-06-24 09:13
Hi!
I upgraded the DMD compiler. ==> no difference.

I also tried different values for monitor interval:
200s -> OK
250s -> break
225s -> OK
240s -> break
239s -> break
235s -> OK
238s -> OK
239s -> OK !!! (repeated, cause I did not save debug output first)
240s -> OK !!!
250s -> break

Last 3 lines of debug output are:
* Too old connection (251 seconds), disconnect it
* Connection 1 seems to be dead!
* Closing connection 1

The same (with different times) I got for 239s, but could not repeat it. Break occurs always with the second (new) loop.

Actually I can use e.g. 200s ...
But I have not much influence on router or ISP settings.

**Comment by abraunegg** [comment] 2021-06-24 09:22
@Drachenlaeufer 
> Connection 1 seems to be dead!

So - this would imply that:
* Something between you and OneDrive is not honoring TCP state of the connection
* Some sort of man in the middle inspection going on break this for you

Unfortunately, this is not a bug, not an issue that I can solve.

If you are based in Europe, you need to take this up with your ISP & Microsoft and complain regarding this situation.

As such, I am closing this issue as not a bug - sorry, but this issue is 100% environmental.

**Closed by abraunegg** 2021-06-24 09:22 UTC
Labels: Invalid - Template Incomplete, More Information Needed, Waiting on Response

**Comment by Drachenlaeufer** [comment] 2021-06-24 10:13
Thanks a lot for your effort and your work on this great software!
