### ISSUE TITLE
SSL error "SSL peer certificate or SSH remote key was not OK " when trying to download the first file

### ISSUE THREAD

**Issue by doubleparadiddle** [abraunegg/onedrive#1599] opened 2021-08-12 08:59 UTC
Hello,

something seem not to work when it comes to download the first file:

### Bug Report Details ###
```
onedrive --synchronize --download-only --verbose
Using 'user' Config Dir: /home/thomas/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /media/root/ExternalDisk
Application version: v2.4.13-1~np1
Account Type: personal
Default Drive ID: 1a7840231b9a780c
Default Root ID: 1A7840231B9A780C!107
Remaining Free Space: 718810198347
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 1A7840231B9A780C!107
Updated Remaining Free Space: 718810198347
Processing 350 OneDrive items to ensure consistent local state
Downloading file Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png ... 
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    SSL peer certificate or SSH remote key was not OK on handle 5573BD4952B0
  Calling Function: download()
```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
->` Linux linuxPC 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed?
-> there is a GUI installed (GNOME)

*   OneDrive Account Type
-> Private

*   Did you build from source or install from a package?
Package (from https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_20.04/ ./)

*   OneDrive Application Version: Output of `onedrive --version`
-> v2.4.13-1~np1

*   OneDrive Application Configuration: Output of `onedrive --display-config`
->
```
configuration file successfully loaded
onedrive version                       = v2.4.13-1~np1
Config path                            = /home/thomas/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /media/root/ExternalDisk
Config option 'skip_dir'               = Desktop|Anwendungen
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 100
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
-> 7.68.0

*   Is your configured 'sync_dir' a local directory or a network mount point?
-> An USB disk

*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
->
```
sdg                                                                              
└─sdg1 ext4     ExternalDisk 9f88189c-8bde-4948-8197-c778a2dc7a22    1,7T     0% /media/root/ExternalDisk
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system (-> NO), shared with any other platform at the same time (->NO), is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time (-> POSSIBLE, maybe from my smartphone)

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
-> Just start onedrive: "onedrive --synchronize --download-only --verbose"

**Complete Verbose Log Output**
-> see attached file

(I am not sure whether the file has been attached. This should be the relevant parts. Showing the first change (a directory), skipping all further directories and just mentioning change 14 where the first file should be downloaded, which fails):
```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/thomas
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/thomas/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/thomas/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/thomas/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/thomas/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/thomas/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/thomas/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /home/thomas/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/thomas/.config/onedrive/config
[DEBUG] syncListFilePath = /home/thomas/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/thomas/.config/onedrive/business_shared_folders
Configuration file successfully loaded
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /media/root/ExternalDisk
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
[DEBUG] Attempting to contact online service
[DEBUG] Shutting down HTTP engine as sucessfully reached OneDrive Online Service
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Configured authUrl:          https://login.microsoftonline.com/common/oauth2/v2.0/authorize
[DEBUG] Configured redirectUrl:      https://login.microsoftonline.com/common/oauth2/nativeclient
[DEBUG] Configured tokenUrl:         https://login.microsoftonline.com/common/oauth2/v2.0/token
[DEBUG] Configured driveUrl:         https://graph.microsoft.com/v1.0/me/drive
[DEBUG] Configured driveByIdUrl:     https://graph.microsoft.com/v1.0/drives/
[DEBUG] Configured sharedWithMeUrl:  https://graph.microsoft.com/v1.0/me/drive/sharedWithMe
[DEBUG] Configured itemByIdUrl:      https://graph.microsoft.com/v1.0/me/drive/items/
[DEBUG] Configured itemByPathUrl:    https://graph.microsoft.com/v1.0/me/drive/root:/
[DEBUG] Configured siteSearchUrl:    https://graph.microsoft.com/v1.0/sites?search
[DEBUG] Configured siteDriveUrl:     https://graph.microsoft.com/v1.0/sites/
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
[DEBUG] companyName = abraunegg
[DEBUG] appTitle    = OneDrive Client for Linux
Opening the item database ...
[DEBUG] Using database file: /home/thomas/.config/onedrive/items.sqlite3
[DEBUG] Configuring default new folder permissions as: 700
[DEBUG] Configuring default new file permissions as: 600
All operations will be performed in: /media/root/ExternalDisk
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: Desktop|Anwendungen
[DEBUG] Configuring skip_dir_strict_match ...
[DEBUG] skip_dir_strict_match: false
[DEBUG] Configuring skip_dotfiles ...
[DEBUG] skip_dotfiles: false
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
[DEBUG] Setting file permissions for: /home/thomas/.config/onedrive/refresh_token
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
[DEBUG] OneDrive Account Details:      {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives\/$entity","driveType":"personal","id":"xxxxxxxxxxxxxx","owner":{"user":{"displayName":"Thomas xxxxxxxxxxxxxx","id":"xxxxxxxxxxxxxx"}},"quota":{"deleted":20,"remaining":xxxxxxxxxxxxxx,"state":"normal","storagePlanInformation":{"upgradeAvailable":false},"total":1104880336896,"used":386070138549}}
[DEBUG] OneDrive Account Root Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#users('xxxxxxxxxxxxxx%40outlook.de')\/drive\/root\/$entity","cTag":"xxxxxxxxxxxxxx","createdBy":{"device":{"id":"xxxxxxxxxxxxxx"},"user":{"displayName":"Thomas xxxxxxxxxxxxxx","id":"xxxxxxxxxxxxxx"}},"createdDateTime":"2015-07-25T09:56:57.557Z","eTag":"xxxxxxxxxxxxxx","fileSystemInfo":{"createdDateTime":"2015-07-25T09:56:57.556Z","lastModifiedDateTime":"2015-07-25T09:56:57.557Z"},"folder":{"childCount":11,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"xxxxxxxxxxxxxx!107","lastModifiedBy":{"device":{"id":"xxxxxxxxxxxxxx"},"user":{"displayName":"Thomas xxxxxxxxxxxxxx","id":"xxxxxxxxxxxxxx"}},"lastModifiedDateTime":"2021-08-10T20:09:28.573Z","name":"root","parentReference":{"driveId":"xxxxxxxxxxxxxx","driveType":"personal"},"root":{},"size":386070138549,"webUrl":"https:\/\/onedrive.live.com\/?cid=xxxxxxxxxxxxxx"}
Application version: v2.4.13-1~np1
Account Type: personal
Default Drive ID: xxxxxxxxxxxxxx
Default Root ID: xxxxxxxxxxxxxx!107
Remaining Free Space: 718810198347
Fetching details for OneDrive Root
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
[DEBUG] lastModifiedDateTime (OneDrive item): 2015-Jul-25 09:56:57.557Z
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
[DEBUG] performSync API scan triggers
[DEBUG] -----------------------------
[DEBUG] fullScanRequired =                   false
[DEBUG] syncListConfiguredFullScanOverride = false
[DEBUG] -----------------------------
[DEBUG] ################################################## NEW SYNC ##################################################
Syncing changes from OneDrive ...
[DEBUG] Initial Scan: Call OneDrive Delta API for delta changes as compared to last successful sync.
[DEBUG] Calling sync.applyDifferences(false);
Applying changes of Path ID: xxxxxxxxxxxxxx!107
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxxxxxxxxxxxx/?select=quota
Updated Remaining Free Space: 718810198347
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxxxxxxxxxxxx/items/xxxxxxxxxxxxxx!107?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] OneDrive Path Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives('xxxxxxxxxxxxxx')\/items\/$entity","cTag":"xxxxxxxxxxxxxx","eTag":"xxxxxxxxxxxxxx","fileSystemInfo":{"createdDateTime":"2015-07-25T09:56:57.556Z","lastModifiedDateTime":"2015-07-25T09:56:57.557Z"},"folder":{"childCount":11,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"xxxxxxxxxxxxxx!107","name":"root","parentReference":{"driveId":"xxxxxxxxxxxxxx","driveType":"personal"},"root":{},"size":386070138549}
[DEBUG] Item details returned no parent reference path
[DEBUG] Sync Folder Name:        root
[DEBUG] Sync Folder Parent Path: 
[DEBUG] Sync Folder Child Path:  
[DEBUG] syncListConfigured = false
[DEBUG] oneDriveFullScanTrigger = false
[DEBUG] performFullItemScan = false
[DEBUG] performFullItemScan is false, using the deltaLink as per database entry
[DEBUG] deltaLink was requested to be used, but contains no data - resulting API query will be treated as a full scan of OneDrive
[DEBUG] Configuring 'idToQuery' as defaultRootId duplicate
[DEBUG] Path object to query configured as 'idToQuery' = xxxxxxxxxxxxxx!107
[DEBUG] Using /delta call to query drive for items to populate 'changes' and 'changesAvailable'
[DEBUG] Attempting query 'changes = onedrive.viewChangesByItemId(driveId, idToQuery, deltaLink)'
[DEBUG] driveId:            xxxxxxxxxxxxxx
[DEBUG] idToQuery:          xxxxxxxxxxxxxx!107
[DEBUG] Previous deltaLink: 
[DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxxxxxxxxxxxx/items/xxxxxxxxxxxxxx!107/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] Query 'changes = onedrive.viewChangesByItemId(driveId, idToQuery, deltaLink)' performed successfully
[DEBUG] OneDrive API /delta response: 
.
.
..
.
.[DEBUG] Attempting query 'changesAvailable = onedrive.viewChangesByItemId(driveId, idToQuery, deltaLinkAvailable)'
[DEBUG] driveId: xxxxxxxxxxxxxx
[DEBUG] idToQuery: xxxxxxxxxxxxxx!107
[DEBUG] deltaLinkAvailable: 
[DEBUG] Request URL = https://graph.microsoft:.com/v1.0/drives/xxxxxxxxxxxxxx/items/xxxxxxxxxxxxxx!107/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size
[DEBUG] Query 'changesAvailable = onedrive.viewChangesByItemId(driveId, idToQuery, deltaLinkAvailable)' performed successfully
[DEBUG] changesAvailable query reports that there are 350 changes that need processing on OneDrive
Processing 350 OneDrive items to ensure consistent local state
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 1 of 350
[DEBUG] OneDrive Change:/change 15
{"@odata.type":"#microsoft.graph.driveItem","cTag":"adDoxQTc4NDAyMzFCOUE3ODBDITEwNy42Mzc2NDIyMjk2ODU3MzAwMDA","eTag":"aMUE3ODQwMjMxQjlBNzgwQyExMDcuMA","fileSystemInfo":{"createdDateTime":"2015-07-25T09:56:57.556Z","lastModifiedDateTime":"2015-07-25T09:56:57.557Z"},"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"xxxxxxxxxxxxxx!107","name":"root","parentReference":{"driveId":"xxxxxxxxxxxxxx","driveType":"personal","id":"xxxxxxxxxxxxxx!0","path":"\/drive\/root:"},"root":{},"size":386070138549}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = xxxxxxxxxxxxxx!107
[DEBUG] 'search id'                                          = xxxxxxxxxxxxxx!107
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = true
[DEBUG] item['name'].str == 'root'                           = true
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] Change will flagged as a 'root' item change
[DEBUG] isRoot                                               = true
[DEBUG] !hasParentReferenceId(item)                          = false
[DEBUG] isItemDeleted(item)                                  = false
[DEBUG] Handling change as 'root item', has no parent reference or is a deleted item
[DEBUG] lastModifiedDateTime (OneDrive item): 2015-Jul-25 09:56:57.557Z
[DEBUG] Handing a OneDrive 'root' change
[DEBUG] Update/Insert local database with item details
[DEBUG] item details: Item("xxxxxxxxxxxxxx", "xxxxxxxxxxxxxx!107", "root", dir, "xxxxxxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxxxxxxx", 2015-Jul-25 09:56:57.557Z, "", "", "", "", "", "", "Y")
.
.
.
[DEBUG] Processing change 14 of 350
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"xxxxxxxxxxxxxxxxxxxxxx","eTag":"xxxxxxxxxxxxxxxxxxxxxx","file":{"hashes":{"quickXorHash":"xxxxxxxxxxxxxxxxxxxxxx\/xxxxxxxxxxxxxxxxxxxxxx+xxxxxxxxxxxxxxxxxxxxxx=","sha1Hash":"xxxxxxxxxxxxxxxxxxxxxx","sha256Hash":"xxxxxxxxxxxxxxxxxxxxxx"},"mimeType":"image\/png"},"fileSystemInfo":{"createdDateTime":"2021-07-07T10:29:55Z","lastModifiedDateTime":"2021-07-07T10:29:55Z"},"id":"xxxxxxxxxxxxxx!92846","name":"Screenshot_20210707-122955.png","parentReference":{"driveId":"xxxxxxxxxxxxxx","driveType":"personal","id":"xxxxxxxxxxxxxx!58279","name":"Eigene Aufnahmen","path":"\/drive\/root:\/Pictures\/Eigene Aufnahmen"},"size":129840}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = xxxxxxxxxxxxxx!107
[DEBUG] 'search id'                                          = xxxxxxxxxxxxxx!107
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = xxxxxxxxxxxxxx!58279
[DEBUG] search criteria: syncFolderName                      = root
[DEBUG] search criteria: syncFolderPath                      = 
[DEBUG] search criteria: syncFolderChildPath                 = 
[DEBUG] thisItemId                                           = xxxxxxxxxxxxxx!92846
[DEBUG] thisItemParentPath                                   = /drive/root:/Pictures/Eigene Aufnahmen
[DEBUG] thisItemFullPath                                     = /drive/root:/Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemParentPath' contains 'syncFolderChildPath'  = true
[DEBUG] 'thisItemParentPath' contains search 'id'            = false
[DEBUG] Change matches search criteria to apply
[DEBUG] lastModifiedDateTime (OneDrive item): 2021-Jul-07 10:29:55Z
[DEBUG] Attempting to calculate local filesystem path for xxxxxxxxxxxxxx and xxxxxxxxxxxxxx!58279
[DEBUG] skip_file item to check: /Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png
[DEBUG] skip_file evaluation for: /Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png
[DEBUG] Result: false
[DEBUG] The item we are syncing is a file
[DEBUG] Attempting to calculate local filesystem path for xxxxxxxxxxxxxx and xxxxxxxxxxxxxx!58279
[DEBUG] OneDrive change is a new local item
[DEBUG] skip_dir evaluation for: /Pictures/Eigene Aufnahmen
[DEBUG] No Strict Matching Enforced
Downloading file Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png ... [DEBUG] Request URL = https://graph.microsoft.com/v1.0/drives/xxxxxxxxxxxxxx/items/xxxxxxxxxxxxxx!92846?select=size,malware,file,webUrl

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    SSL peer certificate or SSH remote key was not OK on handle 55905C34C320
[DEBUG] Raw Error Data: SSL peer certificate or SSH remote key was not OK on handle 55905C34C320
[DEBUG] JSON Message: null
  Calling Function: download()

[DEBUG] Setting file permissions for: Pictures/Eigene Aufnahmen/Screenshot_20210707-122955.png
ERROR: File download size mis-match. Increase logging verbosity to determine why.
ERROR: File download hash mis-match. Increase logging verbosity to determine why.
[DEBUG] Download or creation of local directory failed
.
```

**Comment by abraunegg** [comment] 2021-08-12 10:07
@doubleparadiddle 
There are 2 possibilities here:

1. You have HTTPS/SSL inspection going on between you and the the OneDrive service, and you have not installed the HTTPS/SSL inspection  CA certificates on your system - thus the application will fail certificate validation
2. You have outdated SSL CA certificates on your system

To validate what is going on, use `--verbose --verbose --debug-https` to determine what SSL certificates are being used on your Ubuntu system.

I would also ensure you are updating your Ubuntu system correctly & removing stale ones:
```
#!/bin/bash
rm -rf /var/lib/dpkg/lock-frontend
rm -rf /var/lib/dpkg/lock
apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get autoclean -y
```

**Comment by iandall** [comment] 2021-08-12 17:50
I'm experiencing the same problem.
[ondrive-http.log](https://github.com/abraunegg/onedrive/files/6977463/ondrive-http.log)
There is an initial connection to login.microsoftonline.com which succeeds, using CAfile: /etc/pki/tls/certs/ca-bundle.crt, and the SSL certificate verifies OK. Then there are two attempted connections through the API, using the came CAfile, which fail with "unable to get local issuer certificate". This is on Fedora 33 and the certificate package is up to date.

**Comment by abraunegg** [comment] 2021-08-12 22:33
@iandall 
I have just tried here with a Fedora 33 system and also found no issue - ie - no certificate issue, so that leaves the following possibilities:

1. You have HTTPS/SSL inspection going on between you and the the OneDrive service, and you have not installed the HTTPS/SSL inspection CA certificates on your system - thus the application will fail certificate validation
2. Microsoft have updated a certificate somewhere within their ecosystem & specific to your geographic location, which is different to their other certificates, or uses a different CA certificate which is not in the current certificate bundle for Fedora

In both these cases this is *not* something that can be fixed in the application.

If you have a support contract with Microsoft, please open a case with Microsoft.

**Comment by abraunegg** [comment] 2021-08-12 22:34
Closing issue as not a bug or anything that I can assist with

**Closed by abraunegg** 2021-08-12 22:34 UTC
Labels: Not a bug, Local Environment Issue

**Comment by doubleparadiddle** [comment] 2021-08-13 17:38
In my case the problem was that I had a VPN connection (Checkpoint snx) open in parallel. Closing that connection made the file downloads work.

**Comment by abraunegg** [comment] 2021-08-13 22:13
@doubleparadiddle 
Glad you got it sorted - however it potentially means your Checkpoint 'split tunnel' configuration needs to be amended to avoid the VPN client mangling your connections to OneDrive.
