### ISSUE TITLE
OneDrive Business: curl error when running "onedrive --synchronize", possibly missing quota information

### ISSUE THREAD

**Issue by andrei-rusu** [abraunegg/onedrive#1086] opened 2020-10-05 15:46 UTC
### Bug Report Details ###

I am trying to run the OneDrive Client on a JuNest Linux instance with PRoot (since I do not have admin rights on the machine I need to synchronize my OneDrive to). The configuration and installation went well, however...
```
Running "onedrive --synchronize" ends up throwing a strange 'curl' error:
ERROR: OneDrive returned an error with the following message:
  Error Message: URL using bad/illegal format or missing URL on handle 2B47778D64D0
```
This happens only for my OneDrive Business account! Synchronization seems to work just fine for my normal OneDrive account.
Looking at the --verbose output, it seems that the Client attempts to acquire 'quota information' which is not available for this Business account.

LATER EDIT: Synchronization stopped working for my personal account as well. I don't know why, but the error there is:
```
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  ObjectHandle is Invalid
```

**Application and Operating System Details:**
*   Linux cyan02 3.10.0 #1 SMP Thu May 24 18:18:25 EDT 2018 x86_64 GNU/Linux (via JuNest in Proot mode)
*   no gui
*   Office365
*   Built from the latest source
*   DMD64 D Compiler v2.093.1

*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.6
Config path                            = /home/ar5g15/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/ar5g15/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   curl 7.72.0 (x86_64-pc-linux-gnu) 
*   local
*   I'm not sure mount output is relevant here

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Just run onedrive --synchronize after build + install

**Complete Verbose Log Output**
```
Using 'user' Config Dir: /home/ar5g15/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/ar5g15/OneDrive
Application version: v2.4.6
Account Type: business
Default Drive ID: b!UIosOxO45EWyiH-kNJdOdCSFNgbdYx1Fvvp8t02ot6oNATPL1btbQLAjAuQWq2nI
Default Root ID: 01TNKGNFF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5351692213118
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01TNKGNFF6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 5351692213118
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
OneDrive Client requested to create remote path: .
Applying changes of Path ID: /drives/b!UIosOxO45EWyiH-kNJdOdCSF
ERROR: OneDrive quota information is missing. Potentially your OneDrive account currently has zero space available. Please free up some space online.
```

**Comment by abraunegg** [comment] 2020-10-05 18:44
@andrei-rusu 
Both 'issues' are different.

Please provide a verbose debug log as per  https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support and provide a verbose HTTPS debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support for both issues please.

**Comment by andrei-rusu** [comment] 2020-10-05 19:24
Strangely enough, when I attempted to resync the personal Drive, it worked again.

Sync for Business is still not working on my end. Posting the logs for the Business account here:
[debug_output.log](https://github.com/abraunegg/onedrive/files/5329630/debug_output.log)
[https-debug_output.log](https://github.com/abraunegg/onedrive/files/5329631/https-debug_output.log)

**Comment by abraunegg** [comment] 2020-10-05 19:56
@andrei-rusu 
The log files you have provided are not complete.

There is however some interesting data:
![log_file_error](https://user-images.githubusercontent.com/4956234/95124827-be5ea400-079f-11eb-92fe-51805a6cebfe.JPG)

As your 'curl' version is the latest release (curl 7.72.0 (x86_64-pc-linux-gnu)), but you have not detailed what options / compile options it is using - something 'might' be missing there.

What is the full command line you are using to start the application? I cant seem to replicate this at the moment, but also this might be because of your operating environment (JuNest)

**Comment by abraunegg** [comment] 2020-10-05 21:04
@andrei-rusu 
I have added & moved some debugging around to give more insights to the error you are seeing which I am highlighting above.

Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1073/head:pr1073
git checkout pr1073
./configure; make clean; make;
```
When running the PR version, your client version should be: `onedrive v2.4.6-3-g526df8e` or greater.

**Comment by andrei-rusu** [comment] 2020-10-05 21:25
Indeed, the log features some weird characters where the request is being shown. I am generating the full log as per instructions, there may be some things missing because I am running the command for one folder only. This is because my whole OneDrive is just too big to run it all.  Attaching here the new log with the PR indicated.

[debug.log](https://github.com/abraunegg/onedrive/files/5330146/debug.log)

Also the other 'curl' components:

curl 7.72.0 (x86_64-pc-linux-gnu) libcurl/7.72.0 OpenSSL/1.1.1h zlib/1.2.11 zstd/1.4.5 libidn2/2.3.0 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-08-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

**Comment by abraunegg** [comment] 2020-10-05 21:59
@andrei-rusu 
Unfortunately that new debug log is not right - this is not being generated by using the PR version. In the log you are still using:
```
Application version: v2.4.6
```

You most likely ran the 'installed' binary, rather than running the new binary from the PR folder. You need to do this via running:
```
./onedrive ......<your command options here>
```

**Comment by andrei-rusu** [comment] 2020-10-05 22:08
Ah, you're right. Here: 
[debug.log](https://github.com/abraunegg/onedrive/files/5330349/debug.log)

**Comment by abraunegg** [comment] 2020-10-05 22:25
> Ah, you're right. Here:
> [debug.log](https://github.com/abraunegg/onedrive/files/5330349/debug.log)

Thanks.

OK .. it seems, that for whatever reason, in-between 2 different calls one the items that does not change is being 'munged' .. potentially a compiler issue due to your OS .... 

As you built using DMD, unsure how you installed that, however can you try to utilse the LDC compiler and see if there is a different result? You can install LDC via:
```
curl -fsS https://dlang.org/install.sh | bash -s ldc
```
and then activate as per the instructions, the compile utilising the LDC compiler via running `./configure` again.

Can you try those steps?

**Comment by andrei-rusu** [comment] 2020-10-05 22:36
Unfortunately, with LDC the same error happens:

LDC - the LLVM D compiler (1.23.0):
  based on DMD v2.093.1 and LLVM 10.0.1
  built with LDC - the LLVM D compiler (1.22.0)
  Default target: x86_64-pc-linux-gnu

[debug.log](https://github.com/abraunegg/onedrive/files/5330477/debug.log)

**Comment by abraunegg** [comment] 2020-10-05 22:54
@andrei-rusu 
Interesting ... 

I have made a few slight changes and updated additional debugging. Please can you rebuild your PR, pulling in the latest code. When running, you should have version `onedrive v2.4.6-6-gb721906`

If you can generate a new debug log with that version that would be greatly appreciated.

**Comment by andrei-rusu** [comment] 2020-10-05 23:08
Here:
[Uploading debug.log…]()

**Comment by abraunegg** [comment] 2020-10-06 06:47
@andrei-rusu 
> I am trying to run the OneDrive Client on a JuNest Linux instance with PRoot (since I do not have admin rights on the machine I need to synchronize my OneDrive to). The configuration and installation went well, however...

According to this URL (https://github.com/fsquillace/junest#proot-based) proot is not officially supported anymore, proot bugs may no longer be fixed.

This being said, can you please provide some details in how I can replicate your setup / environment to attempt to replicate this issue.
* What is your exact physical hardware you are running
* Are you running JuNest via QEMU to emulate some 'other' hardware


Additionally, please can you:
* Perform an exhaustive test of your your hardware (memory test via memtest86)
* Perform an exhaustive test of your physical media (file system check to ensure that there are no bad sectors, reallocated sectors, pending reallocation ect) & that all your existing files and data contain zero issues (all files / folders healthy) across your entire ecosystem

**Comment by abraunegg** [comment] 2020-10-06 09:14
@andrei-rusu 
On a Arch Linux system, using either DMD or LDC versions, I am unable to replicate this behavior with 'master' or the PR version. I suspect that this is something that is unique to your operating environment, potentially:
* JuNest itself
* Something inside JuNest
* Something to do with proot inside JuNest

Flagging this as unable to replicate, local environment issue.

**Comment by andrei-rusu** [comment] 2020-10-06 14:44
I am running JuNest with the following command "junest proot -f -b "-k 3.10". This starts up a Linux environment with fake admin and fake kernel version 3.10. The package is precompiled with kernel version 2.6.32.

The machine I'm trying to run onedrive from is an HPC cluster node. Unfortunately, many hardware checking commands do not work (incl. memtest86) or are blocked behind sudo (incl. dmidecode).

**lscpu** output:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               45
Model name:          Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Stepping:            7
CPU MHz:             2600.019
BogoMIPS:            5200.03
Virtualization:      VT-x
L1d cache:           512 KiB
L1i cache:           512 KiB
L2 cache:            4 MiB
L3 cache:            40 MiB
NUMA node0 CPU(s):   0-7
NUMA node1 CPU(s):   8-15

**lspci** output:
00:00.0 Host bridge: Intel Corporation Xeon E5/Core i7 DMI2 (rev 07)
00:01.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 1a (rev 07)
00:02.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 2a (rev 07)
00:03.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 3a in PCI Express Mode (rev 07)
00:03.2 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 3c (rev 07)
00:04.0 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 0 (rev 07)
00:04.1 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 1 (rev 07)
00:04.2 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 2 (rev 07)
00:04.3 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 3 (rev 07)
00:04.4 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 4 (rev 07)
00:04.5 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 5 (rev 07)
00:04.6 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 6 (rev 07)
00:04.7 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 7 (rev 07)
00:05.0 System peripheral: Intel Corporation Xeon E5/Core i7 Address Map, VTd_Misc, System Management (rev 07)
00:05.2 System peripheral: Intel Corporation Xeon E5/Core i7 Control Status and Global Errors (rev 07)
00:11.0 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Virtual Root Port (rev 06)
00:1a.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #2 (rev 06)
00:1c.0 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Root Port 1 (rev b6)
00:1c.7 PCI bridge: Intel Corporation C600/X79 series chipset PCI Express Root Port 8 (rev b6)
00:1d.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #1 (rev 06)
00:1e.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev a6)
00:1f.0 ISA bridge: Intel Corporation C600/X79 series chipset LPC Controller (rev 06)
00:1f.3 SMBus: Intel Corporation C600/X79 series chipset SMBus Host Controller (rev 06)
01:00.0 PCI bridge: Renesas Technology Corp. SH7757 PCIe Switch [PS]
02:00.0 PCI bridge: Renesas Technology Corp. SH7757 PCIe Switch [PS]
02:01.0 PCI bridge: Renesas Technology Corp. SH7757 PCIe Switch [PS]
03:00.0 PCI bridge: Renesas Technology Corp. SH7757 PCIe-PCI Bridge [PPB]
04:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. G200eR2
06:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
06:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
06:00.2 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
06:00.3 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
11:00.0 Network controller: Mellanox Technologies MT27500 Family [ConnectX-3]
1b:00.0 RAID bus controller: LSI Logic / Symbios Logic MegaRAID SAS 2008 [Falcon] (rev 03)
80:00.0 PCI bridge: Intel Corporation Xeon E5/Core i7 DMI2 in PCI Express Mode (rev 07)
80:02.0 PCI bridge: Intel Corporation Xeon E5/Core i7 IIO PCI Express Root Port 2a (rev 07)
80:04.0 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 0 (rev 07)
80:04.1 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 1 (rev 07)
80:04.2 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 2 (rev 07)
80:04.3 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 3 (rev 07)
80:04.4 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 4 (rev 07)
80:04.5 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 5 (rev 07)
80:04.6 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 6 (rev 07)
80:04.7 System peripheral: Intel Corporation Xeon E5/Core i7 DMA Channel 7 (rev 07)
80:05.0 System peripheral: Intel Corporation Xeon E5/Core i7 Address Map, VTd_Misc, System Management (rev 07)
80:05.2 System peripheral: Intel Corporation Xeon E5/Core i7 Control Status and Global Errors (rev 07)

**Comment by abraunegg** [comment] 2020-10-06 18:11
@andrei-rusu 
Thanks. What Host OS is running before you execute the JuNest environment?

**Comment by abraunegg** [comment] 2020-10-06 20:11
@andrei-rusu 
I have installed JuNest hosted on CentOS 6.x platform, to mirror the minimum kernel requirements for JuNest.

Following the directions to install dependencies / application under Arch Linux:
```
pacman -Syy
pacman -Syu
pacman -S curl sqlite dmd
```

Plus additional dependencies to ensure the application can compile:
```
pacman -S pkgconf awk m4 make

```

I was able to download / configure and run the application.

This being said however the application 'segfaults' when downloading data. This segfault **only** occurs when running under JuNest, and does not segfault when compiled under CentOS 6.x using DMD or LDC.

In an attempt to utilise LDC, rather than DMD within the JuNest environment, LDC cannot be installed, so I am curious as to how you installed this under JuNest and used this as your compile test:
```
Downloading and unpacking https://github.com/ldc-developers/ldc/releases/download/v1.23.0/ldc2-1.23.0-linux-x86_64.tar.xz
######################################################################## 100.0%##O=#  #                                                                      
tar: etc/bash_completion.d: Cannot change mode to rwxr-xr-x: Invalid argument
tar: etc: Cannot change mode to rwxr-xr-x: Invalid argument
tar: lib32/libphobos2-ldc-shared.so.93: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libdruntime-ldc-shared.so.93: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libdruntime-ldc-debug-shared.so: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libphobos2-ldc-debug-shared.so.93: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libphobos2-ldc-shared.so: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libphobos2-ldc-debug-shared.so: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libdruntime-ldc-debug-shared.so.93: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
tar: lib32/libdruntime-ldc-shared.so: Cannot change mode to rwxrwxrwx: Too many levels of symbolic links
...
```

As for one of your original issues:
```
ERROR: OneDrive quota information is missing. Potentially your OneDrive account currently has zero space available. Please free up some space online.
```
This is a 100% normal message when the folder you are trying to sync is on a shared folder location or SharePoint repository.

As for the memory issue where the variable is being 'munged', I cannot replicate this exactly, but I do experience issues under JuNest. I suspect all your issues are due to JuNest.

I am not going to look at this any further for the following reasons:
* Running under JuNest & using 'proot' which is no longer supported as per https://github.com/fsquillace/junest#proot-based

To resolve your issue, please choose one of the following options:
1. Configure and use the application without using JuNest
2. Use Docker

Closing issue, flagging as not a bug, however debugging changes will be merged into master as these are beneficial changes.

**Closed by abraunegg** 2020-10-06 20:11 UTC
Labels: Local Environment Issue, More Information Needed, Unable to reproduce, Waiting on Response
