### ISSUE TITLE
don't sync file if open or being written to

### ISSUE THREAD

**Issue by roxyschram** [abraunegg/onedrive#740] opened 2019-11-28 00:57 UTC
So I use rsync to download backups every morning. They download to a directly that is within the onedrive directory. When they are downloading, onedrive is running and trying to upload them but fails due to size differences of what it uploaded and what is there when it checks to verify. Could you make it so that it will ignore a file that is open and once closed then upload?

Logs are full of these entries:
Uploaded file size does not match local file - upload failure - retrying

I noticed it doesn't always upload the file at all when there are a lot of these

**Comment by roxyschram** [comment] 2019-11-28 01:06
Just tested with scp, doesn't seem to have that issue with scp so I'll switch to that but I still think this would be a good feature or enhancement

**Comment by abraunegg** [comment] 2020-01-07 06:52
@roxyschram 
Unable to reproduce this at all - with large or small files, transfered by rsync:
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor
Notification (dbus) server not available, disabling
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Skipping item - has disappeared: ./.ldb-1.4.7.tar.gz.Xs57dD
Moving ./.ldb-1.4.7.tar.gz.Xs57dD to ./ldb-1.4.7.tar.gz
Uploading new file ./ldb-1.4.7.tar.gz ... done.
Skipping item - has disappeared: ./.50k_random_files.tar.gz.JUMgwj
Moving ./.50k_random_files.tar.gz.JUMgwj to ./50k_random_files.tar.gz
Uploading new file ./50k_random_files.tar.gz ... 
Uploading   5% |ooo                                     |   ETA   00:07:22
```

**rsync process**
```
[alex@centos7full OneDrivePersonal]$ rsync -av ../ldb-1.4.7.tar.gz .
sending incremental file list
ldb-1.4.7.tar.gz

sent 1,431,009 bytes  received 35 bytes  2,862,088.00 bytes/sec
total size is 1,430,560  speedup is 1.00
[alex@centos7full OneDrivePersonal]$ rsync -av ../50k_random_files.tar.gz .
sending incremental file list
50k_random_files.tar.gz

sent 874,227,320 bytes  received 35 bytes  69,938,188.40 bytes/sec
total size is 874,013,831  speedup is 1.00
[alex@centos7full OneDrivePersonal]$ 
```

Please can you provide a verbose debug log for your rsync process which shows the upload not working.

**Comment by roxyschram** [comment] 2020-01-07 06:59
@abraunegg 

The error isn't provided by rsync. I have a machine that backups nightly to my machine that has your OneDrive software on it running. While rsync is pulling the files over OneDrive keeps trying to upload them but fails because the file is still open and being written to

**Comment by abraunegg** [comment] 2020-01-07 07:01
@roxyschram 
> While rsync is pulling the files over OneDrive keeps trying to upload them but fails because the file is still open and being written to

As per above, client is in monitor mode, monitoring the onedrive directory, and rsync is uploading / copying data to that folder. The temp file that rsync creates is not uploaded, but the right one is without issue.

Please provide verbose debug logs from the onedrive process which will assist in diagnosing further.

I cannot reproduce.

**Comment by abraunegg** [comment] 2020-01-08 20:05
@roxyschram 
Any update on being able to provide the requested debug log ?

**Comment by roxyschram** [comment] 2020-01-08 22:43
Not yet, I haven't been able to be near that machine... I should be at it tomorrow

**Comment by roxyschram** [comment] 2020-01-09 22:39
So I can't see to reproduce now. Another issue I was having as disappeared too... Rsync, even though both systems were on the same network was taking almost 3 hours to sync but now it's finishing in 30 seconds...

**Comment by abraunegg** [comment] 2020-01-09 23:04
@roxyschram 
> So I can't see to reproduce now.

OK .. so some sort of transient local system issue then. As I cannot reproduce either, closing this issue as not a bug, unable to reproduce.

**Closed by abraunegg** 2020-01-09 23:04 UTC
Labels: More Information Needed, Unable to reproduce, Waiting on Response
