### ISSUE TITLE
Error 500 after deleting a large number of files

### ISSUE THREAD

**Issue by jorgegaspar** [abraunegg/onedrive#1145] opened 2020-11-14 23:22 UTC
On the last version, I've deleted a large number of files on onedrive, and now my onedrive stopped syncing.

```
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 500 (Internal Server Error)
  Error Reason:  Failed to get a coherent view of changes. Try again later.
```

I'm using the --download-only flag because I've lost all my files a few times, after disconnecting the drive that I'm using as --syncdir so I'm only interested in syncing online changes and not local changes.

EDIT: Adding the version:

```
root@tega:~# onedrive --version
onedrive v2.4.6-22-g7a4abff
```

**Comment by abraunegg** [comment] 2020-11-14 23:37
@jorgegaspar 
```
HTTP request returned status code 500 (Internal Server Error)
```
This is not an error by this client. The OneDrive service is generating this response.

You need to wait till OneDrive re-enumerates itself correctly before attempting to download your data.

> because I've lost all my files a few times, after disconnecting the drive that I'm using as --syncdir

Suggest that your 'mount' point utilises the .nosync file and check, so that when you disconnect your drive, the data is not removed.

```
onedrive v2.4.6-22-g7a4abff
```

Suggest you upgrade your client to `onedrive v2.4.7-13-g0d5b004` which is the latest master.

**Comment by abraunegg** [comment] 2020-11-15 18:41
Closing issue as not a bug, question answered

**Closed by abraunegg** 2020-11-15 18:41 UTC
Labels: Local Environment Issue, Not a bug
