### ISSUE TITLE
Is --synchronize deprecated? 

### ISSUE THREAD

**Issue by PoLabs** [abraunegg/onedrive#596] opened 2019-07-18 16:34 UTC
```
(base) vpisano@ubuntu:~$ onedrive --synchronize --verbose --dry-run
Unrecognized option --synchronize
Try 'onedrive -h' for more information
(base) vpisano@ubuntu:~$ onedrive --display-config
Unrecognized option --display-config
Try 'onedrive -h' for more information
(base) vpisano@ubuntu:~$ onedrive --synchronize --local-first
Unrecognized option --synchronize
Try 'onedrive -h' for more information
(base) vpisano@ubuntu:~$ onedrive --sync --local-first
Unrecognized option --sync
Try 'onedrive -h' for more information
```

Actually is everything depreciated?

**Comment by abraunegg** [comment] 2019-07-18 20:51
@PoLabs 
What version of the client are you running?

Please follow these instructions when posting an issue: https://github.com/abraunegg/onedrive#reporting-issues

**Comment by abraunegg** [comment] 2019-07-18 21:19
@PoLabs 
I suspect you have installed / still have the 'skilion' version installed. As built from latest master:
```
[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --dry-run
Using Config Dir: /home/alex/.config/onedrive-personal
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Application version: v2.3.7-18-gb41c5eb
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 12 changes
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
[alex@centos7full onedrive]$ 
```

When running 'skilion' codebase:
```
[alex@centos7full onedrive-skilion]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --dry-run
Unrecognized option --synchronize
Try 'onedrive -h' for more information
[alex@centos7full onedrive-skilion]$ 
```

**Comment by abraunegg** [comment] 2019-07-18 21:20
@PoLabs 
Closing issue - not a bug, incorrect version

**Closed by abraunegg** 2019-07-18 21:20 UTC
Labels: Invalid - Skilion Code Version, Waiting on Response
