### ISSUE TITLE
Cannot upload file due to Sharepoint 'enrichment' 

### ISSUE THREAD

**Issue by 0x3333** [abraunegg/onedrive#450] opened 2019-04-02 20:13 UTC
I'm uploading a file server to SharePoint on Office 365.

This file, even when removed online, return this error, and then, sync stops.

In what seems the first pass, I got:

```
Processing SomeFile.xlsx
The file last modified time has changed
The file content has changed
Uploading file SomeFile.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
done.
```

But latter on the same sync run:
```
Uploading file SomeFile.xlsx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:OneDrive returned a 'HTTP 404 - Item not found' - gracefully handling error
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:
done.
ERROR: OneDrive response missing required 'id' element:
ERROR: {"error":{"code":"itemNotFound","message":"The resource could not be found."}}
Giving up on sync after three attempts: Key not found: cTag
std.json.JSONException@std/json.d(540): Key not found: cTag
----------------
/root/dlang/dmd-2.084.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0xd19da25b]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0xd1a9097e]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0xd1a42e61]
src/sync.d:1286 void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0xd1a1392e]
src/sync.d:1122 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12d28]
src/sync.d:1142 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0xd1a12ee5]
src/sync.d:1119 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12cf5]
src/sync.d:1142 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0xd1a12ee5]
src/sync.d:1119 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12cf5]
src/sync.d:1142 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0xd1a12ee5]
src/sync.d:1119 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12cf5]
src/sync.d:1142 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0xd1a12ee5]
src/sync.d:1119 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12cf5]
src/sync.d:1142 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0xd1a12ee5]
src/sync.d:1119 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0xd1a12cf5]
src/sync.d:1076 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xd1a12add]
src/main.d:666 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, bool) [0xd19ecb34]
src/main.d:494 _Dmain [0xd19ec160]
```

Command line: `onedrive --confdir /srv/samba/SharePoint/.config --synchronize --upload-only --verbose`
Version: `onedrive v2.2.5-34-g9719310`
Linux Debian 9

**Comment by abraunegg** [comment] 2019-04-02 20:16
@0x3333 
You need to upgrade your client to v2.3.2 and retest please.

**Comment by abraunegg** [comment] 2019-04-02 20:30
@0x3333 
Without the full diagnostic log which is requested when creating an issue ticket, I can only suspect that the account type in use is `Account Type: documentLibrary` given issue matches evidence as per #441

**Comment by 0x3333** [comment] 2019-04-03 12:51
Looks like the latest version fixed. It is still running, as the library is huge. Keep you posted. Thanks.

**Comment by abraunegg** [comment] 2019-04-03 18:25
Closing issue as resolved with v2.3.2

**Closed by abraunegg** 2019-04-03 18:25 UTC
Labels: Duplicate, Waiting on Response

**Comment by 0x3333** [comment] 2019-04-03 19:03
Well. Looks like we have another problem. 

I'm using upload only, because I want to have the files on SharePoint, but don't want to sync back changes. but because of bug 935, it tries to change files locally... Which with --upload is not my intention, and should not occur. 

I use a read only bind mount , so in cases like that, I don't get things changed in my file server. 

```           
Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync                                                                            
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details            
Giving up on sync after three attempts: Failed to remove file ./Some.docx: Read-only file system     
std.file.FileException@std/file.d(1061): Failed to remove file ./Some.docx: Read-only file system    
----------------                                                                             
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/file.d:240 @safe bool std.file.cenforce!(bool).cenforce(bool, scope lazy const(char)[], immutable(char)[], ulong) [0xf35a53c3]   
??:? @trusted void std.file.removeImpl(scope const(char)[], scope const(char)*) [0xf3610a2b] 
/root/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/file.d:1016 @safe void std.file.remove!(immutable(char)[]).remove(immutable(char)[]) [0xf35924c1]                                
src/onedrive.d:204 void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[], long) [0xf35d1827]                                                             
src/sync.d:1923 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0xf35e5aa8]           
src/sync.d:1569 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3ce0]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1561 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0xf35e3bd7]          
src/sync.d:1130 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0xf35e205d]      
src/main.d:765 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0xf35b8a75]                                                                       
src/main.d:560 _Dmain [0xf35b7f5e]                                       
```

**Comment by abraunegg** [comment] 2019-04-03 19:15
Whilst this is a different bug - it is caused by Sharepoint.

Please open a new case for this crash - but please remember this crash is being caused by 2 things:
1. Microsoft modifying your file after upload
2. The sync handling / checking of the file data
