### ISSUE TITLE
Application segfault's when ^C is issued when using the Ubuntu PPA

### ISSUE THREAD

**Issue by JesseRiemens** [abraunegg/onedrive#1053] opened 2020-09-03 10:39 UTC
### Bug Report Details ###
See title. I am using Ubuntu 20.04.1 GUI on a Office 365 A1 Plus for students account
I installed from package. 

```
onedrive version                       = v2.4.4-0~202008121743~ubuntu20.04.1
Config path                            = /home/****/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/jesse/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
```

curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```
$ onedrive --monitor
(...)
Downloading file ***/***/***/***.pdf ... ^CGot termination signal, shutting down db connection
Segmentation fault (core dumped)

```

**Comment by abraunegg** [comment] 2020-09-03 11:02
@JesseRiemens 
Please can you provide a verbose debug log in accordance with the support requirements

**Comment by JesseRiemens** [comment] 2020-09-03 11:03
I emailed the link to the debug log to the adress given

**Comment by abraunegg** [comment] 2020-09-03 11:09
@JesseRiemens 
Thanks - will look at itbin the morning

**Comment by JesseRiemens** [comment] 2020-09-03 11:11
@abraunegg Good luck. I don't think the bug has any nasty effects (at least I have discovered none yet) but it might not be quite the right way to exit the application.

**Comment by abraunegg** [comment] 2020-09-03 22:19
@JesseRiemens 
Thanks for debug log.

I have been able to reproduce this with the Ubuntu package using the PPA, however when installing from source, and using either DMD or LDC I cannot reproduce this. The DMD / LDC versions tested were:
* dmd-2.093.1
* ldc-1.23.0

The Ubuntu PPA uses the following:
* LDC 1.20.1 as per [build log](https://launchpadlibrarian.net/494064106/buildlog_ubuntu-focal-amd64.onedrive_2.4.4-0~202008121743~ubuntu20.04.1_BUILDING.txt.gz)

I suspect that this is a Ubuntu packaging issue, Ubuntu LDC issue or something else - but it is 100% related to Ubuntu packages / packaging.

This is not a bug in the application or code. Yes, the binary segfaults on exit (and yes that is not good) when using the PPA. Submit a bug against the PPA or the LDC packages for Ubuntu. I cannot fix this, as this does not occur when the application is built from source.

To resolve your issue, uninstall the PPA package, build from source using either DMD or LDC.

**Install Dependancies:**
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x-ubuntu-20x--debian-9-debian-10---x86_64

**dmd:**
```
curl -fsS https://dlang.org/install.sh | bash -s dmd
```

**ldc:**
```
curl -fsS https://dlang.org/install.sh | bash -s ldc
```

**Build from source:**
* https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#compilation--installation

**Comment by abraunegg** [comment] 2020-09-03 22:21
@yann1cks

Please can you investigate this issue on Ubuntu, as this segfault only occurs when using the Ubuntu PPA.

**Comment by JesseRiemens** [comment] 2020-09-04 06:16
@yann1cks is it okay if I leave it to you? I'm not quite sure how to report it to the PPA, let alone to the LDC packages. I'm not quite as involved in software development, just thought it'd be good courtesy to report the bug.

**Comment by abraunegg** [comment] 2020-09-04 06:26
@JesseRiemens 
Closing this issue as not a bug, but will leave it pinned here in GitHub

**Closed by abraunegg** 2020-09-04 06:26 UTC
Labels: Not a bug, Packaging, Workaround Available

**Comment by abraunegg** [comment] 2020-09-05 02:28
@JesseRiemens , @yann1cks
Just an update - tested LDC 1.20.1 as per below:
```
alex@ubuntu-20-04-LTS:~$ curl -fsS https://dlang.org/install.sh | bash -s ldc-1.20.1
Downloading https://dlang.org/d-keyring.gpg
######################################################################## 100.0%
Downloading https://dlang.org/install.sh
######################################################################## 100.0%
gpg: keybox '/home/alex/.gnupg/pubring.kbx' created
gpg: /home/alex/.gnupg/trustdb.gpg: trustdb created
The latest version of this script was installed as ~/dlang/install.sh.
It can be used it to install further D compilers.
Run `~/dlang/install.sh --help` for usage information.

Downloading and unpacking https://github.com/ldc-developers/ldc/releases/download/v1.20.1/ldc2-1.20.1-linux-x86_64.tar.xz
######################################################################## 100.0%#=#=-#  #                                                                     
Using dub 1.19.0 shipped with ldc-1.20.1

Run `source ~/dlang/ldc-1.20.1/activate` in your shell to use ldc-1.20.1.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
alex@ubuntu-20-04-LTS:~$ source ~/dlang/ldc-1.20.1/activate
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 4038 (delta 14), reused 1 (delta 0), pack-reused 4011
Receiving objects: 100% (4038/4038), 2.76 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (2780/2780), done.
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~$ cd onedrive
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~/onedrive$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... ldc2
checking version of D compiler... 1.20.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~/onedrive$ make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.6-dev > version ; \
fi
ldc2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~/onedrive$ ./onedrive --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Application version: v2.4.5-11-g4ddad0c
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1086154666056
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
Monitor directory: .
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1086154666056
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1086154666056
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection
(ldc-1.20.1)alex@ubuntu-20-04-LTS:~/onedrive$ 
```

In short - zero issue when using LDC 1.20.1 & compiling manually, so this issue is, as per I suspected:
* Issue with Ubuntu PPA package / build process
* Issue with Ubuntu LDC package

**Comment by yann1cks** [comment] 2020-09-16 14:48
Sorry for the late response. It took me some time to look into it. I used version 2.4.5 for my tests.

I repeated @abraunegg's last test using LDC 1.20.1 & compiled manually. Got the same results.

````
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ curl -fsS https://dlang.org/install.sh | bash -s ldc-1.20.1
Downloading https://dlang.org/d-keyring.gpg
######################################################################## 100,0%
Downloading https://dlang.org/install.sh
######################################################################## 100,0%
The latest version of this script was installed as ~/dlang/install.sh.
It can be used it to install further D compilers.
Run `~/dlang/install.sh --help` for usage information.

Downloading and unpacking https://github.com/ldc-developers/ldc/releases/download/v1.20.1/ldc2-1.20.1-linux-x86_64.tar.xz
######################################################################## 100,0%######################################################################### 100,0%
Using dub 1.19.0 shipped with ldc-1.20.1

Run `source ~/dlang/ldc-1.20.1/activate` in your shell to use ldc-1.20.1.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 4059 (delta 28), reused 9 (delta 6), pack-reused 4011
Receiving objects: 100% (4059/4059), 2.79 MiB | 1.77 MiB/s, done.
Resolving deltas: 100% (2794/2794), done.
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ cd onedrive
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ source ~/dlang/ldc-1.20.1/activate
(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... ldc2
checking version of D compiler... 1.20.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.6-dev > version ; \
fi
ldc2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ sudo make install
[sudo] password for onedrive: 
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md docs/BusinessSharedFolders.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user
(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ onedrive

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ onedrive --monitor
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
^CGot termination signal, shutting down db connection
(ldc-1.20.1)onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ 
````

Furthermore, I compiled manually using the [Ubuntu ldc compiler (1:1.20.1-1).](https://packages.ubuntu.com/focal/ldc) In this case the application segfaults. So the Ubuntu ldc package seems to cause the problem. 

````
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ sudo apt install ldc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libphobos2-ldc-shared-dev libphobos2-ldc-shared90
The following NEW packages will be installed:
  ldc libphobos2-ldc-shared-dev libphobos2-ldc-shared90
0 upgraded, 3 newly installed, 0 to remove and 12 not upgraded.
Need to get 11,5 MB of archives.
After this operation, 86,9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 libphobos2-ldc-shared90 amd64 1:1.20.1-1 [1.215 kB]
Get:2 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 libphobos2-ldc-shared-dev amd64 1:1.20.1-1 [6.262 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 ldc amd64 1:1.20.1-1 [4.000 kB]
Fetched 11,5 MB in 2s (6.473 kB/s)
Selecting previously unselected package libphobos2-ldc-shared90:amd64.
(Reading database ... 164670 files and directories currently installed.)
Preparing to unpack .../libphobos2-ldc-shared90_1%3a1.20.1-1_amd64.deb ...
Unpacking libphobos2-ldc-shared90:amd64 (1:1.20.1-1) ...
Selecting previously unselected package libphobos2-ldc-shared-dev.
Preparing to unpack .../libphobos2-ldc-shared-dev_1%3a1.20.1-1_amd64.deb ...
Unpacking libphobos2-ldc-shared-dev (1:1.20.1-1) ...
Selecting previously unselected package ldc.
Preparing to unpack .../ldc_1%3a1.20.1-1_amd64.deb ...
Unpacking ldc (1:1.20.1-1) ...
Setting up libphobos2-ldc-shared90:amd64 (1:1.20.1-1) ...
Setting up libphobos2-ldc-shared-dev (1:1.20.1-1) ...
Setting up ldc (1:1.20.1-1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 4059 (delta 28), reused 9 (delta 6), pack-reused 4011
Receiving objects: 100% (4059/4059), 2.79 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (2794/2794), done.
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ cd onedrive
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... no
checking for ldmd2... ldmd2
checking version of D compiler... 1.20.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ make clean; make;
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	git describe --tags > version ; \
else \
	echo v2.4.6-dev > version ; \
fi
ldmd2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ sudo make install
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md docs/BusinessSharedFolders.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user
onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~/onedrive$ sudo make install
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md docs/BusinessSharedFolders.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user

onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ onedrive

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

onedrive@onedrive-Standard-PC-Q35-ICH9-2009:~$ onedrive --monitor
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
Creating local directory: Bilder
Creating local directory: Anwendungen
Creating local directory: Bilder/Camera Roll
Creating local directory: Anwendungen/Joplin
Downloading file Anwendungen/Joplin/b73b1aeda30a458da381dcbe39bb9be0.md ... done.
Downloading file Anwendungen/Joplin/c3999f3e2bbc42209e690bc4248162f9.md ... ^CGot termination signal, shutting down db connection
Segmentation fault (core dumped)
````

Unfortunately I cannot use any other LDC version to build the PPA, because of the Launchpad restrictions. So there is no way to fix this error in the PPA. There are not nasty side effect so I wont take the PPA offline.

I know nothing about compiler development. But anyway I will report the bug upstream.

**Comment by abraunegg** [comment] 2020-09-16 19:53
@yann1cks 
> I know nothing about compiler development. But anyway I will report the bug upstream.

Thanks for confirming what I suspected. Can you please post here the link to the bug against LDC as I do not see it listed here: https://packages.ubuntu.com/focal/ldc at present.

**Comment by yann1cks** [comment] 2020-09-21 09:44
@abraunegg You can find it on Launchpad: https://launchpad.net/ubuntu/+source/ldc/+bugs

**Comment by abraunegg** [comment] 2020-09-21 21:37
@yann1cks 
Many thanks - hopefully the LDC package developers pick this up and fix it

**Comment by tribbloid** [comment] 2021-05-27 21:18
Can we use a different compiler or runtime for D?

**Comment by abraunegg** [comment] 2021-05-27 21:21
@tribbloid 
Please *do not* respond to closed threads .. 

Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
