### ISSUE TITLE
Shared Personal folder not Synced

### ISSUE THREAD

**Issue by FutureCow** [abraunegg/onedrive#323] opened 2019-01-02 13:10 UTC
### Bug Report Details ###
**Describe the bug**

**Application and Operating System Details:**
- OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
Debian Testing 4.18
- OneDrive Account Type
Personal
- DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
dmd-2.084.0
- Application version: Output of `onedrive --version`
onedrive v2.2.4-1-gbc059ea
- Application configuration: Output of `onedrive --display-config`
```
Config path                         = /home/user/.config/onedrive
Config file found in config path    = true
Config option 'sync_dir'            = /home/user/OneDrive2
Config option 'skip_file'           = .*|~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 300
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
```
**To Reproduce**
Another person shared a folder to my Personal OneDrive. This folder is inside my OneDrive account and synced. The folder does not yet exist on my local machine. When trying to sync, the folder is created, but no data is transfert. When seeing: "Applying changes of Path ID:..." This takes about 30 seconds. 
A full log is in your mail. 
I'm using syn_list to only sync one folder.

support@mynas.com.au 

**Complete Verbose Log Output**
```
user@server:~$ onedrive --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/user/.config/onedrive
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/user/OneDrive2
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: fd47324d6d16a598
Default Root ID: FD47324D6D16A598!127
Remaining Free Space: 3809129258
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: FD47324D6D16A598!127
Creating directory: Boekenuitwisseling
Applying changes of Path ID: D9DEEB2C3045413!32245
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: FD47324D6D16A598!127
Applying changes of Path ID: D9DEEB2C3045413!32245
```

**Comment by abraunegg** [comment] 2019-01-02 22:56
@FutureCow 
Unable to reproduce this issue
**config**
```
./onedrive --display-config --confdir '~/.config/onedrive-personal'                
Config path                         = /home/alex/.config/onedrive-personal
Config file found in config path    = true
Config option 'sync_dir'            = /home/alex/OneDrive
Config option 'skip_file'           = .*|~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = true
```
**sync_list**
```
cat ~/.config/onedrive-personal/sync_list 
3A/DESIGN _ BRASIL
```
**application log**
```
./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Creating directory: 3A
Applying changes of Path ID: BC7D88EC1F539DCF!107
Creating directory: 3A/DESIGN _ BRASIL
Creating directory: 3A/DESIGN _ BRASIL/asdf
Creating directory: 3A/DESIGN _ BRASIL/qwerqwer
Creating directory: 3A/DESIGN _ BRASIL/qwer
Downloading file 3A/DESIGN _ BRASIL/asdf/Document.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwerqwer/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwer/Document1.docx ... done.
Creating directory: 3A/DESIGN _ BRASIL/asdf/1
Creating directory: 3A/DESIGN _ BRASIL/asdf/2
Creating directory: 3A/DESIGN _ BRASIL/qwerqwer/1
Creating directory: 3A/DESIGN _ BRASIL/qwerqwer/2
Creating directory: 3A/DESIGN _ BRASIL/qwer/2
Creating directory: 3A/DESIGN _ BRASIL/qwerqwer/ggggggg
Creating directory: 3A/DESIGN _ BRASIL/qwer/1
Creating directory: 3A/DESIGN _ BRASIL/qwer/ggggggg
Downloading file 3A/DESIGN _ BRASIL/asdf/1/Document.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/asdf/2/Document.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwerqwer/1/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwerqwer/2/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwer/2/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwerqwer/ggggggg/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwer/1/Document1.docx ... done.
Downloading file 3A/DESIGN _ BRASIL/qwer/ggggggg/Document1.docx ... done.
Creating directory: 3A/DESIGN _ BRASIL/SMPP
Downloading file 3A/DESIGN _ BRASIL/SMPP/SMPP-IF-SPEC_v3_3-24858.pdf ... done.
Downloading file 3A/DESIGN _ BRASIL/SMPP/SMPP_v3_4_Issue1_2-24857.pdf ... done.
Uploading differences of .
Processing root
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: BC7D88EC1F539DCF!107
```

**Comment by norbusan** [comment] 2019-01-03 04:09
Me neither, I tried myself and cannot reproduce this

**Comment by abraunegg** [comment] 2019-01-03 21:46
@FutureCow 
Please can you test the following PR for your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/327/head:pr327
git checkout pr327
make
make install
```
When running please use the following command line:
```
./onedrive --synchronize <+any of your CLI switches> --verbose --verbose --force-http-1.1
```

If you can provide the entire log output (no need to use `--debug-https`) that would be greatly appreciated.

**Comment by FutureCow** [comment] 2019-01-04 08:39
Here is the debug log:

`[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/frans
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/frans/.config
[DEBUG] configDirName: Configuring application to use default config path
Loading config ...
Using Config Dir: /home/frans/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/frans/OneDrive2
Initializing the OneDrive API ...
[DEBUG] Downgrading all HTTP operations to HTTP 1.1
Opening the item database ...
All operations will be performed in: /home/frans/OneDrive2
[DEBUG] Loading user configured sync_list file ...
[DEBUG] sync_list: Boekenuitwisseling
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: fd47324d6d16a598
Default Root ID: FD47324D6D16A598!127
Remaining Free Space: 3807857580
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: FD47324D6D16A598!127
[DEBUG] Sync Folder Name: root
[DEBUG] Number of changes from OneDrive to process: 0
Applying changes of Path ID: D9DEEB2C3045413!32245
[DEBUG] Sync Folder Name: Boekenuitwisseling
[DEBUG] Number of changes from OneDrive to process: 200
[DEBUG] The item we are syncing is a folder
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
`
The last line ([DEBUG] Skipping OneDrive change as this is determined to be unwanted) is repeated 200 times.

**Comment by abraunegg** [comment] 2019-01-04 09:39
@FutureCow 
With this version do the files / folders download as expected?

**Comment by FutureCow** [comment] 2019-01-04 09:49
No, folder is still empty

**Comment by abraunegg** [comment] 2019-01-04 20:05
@FutureCow 
OK .. will have to dig into why the 'matching' is not working for you.

Can you also validate at your end that your 'sync_list' file & contents contains not extra space characters (trailing white space etc).

**Comment by FutureCow** [comment] 2019-01-04 21:03
I also tried to remove the sync_list and you the --download-only option. Same results as above.

**Comment by abraunegg** [comment] 2019-01-04 21:04
@FutureCow 
OK - will create a new PR that has extreme debugging - will need you to rebuild and provide that log via email please

**Comment by FutureCow** [comment] 2019-01-04 21:31
Here a part of the debug log:

> [DEBUG] Sync Folder Name: Boekenuitwisseling
[DEBUG] Number of changes from OneDrive to process: 200
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhMzIyNDUuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITMyMjQ1Ljk","fileSyste$
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a folder
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjMuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjIzLjI","fileSyste$
[DEBUG] Change matches search criteria to apply
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjI0LjI","fileSyste$
[DEBUG] Change matches search criteria to apply
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNjI3NjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITYyNzY0LjE","fileSyste$
[DEBUG] Change matches search criteria to apply
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNjQ2ODcuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITY0Njg3LjE","fileSyste$
[DEBUG] Change matches search criteria to apply

**Comment by abraunegg** [comment] 2019-01-04 21:31
@FutureCow 
Please can you compile and run this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/328/head:pr328
git checkout pr328
make
```
Please use this command to run:

```
./onedrive --synchronize <+any of your CLI switches> --verbose --verbose --force-http-1.1 --resync
```

**Note:** Adding the `--resync` to force your database to be rebuilt.

Please can you you provide the output from this version for analysis.

**Comment by FutureCow** [comment] 2019-01-04 21:35
See comment above, send full debug to your mail.

**Comment by abraunegg** [comment] 2019-01-04 21:42
@FutureCow 
Did you add the `--resync`  when running the above command?

If not, can you delete the 'items.sqlite3' file so the local database get's re-created totally.

**Comment by FutureCow** [comment] 2019-01-04 21:45
Yes, --resync was added to the command line

**Comment by FutureCow** [comment] 2019-01-04 22:06
Rebuild, here a part of the debug log:

> Applying changes of Path ID: D9DEEB2C3045413!32245
[DEBUG] Sync Folder Name: Boekenuitwisseling
[DEBUG] Number of changes from OneDrive to process: 200
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhMzIyNDUuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITMyMjQ1Ljk","fileSystemInfo":{"createdDateTime":"2015-12-02T17:59:30Z","lastModifiedDateTime":"2018-01-17T08:07:16.96Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!107"},"size":599706621}
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a folder
[DEBUG] Flagging as unwanted: item.driveId, item.parentId not in local database
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjMuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjIzLjI","fileSystemInfo":{"createdDateTime":"2018-01-06T21:45:49Z","lastModifiedDateTime":"2018-01-17T08:07:26.96Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!72623","name":"Boeken","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:"},"size":578572199}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - Boeken
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjI0LjI","fileSystemInfo":{"createdDateTime":"2018-01-06T21:46:02Z","lastModifiedDateTime":"2018-12-30T11:43:32.2Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!72624","name":"Rest","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:"},"size":21134422}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - Rest
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNjI3NjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITYyNzY0LjE","fileSystemInfo":{"createdDateTime":"2018-01-05T15:02:28Z","lastModifiedDateTime":"2018-01-05T15:45:08Z"},"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!62764","name":"James Oswald","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!72623","name":"Boeken","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:\/Boeken"},"size":14861839}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - James Oswald
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNjQ2ODcuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITY0Njg3LjE","fileSystemInfo":{"createdDateTime":"2018-01-05T15:02:28Z","lastModifiedDateTime":"2018-01-05T15:45:14Z"},"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!64687","name":"Kobo","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!72624","name":"Rest","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:\/Rest"},"size":15916074}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - Kobo
[DEBUG] Skipping OneDrive change as this is determined to be unwanted

**Comment by abraunegg** [comment] 2019-01-04 22:55
@FutureCow 
OK .. this gives me something now to work on.

In the meantime, to rule this 'out' as an API issue, can you 'remove' your shared folder 'Boekenuitwisseling' from your OneDrive (you will not loose any data), then re-add it?

Once done, can you re-test and respond back?

**Comment by FutureCow** [comment] 2019-01-04 23:02
Debug not relly different:
```
Creating directory: Boekenuitwisseling
.....
[DEBUG] Sync Folder Name: Boekenuitwisseling
[DEBUG] Number of changes from OneDrive to process: 200
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhMzIyNDUuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITMyMjQ1Ljk","fileSystemInfo":{"createdDateTime":"2015-12-02T17:59:30Z","lastModifiedDateTime":"2018-01-17T08:07:16.96Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!107"},"size":599706621}
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a folder
[DEBUG] Flagging as unwanted: item.driveId, item.parentId not in local database
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjMuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjIzLjI","fileSystemInfo":{"createdDateTime":"2018-01-06T21:45:49Z","lastModifiedDateTime":"2018-01-17T08:07:26.96Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!72623","name":"Boeken","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:"},"size":578572199}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - Boeken
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNzI2MjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITcyNjI0LjI","fileSystemInfo":{"createdDateTime":"2018-01-06T21:46:02Z","lastModifiedDateTime":"2018-12-30T11:43:32.2Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!72624","name":"Rest","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32245","name":"Boekenuitwisseling","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:"},"size":21134422}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - Rest
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpEOURFRUIyQzMwNDU0MTMhNjI3NjQuNjM2ODIxMTUyMTM5NjAwMDAw","eTag":"aRDlERUVCMkMzMDQ1NDEzITYyNzY0LjE","fileSystemInfo":{"createdDateTime":"2018-01-05T15:02:28Z","lastModifiedDateTime":"2018-01-05T15:45:08Z"},"folder":{"childCount":0,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"D9DEEB2C3045413!62764","name":"James Oswald","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!72623","name":"Boeken","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:\/Boeken"},"size":14861839}
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] Flagging as unwanted: item name is excluded - James Oswald
[DEBUG] Skipping OneDrive change as this is determined to be unwanted

**Comment by abraunegg** [comment] 2019-01-04 23:07
Thanks - just wanted to rule out some sort of API change when adding shared folders as I cannot reproduce this, but now have the data to fix. 

Thanks.

**Comment by abraunegg** [comment] 2019-01-04 23:44
@FutureCow 
Can you please rebuild with the latest PR #328 

Application version should be `v2.2.4-8-gdf8ada2` & hopefully this resolves your issue.

If you can test with the following command line that would be greatly appreciated:
```
./onedrive --synchronize <+any of your CLI switches> --verbose --verbose --force-http-1.1 --resync
```

**Comment by abraunegg** [comment] 2019-01-05 04:50
@FutureCow 
Appreciate the patience here, however I feel I have gotten to the bottom of this issue.

Can you please rebuild with the latest PR #328

Application version should be `v2.2.4-15-g37b3c76` & this should resolve your issue.

If you can test with the following command line that would be greatly appreciated:
```
./onedrive --synchronize <+any of your CLI switches> --verbose --verbose --force-http-1.1 --resync
```

**Comment by FutureCow** [comment] 2019-01-05 08:34
Yes! the last PR is workinf for me.

onedrive --version: onedrive v2.2.4-17-gbf28e84

Debug log (Do you need a full debug?):
```
Creating directory: Boekenuitwisseling/Boeken/Dorrestein, Renate
[DEBUG] Inserting item details to local database
[DEBUG] item details: Item("d9deeb2c3045413", "D9DEEB2C3045413!33087", "Dorrestein, Renate", dir, "aRDlERUVCMkMzMDQ1NDEzITMzMDg3LjE", "adDpEOURFRUIyQzMwNDU0MTMhMzMwODcuNjM2ODIxMTUyMTM5NjAwMDAw", 2018-Jan-05 15:02:28Z, "D9DEEB2C3045413!72623", "", "", "", "", "")
[DEBUG] ------------------------------------------------------------------
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzpEOURFRUIyQzMwNDU0MTMhMzI0MTYuMjU3","eTag":"aRDlERUVCMkMzMDQ1NDEzITMyNDE2LjM","file":{"hashes":{"crc32Hash":"BC9A903B","sha1Hash":"0EA2790F26716DF4DBED291CA39A3AC6640D31A9"},"mimeType":"application\/pdf","processingMetadata":true},"fileSystemInfo":{"createdDateTime":"2015-12-02T18:13:21Z","lastModifiedDateTime":"2009-09-08T06:48:00Z"},"id":"D9DEEB2C3045413!32416","name":"Trevayne.pdf","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32390","name":"LUDLUM","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:\/Boeken\/LUDLUM"},"size":1173604}
[DEBUG] 'search id'                                       = D9DEEB2C3045413!32245
[DEBUG] 'parentReference id'                              = D9DEEB2C3045413!32390
[DEBUG] syncFolderPath                                    = 
[DEBUG] syncFolderChildPath                               = 
[DEBUG] thisItemPath                                      = /drives/d9deeb2c3045413/items/D9DEEB2C3045413!32245:/Boeken/LUDLUM
[DEBUG] 'item id' matches search 'id'                     = false
[DEBUG] 'parentReference id' matches search 'id'          = false
[DEBUG] 'item path' contains 'syncFolderChildPath'        = true
[DEBUG] 'item path' contains search 'id'                  = true
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a file
[DEBUG] sql query:    SELECT * FROM item WHERE driveId = d9deeb2c3045413 AND id = D9DEEB2C3045413!32390
[DEBUG] sql response: [["d9deeb2c3045413", "D9DEEB2C3045413!32390", "LUDLUM", "dir", "aRDlERUVCMkMzMDQ1NDEzITMyMzkwLjE", "adDpEOURFRUIyQzMwNDU0MTMhMzIzOTAuNjM2ODIxMTUyMTM5NjAwMDAw", "2018-01-05T15:03:37Z", "D9DEEB2C3045413!72623", "", "", "", "", "", ""]]
[DEBUG] OneDrive change is a new local item
Downloading file Boekenuitwisseling/Boeken/LUDLUM/Trevayne.pdf ... done.
[DEBUG] Inserting item details to local database
[DEBUG] item details: Item("d9deeb2c3045413", "D9DEEB2C3045413!32416", "Trevayne.pdf", file, "aRDlERUVCMkMzMDQ1NDEzITMyNDE2LjM", "aYzpEOURFRUIyQzMwNDU0MTMhMzI0MTYuMjU3", 2009-Sep-08 06:48:00Z, "D9DEEB2C3045413!32390", "BC9A903B", "", "", "", "")
[DEBUG] ------------------------------------------------------------------
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzpEOURFRUIyQzMwNDU0MTMhMzI0MTcuMjU3","eTag":"aRDlERUVCMkMzMDQ1NDEzITMyNDE3LjM","file":{"hashes":{"crc32Hash":"FF5CD060","sha1Hash":"2B888369F21F9008FD798BEF622BB76540F0A194"},"mimeType":"application\/pdf","processingMetadata":true},"fileSystemInfo":{"createdDateTime":"2015-12-02T18:13:21Z","lastModifiedDateTime":"2009-09-08T06:48:00Z"},"id":"D9DEEB2C3045413!32417","name":"The Scorpio Illusion.pdf","parentReference":{"driveId":"d9deeb2c3045413","driveType":"personal","id":"D9DEEB2C3045413!32390","name":"LUDLUM","path":"\/drives\/d9deeb2c3045413\/items\/D9DEEB2C3045413!32245:\/Boeken\/LUDLUM"},"size":1553779}
[DEBUG] 'search id'                                       = D9DEEB2C3045413!32245
[DEBUG] 'parentReference id'                              = D9DEEB2C3045413!32390
[DEBUG] syncFolderPath                                    = 
[DEBUG] syncFolderChildPath                               = 
[DEBUG] thisItemPath                                      = /drives/d9deeb2c3045413/items/D9DEEB2C3045413!32245:/Boeken/LUDLUM
[DEBUG] 'item id' matches search 'id'                     = false
[DEBUG] 'parentReference id' matches search 'id'          = false
[DEBUG] 'item path' contains 'syncFolderChildPath'        = true
[DEBUG] 'item path' contains search 'id'                  = true
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a file
[DEBUG] sql query:    SELECT * FROM item WHERE driveId = d9deeb2c3045413 AND id = D9DEEB2C3045413!32390
[DEBUG] sql response: [["d9deeb2c3045413", "D9DEEB2C3045413!32390", "LUDLUM", "dir", "aRDlERUVCMkMzMDQ1NDEzITMyMzkwLjE", "adDpEOURFRUIyQzMwNDU0MTMhMzIzOTAuNjM2ODIxMTUyMTM5NjAwMDAw", "2018-01-05T15:03:37Z", "D9DEEB2C3045413!72623", "", "", "", "", "", ""]]
[DEBUG] OneDrive change is a new local item
Downloading file Boekenuitwisseling/Boeken/LUDLUM/The Scorpio Illusion.pdf ... done.
[DEBUG] Inserting item details to local database
[DEBUG] item details: Item("d9deeb2c3045413", "D9DEEB2C3045413!32417", "The Scorpio Illusion.pdf", file, "aRDlERUVCMkMzMDQ1NDEzITMyNDE3LjM", "aYzpEOURFRUIyQzMwNDU0MTMhMzI0MTcuMjU3", 2009-Sep-08 06:48:00Z, "D9DEEB2C3045413!32390", "FF5CD060", "", "", "", "")
[DEBUG] ------------------------------------------------------------------

**Comment by abraunegg** [comment] 2019-01-05 21:02
@FutureCow 
Can you please rebuild with the latest PR #328

Everything should be working normally, thus you should only need this command:

```
./onedrive --synchronize <+any of your CLI switches> --verbose
```

If your curl version is >= 7.62.0 please also add `--force-http-1.1` to the above.

**Comment by FutureCow** [comment] 2019-01-06 07:32
onedrive v2.2.4-24-g5f96340 (want some debug?) 

This is still working great, thank you for your time investigating this problem, was there a specific issue with my onedrive so you couldn't reproduce is? 
Again thank you very much!

**Comment by abraunegg** [comment] 2019-01-06 07:40
> onedrive v2.2.4-24-g5f96340 (want some debug?)
> 
> This is still working great, thank you for your time investigating this problem, was there a specific issue with my onedrive so you couldn't reproduce is?
> Again thank you very much!

All good - it is working so no more debug needed :)

Yes this was a specific issue which could not be replicated locally, despite best efforts. This issue & #324 were the same, but coming from different angles - but same root cause. 

I suspect that there is a OneDrive API change behind this which is slowly being rolled out amongst users which is why I was not able to reproduce this, but also explains #330 occuring today.

**Comment by abraunegg** [comment] 2019-01-06 16:04
Closing as PR #328 merged

**Closed by abraunegg** 2019-01-06 16:04 UTC
Labels: Bug, Fixed, OneDrive Personal
