### ISSUE TITLE
Bug: EXPKEYSIG Error when running apt update on the opensuse site

### ISSUE THREAD

**Issue by jtrelfa** [abraunegg/onedrive#2775] opened 2024-08-14 14:50 UTC
### Describe the bug

I followed the instructions here https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
and when I run apt update, it fails with this:

```
Err:12 https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04 ./ InRelease
  The following signatures were invalid: EXPKEYSIG B8AC39B0876D807E home:npreining OBS Project <home:npreining@build.opensuse.org>

W: GPG error: https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG B8AC39B0876D807E home:npreining OBS Project <home:npreining@build.opensuse.org>
E: The repository 'https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04 ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

### Operating System Details

```shell
$>uname -a
Linux MSI 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

$>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

Not installed

### What is your OneDrive Application Configuration

```shell
I can't install it
```

### What is your 'curl' version

```shell
$>curl --version
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
N/A
```

### What are all your local file system partition types

```shell
N/A
```

### How do you use 'onedrive'

I can't install it... N/A

### Steps to reproduce the behaviour

Follow the instructions on the install.md for ubuntu 22.04

### Complete Verbose Log Output

```shell
N/A
```

**Comment by MRDGH2821** [comment] 2024-08-14 16:33
Can confirm, facing the same issue:
![image](https://github.com/user-attachments/assets/82e41c87-47dc-4372-b3e7-5931378d648a)

**Comment by jtrelfa** [comment] 2024-08-14 16:50
I was able to do a workaround without using apt install:

1. Downloaded the .deb https://download.opensuse.org/repositories/home:/npreining:/debian-ubuntu-onedrive/xUbuntu_22.04/amd64/onedrive_2.4.25-1+np2+4.1_amd64.deb
2. sudo dpkg -i onedrive_2.4.25-1+np2+4.1_amd64.deb
3. I had an issue with libphobos2-ldc-shared98 and one of its requirements so I did sudo apt --fix-broken install and that cleared up those particular issues (probably unrelated)
4. Everything fired up and was good

**Comment by MRDGH2821** [comment] 2024-08-14 17:07
I use [Nala](https://github.com/volitank/nala), so I could install without any hassles.

It still shows the same problem of the key, but everything works well.

**Comment by aravindprasad** [comment] 2024-08-14 19:17
Signature has expired on 2024-08-13

**Comment by abraunegg** [comment] 2024-08-14 19:58
**TO ALL**
This is not a *bug* with this GitHub repo or application.

This is a *packaging* issue. @norbusan is aware of this and when available will look into the issue.

Closing this issue as a duplicate of https://github.com/abraunegg/onedrive/issues/2773

**Closed by abraunegg** 2024-08-14 19:58 UTC
Labels: Bug

**Comment by abraunegg** [comment] 2024-08-15 03:24
Issue has been resolved. With many thanks to @norbusan 

Please refer to https://github.com/abraunegg/onedrive/issues/2773 for details.
