### ISSUE TITLE
Cannot upload file changes/creation: <some_path>/4913: No such file or directory

### ISSUE THREAD

**Issue by petobens** [abraunegg/onedrive#1595] opened 2021-08-07 15:04 UTC
### Bug Report Details ###
**Describe the bug**

Whenever I save a file I get an error saying: 
```
Aug 07 11:52:25 Matebook-X-Pro onedrive[1296]: Cannot upload file changes/creation: <some_path>/4913: No such file or directory
```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`: `Linux Matebook-X-Pro 5.13.8-arch1-1 #1 SMP PREEMPT Wed, 04 Aug 2021 16:57:44 +0000 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed? No Gui
*   OneDrive Account Type: Standard
*   Did you build from source or install from a package? From the AUR
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   OneDrive Application Version: Output of `onedrive --version`: `onedrive v2.4.13
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.13
Config path                            = /home/pedro/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/pedro/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp|*.swp|#*
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 180
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`: `curl 7.78.0 (x86_64-pc-linux-gnu) libcurl/7.78.0 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.5.0 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.44.0`
*   Is your configured 'sync_dir' a local directory or a network mount point? Local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f`: hoe
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time -> just local folder with unique account/user

**To Reproduce**
I simply open some file in vim (such as a markdown file) and write it with `:write` and then I get the notification with the aforementioned error.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```
There is nothing weird seen with the command above.. when running with monitor I see the following in the logs:
```
-- Journal begins at Sat 2021-07-17 13:43:20 -03. --
Aug 07 11:51:21 Matebook-X-Pro onedrive[1296]: Uploading new file teaching/ieee/notes/.mypy_cache/.gitignore ... done.
Aug 07 11:51:59 Matebook-X-Pro onedrive[1296]: Uploading new file ./varios/todos_mutt.md ... done.
Aug 07 11:52:03 Matebook-X-Pro onedrive[1296]: Uploading new file ./teaching/ieee/notes/notes.md ... done.
Aug 07 11:52:04 Matebook-X-Pro onedrive[1296]: Uploading new file ./teaching/ieee/notes/foo.py ... done.
Aug 07 11:52:25 Matebook-X-Pro onedrive[1296]: Cannot upload file changes/creation: teaching/ieee/notes/4913: No such file or directory
Aug 07 11:52:26 Matebook-X-Pro onedrive[1296]: Deleting item from OneDrive: teaching/ieee/notes/notes.md
Aug 07 11:55:06 Matebook-X-Pro onedrive[1296]: Starting a sync with OneDrive
Aug 07 11:55:06 Matebook-X-Pro onedrive[1296]: Syncing changes from OneDrive ...
Aug 07 11:55:23 Matebook-X-Pro onedrive[1296]: Uploading new file ./teaching/ieee/notes/notes.md ... done.
Aug 07 11:55:25 Matebook-X-Pro onedrive[1296]: Sync with OneDrive is complete
```

**Screenshots**

![Peek 2021-08-07 12-02](https://user-images.githubusercontent.com/2583971/128604576-7aff5304-a3c0-404a-a6f8-b8cfad872648.gif)

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-08-07 20:08
@petobens 

The client is complaining that the local directory or file '4913' does not exist - as this 'may' be a temporary file due to how you are creating files - and is temporary for a very short time, but still long enough for the client to look for & then complain that it is missing.

Can you please provide a complete verbose debug log as per the support requirements: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support 

Please stop any systemd services before running the client manually to generate the verbose debug log whilst replicating the issue.

**Comment by petobens** [comment] 2021-08-08 13:27
Hi @abraunegg thanks for the pointers! Vim/nvim was indeed creating a temporary `4913` file as per https://github.com/neovim/neovim/issues/3460.. adding that to the `skip_file` config seems to have solved my problem. Feel free to close this one if you deem fit.

**Comment by abraunegg** [comment] 2021-08-08 19:10
Closing issue, not a bug or issue

**Closed by abraunegg** 2021-08-08 19:10 UTC
Labels: Not a bug
