### ISSUE TITLE
How to skip folders

### ISSUE THREAD

**Issue by FedericoFontana** [abraunegg/onedrive#393] opened 2019-02-27 17:28 UTC
**Is your feature request related to a problem? Please describe.**
Similar to [issue #159](https://github.com/abraunegg/onedrive/issues/159). My goal is to skip any kind of synchronization for all folders name `.venv` in any subdirectory level within the main directory `OneDrive`.

**Describe the solution you'd like**
Add a skip_dir option in the configuration file. A solution might look like `skip_dir="*/.venv/*"`.

**Describe alternatives you've considered**
There is the option to use `skip_file="<file_name>"`, but this is not practical when the number of files is large.

**Comment by abraunegg** [comment] 2019-02-27 18:27
@FedericoFontana 
Flagging this as a duplicate of #123 

If you can help test the following PR which implements this feature:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/388/head:pr388
git checkout pr388
make
```

If you are able to test this PR, and report back that would be greatly appreciated.

Please use this against a **TEST** OneDrive account - as I would currently call this feature **BETA** quality as I have only tested it. 

The feature currently does what it "should" do in my test cases, however this needs some extensive testing & confirmation that there is no undesirable bug which could cause data to be lost.

**Note:** The current PR #388 expects the director match to be an "exact" patch match, so it is not going to deliver "exactly what you want.

On top of this, PR #390 implements another capability - skip any directory where a .nosync file is found:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/390/head:pr390
git checkout pr390
make
```

In each of your .venv folders, you could create the .nosync file and this would be skipped

**Comment by abraunegg** [comment] 2019-03-12 08:11
@FedericoFontana 
Have you been able to test the proposed PR?

**Comment by abraunegg** [comment] 2019-03-14 19:56
Closing issue as PR #388 merged

**Closed by abraunegg** 2019-03-14 19:56 UTC
Labels: Duplicate, PR Provided - Needs Testing
