### ISSUE TITLE
--upload-only removes files from OneDrive when they do not exist locally

### ISSUE THREAD

**Issue by iminet** [abraunegg/onedrive#959] opened 2020-06-20 09:59 UTC
Hey Developers,

This app has a massive bug: wanted to remove everything with the upload only command. Removed 64 GB of data instead of uploading a single file.

For trying this, I've put a file to my empty local OneDrive folder and tried the command: 
`onedrive --synchronize --upload-only`
Upload only!!
So the application started to remove everything. I almost lost 64 GB, but fortunately got back from the trash.

Please take a look at this issue. I something says me: upload only, it means for me: upload, not delete. Thanks!

**Comment by abraunegg** [comment] 2020-06-20 10:28
@iminet 
Whilst I appreciate that you have an issue .. you do not provide any details as per https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues

Please update your post above with the required details.

**Comment by iminet** [comment] 2020-06-20 10:40
### Bug Report Details ###
This app has a massive bug: wanted to remove everything with the upload only command. Removed 64 GB of data instead of uploading a single file.

For trying this, I've put a file to my empty local OneDrive folder and tried the command:
`onedrive --synchronize --upload-only`
Upload only!!
So the application started to remove everything. I almost lost 64 GB, but fortunately got back from the trash.

**Application and Operating System Details:**
*   OS: 
`Linux imiserver.home.iminet.hu 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux & Raspbian 10`
*   Are you using a headless system (no gui) or with a gui installed?
Headless, no GUI
*   OneDrive Account Type
Private
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
LDC - the LLVM D compiler (1.16.0):
  based on DMD v2.086.1 and LLVM 7.0.0
  built with LDC - the LLVM D compiler (1.16.0)
  Default target: arm-unknown-linux-gnueabihf
  Host CPU: cortex-a72
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    arm     - ARM
    armeb   - ARM (big endian)
    thumb   - Thumb
    thumbeb - Thumb (big endian)
    wasm32  - WebAssembly 32-bit
    wasm64  - WebAssembly 64-bit
*   Application configuration: Output of `onedrive --display-config`
Configuration file successfully loaded
onedrive version                       = v2.4.2-17-g9316305
Config path                            = /home/imi/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/imi/Storage/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = true
sync_list contents:
Temp
*   Curl Version: Output of `curl --version`
curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  `mkdir Temp`
2. `cp [somefile] [to the folder you can see above]`
3.  `onedrive --synchronize --upload-only`

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Creating local directory: Temp
Trying to delete item Galéria/Filmtekercs
Trying to delete item Galéria
Trying to delete item Symlinked
^C

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2020-06-20 11:09
@iminet 
Thanks .. OK .. this is not the 'bug' you think this is. This is actually not a bug.

In 'normal' operation, the client does the following:
* Download changes from OneDrive to replicate online state locally
* Upload any delta changes locally to OneDrive
* True-Up Download sync to ensure local matches what is now being reported online

There are 2 ways to change this behavior:
* `--download-only`
  * Download the online OneDrive folder state to the locally configured folder. Delete any local data that is not present on OneDrive. Do not upload any local data.
* `--upload-only`
  * Upload to OneDrive the local folder, replicating the local state on OneDrive. Any data missing locally, but found on OneDrive will be deleted.

Now to your 'bug' .. this is not a bug. The client is working 100% correctly replicating the local state to the remote location as you are only using `--upload-only`

However, you do not want your 'existing' data (that does not appear locally) to be removed. To enforce this, you need to utilise the `--no-remote-delete` flag as well. so that files & folders not present locally, will not be removed from OneDrive.

So for your situation, your command should be:
```
onedrive --synchronize --upload-only --no-remote-delete
```


Please refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#all-available-commands for further details and reference

**Comment by abraunegg** [comment] 2020-06-20 11:16
@iminet 
Additionally, please also utilise the `--dry-run` capability to *test* any configuration before you run it .. this is why this option exists to provide this capability to avoid heartache / accidental deletion of data when performing configuration changes.

**Comment by iminet** [comment] 2020-06-20 11:23
> @iminet
> Additionally, please also utilise the `--dry-run` capability to _test_ any configuration before you run it .. this is why this option exists to provide this capability to avoid heartache / accidental deletion of data when performing configuration changes.

Ok, understand... I have to study the documentation more deeply.
But... I have to tell you, your support is five stars! I've never got such fast and detailed answers here in Github, thank you very much!

By the way...
May I have another question or do I rather need to open a new ticket?

**Comment by abraunegg** [comment] 2020-06-20 11:28
@iminet 
Sure .. what is the question .. fire away

**Comment by iminet** [comment] 2020-06-20 11:34
@abraunegg 

I've tried two another ways, but it seems, sync is too slow.

### First:
- Created a sync_list, and put a single folder into (Temp)
- Ran this command `onedrive --synchronize --verbose` (first with --resync, then without it)

I've got a lot of outputs similar these:
```
Skipping item - excluded by sync_list config: Galériaaa
Skipping item - excluded by sync_list config: Backup
Skipping item - excluded by sync_list config: Mobil
Skipping item - excluded by sync_list config: Képek
Skipping item - excluded by sync_list config: Galéria
...
```
A lot... It has been taken for half an hour or more, even I had a single folder within a single file.

### Second:
`onedrive --synchronize --single-directory Temp --verbose`
May be the similar variant of it.

Output:
```
Remote change discarded - not in --single-directory sync scope
Remote change discarded - not in --single-directory sync scope
....
```
Took similar to the first (or more..)

Why does it take for a long time if I need to syn a small folder only? Okay, I know, I have a massive account with 108 GB of data and a thousands of other files/folders.
Why the app cannot skip those files I don't want to sync?

Thanks!

**Comment by abraunegg** [comment] 2020-06-20 11:47
@iminet 
The issue here is the following:
* First time sync
* Using `--resync`

When you first use the application, the application has to go through your entire OneDrive contents online, to know what it needs to sync locally. Once it has done this once, if has a cache file that makes this operation quicker.

If you use `--resync` ... you are putting yourself back to point 1 .... ie .. dont use resync unless the application tells you to.

OK .. to your question .. syncing 1 folder. If you use 'sync_list' .. then, because of the way this works, if has to 'constantly' rescan what is in-scope / out-of-scope. Good for 'many file / folder' inclusion .. but not good for just one folder ... wrong choice. When it is processing OneDrive objects for applicability, this is why you are seeing this:
```
Skipping item - excluded by sync_list config: Galériaaa
```

Use `--single-directory` .. it will be faster - however, see point 1 above, first sync it has to go through your files, which is why you see:
```
Remote change discarded - not in --single-directory sync scope
```

Let it sync and do it's thing. 

So chaining your original issue & this question together:
```
onedrive --synchronize --upload-only --no-remote-delete --single-directory 'Temp' --verbose
```

You are also running `Raspbian` ... your choice of hardware here will also impact the systems ability to process  through the responses from OneDrive - I can't speed up your hardware.

**Comment by iminet** [comment] 2020-06-20 11:58
> So chaining your original issue & this question together:
> onedrive --synchronize --upload-only --no-remote-delete --single-directory 'Temp' --verbose

This is the command what I'm looking for! I want to use this program for uploading all of Raspberry Pi's backups, not for others.

Thanks again!

**Comment by abraunegg** [comment] 2020-06-20 21:19
Closing issue as question answered

**Closed by abraunegg** 2020-06-20 21:19 UTC
Labels: Answer Provided, Not a bug, Question
