### ISSUE TITLE
Bug: sync issue with skip_dotfiles = "true"

### ISSUE THREAD

**Issue by mjekdi** [abraunegg/onedrive#2276] opened 2022-12-28 20:20 UTC
### Describe the bug

I have a local test file in the sync dir that no longer exists in OneDrive cloud: ~/OneDrive/'todo - Copy.txt'

With skip_dotfiles = "true" the file is not removed:
```
onedrive --synchronize --dry-run
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
User Configured Rate Limit: 1048576
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
Sync with OneDrive is complete
```
With skip_dotfiles = "false" the file is removed:
```
onedrive --synchronize --dry-run
Configuration file successfully loaded
config file has been updated, checking if --resync needed
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
User Configured Rate Limit: 1048576
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Trying to delete item todo - Copy.txt
Deleting item todo - Copy.txt
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
Sync with OneDrive is complete
```
### Operating System Details

```shell
uname -a
Linux matt-sped 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

onedrive v2.4.22-1+np1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.22-1+np1
Config path                                  = /home/sped/.config/onedrive
Config file found in config path             = true
Config option 'sync_dir'                     = /home/sped/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = true
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 775
Config option 'sync_file_permissions'        = 664
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 1048576
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=8079052k,nr_inodes=2019763,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1622964k,mode=755,inode64)
/dev/sda2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16939)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1622960k,nr_inodes=405740,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME   FSTYPE FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sda                                                                           
├─sda1 vfat   FAT32       555E-6ED7                             505.7M     1% /boot/efi
└─sda2 ext4   1.0         63159439-5b31-4931-8f6f-1777b3793ab4  393.7G     5% /
```

### How do you use 'onedrive'

The OneDrive folder is shared across two Linux platforms and two Windows platforms at the same time.

### Steps to reproduce the behaviour

1. Set skip_dotfiles = "true"
2. Sync a file called 'todo - Copy.txt'
3. Remove the file from OneDrive cloud
4. Run onedrive --synchronize --dry-run
5. Set skip_dotfiles = "false"
6. Run onedrive --synchronize --dry-run

### Complete Verbose Log Output

```shell
I can't share verbose output due to this being a business account.
```

**Comment by abraunegg** [comment] 2022-12-29 20:15
@mjekdi 
I am unable to reproduce this bug:

### Starting Point:
Upload file, ensure it is there, no pending changes:
![File on OneDrive](https://user-images.githubusercontent.com/4956234/210005872-544f5837-b6ef-4e48-b337-89748edab46d.JPG)

```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --display-sync-status
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
No pending remote changes - in sync
[alex@onedrive-client-dev fix-issue-2276]$ 
```
No pending changes as everything is in sync.

### Remove the file from OneDrive cloud
![File Delete](https://user-images.githubusercontent.com/4956234/210005919-9d41407f-eab8-47b7-b234-5d33642983ae.JPG)
```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --display-sync-status
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Local directory is out of sync with OneDrive
[alex@onedrive-client-dev fix-issue-2276]$ 
```
### Ensure that skip_dotfiles = "true"
```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --display-config
Configuration file successfully loaded
onedrive version                             = v2.4.22-10-gad20628
Config path                                  = /home/alex/.config/onedrive-personal/
Config file found in config path             = true
Config option 'sync_dir'                     = /home/alex/OneDrivePersonal
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = true    <-- Option is correctly set
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```
### Run 'onedrive --synchronize --dry-run'
```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --dry-run
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Trying to delete item todo - Copy.txt     <-- Client attempts to delete the file ......
Deleting item todo - Copy.txt             <-- File is removed ......
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDrivePersonal
Uploading new items of ~/OneDrivePersonal
Sync with OneDrive is complete
[alex@onedrive-client-dev fix-issue-2276]$ 
```

As `--dry-run` is being used, file is technically *not* removed .. but the client would have performed that instruction to do so .....

### Set skip_dotfiles = "false"
```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --display-config       
Configuration file successfully loaded
onedrive version                             = v2.4.22-10-gad20628
Config path                                  = /home/alex/.config/onedrive-personal/
Config file found in config path             = true
Config option 'sync_dir'                     = /home/alex/OneDrivePersonal
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false    <-- Option is correctly set
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```
### Run 'onedrive --synchronize --dry-run' after config change
```
[alex@onedrive-client-dev fix-issue-2276]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --dry-run
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Trying to delete item todo - Copy.txt     <-- Client again attempts to delete the file ......
Deleting item todo - Copy.txt             <-- File again is removed ......
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDrivePersonal
Uploading new items of ~/OneDrivePersonal
Sync with OneDrive is complete
[alex@onedrive-client-dev fix-issue-2276]$ 

```
Again, as `--dry-run` is being used, file is technically *not* removed .. but the client would have performed that instruction to do so .....


So essentially I cannot reproduce this claimed issue .... 

**Note:** Because you are using ~~Crapbuntu~~ Ubuntu, and depending on when|how you installed the client (yes you are using the correct OpenSuSE Repository at the moment), in the *past* the Ubuntu packages contained a systemd installation error where an unwanted service is running in the background, essentially giving you two active running instances. This *was* fixed with the OpenSuSE repositories, so if you installed clean then you do not have this issue - if you installed a long time ago, then you will. If this is the case, please read: https://github.com/abraunegg/onedrive/issues/1274

The solution to the that issue is listed here: https://github.com/abraunegg/onedrive/issues/1274#issuecomment-813846904

**Closed by abraunegg** 2022-12-29 20:15 UTC
Labels: Bug

**Comment by mjekdi** [comment] 2022-12-29 20:40
Weird! Thanks for trying this. I will try some more troubleshooting on my end.

**Comment by abraunegg** [comment] 2023-01-06 01:56
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
