### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by jochensiegler** [abraunegg/onedrive#223] opened 2018-11-08 21:22 UTC
### Bug Report Details ###
the program has not been synced for some days

**Application and Operating System Details:**
- Linux x220t 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64 GNU/Linux
ArchLinux
- xfce4
- onedrive v2.1.4-6-geb2cbfd
- OneDrive Account personal
- DMD or LDC compiler version 
dmd --version
DMD64 D Compiler v2.083.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
jochen@x220t:~ $ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/jochen/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/jochen/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: b575f813ccb8f7ef
Default Root ID: B575F813CCB8F7EF!128
Remaining Free Space: 32208700605
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: B575F813CCB8F7EF!128
Downloading file Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg ... done.
Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg: No such file or directory
Syncing changes from OneDrive ...
Applying changes of Path ID: B575F813CCB8F7EF!128
Downloading file Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg ... done.
Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg: No such file or directory
Syncing changes from OneDrive ...
Applying changes of Path ID: B575F813CCB8F7EF!128
Downloading file Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg ... done.
std.file.FileException@/usr/include/dlang/dmd/std/file.d(1556): Bilder/Eigene Aufnahmen/2018/11/20181108_203928774_iOS.jpg: No such file or directory
----------------
??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x80ce268c]
??:? @safe void std.file.setTimes!(immutable(char)[]).setTimes(immutable(char)[], std.datetime.systime.SysTime, std.datetime.systime.SysTime) [0x80cf2e76]
??:? void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x80d2653f]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x80d25eab]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x80d25d41]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x80d2522f]
??:? void sync.SyncEngine.applyDifferences() [0x80d24261]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x80d095ea]
??:? _Dmain [0x80d08e80]

**Additional context**
I have deletes the complete files in my onedrive and started with a fresh installation. Then i uploaded a picture through mi iphone and the error was thrown.

**Comment by abraunegg** [comment] 2018-11-08 21:36
Duplicate of #220

**Closed by abraunegg** 2018-11-08 21:36 UTC
Labels: Duplicate
