### ISSUE TITLE
Bug: Can't connect to microsoft api using docker

### ISSUE THREAD

**Issue by arnaudlamy** [abraunegg/onedrive#2633] opened 2024-02-10 15:41 UTC
### Describe the bug

When I docker run -ti here's what I have:

```
Cannot connect to Microsoft OneDrive Service - Network Connection Issue
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't resolve host name on handle 56034D2C8D90
```

I double checked just in case my docker network with:

```
docker run -ti ubuntu:18.04 bash
root@2a9b92056d79:/# ping free.fr
PING free.fr (212.27.48.10) 56(84) bytes of data.
64 bytes from www.free.fr (212.27.48.10): icmp_seq=1 ttl=58 time=2.47 ms
64 bytes from www.free.fr (212.27.48.10): icmp_seq=2 ttl=58 time=3.14 ms
```

For info I already have a onedrive running on host, and I want to setup another that's why I'm using docker.

Thanks for your help

### Operating System Details

```shell

uname -a
6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

~/OneDrive % docker exec -ti onedrive_onedrive_1 sh
# /usr/local/bin/onedrive --version
onedrive v2.4.25-13-g1a88d33
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.25-13-g1a88d33

### What is your OneDrive Application Configuration

```shell
# cat config
# Directory where the files will be synced
sync_dir = "/onedrive/data"
# Skip files and directories that match this pattern
skip_file = ".~*|~*|env"
upload_only = "true"
```

### What is your 'curl' version

```shell
no curl in the docker
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
-
```

### What are all your local file system partition types

```shell
-
```

### How do you use 'onedrive'

with docker

### Steps to reproduce the behaviour

just docker run 

### Complete Verbose Log Output

```shell
Cannot connect to Microsoft OneDrive Service - Network Connection Issue
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't resolve host name on handle 56034D2C8D90
```

**Comment by arnaudlamy** [comment] 2024-02-10 15:53
Tried ip_protocol_version = "1" & ip_protocol_version = "2" didn't change anything.

**Comment by abraunegg** [comment] 2024-02-10 20:00
@arnaudlamy 
Unfortunately this is not a bug. You have a Docker networking issue that is preventing DNS and/or HTTPS from exiting your Docker environment and accessing the OneDrive API service. Please be mindful of what is a bug and what is *not* a bug as this should have been opened as a Discussion - as this is what [Discussions](https://github.com/abraunegg/onedrive/discussions) are for.

> Tried ip_protocol_version = "1" & ip_protocol_version = "2" didn't change anything.

This then just proves you have a networking issue that is preventing DNS and/or HTTP from exiting your Docker environment.

Things for you to check:
* Your Docker networking configuration
* The network route being assigned to the OneDrive Docker instance
* Your Firewall rules

Closing this issue as this is *not* a bug but a local network environment issue.

**Closed by abraunegg** 2024-02-10 20:00 UTC
Labels: Bug

**Comment by arnaudlamy** [comment] 2024-02-10 20:24
Thank you very much for your time and answer. Not sure it's linked since as I detailed, I have no issue to contact internet from another docker running. From the message I see it succeed to contact the Microsoft API since I've got a message from it. Sorry if I didn't understand something.

**Comment by abraunegg** [comment] 2024-02-10 23:42
@arnaudlamy 
> From the message I see it succeed to contact the Microsoft API since I've got a message from it. Sorry if I didn't understand something.

Your message from the application is:
```
Cannot connect to Microsoft OneDrive Service - Network Connection Issue
ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Couldn't resolve host name on handle 56034D2C8D90
```

This means that your environment cannot resolve the required hostname to connect to the OneDrive API correctly.

This means, in your environment, the OneDrive Docker image cannot resolve:
* https://login.microsoftonline.com
* https://graph.microsoft.com

This points to DNS resolution as a problem area for your environment.

So let's step through this in more detail.

1. You are using Ubuntu (your choice ... however there are way better options out there) 22.x based on your kernel version `6.5.0-14-generic`
2. What is your Docker version? Did you install Docker from Ubuntu packages (thus getting an old and bug ridden version) or did you install the *correct* way by using the more *up-to-date* Docker packages by following: https://docs.docker.com/engine/install/ubuntu/ ?
3. This specific issue is discussed at length here: https://github.com/abraunegg/onedrive/discussions/2039

The *actual* issue stems from Ubuntu. Please read: https://pascalroeleven.nl/2021/09/09/ubuntu-21-10-and-fedora-35-in-docker/

### Actions for you
1. Re-evaluate your desire to use Ubuntu as your host platform. Why use a platform that locks you into old packages with known bugs and issues under the *guise* of stability .. when those bugs and issues cause stability problems
2. Uninstall your Docker engine and install the *correct* way following the Docker instructions from https://docs.docker.com/engine/install/ubuntu/

**Comment by arnaudlamy** [comment] 2024-02-12 10:35
thx for all these details and sorry for the opening a non bug.

**Comment by abraunegg** [comment] 2024-02-20 01:25
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
