### ISSUE TITLE
Bug: Unable to retrieve user information for LDAP Users

### ISSUE THREAD

**Issue by PHeberlein** [abraunegg/onedrive#3019] opened 2024-11-29 15:41 UTC
### Describe the bug

Starting the user service via systemd for an user which signs in via ldap onedrive crashes with the error:
>```
>onedrive[64835]: object.Exception@src/util.d(1194): Failed to retrieve user information for UID: 15721
>onedrive[64835]: ----------------
>onedrive[64835]: ??:? pure @safe noreturn std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5d3c04283d63]
>onedrive[64835]: ??:? pure @safe bool std.exception.enforce!().enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5d3c04283cd7]
>onedrive[64835]: ??:? immutable(char)[] util.getUserName() [0x5d3c043a781f]
>onedrive[64835]: ??:? _Dmain [0x5d3c0427a862]
>```

### Operating System Details

```shell
Linux 6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux

LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

### Client Installation Method

From Source

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

onedrive v2.5.3

### What is your OneDrive Application Configuration

```shell
Application version                          = onedrive v2.5.3
Compiled with                                = DMD 2109
Curl version                                 = libcurl/8.11.0 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.64.0 nghttp3/1.6.0
User Application Config path                 = /home/heberlein/.config/onedrive
System Application Config path               = /etc/onedrive
Applicable Application 'config' location     = /home/heberlein/.config/onedrive/config
Configuration file found in config location  = true - using 'config' file values to override application defaults
Applicable 'sync_list' location              = /home/heberlein/.config/onedrive/sync_list
Applicable 'items.sqlite3' location          = /home/heberlein/.config/onedrive/items.sqlite3
Config option 'drive_id'                     = 
Config option 'sync_dir'                     = ~/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive
Config option 'disable_notifications'        = false
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp|*.swp|*.partial
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 12
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'disable_download_validation'  = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = 
Config option 'user_agent'                   = ISV|abraunegg|OneDrive Client for Linux/v2.5.3
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'dns_timeout'                  = 60
Config option 'connect_timeout'              = 10
Config option 'data_timeout'                 = 60
Config option 'ip_protocol_version'          = 0
Config option 'threads'                      = 8
Config option 'max_curl_idle'                = 120
Environment var 'XDG_RUNTIME_DIR'            = true
Environment var 'DBUS_SESSION_BUS_ADDRESS'   = true
Config option 'notify_file_actions'          = false

Selective sync 'sync_list' configured        = true
sync_list config option 'sync_root_files'    = true
sync_list contents:
# sync_list supports comments
#
# The ordering of entries is highly recommended - exclusions before inclusions
#
# Exclude temp folders under Documents
!/Profil/*
!/Dokumente/Meine\ Shapes/*
!/Buecher/*
!/src/*
!/Firewall/*
#

Config option 'sync_business_shared_items'   = false

Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 8.11.0 (x86_64-pc-linux-gnu) libcurl/8.11.0 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.64.0 nghttp3/1.6.0
Release-Date: 2024-11-06
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp ws wss
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
/dev/mapper/root on / type ext4 (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4096k,nr_inodes=3941965,mode=755,inode64)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=6318136k,nr_inodes=819200,mode=755,inode64)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=6871)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,nosuid,nodev,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/credentials/systemd-journald.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-network-generator.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-udev-load-credentials.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev-early.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
tmpfs on /run/credentials/systemd-sysctl.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-vconsole-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
/dev/nvme0n1p1 on /efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
tmpfs on /run/credentials/systemd-tmpfiles-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/credentials/systemd-resolved.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-networkd.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/user/15721 type tmpfs (rw,nosuid,nodev,relatime,size=3159068k,nr_inodes=789767,mode=700,uid=15721,gid=10513,inode64)
portal on /run/user/15721/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=15721,group_id=10513)
```

### What are all your local file system partition types

```shell
NAME        FSTYPE      FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
nvme0n1                                                                                 
├─nvme0n1p1 vfat        FAT32 EFI   F864-DA95                             165,4M    67% /efi
├─nvme0n1p2 crypto_LUKS 2           0be56e37-54bc-4d04-97a8-32198a90c76d                
│ └─swap    swap        1     swap  b15433bc-d3f0-408c-a6ce-b7a863903aa8                [SWAP]
└─nvme0n1p3 crypto_LUKS 2           13d3f7c0-bec3-41e3-b000-59784625595c                
  └─root    ext4        1.0   root  a2620b1d-54fa-41da-83da-ac8b878cdf4d  264,6G    37% /
```

### How do you use 'onedrive'

I use the sync between one machine and one OneDrive Bussines account. 
The OneDrive account is also used on an Windows 10 machine with the official Microsoft OneDrive app.

### Steps to reproduce the behaviour

Try to start the onedrive systemd user service on a AD domain joined machine for a domain user.
When run from a console as **onedrive --sync** it works as expected.
The join to the domain is done via samba/winbind.

### Complete Verbose Log Output

```shell
Reading configuration file: /home/heberlein/.config/onedrive/config
Configuration file successfully loaded
Using 'user' configuration path for application config and state data: /home/heberlein/.config/onedrive
D-Bus message bus daemon is available; GUI notifications are now enabled

DEPRECIATION WARNING: --synchronize has been deprecated in favour of --sync or -s
DEPRECIATION WARNING: Deprecated commands will be removed in a future release.

Using IPv4 and IPv6 (if configured) for all network operations
Attempting to contact Microsoft OneDrive Login Service
Successfully reached Microsoft OneDrive Login Service
Checking Application Version ...
Attempting to initialise the OneDrive API ...
Configuring Global Azure AD Endpoints
The OneDrive API was initialised successfully
Opening the item database ...
The item database is incompatible, re-creating database table structures
Application Version:  onedrive v2.5.3
Account Type:         business
Default Drive ID:     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Default Root ID:      XXXXXXXXXXXXXXXXXXXXXXXX
Remaining Free Space: 979.41 GB (1051638671986 bytes)
Sync Engine Initialised with new Onedrive API instance
All application operations will be performed in the configured local 'sync_dir' directory: /home/heberlein/OneDrive
Fetching /delta response from the OneDrive API for Drive ID: XXXXXXXXXXXXXXXXXXXXXXXX
Processing API Response Bundle: 1 - Quantity of 'changes|items' in this bundle to process: 201
Skipping path - excluded by sync_list config: ./Attachments
.
.
.
Finished processing /delta JSON response from the OneDrive API
Processing 2748 applicable changes and items received from Microsoft OneDrive
Processing OneDrive JSON item batch [1/6] to ensure consistent local state
Processing OneDrive JSON item batch [2/6] to ensure consistent local state
Processing OneDrive JSON item batch [3/6] to ensure consistent local state
Processing OneDrive JSON item batch [4/6] to ensure consistent local state
Processing OneDrive JSON item batch [5/6] to ensure consistent local state
Processing OneDrive JSON item batch [6/6] to ensure consistent local state
Number of items to download from Microsoft OneDrive: 1
Downloading file: ./Logs_1731428283.zip ... done
Performing a database consistency and integrity check on locally stored data
Processing DB entries for this Drive ID: XXXXXXXXXXXXXXXX
Processing: ~/OneDrive
The file has not changed
Scanning the local file system '~/OneDrive' for new data to upload

Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching /delta response from the OneDrive API for Drive ID: XXXXXXXXXXXXXXXXXXXXXXXXXX
Processing API Response Bundle: 1 - Quantity of 'changes|items' in this bundle to process: 0
Finished processing /delta JSON response from the OneDrive API
No changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
Attempting to perform a database vacuum to optimise database
Database vacuum is complete
```

### Additional context

The userid is from LDAP mapping, so there is no entry in passwd. getent works just fine and finds user information from ldap.

**Comment by abraunegg** [comment] 2024-11-29 20:21
@PHeberlein 
Please can you provide via email a little more details around your LDAP setup so that this can be reproduced in order to solve this problem.

**Comment by PHeberlein** [comment] 2024-12-02 08:28
It is basically the setup from the arch wiki:
[https://wiki.archlinux.org/title/Active_Directory_integration](https://wiki.archlinux.org/title/Active_Directory_integration)
with the rid backend for idmapping selected.

But i can send you the detailed configs if you need it.
Should i use the [support@mynas.com.au](mailto:support@mynas.com.au) address?

**Comment by abraunegg** [comment] 2024-12-02 20:35
@PHeberlein 
> It is basically the setup from the arch wiki:
https://wiki.archlinux.org/title/Active_Directory_integration
with the rid backend for idmapping selected.


This should be enough for the moment to create an environment that uses this setup.

At the moment this issue is 3rd in the list to resolve before v2.5.4 can be released.

**Comment by abraunegg** [comment] 2024-12-08 02:26
@PHeberlein 
Before I start going down a rabbit hole with this issue, please can you have a read of the following link:

https://stackoverflow.com/questions/18570177/getpwuid-returns-null-for-ldap-user

On your platform, have you installed all the required 'libnss' components - x86_64 and i686 ?

I have currently built a new Arch Linux test box + a Test Windows 2019 Active Directory, and will start connecting the two together shortly.

**Comment by abraunegg** [comment] 2024-12-09 01:45
@PHeberlein 

After following https://wiki.archlinux.org/title/Active_Directory_integration to the letter, and setting up a Windows 2016 Server, using Active Directory, I cannot replicate this issue at all.

#### Windows Active Directory Configuration
![image](https://github.com/user-attachments/assets/ea1f0e37-61a6-4d42-83a8-f11daa6d7fc5)

#### Application run, logging in via SSH, using AD User Credentials
```
[alex-domain@archlinux onedrive-master]$ ./onedrive -v -v
DEBUG: Application started
DEBUG: Process ID: 7E8B013A5220
DEBUG: User UID:   11105
DEBUG: User GID:   10513
DEBUG: User Name:  alex-domain
DEBUG: Application Version: onedrive v2.5.3-22-g2790579
DEBUG: Application Compiled With: LDC 2109
DEBUG: Passed in 'cliArgs': ["./onedrive"]
DEBUG: Note: --confdir and --verbose are not listed in 'cliArgs' array
DEBUG: Passed in --confdir if present: 
DEBUG: Passed in --verbose count if present: 2
DEBUG: runtime_environment: HOME environment variable detected, expansion of '~' should be possible
DEBUG: runtime_environment: Calculated defaultHomePath: /home/alex-domain
DEBUG: configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
DEBUG: configDirBase: /home/alex-domain/.config
DEBUG: configDirName: Configuring application to use calculated config path
DEBUG: refreshTokenFilePath =   /home/alex-domain/.config/onedrive/refresh_token
DEBUG: deltaLinkFilePath =      /home/alex-domain/.config/onedrive/delta_link
DEBUG: databaseFilePath =       /home/alex-domain/.config/onedrive/items.sqlite3
DEBUG: databaseFilePathDryRun = /home/alex-domain/.config/onedrive/items-dryrun.sqlite3
DEBUG: uploadSessionFilePath =  /home/alex-domain/.config/onedrive/session_upload
DEBUG: userConfigFilePath =     /home/alex-domain/.config/onedrive/config
DEBUG: syncListFilePath =       /home/alex-domain/.config/onedrive/sync_list
DEBUG: systemConfigFilePath =   /etc/onedrive/config
DEBUG: configBackupFile =       /home/alex-domain/.config/onedrive/.config.backup
DEBUG: configHashFile =         /home/alex-domain/.config/onedrive/.config.hash
DEBUG: syncListHashFile =       /home/alex-domain/.config/onedrive/.sync_list.hash
DEBUG: runtime_environment: XDG_RUNTIME_DIR exists with value: /run/user/11105
DEBUG: runtime_environment: DBUS_SESSION_BUS_ADDRESS exists with value: unix:path=/run/user/11105/bus
DEBUG: WARNING: D-Bus message bus daemon is not available; GUI notifications are disabled
DEBUG: Configuring Client Side Filtering (Selective Sync)
DEBUG: Configuring skip_dir ...
DEBUG: skip_dir: 
DEBUG: Selective Sync Directory Mask: Regex!char("^$", "i")
DEBUG: Configuring skip_dir_strict_match ...
DEBUG: skip_dir_strict_match: false
DEBUG: Configuring skip_dotfiles ...
DEBUG: skip_dotfiles: false
DEBUG: Configuring skip_file ...
DEBUG: skip_file: ~*|.~*|*.tmp|*.swp|*.partial
DEBUG: Selective Sync File Mask: Regex!char("^~.*$|^\\.~.*$|^.*\\.tmp$|^.*\\.swp$|^.*\\.partial$", "i")
DEBUG: sync_dir: Setting runtimeSyncDirectory from config value 'sync_dir'
DEBUG: sync_dir: A '~' was found in the configured 'sync_dir', automatically expanding as SHELL and USER environment variable is set
DEBUG: sync_dir: runtimeSyncDirectory set to: /home/alex-domain/OneDrive
DEBUG: --------------- Application Runtime Configuration ---------------
DEBUG: Application version                          = onedrive v2.5.3-22-g2790579
DEBUG: Compiled with                                = LDC 2109
DEBUG: Curl version                                 = libcurl/8.11.0 OpenSSL/3.4.0 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.64.0 nghttp3/1.6.0
DEBUG: User Application Config path                 = /home/alex-domain/.config/onedrive
DEBUG: System Application Config path               = /etc/onedrive
DEBUG: Applicable Application 'config' location     = /home/alex-domain/.config/onedrive/config
DEBUG: Configuration file found in config location  = false - using application defaults
```
```
[alex-domain@archlinux onedrive-master]$ wbinfo --user-info=alex-domain
alex-domain:*:11105:10513:alex-domain:/home/alex-domain:/bin/bash
[alex-domain@archlinux onedrive-master]$ 
```

Now .. Windows Server 2016 does not use RFC2307 extensions so I followed this as part of the Arch Linux configuration:

![image](https://github.com/user-attachments/assets/f11bfa88-bb64-492f-90ec-98c54056cd44)


Without being able to replicate this, it is difficult to make a code change to resolve - as resolving the UID|GID and fetching the username as part of that process is needed for setting up correct permissions, logging and so on.

I suspect there is something incorrect with your system at this stage.

Closing this as a local environment issue, not a bug, unable to replicate.

**Closed by abraunegg** 2024-12-09 01:45 UTC
Labels: Bug, In Progress

**Comment by PHeberlein** [comment] 2024-12-09 09:16
I understand your decision.

I did some more digging and interestingly if i use the ```onedrive@domuser.service``` method everything works correctly. I have been using the ```systemctl --user onedrive```.

So if anyone finds this in the future, try the ```@domuser``` service.

It looks like Archlinux doesn't provide a ```/usr/lib32/libnss_winbind.so.2``` so for 32bit applications ```getpwuid``` fails for winbind users. Somehow systemd can get around that if the service is run from the main systemd pid (e.g. with the ```onedrive@user``` service

**Comment by abraunegg** [comment] 2024-12-17 02:05
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
