### ISSUE TITLE
A libcurl function was given a bad argument on handle null

### ISSUE THREAD

**Issue by tyger** [abraunegg/onedrive#1154] opened 2020-11-19 23:12 UTC
### Bug Report Details ###
**Describe the bug**
Using latest master getting sudden issue from libcurl: `A libcurl function was given a bad argument on handle null`

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
  `Linux pi 5.4.72-v7l-MY_CRYPTO_KERNEL+ #1 SMP Mon Oct 19 19:42:18 BST 2020 armv7l GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?
   `headless`
*   OneDrive Account Type
   `personal`
*   Did you build from source or install from a package?
    `build from source`
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
    
*   OneDrive Application Version: Output of `onedrive --version`
    `onedrive v2.4.7-16-gac4da2e`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
 ```
Configuration file successfully loaded
onedrive version                       = v2.4.7-16-gac4da2e
Config path                            = /var/lib/onedrive/.config/onedrive-d
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /srv/dev-disk-by-label-disk/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp|.DS_Store|._.DS_Store
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/onedrive-d/
Config option 'classify_as_big_delete' = 200
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
url 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local disk
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
├─sdb2       crypto_LUKS          
│ └─extcrypt ext4        disk   523.6G    42% /srv/dev-disk-by-label-disk
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
`Rasbin OS on Raspbian Pi 4 4GB`

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Nov 19 22:55:25 reezonpi onedrive[31266]: [DEBUG] skip_dir evaluation for: /Pictures/2017
Nov 19 22:55:25 reezonpi onedrive[31266]: [DEBUG] No Strict Matching Enforced
Nov 19 22:55:25 reezonpi onedrive[31266]: Monitor directory: ./Pictures/2017
Nov 19 22:55:27 reezonpi onedrive[31266]: object.Exception@std/file.d(4020): Failed to stat file `./Pictures/2017/20170310_141230.jpg'
Nov 19 22:55:27 reezonpi onedrive[31266]: ----------------
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x152fc3]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x15e65b]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x142c2f]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x103eaf]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x105923]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x10586b]
Nov 19 22:55:27 reezonpi onedrive[31266]: monitor.d:139 [0x5898b]
Nov 19 22:55:27 reezonpi onedrive[31266]: monitor.d:140 [0x589b3]
Nov 19 22:55:27 reezonpi onedrive[31266]: main.d:999 [0x65b37]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x142863]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x14271b]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x1425ab]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? __libc_start_main [0xb6bbd717]
Nov 19 22:55:27 reezonpi onedrive[31266]: std.net.curl.CurlException@std/net/curl.d(4364): A libcurl function was given a bad argument on handle null
Nov 19 22:55:27 reezonpi onedrive[31266]: ----------------
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x152fc3]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x15e65b]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x142c2f]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x10420f]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x11dc2f]
Nov 19 22:55:27 reezonpi onedrive[31266]: onedrive.d:280 [0x61d5b]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x142863]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x14271b]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? [0x1425ab]
Nov 19 22:55:27 reezonpi onedrive[31266]: ??:? __libc_start_main [0xb6bbd717]
Nov 19 22:55:27 reezonpi systemd[1]: onedrive-d@onedrive.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 22:55:27 reezonpi systemd[1]: onedrive-d@onedrive.service: Failed with result 'exit-code'.
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2020-11-19 23:19
@tyger 
If you can provide the full debug log via email that would be greatly appreciated.

This, again will be related to your local permissions - `Failed to stat file` - but it should not crash. The full debug log will help track down where.

**Comment by abraunegg** [comment] 2020-11-20 02:40
@tyger 
In addition to the full debug log, a full file system permissions list would be great, so that I can try can replicate what is going on here.

**Comment by abraunegg** [comment] 2020-11-20 18:50
@tyger 
Any update in providing the required information so I can attempt to reproduce & fix

**Comment by tyger** [comment] 2020-11-21 15:49
I'm on it. Has got proper time only now, sorry.

**Comment by tyger** [comment] 2020-11-21 18:56
Strangely that I can see this error in `journal`:
`sudo journalctl --unit=onedrive-d@onedrive.service -n 100` almost right after service start through `systemctl`. This error is not show in the log file of the app. The process seems to be killed abruptly and systemctl says that service is loaded but unhealthy. 

When I run onedrive manually from under the same user as in systemd service I don't see anything like that.
So by doing `onedrive@pi:~ $ onedrive --confdir=/var/lib/onedrive/.config/onedrive-d --monitor --verbose --verbose > /tmp/onedrive_debug.log 2>&1`
I'm getting normal debug output in log file which ends with:
```
[DEBUG] ################################################ SYNC COMPLETE ###############################################
Sync with OneDrive is complete
[DEBUG] Merge contents of WAL and SHM files into main database file
[DEBUG] ################################################ LOOP COMPLETE ###############################################
```

Trying to figure out how to reproduce it in manual run or get more info out of it.

**Comment by abraunegg** [comment] 2020-11-21 19:15
@tyger 
To assist with tracking down what is going on:

1. Enable debug symbols: `./configure --enable-debug`
2. Can you send me the full journal output?
3. What is the permissions (files and directories) for:
    * configuration folder - typically `~/.config/onedrive/`
    * folder and file associated with error `Failed to stat file` when it pops up
4. What onedrive service are you running
    * From your log above - your systemd unit is odd .... it should be in the format of: `onedrive@<username>.service` - unless you have gone and manually changed them to 'onedrive-d' .. which in itself is odd - unsure why you would do that.
    * When the User Unit is running, what is it's effective user | group - when logged in as 'root' and you show via 'ps' - what is the systemd unit running as?
    * Does it have the right permissions to the configuration folder?
    * Does it have the right permissions to the file which was unable to be stat?

**Comment by tyger** [comment] 2020-11-21 19:54
> To assist with tracking down what is going on:
> 
>     1. Enable debug symbols: `./configure --enable-debug`
I need to rebuild service.
> 
>     2. Can you send me the full journal output?
I will try - need to check for sensitive data first.
> 
>     3. What is the permissions (files and directories) for:
>        
>        * configuration folder - typically `~/.config/onedrive/`
```bash
/var/lib/onedrive/.config $ ll
total 24K
drwxr-x--x 5 onedrive onedrive 4.0K Nov 17 08:54 ./
drwxr-x--x 3 onedrive onedrive 4.0K Nov 19 09:43 ../
drwxr-x--x 2 onedrive onedrive 4.0K Nov 21 18:56 onedrive-d/

$ ll onedrive-d
total 22M
drwxr-x--x 2 onedrive onedrive 4.0K Nov 21 18:56 ./
drwxr-x--x 5 onedrive onedrive 4.0K Nov 17 08:54 ../
-rw-r----- 1 onedrive onedrive 1.4K Nov 17 22:03 config
-rw-r--r-- 1 onedrive nogroup  1.4K Nov 17 22:03 .config.backup
-rw-r--r-- 1 onedrive nogroup    28 Nov 17 22:03 .config.hash
-rw-r--r-- 1 onedrive onedrive  10M May  3  2020 items-dryrun.sqlite3
-rw-r--r-- 1 onedrive onedrive  12M Nov 21 18:56 items.sqlite3
-rw-rw---- 1 onedrive onedrive  437 Nov 21 18:46 refresh_token;
```
>        * folder and file associated with error `Failed to stat file` when it pops up
Current state after several modifications
```
$ ll -d OneDrive/
drwxrwsr-x 21 pi users 4.0K Oct 18 20:44 OneDrive//
$ ll -d Pictures
drwxrwsr-x 84 onedrive onedrive 4.0K Nov  1 15:20 Pictures/
$ ll -d 2017
drwxrwsr-- 2 pi onedrive 68K Nov 21 17:23 2017/
$ ll 20170310_141230.jpg
-rw-r--r-- 1 onedrive onedrive 2.0M Mar 10  2017 20170310_141230.jpg
```
> 
>     4. What onedrive service are you running
>        
>        * From your log above - your systemd unit is odd .... it should be in the format of: `onedrive@<username>.service` - unless you have gone and manually changed them to 'onedrive-d' .. which in itself is odd - unsure why you would do that.
Two things:
1. Each time installing new version by `make install` onedrive@.service is overwritten dropping changes in that file, so by using different name I make it safe
2. I use two instances of service in order to sync two onedrive accounts, hence I need two separate service files.
>        * When the User Unit is running, what is it's effective user | group - when logged in as 'root' and you show via 'ps' - what is the systemd unit running as?
This is upon start:
```
onedrive  7329  0.0  0.2  34408 11068 ?        Ss   19:46   0:00 /usr/local/bin/onedrive --monitor --confdir=/var/lib/onedrive/.config/onedrive-d --verbose --verbose
```
This is when service failed I suppose:
```
onedrive  7329 62.0  0.3  41976 12936 ?        Rs   19:46   0:00 /usr/local/bin/onedrive --monitor --confdir=/var/lib/onedrive/.config/onedrive-d --verbose --verbose

onedrive  7329 49.0  0.7  56356 27524 ?        Ds   19:46   0:00 /usr/local/bin/onedrive --monitor --confdir=/var/lib/onedrive/.config/onedrive-d --verbose --verbose
```
>        * Does it have the right permissions to the configuration folder?
I think so.
>        * Does it have the right permissions to the file which was unable to be stat?
See my previous message: onedrive seems don't have any issue dealing with this file when run manually.

**Comment by abraunegg** [comment] 2020-11-21 20:09
@tyger 
It looks like that you still have special permission bits set on your files / folders - not supported. Please fix.

Also, your groups for your 'onedrive' user are not right:
* Via systemd, you are setting primary group as `nogroup`
* When running manually, most likely primary group is `onedrive`
* File / Folder permissions on file that fails: `UID: pi, GID: onedrive`

Please fix your file and folder permissions, remove any special permission bits.

When running the debug version, can you also use this PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1157/head:pr1157
git checkout pr1157
./configure; make clean; make;
```

What this adds is additional debugging output in `--monitor` mode around when a file / folder is being checked with inotify.

**Comment by tyger** [comment] 2020-11-21 20:25
@abraunegg 
yes, I did remove all those extra bits from folders when was debugging previous problem, but then it worked without issue until I bumped into this issue. 
I will normalise it and try again.

**Comment by tyger** [comment] 2020-11-21 20:28
This is my service file:
```
# /lib/systemd/system/onedrive-d@.service
[Unit]
Description=OneDrive Free Client for %i on K
Documentation=https://github.com/abraunegg/onedrive
After=network-online.target local-fs.target srv-dev\x2ddisk\x2dby\x2dlabel\x2dDrive.mount
Requires=network-online.target local-fs.target srv-dev\x2ddisk\x2dby\x2dlabel\x2dDrive.mount
RequiresMountsFor=/srv/dev-disk-by-label-Drive

[Service]
ExecStart=/usr/local/bin/onedrive --monitor --confdir=/var/lib/%i/.config/onedrive-d --verbose --verbose
User=%i
Group=users
Restart=on-failure
RestartSec=60
RestartPreventExitStatus=3

[Install]
WantedBy=multi-user.target
```

Probably that bit about group `Group=users` need to be changed as well, will try also.

**Comment by abraunegg** [comment] 2020-11-21 20:31
Also, just updating the PR.

Based on your systemd / normal runs, & based on the user | group | special permission bits - I suspect the 'file exception' is coming in from trying to set the correct time on the file. The updated PR adds another exception check for that.

When running the PR - you should have: `onedrive v2.4.7-20-g377ca20`

**Comment by tyger** [comment] 2020-11-21 20:41
@abraunegg 
It seems that you were right suggesting that there is group issue - changing to `Group=onedrive` in my service file helped.

Do you still want me to try now this latest PR on broken state of my system?

**Comment by tyger** [comment] 2020-11-21 21:00
@abraunegg 
So, running `onedrive v2.4.7-20-g377ca20` with wrong `Group` in service file I can see this line in the log:
```
2020-Nov-21 20:56:23.7013162    [DEBUG] ERROR: Failed to stat file `./Pictures/2017/20170310_141230.jpg'
```

**Comment by abraunegg** [comment] 2020-11-21 21:12
@tyger 
OK .. great .. what are the debug lines before:
```
2020-Nov-21 20:56:23.7013162    [DEBUG] ERROR: Failed to stat file `./Pictures/2017/20170310_141230.jpg'
```

**Comment by tyger** [comment] 2020-11-21 21:17
Interesting observation that this file (and bunch others) where removed running this new PR on my system in broken state (`Group=users` in systemd service file)
Here is part of the log
```
Nov 21 20:59:17 r onedrive[10915]: Processing Pictures/2017/20170310_141230.jpg
Nov 21 20:59:17 r onedrive[10915]: [DEBUG] skip_file evaluation for: 20170310_141230.jpg
Nov 21 20:59:17 r onedrive[10915]: The file appears to have been deleted locally .. but we are running in --monitor mode. This may have been 'moved' on the local filesystem rather than being 'deleted'
Nov 21 20:59:17 r onedrive[10915]: [DEBUG] Most likely cause - 'inotify' event was missing for whatever action was taken locally or action taken when application was stopped
Nov 21 20:59:17 r onedrive[10915]: Deleting item from OneDrive: Pictures/2017/20170310_141230.jpg
Nov 21 20:59:17 r onedrive[10915]: [DEBUG] Number of items to delete: 0
Nov 21 20:59:17 r onedrive[10915]: [DEBUG] Attempting to delete item from drive: xxxx
Nov 21 20:59:17 r onedrive[10915]: [DEBUG] Attempting to delete this item id: xxxx!43747
```
Let me express some concern here: it's very likely that not only me who has messed up permissions in the system (files and service) especially from previous versions where it was quite "safe", now in similar cases to mine files are going to be just deleted from the Cloud.

**Comment by abraunegg** [comment] 2020-11-21 21:23
@tyger 
Your concern is duly noted however:
* Your data is not 'deleted' ... it should be in the recycle bin on OneDrive, allowing you to 'undelete'

Previous versions - yes, were 'safe' - but this is because the defaults were to make things 'world readable / world writable' .. so in your broken permissions / user / group setting - the world permissions bits is what was making it work for you.

**Comment by tyger** [comment] 2020-11-21 21:29
@abraunegg 
Relevant lines would be (my build is **without** `./configure --enable-debug`)
```
2020-Nov-21 20:56:23.699098     [DEBUG] Calling addRecursive() for this directory: ./Pictures/2017
2020-Nov-21 20:56:23.6991736    [DEBUG] skip_dir evaluation for: /Pictures/2017
2020-Nov-21 20:56:23.6992282    [DEBUG] No Strict Matching Enforced
2020-Nov-21 20:56:23.69931      [DEBUG] Calling add() for this dirname: ./Pictures/2017
2020-Nov-21 20:56:23.6996568    [DEBUG] inotify_add_watch successfully added for: ./Pictures/2017
2020-Nov-21 20:56:23.6997464    Monitor directory: ./Pictures/2017
2020-Nov-21 20:56:23.7013162    [DEBUG] ERROR: Failed to stat file `./Pictures/2017/20170310_141230.jpg'
```

Yep, I know about recycle bin, it's just that if delete happens on low scale user might not even get notification and files could be deleted after 30 days.

Agree, such transitions are not easy, I understand implications of migrating to this "permission concerned version". 
Just throwing idea out: maybe it's possible to allow first run upon update with special flag which will indicate issues with permission before act on files.

**Comment by abraunegg** [comment] 2020-11-21 21:50
@tyger 
> Just throwing idea out: maybe it's possible to allow first run upon update with special flag which will indicate issues with permission before act on files

Unfortunately, that granularity is not possible. You should always also test, using `--dry-run` as well - to ensure that there are no adverse issues - but your issue really stems from not updating the user / groups the application runs with, which the defaults are:
```
User=%i
Group=users
```

The issue at play here - is this:
1. If the application cannot 'read' | 'stat' the file (permission or otherwise) - the file system returns that it has 'gone', there is no way to validate if it is actually there, not there, there but no read .. all 3 cases return the same result - gone.
2. The code makes several checks to determine it the file is there, not there before initiating a delete action - it is not just arbitrarily done

In your case, lack permission access to the file, the file system tells the application that the file has gone, thus this is why the delete is occurring.

The lack of permissions to read access crash is fixed, but now now that it is caught, error message generated - the result on that is a 'no access | file not there' .. hence the stat reason that is presented.

I suspect that this 'file system access issue' has *most* likely always been there for you, and most likely you are only really seeing this now because of the focus on the new default permissions for new files - which you saw issues with because of your broken file system permissions to begin with.

**Comment by tyger** [comment] 2020-11-21 22:42
Thank you for details.
I suppose issue can be closed now.

**Comment by abraunegg** [comment] 2020-11-21 23:03
@tyger 
> I suppose issue can be closed now.

Yes and no.

The 'crash' you are seeing still will occur in 'master', the current PR, fixes the crash, but has an adverse side effect. 

The cause is now known, permissions on files, based on group permissions. What I need to do is find the time to replicate this, now the cause is know, so I can work on a better fix (if possible) and / or better messaging about this scenario & attempt / try to not make the 'delete' action occur when this is triggered.

This way:

* An error message is correctly generated
* Notification is sufficient for user action to take place (fix permissions)
* No delete action (if possible)

> Let me express some concern here: it's very likely that not only me who has messed up permissions in the system (files and service) especially from previous versions where it was quite "safe", now in similar cases to mine files are going to be just deleted from the Cloud.

Additionally re this point - all users (unless they are running this PR in the current state) - the systemd process will be crashing when it cannot read the file due to no group permission read if set incorrectly, thus, no delete, thus, no major / wider issue. If the PR was merged into 'master' in its current state, then yes, potentially a wider issue - but right now, this flaw is contained to just yourself (AFAIK as no other issues have been reported).

**Comment by abraunegg** [comment] 2020-11-23 04:54
@tyger 
Please can you rebuild your PR version for this issue, when testing you should have `onedrive v2.4.7-21-gb0302d0`

When the permission issue is detected, the following now occurs:
```
alex@mint-20-read-only:~/code/onedrive-pr1157$ ./onedrive --monitor --verbose --resync           
Using 'user' Config Dir: /home/alex/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /mnt/OneDrive/
Application version: v2.4.7-21-gb0302d0
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368287434
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
Monitor directory: .
Monitor directory: ./random_images
Monitor directory: ./Dropbox
Monitor directory: ./Music
Monitor directory: ./random_files
Monitor directory: ./random_videos
Monitor directory: ./Documents
Monitor directory: ./Documents/Images
Monitor directory: ./Documents/SpeedTest
ERROR: The local file system returned an error with the following message:
  Error Message: Failed to stat file `./Documents/SpeedTest/Bandwidth measurement_ Speedtest.net.xlsx'
ACCESS ERROR: Please check your UID and GID access to this file, as the permissions on this file is preventing this application to read it

FATAL: Exiting application to avoid deleting data due to local file system access issues

alex@mint-20-read-only:~/code/onedrive-pr1157$ 
```

If you are running systemd service file or `--monitor` the same response will be generated, when the application:
* Cannot access a file due to user | group designation
* setgid has been used on the parent directory - eg: `chmod 2770 <folder_name>`

The application will exit(-1), print that error message, which, is better than having data delete.

Please can you provide feedback on the updated PR.

**Comment by abraunegg** [comment] 2020-11-24 07:16
@tyger 
Any chance to look at the updated PR and test in your environment?

**Comment by tyger** [comment] 2020-11-24 16:49
@abraunegg 
Sorry, not yet, will try to find time this evening to do that, anyway it's in my plans as soon as I get enough time.

**Comment by abraunegg** [comment] 2020-11-25 19:36
@tyger 
PR merged into 'master'

**Closed** 2020-11-25 19:35 UTC
Labels: Bug, PR Provided - Needs Testing, Waiting on Response

**Comment by tyger** [comment] 2020-11-25 22:43
@abraunegg 
I see that you've merged the changes already.
So I tried lastest master on my configuration with the wrong group for `onedrive` process, it behaved as expected:
```
Monitor directory: ./Pictures/2017
ERROR: The local file system returned an error with the following message:
  Error Message: Failed to stat file `./Pictures/2017/20170310_141230.jpg'
ACCESS ERROR: Please check your UID and GID access to this file, as the permissions on this file is preventing this application to read it

FATAL: Exiting application to avoid deleting data due to local file system access issues
```
Hope that helps and sorry for delay.

**Comment by abraunegg** [comment] 2020-11-26 00:23
@tyger 
Thanks for the confirmation

At least now, when there is an access issue:
* Will be reported so permissions can be fixed
* Application will exit preserving data from being removed from OneDrive
