### ISSUE TITLE
Signing key is invalid but client successfully authorizes

### ISSUE THREAD

**Issue by dab414** [abraunegg/onedrive#1344] opened 2021-03-15 20:39 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

This bug all of a sudden started happening on two of my machines (I think) without me changing anything in my local configuration.

```
$ onedrive --synchronize
Configuring Global Azure AD Endpoints

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 401 (Unauthorized)
  Error Reason:     Signing key is invalid.
  Error Timestamp:  2021-03-15T20:24:44
  API Request ID:   908683d3-e640-4ba9-a762-de7f89a1cff4
  Calling Function: init()


ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.

```
This issue persists after re-authorizing the client. Here's my successful authorization output (minus the URLs).

```
onedrive --logout

[prompt URL and return URL]

Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

```

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`  
    *  Ubuntu 20.04; `Linux dave-desktop 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
*   Are you using a headless system (no gui) or with a gui installed?  
    * gui installed
*   OneDrive Account Type  
    * Professional / business 
*   Did you build from source or install from a package?  
    * Build from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
   * `DMD64 D Compiler v2.091.1` also failed with `DMD64 D Cp,[o;er v2/095.1`
*   OneDrive Application Version: Output of `onedrive --version`
    * `onedrive v2.4.10-16-g6bec0dd`
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.4.10-16-g6bec0dd
Config path                            = /home/dave/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dave/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.68.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.2
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
   * local
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
NAME   FSTYPE   LABEL        UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0  squashfs                                                         0   100% /snap/core/10859
loop1  squashfs                                                         0   100% /snap/core/10823
loop2  squashfs                                                         0   100% /snap/core18/1944
loop3  squashfs                                                         0   100% /snap/gnome-3-34-18
loop4  squashfs                                                         0   100% /snap/gnome-3-34-18
loop5  squashfs                                                         0   100% /snap/vlc/1700
loop6  squashfs                                                         0   100% /snap/gtk-common-th
loop7  squashfs                                                         0   100% /snap/snapd/11036
loop8  squashfs                                                         0   100% /snap/core18/1988
loop9  squashfs                                                         0   100% /snap/snap-store/49
loop10 squashfs                                                         0   100% /snap/snap-store/51
loop11 squashfs                                                         0   100% /snap/tree/18
loop12 squashfs                                                         0   100% /snap/gtk-common-th
loop13 squashfs                                                         0   100% /snap/snapd/11107
loop14 squashfs                                                         0   100% /snap/tmux/11
loop15 squashfs                                                         0   100% /snap/vlc/2103
sda                                                                              
├─sda1 ntfs     Recovery     2A1E6F751E6F3949                                    
├─sda2 vfat                  B870-3D11                              38.1M    60% /boot/efi
├─sda3 ntfs                  7300506C6D804E14                                    
├─sda4 ntfs                  468A90C68A90B441                                    
└─sda5 ext4                  1ab38b98-c4d2-414b-8859-3ef0bfd4203c    3.2G    92% /
sdb                                                                              
└─sdb1 ntfs     Elements     021AD06A1AD05C6B                      392.8G    72% /media/dave/Element
sdc                                                                              
├─sdc1 ext4                  ac364f31-5b4f-4d2c-8e4a-7bbc8f44b9fe                
└─sdc2 ntfs     Windows Data 4E6A8F7716BC838C                               
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
* It's a University onedrive account, but it's just on my local machine and no one accesses it except me.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>

Using 'user' Config Dir: /home/dave/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/dave/OneDrive

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 401 (Unauthorized)
  Error Reason:     Signing key is invalid.
  Error Timestamp:  2021-03-15T20:36:54
  API Request ID:   44374060-296d-4f0f-900e-e0f81f570110
  Calling Function: init()


ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --logout and re-authorise this client.


```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [x] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-03-15 20:51
@dab414 
FYI this is *not* an issue with the client ..

I am also seeing this with Business / O365 accounts, and it appears that Microsoft has enforced / forcing a password change - as it is requesting this to occur (despite the password not being expired). The OneDrive / Azure API is then throwing an error:

![Capture](https://user-images.githubusercontent.com/4956234/111219582-53f23f80-862c-11eb-8ff7-77a7ea496707.JPG)

I suspect that there is an Azure / OneDrive API issue going on at the moment and this is the cause of the error message

**Comment by dab414** [comment] 2021-03-15 20:56
Interesting! Okay, thanks for clearing that up.

**Comment by abraunegg** [comment] 2021-03-15 21:43
@dab414 
FYI - it appears now that there is another error occurring:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 400 (Bad Request)
  Error Reason:     Unable to retrieve tenant service info.
  Error Timestamp:  2021-03-15T21:42:02
  API Request ID:   d25f6318-172c-4d1f-b145-ce48878dfdeb
  Calling Function: init()
```

Strongly suspect that there is an internal failure with Azure AD at present.

**Comment by abraunegg** [comment] 2021-03-15 21:52
@dab414 
Additional information from 2 hours ago:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">⚠️We are investigating an issue impacting Azure Active Directory. More information and updates can be found on the Azure Status page at <a href="https://t.co/k8iCqB52q8">https://t.co/k8iCqB52q8</a>.</p>&mdash; Azure Support (@AzureSupport) <a href="https://twitter.com/AzureSupport/status/1371544292502564866?ref_src=twsrc%5Etfw">March 15, 2021</a></blockquote>

Also:

![Capture2](https://user-images.githubusercontent.com/4956234/111226225-eb5b9080-8634-11eb-8a4b-c6e8777152d4.JPG)

**Comment by abraunegg** [comment] 2021-03-15 22:44
@dab414 
Based on testing and details from Microsoft, the Azure issue is now resolved, closing issue.

**Closed by abraunegg** 2021-03-15 22:44 UTC
Labels: Not a bug, OneDrive API Regression
