### ISSUE TITLE
Can't authenticate the onedrive account

### ISSUE THREAD

**Issue by Joel-max-s** [abraunegg/onedrive#1176] opened 2020-12-09 20:48 UTC
### Bug Report Details ###
I can not authenticate the onedrive client with the provided link.

**OS Details**
- OS: Ubuntu 20.04.1 LTS with GUI
`Linux ubuntu 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- OneDrive Account Type: Microsoft 365 Family
- I built it from source and installed the package, in both the error occured
- DMD Version (Installed from SnapStore):
`DMD64 D Compiler v2.090.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright`
- Onedrive version: `onedrive v2.4.8-3-g3b18638`
- Onedrive config (I changed nothing):
```
onedrive --display-config
onedrive version                       = v2.4.8-3-g3b18638
Config path                            = /home/joel/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/joel/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
- Curl version
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
- sync_dir is local
- parition format guide: ext4
- the folder is not shared with any other system at the same time, it is on its own disk, the onedrive account is in use on Windows, Linux Mint, Ubuntu and ios, sometimes at the same time

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  new installation with no config of the onedrive client
2.  open the provided link and log in
3.  accept that you trust the application
4.  See the error from the microsoft page

**Screenshots**
![image](https://user-images.githubusercontent.com/55981314/101685561-33807b00-3a68-11eb-8abd-5a56be9eeec0.png)

Message from Microsoft web page: 
```
Request Id: 73daa070-8203-4a96-8611-eddc0fb10501
Correlation Id: 116c0707-98ad-4adb-8bad-875035754166
Timestamp: 2020-12-09T20:07:06Z
Message: AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.
```

**Comment by abraunegg** [comment] 2020-12-09 20:56
@Joel-max-s 
Please can you provide a full HTTPS verbose debug log as per the support requirements following this process: https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

This will then clearly detail what is going on from the application and what authentication URL's are being used.

The application currently *does* use the v2.0 authentication, and given that this is an EU/DE authentication issue, most likely this is something which is related to other issues seen with Microsoft European Data Centers.

**Comment by Joel-max-s** [comment] 2020-12-09 21:07
Thank you for the fast answer, here is the debug log:

`                            
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/joel
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/joel/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/joel/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/joel/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/joel/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/joel/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/joel/.config/onedrive/items-dryrun.sqli>
[DEBUG] uploadStateFilePath = /home/joel/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/joel/.config/onedrive/config
[DEBUG] syncListFilePath = /home/joel/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/joel/.config/onedrive/business_sh>
No user or system config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expand>
[DEBUG] syncDir: /home/joel/OneDrive
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive S>
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
[DEBUG] Downgrading all HTTP operations to HTTP/1.1 by default
[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
`

**Comment by abraunegg** [comment] 2020-12-09 21:20
@Joel-max-s 
OK .. nothing out of the ordinary there.

Doing some research, this error is generally when using Business / Office365 and separate tenants. 

There is no error with the client, it has to do with the account you are using to authenticate with. This error needs to be fixed by your Azure Administrator by potentially:
* Allowing the application
* Creating your own application ID for use
* Assigning all the appropriate authentication scopes for this application

If this is *not* something you can achieve, as this is an Office365 account, suggest you speak to Microsoft to resolve and provide support.

This error is something which cannot be fixed by this application / application code.

**Comment by Joel-max-s** [comment] 2020-12-09 21:39
Ok, thank you for your help 👍

**Comment by abraunegg** [comment] 2020-12-10 01:33
Closing issue, not a bug, Azure account configuration

**Closed by abraunegg** 2020-12-10 01:33 UTC
Labels: Not a bug, OneDrive Office365
