### ISSUE TITLE
skip_dir not being applied to shared diretory

### ISSUE THREAD

**Issue by gigaSproule** [abraunegg/onedrive#1001] opened 2020-07-25 23:00 UTC
### Bug Report Details ###
**Describe the bug**
I have a shared directory (owned by someone else and added to my personal OneDrive, called `Pictures (1)`) which I'm trying to ignore with `skip_dir`, but it's always getting downloaded. I've tried `Pictures (1)`, `Pictures \(1\)`, `Pictures \\(1\\)` and `Pictures*`, but none of them seem to work.

**Application and Operating System Details:**
*   OS: 5.7.10-arch1-1
*   Are you using a headless system (no gui) or with a gui installed? With Gnome 3
*   OneDrive Account Type: Personal
*   Did you build from source or install from a package? Installed from AUR today (25th July 2020)
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
*   Application configuration: 
```
Configuration file successfully loaded
onedrive version                       = v2.4.3
Config path                            = /home/benjamin/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/benjamin/OneDrive
Config option 'skip_dir'               = Documents|ebooks|Email attachments|Music|Pictures|Pictures \\(1\\)|Pictures 1|Software
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Curl Version: Output of `curl --version`: 
```
curl 7.71.1 (x86_64-pc-linux-gnu) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Have a shared directory owned by someone else in OneDrive
2.  Try and skip it using `skip_dir`
3.  Run the sync using `systemctl --user enable onedrive` and `systemctl --user start onedrive`
4.  See it be downloaded

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
Using 'user' Config Dir: /home/benjamin/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/benjamin/OneDrive
Application version: v2.4.3
Account Type: personal
Default Drive ID: 37dded99dad2012d
Default Root ID: 37DDED99DAD2012D!150
Remaining Free Space: 563473245717
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 37DDED99DAD2012D!150
Syncing this OneDrive Personal Shared Folder: Media Source
Applying changes of Path ID: DD8E6068FCEC7A00!82861
Syncing this OneDrive Personal Shared Folder: Pictures (1)
Applying changes of Path ID: 82CC6C6189B2E98F!545
Processing 200 OneDrive items to ensure consistent local state
The local item has a different modified time 2020-Jul-25 22:59:08Z remote is 2017-Mar-25 13:02:54Z
The local item has a different hash
Local item does not exist in local database - replacing with file from OneDrive - failed download?
Downloading file Pictures (1)/Camera Roll/VID_20170325_130254.mp4 ... 
Downloading   0% |                                        |   ETA   --:--:--:^C   
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [ ] Verbose Log Output

**Comment by abraunegg** [comment] 2020-07-25 23:07
@gigaSproule 
Please can you:
* Upgrade your client to latest 'master' to ensure that you have the latest code
* Retest after reconfigure your 'skip_dir' directive for the following:
     * `skip_dir = "Documents|ebooks|Email attachments|Music|Pictures|Pictures (1)|Software"`

If you still have an issue, as per the support requirements, please provide a verbose debug log via email.

**Comment by abraunegg** [comment] 2020-07-25 23:55
@gigaSproule 
Unable to reproduce in either of the following scenarios:
* Shared folder called 'Pictures (1)'
* Sub folder in a shared folder called 'Pictures (1)'

In each case, with `skip_dir` configured as per above, the folder is excluded as expected:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.3-14-g76ce103
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 7 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config: Pictures (1)
Number of items from OneDrive to process: 1
Syncing this OneDrive Personal Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
Processing 8 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config match: shared/Pictures (1)
Skipping item - excluded by skip_file config: white_paper_c11-494994.pdf
Skipping item - excluded by skip_file config: SMPP-IF-SPEC_v3_3-24858.pdf
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing shared
The directory has not changed
Processing shared
The directory has not changed
Processing shared/Cisco VDI Whitepaper
The directory has not changed
Processing shared/Cisco VDI Whitepaper/campover.pdf
The file has not changed
Processing shared/SMPP
The directory has not changed
Processing shared/SMPP/SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing this OneDrive Personal Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
```

**Comment by gigaSproule** [comment] 2020-07-26 19:07
Just a quick update. `Pictures`, `Pictures (1)` and `Pictures 1` are all different folders. I know, why? Because OneDrive _really_ wants to ensure I have them for some reason. Tried `Pictures (1)` in skip_dir again, but no good. Not with master, so will try that.

**Comment by abraunegg** [comment] 2020-07-26 21:05
@gigaSproule 
> Just a quick update. `Pictures`, `Pictures (1)` and `Pictures 1` are all different folders. I know, why? Because OneDrive _really_ wants to ensure I have them for some reason. Tried `Pictures (1)` in skip_dir again, but no good. Not with master, so will try that.
> 
> Just tried the onedrive-abraunegg-git package and that still fails. Will try actually cloning the repo.
> 
> Even cloned and built master fails.
> 
> I've just emailed the log to you.

Thanks for the feedback and debug log.

So .. the reason for why this is failing for you is the following:
* Not upgrading the client as requested, before changing configuration file & retesting 

What this means is, you were still running a version that had a bug when the client configuration was changed - thus, the resync required due to config change would have not done what was required when using the updated code base as it was not present. I have been able to replicate this scenario due to the debug log you have provided.

Please can you test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1003/head:pr1003
git checkout pr1003
./configure; make clean; make;
```

When running the PR version you should be using `onedrive v2.4.3-16-gf3231b2` or greater.

You will need to run the PR client from the PR folder, or perform the install to use the PR version in a more wide scenario. When testing a PR version:
* Do not use monitor mode (--monitor)
* Test first with --dry-run

**Testing evidence with PR:**
```
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
config file has been updated, checking if --resync needed
DRY-RUN Configured. Output below shows what 'would' have occurred.
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.3-16-gf3231b2
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 7 OneDrive items to ensure consistent local state
Number of items from OneDrive to process: 1
Syncing this OneDrive Personal Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
Processing 8 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config: shared/Pictures (1)
Skipping item - excluded by skip_file config: white_paper_c11-494994.pdf
Skipping item - excluded by skip_file config: SMPP-IF-SPEC_v3_3-24858.pdf
Skipping item - excluded by skip_dir config: Pictures (1)
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing shared
The directory has not changed
Processing shared
The directory has not changed
Processing shared/Cisco VDI Whitepaper
The directory has not changed
Processing shared/Cisco VDI Whitepaper/campover.pdf
The file has not changed
Processing shared/SMPP
The directory has not changed
Processing shared/SMPP/SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing Pictures (1)
Uploading new items of ~/OneDrivePersonal
Skipping item - excluded by skip_dir config: ./shared/Pictures (1)
Skipping item - excluded by skip_dir config: ./Pictures (1)
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing this OneDrive Personal Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
Skipping item - excluded by skip_dir config: Pictures (1)
```

**Comment by gigaSproule** [comment] 2020-07-26 21:52
Ran it with the downloaded `Pictures (1)` folder and without, no mention of skipping it, but no mention of it at all. So good?

**Comment by abraunegg** [comment] 2020-07-26 22:06
@gigaSproule 

> Ran it with the downloaded `Pictures (1)` folder and without, no mention of skipping it, but no mention of it at all. So good?
> 
> Scratch that `Skipping item - excluded by skip_dir config: Pictures (1)` 👍

The logging output would only be present if `--verbose` is being used, otherwise, no output would occur if an item is being skipped.

**Comment by gigaSproule** [comment] 2020-07-26 22:17
Yeah, I forgot that, which is why I ran it with verbose and it worked. I'll try clearing everything down and using master version as well. Thanks for the help.

**Comment by abraunegg** [comment] 2020-07-26 22:19
@gigaSproule 
> Yeah, I forgot that, which is why I ran it with verbose and it worked. I'll try clearing everything down and using master version as well. Thanks for the help.

Please don't use 'master' as it will not contain the fix the PR does. Please continue to use the PR version until you see this issue closed due to the PR being merged.

**Comment by gigaSproule** [comment] 2020-07-26 22:27
Thought I'd just try master, and with _everything_ deleted, it's working.

**Closed** 2020-07-27 21:00 UTC
Labels: Bug, OneDrive Personal - Shared Folders, PR Provided - Needs Testing

**Comment by abraunegg** [comment] 2020-07-27 21:02
Closed issue as PR merged into 'master'

@gigaSproule 
Please rebuild your client to ensure you are running the updated code. The 'master' version will be `onedrive v2.4.3-16-g928ad95`
