### ISSUE TITLE
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled Sleeping for 120 seconds

### ISSUE THREAD

**Issue by ParikhKadam** [abraunegg/onedrive#978] opened 2020-07-02 16:07 UTC
Running onedrive synchronize, I keep getting the following error:
```
Using Config Dir: /home/kadam/.config/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/kadam/OneDrive
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 120 seconds
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 120 seconds
```

I am facing this issue from past few days. Though I am able to open onedrive from my phone, but can't access it via client. Help please..

**Comment by abraunegg** [comment] 2020-07-02 17:31
@ParikhKadam 
Please can you update your post above following the directions as per: https://github.com/abraunegg/onedrive#reporting-issues.

Your post above is lacking critical details which help in providing assistance, such as:
* What application version you are running
* How did you install - via package or compile?
* If compile, what compiler did you use
* What OneDrive account type you use
* What Curl version are you using

As you are getting a 429 response from Microsoft, they are throttling your account based on the actions / volume of actions you are undertaking using your account. This is not something I can assist with.

Depending on your 'client' version, there were some tweaks made - but as your first post lacks the required support details, I don't know if you have those tweaks or not.

So why is Microsoft is generating a 429 for your access. Some how you are 'flooding' Microsoft which is why you are getting the 429.

Your options are (in order of ease to complete):
* If you are a business account user, open a support ticket with Microsoft
* If you are a personal account user, upgrade to Office365 / Business account & re-try. If still an issue, see above point.
* Don't use the client for 24-48 hours - ensure 'every' Linux client you have running with your 'account' is shut down to allow Microsoft to see you have taken corrective action.
* Register a new 'application id' - follow steps 1, 2, 3 and 4 only.  For step 3 however, the response URI should be as per the image.

**Comment by ParikhKadam** [comment] 2020-07-03 13:27
What application version you are running - 2.4.2
    How did you install - via package or compile? - compile
    If compile, what compiler did you use - gcc
    What OneDrive account type you use - student (business)
    What Curl version are you using - 7.58.0



    If you are a business account user, open a support ticket with Microsoft - can you guide me with this? They said only admins can contact microsoft support team
    Don't use the client for 24-48 hours - ensure 'every' Linux client you have running with your 'account' is shut down to allow Microsoft to see you have taken corrective action. - I used it 4 hours each day with data transfer of about 3.5GB each day.
    Register a new 'application id' - follow steps 1, 2, 3 and 4 only. For step 3 however, the response URI should be as per the image. - Can you elaborate on this? Also, there's no image attached.


Thank you

**Comment by ParikhKadam** [comment] 2020-07-03 13:28
I tired to delete the session and login in again with the application after revoking the rights given to this client. But still it didn't work.

**Comment by abraunegg** [comment] 2020-07-03 19:31
@ParikhKadam 
> > What application version you are running
> 
> 2.4.2

Please upgrade your client to v2.4.3

> > How did you install - via package or compile?
> 
> compile
> 
> > If compile, what compiler did you use
> 
> gcc

Not possible that you used gcc ... 

> > What OneDrive account type you use
> 
> student (business)

OK

> > If you are a business account user, open a support ticket with Microsoft
> 
> can you guide me with this? They said only admins can contact microsoft support team

You need to speak with your education provider support team - I cannot assist. Only *you* can do this.

> > Don't use the client for 24-48 hours - ensure 'every' Linux client you have running with your 'account' is shut down to allow Microsoft to see you have taken corrective action.
> 
> I used it 4 hours each day with data transfer of about 3.5GB each day.

This is normal usage. Most likely, your Administrators have changed settings regarding using API's to query data in their Azure configuration. See point above.

> > Register a new 'application id' - follow steps 1, 2, 3 and 4 only. For step 3 however, the response URI should be as per the image.
> 
> Can you elaborate on this? Also, there's no image attached.

Sorry - I missed adding the URL: https://github.com/abraunegg/onedrive/blob/master/docs/national-cloud-deployments.md

Register a new 'application id' - follow steps 1, 2, 3 and 4 only. For step 3 however, the response URI should be as per the image in Step 3 of https://github.com/abraunegg/onedrive/blob/master/docs/national-cloud-deployments.md


Again - this is *not* a problem with this client. This is an issue with your account / Azure configuration. You need to seek support from your education providers support team & Microsoft.

**Comment by ParikhKadam** [comment] 2020-07-04 04:07
Can you please guide me on how to update? Or will I need to reinstall the latest build? In that case, how can I uninstall this one?

**Comment by abraunegg** [comment] 2020-07-04 04:50
@ParikhKadam 
> Can you please guide me on how to update? Or will I need to reinstall the latest build? In that case, how can I uninstall this one?

Please follow the directions as per https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md for your Operating System

**Comment by abraunegg** [comment] 2020-07-05 06:52
Closing issue as not a bug, end user needs to seek support through educational support team and Microsoft to resolve issue

**Closed by abraunegg** 2020-07-05 06:52 UTC
Labels: Answer Provided, Not a bug, Question
