### ISSUE TITLE
Immediately delete after uploading modified PPT file using WPS Office

### ISSUE THREAD

**Issue by Troublor** [abraunegg/onedrive#712] opened 2019-11-01 09:28 UTC
### Bug Report Details ###
**Describe the bug**
When I open a pptx file in the OneDrive folder and modified it, after I press `Ctrl + S`, which is used to save the file, the file is detected to be modified, uploaded and, however, deleted from OneDrive immediately. 

**Application and Operating System Details:**
*   OS: Ubuntu 18.04 
*   Output of `uname -a`: `Linux troublor-wl 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   Ubuntu 18.04 with default GUI installed
*   Personal OneDrive account with Office 365 Home subscription. 
*   DMD64 D Compiler v2.088.1
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.10-7-g9d0a653
Config path                         = /home/troublor/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/troublor/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
PhD
troubleLearning/COMP 5331 Knowledge Discovery in Databases
troubleLearning/COMP 5211 Advanced Artificial Intelligence
```

*   Curl Version: Output of `curl --version`
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Open a `pptx` file in OneDrive folder.
2.  Make some changes and save it but do not close the file. 
3.  You will find on OneDrive cloud, the file has been deleted.
4.  Close the `pptx` file. 
5.  You will find on OneDrive cloud, the file shows up again.

**Debug Log**
* How the debug log is generate: 
I first upload a new `ppt_file.pptx` file in folder `OneDrive/PhD`, and check in OneDrive website that this file has been uploaded successfully. Then I open this `pptx` file and make some changes in it and save the file (without closing it). Then I found the file has been delete from OneDrive cloud. After I close the `ppt_file.pptx`, the file is uploaded again. 
* Debug log: 
The debug log can be found here: [debug log file](https://github.com/Troublor/public_files/blob/master/debug_output.log). 

**Complete Verbose Log Output**
```bash
onedrive --monitor
```

```
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Uploading new file PhD/ppt_file.pptx ... done.
Deleting item from OneDrive: PhD/ppt_file.pptx
Uploading new file PhD/ppt_file.pptx ... done.
Uploading modified file PhD/ppt_file.pptx ... done.
Deleting item from OneDrive: PhD/ppt_file.pptx
Uploading new file PhD/ppt_file.pptx ... done.
```

**Additional context**
Although the `pptx` file is uploaded again after closing the file, it is still annoying that the file will be deleted immediately after I save the file but haven't closed it. 

In addition, the problem does not exist on `docx` files.

**Comment by abraunegg** [comment] 2019-11-01 09:57
@Troublor 
Thanks for the bug report.

> In addition, the problem does not exist on docx files.

This is rather interesting, as there is no application code differences here between docx and pptx files - to the client they are just 'files'. On the OneDrive server side however - Microsoft 'enrich' all Office format files, thus this potentially could account for the scenario your seeing - and given this in your log file:
```
[DEBUG] event IN_CREATE: PhD/ppt_file.pptx
[DEBUG] event IN_CLOSE_WRITE and ...: PhD/ppt_file.pptx
[M] File changed: PhD/ppt_file.pptx
Uploading differences of PhD/ppt_file.pptx
Processing ppt_file.pptx
The file last modified time has changed
The file content has changed
Uploading modified file PhD/ppt_file.pptx ... skipped.
OneDrive returned a 'HTTP 404 - eTag Issue' - gracefully handling error
Uploading new items of PhD/ppt_file.pptx
[DEBUG] Checking file: PhD/ppt_file.pptx
Uploading new file PhD/ppt_file.pptx ... done.
```
That certainly leads strength to that.

The delete however appear's to be coming from the following:
```
The file has not changed
Uploading new items of PhD/ppt_file.pptx
[DEBUG] Checking file: PhD/ppt_file.pptx
[DEBUG] deleting (post loop): PhD/ppt_file.pptx
[M] Item deleted: PhD/ppt_file.pptx
Deleting item from OneDrive: PhD/ppt_file.pptx
[DEBUG] event IN_CLOSE_WRITE and ...: PhD/ppt_file.pptx
[M] File changed: PhD/ppt_file.pptx
```

**Question:** What application are you using to edit / open the pptx files on your Ubuntu system - OpenOffice or something else? What is the process there that you are using?

**Comment by abraunegg** [comment] 2019-11-01 19:38
@Troublor 
Whilst I have not been able to replicate this using a test Ubuntu system, please can you use the following PR against your use case:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/714/head:pr714
git checkout pr714
./configure; make clean; make;
```

After this gets printed:
```
[DEBUG] deleting (post loop): PhD/ppt_file.pptx
```

It should print out if the file is no longer on disk. If this IS the case (ie - the application you are using deleted, then 'wrote out a new copy' as the save, then this would explain the application behaviour your seeing.

**Comment by abraunegg** [comment] 2019-11-01 20:04
@Troublor 
It testing & trying to trigger this / replicate this - the only time the file is removed from OneDrive is in this scenario:
```
Uploading modified file ppt_file.pptx ... skipped.
[DEBUG] Simple Upload Replace Failed - OneDrive eTag / cTag match issue
OneDrive returned a 'HTTP 412 - Precondition Failed' - gracefully handling error. Will upload as new file.
Uploading new items of ./ppt_file.pptx
[DEBUG] Checking file: ./ppt_file.pptx
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./ppt_file.pptx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./ppt_file.pptx ... done.
```

This is where the modification of Office files by Microsoft is impacting the file. As your also using an Office 365 account, will specifically test this against that as well in an attempt to replicate.

**Comment by abraunegg** [comment] 2019-11-01 20:13
@Troublor 
Even when using an Office 365 account I cannot replicate this at all.

So back to this question - what application are you using to edit / open the pptx files on your Ubuntu system - OpenOffice or something else? What is the process there that you are using?

Unable to replicate with LibreOffice v6.0.7.3 as per installed with Ubuntu 18.04.3 LTS

**Comment by abraunegg** [comment] 2019-11-03 21:29
@Troublor 
Please can you respond in regards to this issue.

**Comment by Troublor** [comment] 2019-11-04 05:16
@abraunegg Sorry for the late. I was using WPS Office. Maybe it's due to the WPS Office. I plans to try with LibreOffice and OpenOffice, but I haven't got some spare time. I will get back to you later.

**Comment by Troublor** [comment] 2019-11-04 07:56
@abraunegg Indeed this issue does not manifest using LibreOffice. Maybe it is because some different file-saving strategy used by WPS Office. Could you investigate the issue on WPS Office?

**Comment by abraunegg** [comment] 2019-11-04 08:19
@Troublor 
>  Could you investigate the issue on WPS Office?

Given that you have also tried LibreOffice and the issue does not present, but only presents with WPS Office, this most certainly has to do with WPS Office and how files are saved.

As this client has nothing to do with WPS Office, you will need to file a bug with the WPS Office folk.

Unfortunately I cannot assist here further.

**Comment by abraunegg** [comment] 2019-11-04 08:20
Closing issue, not a bug with this client.

**Closed by abraunegg** 2019-11-04 08:20 UTC
Labels: Local Environment Issue, Not a bug, Unable to reproduce
