### ISSUE TITLE
Uploaded file size does not match local file - upload failure - retrying

### ISSUE THREAD

**Issue by erenoglu** [abraunegg/onedrive#2492] opened 2023-09-19 19:43 UTC
### Describe the bug

I'm using onedrive for a corporate Onedrive syncing. To start fresh, I synced my Onedrive to the local PC with almost all folders excluded, which went fine. Then I added a folder with many files in it, and I'm frequently hitting this in the console and the only way to continue syncing is to delete that file from the filesystem.

> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.

and it goes on forever in a loop until I delete that file from local filesystem. 

This is an upload from local to cloud, so I don't understand why this is happening. Any clues?

### Operating System Details

```shell
Ubuntu 22.04 with latest onedrive package onedrive v2.4.25-1+np1.
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

2.4.25-1+np1

### What is your OneDrive Application Configuration

```shell
Using config option for Global Azure AD Endpoints
Configuration file successfully loaded
onedrive version                             = v2.4.25-1+np1
Config path                                  = /home/myuser/.config/onedrive/accounts/abcd/
Config file found in config path             = true
Config option 'sync_dir'                     = /home/myuser/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = true
Config option 'skip_symlinks'                = true
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 5
Config option 'monitor_fullscan_frequency'   = 10
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 125000000
Config option 'operation_timeout'            = 3600
Config option 'dns_timeout'                  = 60
Config option 'connect_timeout'              = 10
Config option 'data_timeout'                 = 600
Config option 'ip_protocol_version'          = 0
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = true
sync_list contents:
!/Archive/*
!/Apps/*
!/External/*
!/Office Lens/*
# Include everything else in root directory
/*
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = true
business_shared_folders contents:
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
This filesystem is ext4 running on encrypted LUKS2.
```

### What are all your local file system partition types

```shell
─nvme0n1p6
│         crypto 2                             
│ └─nvme0n1p6_crypt
│         ext4   1.0
```

### How do you use 'onedrive'

I'm using onedrive client against corporate Office 365.  Folder is not shared with anybody. Just tying to upload/sync a new local folder & subfolders & files to cloud.  No other onedrive client running at this time. Error appears apperantly on random files but always office (xlsx, xlsb, ...)

### Steps to reproduce the behaviour

Have a corporate Office 365 account.
Sync with onedrive using --monitor parameter with minimal downloads (use exclude directives), 
Then paste a new folder with many subfolders & files into the local onedrive sync folder
Watch logs and see the error

### Complete Verbose Log Output

```shell
> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.
> Uploaded file size does not match local file - upload failure - retrying
> Uploading new file ./xxx/yyy/zzz.xlsx
> Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                              
> done.
```

**Comment by abraunegg** [comment] 2023-09-19 19:59
@erenoglu 
FYI - technically this is *not* an application bug.

100% most likely you are hitting the known SharePoint problem where SharePoint modifies your file post upload - this is *why* the application is reporting this and attempting a re-try.

If you increase the application verbosity by adding `--verbose` to your command - you should be able to see a little more detail as to what is going on.

To get around this SharePoint issue, in your 'config' file add the following:
```
disable_upload_validation = "true"
```

This should stop the upload size check from kicking in.

If you could give that a go and report back that would be greatly appreciated.

**Comment by erenoglu** [comment] 2023-09-19 20:33
Thanks. I already have --verbose in my command, but it only produces the above logs. Anyway to increase that verbosity?
I'm now running with the new option flag to disable upload validation. I'll report back after some time.

**Comment by erenoglu** [comment] 2023-09-19 20:34
Ah now I started to see following warning on some files:
> WARNING: Uploaded file size does not match local file - skipping upload validation
> WARNING: Due to Microsoft Sharepoint 'enrichment' of files, this file is now technically different to your local copy
> See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
> Remaining free space on OneDrive: 1033413388816

This is indeed worrysome. So is this the right workaround? basically we will "hope" no transfer issue happens when uploading since we are disabling the check.

**Comment by abraunegg** [comment] 2023-09-19 20:57
@erenoglu 
This is a Microsoft problem - that is the correct workaround.

Please complain (and loudly) to Microsoft - it is their platfom that is modifying your data post upload - thus you cannot guarantee your data integrity.

**Comment by abraunegg** [comment] 2023-09-20 05:49
Closing this issue as it is not a bug, but an issue with Microsoft and the use of SharePoint to deliver OneDrive Business services.

**Closed by abraunegg** 2023-09-20 05:49 UTC
Labels: OneDrive Business, Workaround Available, Not a bug, OneDrive SharePoint Library

**Comment by erenoglu** [comment] 2023-09-20 06:02
OK will do, we may have a way to complain. Thanks.

**Comment by abraunegg** [comment] 2023-09-28 01:27
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
