### ISSUE TITLE
Removed a very large chunk of my OneDrive files

### ISSUE THREAD

**Issue by marono** [abraunegg/onedrive#511] opened 2019-05-24 08:19 UTC
**Is your feature request related to a problem? Please describe.**
I'm syncing a large portion of my OneDrive storage to an extral drive connected to a raspberryPi. In the past I had issues with the drive not mounting properly, which caused wipes on my OneDrive account, started using the `--check-for-nomount` switch and for a while it seems to have done the trick. Yesterday I woke up to a different kind of issue, my drive being monted, but the FS not being available. My understanding is that the `.nosync` file was not being reachable, but the `sync_dir` was missing as well, so the client went ahead and deleted all of my synced files. BTW the client had been running for a couple weeks before this happened so the FS became unavailable during operations.

**Describe the solution you'd like**
Would it be possible to actually check of the presence of the `sync_dir` directory and only afterwards trigger syncing operations?

**Describe alternatives you've considered**
Used `--check-for-nomount`, but doesn't work in all scenarios.

Thanks

**Comment by norbusan** [comment] 2019-05-24 09:12
Sounds like a reasonable idea to only do any operation if the `sync_dir` is actually present, and not remove anything if it is not.

**Comment by abraunegg** [comment] 2019-05-24 09:15
@marono 
The way the client works for `--check-for-nomount` is that is attempts to detect the presence of `.nosync` in your OneDrive root folder (`sync_dir`), which, based on your information - is your drive mount point. 

Once the client has initialised, it will always "assume" that the sync location is available - it has zero awareness of FS issues or mount points becoming unavailable. To the client, this is seen as a "delete" - thus, it will delete the files - even though this is not what you want to happen. This is due to essentially the same check to check if the directory is readable, would return not found / non-readable - thus = delete.

Strongly suggest that for more complex setups like this, that you have a rigorous system monitoring in place, where it alerts you for when a mount becomes unavailable or some other system action & undertake to 'stop' any external sync based on that condition.

**Comment by marono** [comment] 2019-05-24 09:22
As a workaround I'm considering having 2 instances of the client running:

* one with `--monitor --download-only`
* one with `--monitor --upload-only --no-remote-delete`
They would be running off separate `sync_dirs`.

My main requirement is to have a local cache of the files (it's a Photo library that I run slideshows from). A secondary requirement is to have an overnight upload facility as when I upload photos I don't want to leave my laptop open, I just copy them to a share and the rPI does its thing. I realise the library would be updaed via one drive and not by just copying files to the share but I'd say that's still acceptable.

I'm not very familiar with how systemd works, do you think 2 units withe the mentioned configuration would work properly?

Also sorry I'm not able to contribute with code for this bug, I'm quite useless at what you guys are using here ...

**Comment by abraunegg** [comment] 2019-05-24 09:28
@marono 
What ever the solution is that you come up with, separate configuration directories as well would be required - but I would also ensure that you put some form of 'event monitoring' on the solution you come up with so you can:
* get alerts when it is not working
* when something breaks
* notification if / when you do a sync

I would look and also not using `--monitor` for your operations - but use `--synchronize` and script where needed & schedule via cron for the overnight sync. There is no need to have something running 100% of the time if there is a very very low rate of change 99% of the time.

**Comment by marono** [comment] 2019-05-24 09:53
Yes, was kind of aware that config needs to be separate, just slipped my mind when writing the above. My only concern with using `--synchronize` is overlapping runs. As you said 99% of the time there's nothing to do but on the ocasion there is something to do it's a couple GBs of data and my upload bandwith is quite low (hence the overnight upload solution).

How would onedrive client behave if one sync is in progress and another one is triggered, are the DB files locked and the subsequent one would just fail?

Indeed it's not a problem running the upload every 24hrs, just need to be aware of the concequences of having it as a cron job.

**Comment by abraunegg** [comment] 2019-05-24 10:01
> How would onedrive client behave if one sync is in progress and another one is triggered, are the DB files locked and the subsequent one would just fail?

The database file should be 'locked' for each instance your running - thus it 'should' fail gracefully as cannot get a database lock.

Best to test the scenario's and ensure that this is what is happening for you. With scripting, you could even write your own lock file / run PID etc ... and check if that is not present before continuing on to sync.

**Comment by abraunegg** [comment] 2019-05-27 05:39
Closing issue as not a bug, local environment issue & local monitoring required

**Closed by abraunegg** 2019-05-27 05:39 UTC
Labels: Local Environment Issue, Not a bug
