### ISSUE TITLE
Lots of "Processing changes" during synchronize, but no changes have happened on OneDrive

### ISSUE THREAD

**Issue by OneLineTwoBugs** [abraunegg/onedrive#679] opened 2019-10-02 09:00 UTC
OS: Debian buster headless (no GUI)
Kernel: Linux nas 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
OneDrive personal account, 50k files, 6.2k folders, 11GB total size
`sync_list` content folders: 1.2k files, 112 folders, 2.5GB size.
DMD64 D Compiler v2.088.0
curl 7.64.0 (x86_64-pc-linux-gnu)
```
onedrive version                    = v2.3.10
Config path                         = /home/user/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /opt
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = ~/onedrivelog
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Ablage
```

Problem description: 
`onedrive --synchronize` takes a long time to complete (several minutes) and it sees a lot of "changes" outside of the `sync_list` folder, even if no changes have happened since the last sync and those changes would be irrelevant anyway. Also, it makes my regular OneDrive clients stop working during the duration - I assume because of rate limits.

The detected "changes" don't go away, the next sync finds exacthly the same number of changes on the same files, even though no changes have happened.

I've created two debug logs which are the result of two `onedrive --synchronize` runs. The second run was started immediately after the first. No changes were made to the OneDrive repository during or in between the runs, neither online nor local on the linux box that runs `onedrive`. The resulting log file is absolutely identical to the first. ~~I've sent the two log files to support@mynas.com.au - uncompressed, they're about 300MB each, but they've actually done nothing (no uploads, no downloads).~~ Logfiles are too large, please find them here (link is only valid for 24 hours): https://1drv.ms/u/s!AqoGaHdTCWEoiYde7Gor7Qb6_Acfsg?e=FqzlMQ

**Comment by abraunegg** [comment] 2019-10-02 09:25
@OneLineTwoBugs 
Will download the logfiles if you can confirm you have:
1. Performed the log file with `--verbose --verbose` so that there is debug data present
2. After making any change to 'sync_list' you are performing a `--resync` as required

> `onedrive --synchronize` takes a long time to complete (several minutes) and it sees a lot of "changes" outside of the `sync_list` folder, even if no changes have happened since the last sync and those changes would be irrelevant anyway. Also, it makes my regular OneDrive clients stop working during the duration - I assume because of rate limits.

This is because you are using `sync_list` - and when using this, you are telling the client to 'exclude' operations - however if you move files from a previously 'excluded' path into something that is 'included' via 'sync_list', then this is 'missed' because the 'parent' path will not exist unless you use '--resync' .. this is why, every sync, when using 'sync_list' - it gets 'every change' so that it can process correctly. 


> The detected "changes" don't go away, the next sync finds exacthly the same number of changes on the same files, even though no changes have happened

See above.


> I've created two debug logs which are the result of two `onedrive --synchronize` runs. The second run was started immediately after the first. No changes were made to the OneDrive repository during or in between the runs, neither online nor local on the linux box that runs `onedrive`. The resulting log file is absolutely identical to the first.

So the debug log output will clearly articulate what is going on here and why something is not occuring - normal log level does not provide that detail.

Please can you confirm the points in question above.

**Comment by OneLineTwoBugs** [comment] 2019-10-02 09:27
1. Yes, the logs have been created with --verbose --verbose (that's why they're 300MB). 
2. I have never made changes to sync_list. This is the same config that performed the initial sync.

**Comment by abraunegg** [comment] 2019-10-02 10:29
@OneLineTwoBugs 
Thanks for the confirmation - I have downloaded `onedrive_debuglog2.7z - 12.4 MB` - will look at this tomorrow.

**Comment by abraunegg** [comment] 2019-10-02 10:33
@OneLineTwoBugs 
Can you also provide the following - via email:

1. A screen shot of your 'OneDrive' account / root folder when logged in via the 'https://onedrive.live.com/' site
2. Confirmation that the 'only' folder you want to sync locally from 'OneDrive' is the root folder called 'Ablage' as per your 'sync_list' configuration above.

**Comment by OneLineTwoBugs** [comment] 2019-10-02 10:57
@abraunegg 
1. sent
2. this is correct.

Just to clarify 2, as per config, I'm synching my OneDrive into /opt. The only folder I want to sync is Ablage. The expected result is that /opt/Ablage is in sync with /drive/root:/Ablage. Both /drive/root: and /opt have other files and subfolders which should not be synchronized.

**Comment by abraunegg** [comment] 2019-10-02 11:07
@OneLineTwoBugs 
Thanks.

As part of debugging this as well - can you try the following

* Not use 'sync_list' - you are only syncing a 'single directory' - so remove that configuration
* Utilise `--single-directory` sync as per https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-directory-sync

So in your case (after you have removed the sync_list file):
```
onedrive --synchronize --single-directory 'Ablage' --resync --dry-run
```

This should have the effect of:
1. Syncing **only** the 'Ablage' folder
2. Will query 'only' that folder for changes
3. Will only process changes from the 'Ablage' folder both local and remote

**Comment by zell-mbc** [comment] 2019-10-02 15:59
Just to let you know that I see the same issue here after upgrading to v2.3.10 today.
I didn't make any config changes in the last couple of days and throughout today only few files have changed.
I installed the update, reloaded the service and things were ok. Later on I had to reboot and ever since I restarted I am getting these "Processing ... changes" , made my notifier crash, and then continues on.

Journactl:
Processing 241 changes
Processing 245 changes
Processing 204 changes
Got exception from showing notification: dnotify.NotificationError@src/notifications/dnotify.d(50): GDBus.Error:org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession


OS is 5.3.1-arch1-1-ARCH

onedrive version                    = v2.3.10
Config path                         = /home/thomas/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /media/data/OneDriveSync/
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 60
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
SyncFolder
Share
Security
EmergencyDocuments
PhotoUpload


I also upgraded a Ubuntu server today which seems to work fine.

**Comment by abraunegg** [comment] 2019-10-02 20:27
@OneLineTwoBugs, @zell-mbc 
This appears to be an 'impact' of fixing this bug - https://github.com/abraunegg/onedrive/issues/658

When I look at the debug log file, there are many 'changes' to process, but as you have not actually made 'any' change at all, it is outputting that is is processing changes which is technically not correct.

Technically this is not a bug, as based on the log file, the application is working 100% correctly, however I can understand how the current 'messaging' of `Processing X changes` can appear to be misleading when you may not have actually made any 'change' on OneDrive.

@zell-mbc 
```
Got exception from showing notification: dnotify.NotificationError@src/notifications/dnotify.d(50): GDBus.Error:org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession
```

Not much I can do about that - as that is a Desktop Manager issue ... 

@OneLineTwoBugs, @zell-mbc 
This being said - I am going to look into how / where the output notification is occurring, and tighten this up to be more accurate with what is going on.

**Comment by zell-mbc** [comment] 2019-10-02 22:00
`Not much I can do about that - as that is a Desktop Manager issue .`

Understood, I will turn off notifications for now. Just thought I highlight the fact that there is a notification every second, as this didn't happen before. But maybe things settle down after a while. 
I will be away from my machine for a couple of days now, so if there is anything to test I will have to delay.

By the way, let me take this opportunity to say thank you for this great piece of software! It worked very reliable for me for quite some time now...

**Comment by abraunegg** [comment] 2019-10-03 04:21
@OneLineTwoBugs , @zell-mbc 
Can you please evaluate the following PR which will 'tone down' the messaging when using 'sync_list':

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/680/head:pr680
git checkout pr680
make clean; ./configure; make;
```

**Comment by OneLineTwoBugs** [comment] 2019-10-03 04:45
@abraunegg Your patch does wonders. My runtime is reduced from 5 mintues to 5 seconds per sync. I didn't care so much about the log output but about the runtime

**Comment by abraunegg** [comment] 2019-10-03 04:53
@OneLineTwoBugs 
Can you confirm the version of client your running - `onedrive v2.3.10-2-g0110179`  - or have you switched to using `--single-directory` ?

**Comment by OneLineTwoBugs** [comment] 2019-10-03 04:58
I am running `onedrive v2.3.10-2-g0110179` but my short runtime test was done using `--single-directory`. But even `--single-directory` had a very long runtime yesterday, now it finishes very quickly and does still handle changes if there are any. I will resync using `sync_list` and report back

**Comment by abraunegg** [comment] 2019-10-03 04:59
@OneLineTwoBugs 
OK ... using `sync_list` will bring back that 5 minute sync time.

The reason why `--single-directory` is so quick, is that it is able to use the changes specific to that directory your looking at - which you cannot do when using `sync_list`

**Comment by OneLineTwoBugs** [comment] 2019-10-03 05:02
@abraunegg Yes, this is exactly what I observe. I don't quite see why though. It seems that performance-wise, `--single-directory` is vastly superior to `sync_list` with a few items. Given that, wouldn't it make sense to run multiple `--single-directory` jobs for a `sync_list` with a few entries? I'm aware that this is not universally true (e.g. if someone has a sync_list of every folder in OneDrive, this may be slower), but I guess it would boost performance in many cases.

**Comment by abraunegg** [comment] 2019-10-03 05:10
> @abraunegg Yes, this is exactly what I observe. I don't quite see why though. It seems that performance-wise, `--single-directory` is vastly superior to `sync_list` with a few items. Given that, wouldn't it make sense to run multiple `--single-directory` jobs for a `sync_list` with a few entries? I'm aware that this is not universally true (e.g. if someone has a sync_list of every folder in OneDrive, this may be slower), but I guess it would boost performance in many cases.

Whilst this may seem totally logical, `sync_list` has 'files' & 'folders' as possible objects, + full path's or partial paths matching - so taking that approach is not possible.

The 'code' before fixing #658 took into account the 'previous' sync state, thus when you ran the client next, you only got all the 'object changes' since last sync. As in #658, a change could occur earlier & be missed due to parent not being included in 'sync_list' .. thus when moved into sync_list scope the change would be discarded.

The only reliable way to capture all 'changes on OneDrive' (ie - you moved something) when using a 'sync_list' file is to not use the 'last known delta' and re-validate all objects. 

This is why, when you are syncing so many objects and relying on 'sync_list' it now takes time to process through all objects.

**Comment by abraunegg** [comment] 2019-10-05 00:08
@OneLineTwoBugs , @zell-mbc 
Can you help validate the latest update to PR #680 which has the following changes:
* Updates messaging when using sync_list & what is actually occuring
* Only performs a full scan of all objects once (due to using sync_list and #658 bug fix), second scan uses the delta link

This should have the net effect of:
* full object scan being only done once to reduce processing overheads & time to complete
* files & folders moved into 'sync_list' scope when using the OneDrive Web UI are correctly downloaded

**Comment by zell-mbc** [comment] 2019-10-06 18:00
I did run the commands above but I am getting v v2.3.10-9-g0589113?
I also get an error when running make, not sure if this is as intended?
Also no change regarding the notifactions, they come in one after another.
`
git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 3449, done.
remote: Total 3449 (delta 0), reused 0 (delta 0), pack-reused 3449
Receiving objects: 100% (3449/3449), 2.04 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (2358/2358), done.

thomas at hermes in ~
$ cd onedrive 

thomas at hermes in ~/onedrive (master)
$ git fetch origin pull/680/head:pr680               
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/680/head -> pr680

thomas at hermes in ~/onedrive (master)
$ git checkout pr680
Switched to branch 'pr680'

thomas at hermes in ~/onedrive (pr680)
$ make clean; ./configure; make;
make: *** No rule to make target 'clean'.  Stop.
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.088.0-dirty
expr: non-integer argument
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.3.11-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive

thomas at hermes in ~/onedrive (pr680)
$ cat version
v2.3.10-9-g0589113
`

**Comment by abraunegg** [comment] 2019-10-06 18:47
@zell-mbc 
Looks like I switched the commands around - it's a non-fatal error anyways. The correct sequence is:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/680/head:pr680
git checkout pr680
./configure; make clean; make;
```

The version looks right for PR680 as well.

**Comment by zell-mbc** [comment] 2019-10-06 19:06
Ran the updated make statement and the error is indeed gone. Is there anything else I need to do make sure the patched version is used?
I ran sudo systemctl daemon-reload and also rebooted but it doesn't look like anything changed. These messenges are now showing every ~second for a good hour: 
Oct 06 21:05:06 hermes onedrive[5278]: Processing 220 changes

**Comment by abraunegg** [comment] 2019-10-06 19:08
@zell-mbc 
OK - so your running via systemd - did you install the PR version ?

From the above it sounds like you did not - I never advise to install the PR versions - it is best to run them standalone to validate the functionality / change before 'installing'

**Comment by OneLineTwoBugs** [comment] 2019-10-06 19:09
@abraunegg will test it tomorrow and report back here

**Comment by zell-mbc** [comment] 2019-10-06 19:36
Yes, of course, should have thought of that. 
I stopped the systemd service and ran the app manually from the onedrive folder. No visible change though...

thomas at hermes in ~/onedrive (pr680)
$ onedrive --monitor
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
Processing 246 changes
Processing 229 changes
Processing 202 changes
...

**Comment by abraunegg** [comment] 2019-10-06 20:12
@zell-mbc 
> `$ onedrive --monitor`

Yes - however you 'ran' your installed version ...

To run the PR version, in your PR directory:
```
./onedrive --monitor --verbose
```

**Comment by zell-mbc** [comment] 2019-10-06 20:20
@abraunegg 
I did indeed, sorry, getting late here...

$ ./onedrive --monitor --verbose
Using Config Dir: /home/thomas/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/data/OneDriveSync/
Application version: v2.3.10-9-g0589113
Account Type: personal
Default Drive ID: ff5afc812ce1f4fb
Default Root ID: FF5AFC812CE1F4FB!130
Remaining Free Space: 390180929923
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 60
Monitor directory: .
Monitor directory: ./SyncFolder
...lists all my folders
...followed by the usual processing messages
Processing 224 changes
Processing 224 changes
...

**Comment by abraunegg** [comment] 2019-10-06 20:21
@zell-mbc 
Something is not right. Below is a reference example:
```
[alex@centos7full onedrive-pr680]$ ./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose            
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-9-g0589113
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 4859752162
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_files/ES7B6yT9tyMmkIK4kboQ4fUKb4nXIzgM
Monitor directory: ./random_files/K2SLE0d9CUwqTjNFYbp7qI4slMJ7oIY8
Monitor directory: ./random_files/O8oC2wQAkiY7hokWv2beZd0MTd0JHcH1
Monitor directory: ./random_files/En3gHZR4hT03SNfnhWBfro7NODSIgW2W
Monitor directory: ./random_files/RqKRE4pzSwkzKtsVXPwGEom1ZIT8dLFt
Monitor directory: ./random_files/SMPP
Monitor directory: ./random_files/Architecture Layres
Monitor directory: ./random_files/eakbas
Monitor directory: ./random_files/MYOB Work
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing En3gHZR4hT03SNfnhWBfro7NODSIgW2W
The directory has not changed
Processing file13.data
The file has not changed
Processing file15.data
...
The file has not changed
Uploading new items of .
Skipping item - path excluded by sync_list: ./random_data
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 235 OneDrive items to ensure consistent state due to sync_list being used
Processing 191 OneDrive items to ensure consistent state due to sync_list being used
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing En3gHZR4hT03SNfnhWBfro7NODSIgW2W
The directory has not changed
Processing file13.data
The file has not changed
Processing file15.data
The file has not changed
...
The file has not changed
Uploading new items of .
Skipping item - path excluded by sync_list: ./random_data
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by zell-mbc** [comment] 2019-10-07 08:13
@abraunegg 
I restarted this morning and after initialising, onedrive started off with the usual "Processing xxx changes"
But when checking back just now, I see that things started to change at some point.

A see a bunch of these:
Processing 4MWUBJAVPEKNYMEDEK6XAII55ISHH367.lng
The file has not changed
Processing ZM

Then: "Deleting..., uploading...", looks all good.

And now I get hundreds of these:
Processing 261 OneDrive items to ensure consistent state due to sync_list being used

I will leave it running and report back here once it finished or something noteworthy happened.
Maybe it just needs to go through this once...

**Comment by abraunegg** [comment] 2019-10-07 08:44
@zell-mbc
It should only do a 'full' scan of OneDrive by default every 10 sync's. This is configurable via the config file options

**Comment by zell-mbc** [comment] 2019-10-07 13:28
@abraunegg, things have settled down again, but I wonder if what I see is simply due to the amount of data I have on Onedrive (>700 GB) and the fact that all of it is encrypted (=lot's of files).

Reading the posts above I may be better off switching from sync-list to a skip-dir setup?

**Comment by abraunegg** [comment] 2019-10-07 18:10
@zell-mbc 
> $ ./onedrive --synchronize --verbose --resync

You only need to run this 'once' when removing 'sync_list', not for each and every time - otherwise, your essentially deleting your local state each time and you have to check each and every file again from OneDrive.

> Reading the posts above I may be better off switching from sync-list to a skip-dir setup?

Most likely - as, what will happen is that when you remove the 'sync_list' & perform a resync your local state will now be in a state of 'sync' that the 'delta' can effectively be used - it wont need to scan OneDrive every X sync's to determine if you have moved 'something' into the sync scope which was previously out of scope.

> things have settled down again, but I wonder if what I see is simply due to the amount of data I have on Onedrive (>700 GB) and the fact that all of it is encrypted (=lot's of files).

OK - this is interesting. This tells me that your basically uploading to OneDrive and not editing files on OneDrive .. is this assumption correct?

If this assumption is correct, potentially you can bypass then entire OneDrive 'processing' checks for any method you pick for skipping directories by adding `--upload-only` to your command string

**Comment by zell-mbc** [comment] 2019-10-07 19:45
> Most likely - as, what will happen is that when you remove the 'sync_list' & perform a resync your local state will now be in a state of 'sync' that the 'delta' can effectively be used 

Things did indeed settle down by now and changes get picked up right away, as they used to do.

> If this assumption is correct...

Indeed, no updates from inside Onedrive, but potentially multiple machines synching into the same account (server,  pc, phone). But maybe I can simplify things be declaring one machine to be the "master" and only do uploads from that machine...need to think about this some more.
But in any case, my issue seems to be solved! Thanks for staying with me 😏

**Comment by abraunegg** [comment] 2019-10-07 20:30
@zell-mbc 
> But in any case, my issue seems to be solved!

Glad to hear

> Skipping item - excluded by skip_file config: Archive

A couple of questions: 
1. The use of skip_file & skip_dir .. are you using skip_file or skip_dir to skip these?
2. If 'skip_file' - are these symbolic links on your local system? (thus technically files) and messaging above is correct ...

**Comment by zell-mbc** [comment] 2019-10-07 21:16
@abraunegg, 
1. all entries are in skip_file: 

> #/ Skip files and directories that match this pattern
skip_file = "Archive|Attachments|Documents|Music|OneDriveOnly|Pictures"

2. No symbolic links, regular folders

The way I read the comment was that everything needs to be added to skip_file, and I am pretty sure it used to be like this at some point? Am I using an old config file where skip_directories did not yet exist? 

Changed skip_file to skip_dir and restarted the service. Looks like this will require a one time --resync again which I will have to complete on Wednesday as I am running out of time today and will be traveling tomorrow. I'll keep you posted!

**Comment by abraunegg** [comment] 2019-10-07 21:21
@zell-mbc 
> The way I read the comment was that everything needs to be added to skip_file, and I am pretty sure it used to be like this at some point? 

Unsure as skip_file | skip_dir was not discussed above - but `--single-directory` was

> Am I using an old config file where skip_directories did not yet exist?

skip_dir was not in the 'skilion' version, but has been included since v2.3.0 - https://github.com/abraunegg/onedrive/releases/tag/v2.3.0

**Comment by OneLineTwoBugs** [comment] 2019-10-08 15:28
Sorry for the late response.

I've used both `v2.3.10-14-ga92fe0d` and `v2.3.10-2-g0110179`. Both of them take a long time in case of having a sync_list and work very fast when using `--single-directory`. I haven't noticed a difference between the two. Is there something in particular I should check?

**Comment by abraunegg** [comment] 2019-10-08 19:15
@OneLineTwoBugs 
The main difference will be the messaging should be consistent in `10-14` however what all PR versions should do, when using sync_list is only perform a 'full scan' once. Before the PR, in monitor or synchronize mode the full scan would happen twice, falsely increasing the time it took to sync.

All of this is, as youve seen is vastly slower than using `--single-directory` - and given you only have 1 directory in `sync_list` then this is really the right approach for you.

**Comment by abraunegg** [comment] 2019-10-09 01:03
Closing issue as PR #680 is merged into master

**Closed by abraunegg** 2019-10-09 01:03 UTC
Labels: Enhancement, Implemented, Not a bug
