### ISSUE TITLE
Bug: Empty files are skipped

### ISSUE THREAD

**Issue by JC-comp** [abraunegg/onedrive#2602] opened 2024-01-21 18:33 UTC
### Describe the bug

Empty files are being skipped and marked as 'cannot be read'.
According to the [documentation](https://learn.microsoft.com/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online), it doesn't mention that we cannot upload empty files. I've tested, and we can indeed upload/update empty files. This might be a bug or at least the error message is not accurate.

```
Skipping processing this file as it cannot be read (file permissions or file corruption): path/to/empty/file
```

I think there are many places where empty files are not being handled, and this is the only one that is currently handled.
https://github.com/abraunegg/onedrive/blob/e92947ea327ced54dae276beb8d8481d9d88bb90/src/sync.d#L4735

### Operating System Details

```shell
skipped
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

v2.5.0-alpha-5 GitHub version: v2.4.25-47-ge92947e

### What is your OneDrive Application Configuration

```shell
skipped
```

### What is your 'curl' version

```shell
skipped
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
skipped
```

### What are all your local file system partition types

```shell
skipped
```

### How do you use 'onedrive'

skipped

### Steps to reproduce the behaviour

skipped

### Complete Verbose Log Output

```shell
v
```

**Comment by abraunegg** [comment] 2024-01-21 20:58
@JC-comp 
This is a regression - they were handled correctly. Fixed by https://github.com/abraunegg/onedrive/pull/2584/commits/deb63b6e7690c8220eba89da826591450d76c6b9

**Closed** 2024-01-21 20:58 UTC
Labels: Bug, Fixed, Regression

**Comment by abraunegg** [comment] 2024-01-29 01:27
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
