### ISSUE TITLE
Bug: When a complete folder with many files and subfolders is deleted and immediately replaced with a backup, the client may also delete some of the new files before it has finished deleting the old ones

### ISSUE THREAD

**Issue by pablobass** [abraunegg/onedrive#2476] opened 2023-08-25 22:40 UTC
### Describe the bug

When a complete folder with many files and subfolders is deleted and immediately copied (locally) from a backup with different versions of the same files, before the client finishes deleting the old files, it starts deleting some of the new ones as well (those that it had not yet deleted or is deleting from the previous folder). It deletes them both in the local folder and in the cloud. This can lead to the complete loss of a significant portion of the information.

### Operating System Details

```shell
Linux server 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.25-5-gfc5cbaf

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.25-5-gfc5cbaf
Config path                                  = /home/ingesir/.config/onedrive
Config file found in config path             = true
Config option 'sync_dir'                     = /shares
Config option 'enable_logging'               = true
Config option 'log_dir'                      = /home/ingesir/.config/onedrive/logs/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = lost+found|backup
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = *.tmp|*.crdownload|desktop.ini|thumbs*|.~*|.DS_Store|._.DS_Store|aquota.*|*.partial|~*
Config option 'skip_dotfiles'                = true
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 90
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 100
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'dns_timeout'                  = 60
Config option 'connect_timeout'              = 10
Config option 'data_timeout'                 = 600
Config option 'ip_protocol_version'          = 0
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=3942032k,nr_inodes=985508,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=800128k,mode=755,inode64)
/dev/mapper/vg0-lv--0--root on / type ext4 (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=20831)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/canonical-livepatch_235.snap on /snap/canonical-livepatch/235 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core_15511.snap on /snap/core/15511 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/canonical-livepatch_216.snap on /snap/canonical-livepatch/216 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core_15925.snap on /snap/core/15925 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1974.snap on /snap/core20/1974 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_2015.snap on /snap/core20/2015 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_19457.snap on /snap/snapd/19457 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/lxd_24322.snap on /snap/lxd/24322 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_19122.snap on /snap/snapd/19122 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/dev/mapper/vg0-lv--0--shares on /shares type ext4 (rw,relatime,quota,usrquota,grpquota)
/dev/md0p1 on /boot type ext4 (rw,relatime)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=800124k,nr_inodes=200031,mode=700,inode64)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=800124k,nr_inodes=200031,mode=700,uid=1000,gid=1000,inode64)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=800128k,mode=755,inode64)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
nsfs on /run/snapd/ns/canonical-livepatch.mnt type nsfs (rw)
```

### What are all your local file system partition types

```shell
NAME                    FSTYPE            FSVER    LABEL           UUID                                   FSAVAIL FSUSE% MOUNTPOINTS
loop0                   squashfs          4.0                                                                   0   100% /snap/canonical-livepatch/216
loop1                   squashfs          4.0                                                                   0   100% /snap/canonical-livepatch/235
loop2                   squashfs          4.0                                                                   0   100% /snap/core/15511
loop3                   squashfs          4.0                                                                   0   100% /snap/core/15925
loop4                   squashfs          4.0                                                                   0   100% /snap/core20/1974
loop5                   squashfs          4.0                                                                   0   100% /snap/core20/2015
loop6                   squashfs          4.0                                                                   0   100% /snap/snapd/19122
loop7                   squashfs          4.0                                                                   0   100% /snap/snapd/19457
loop8                   squashfs          4.0                                                                   0   100% /snap/lxd/24322
sda                                                                                                                      
├─sda1                  vfat              FAT32                    7BE4-A298                                   1G     1% /boot/efi
├─sda2                  linux_raid_member 1.2      ubuntu-server:0 6040f909-0167-0a98-9cc1-04a004314751                  
│ └─md0                                                                                                                  
│   └─md0p1             ext4              1.0                      71c30a6f-1959-45fe-af28-87e2f9dd1686    664.2M    26% /boot
└─sda3                  linux_raid_member 1.2      ubuntu-server:1 165f65a3-e340-e148-2cc6-49793096a0dd                  
  └─md1                 LVM2_member       LVM2 001                 gjFgdM-xopC-Ttjz-eWNL-r3WQ-g2sY-Co4f8D                
    ├─vg0-lv--0--root   ext4              1.0                      f61876de-b5fe-499e-b276-032df93e987f    168.8G     9% /
    └─vg0-lv--0--shares ext4              1.0                      cedeeea7-b280-4ae8-bcc8-64a5f0e5ac4f      1.2T    19% /shares
sdb                                                                                                                      
├─sdb1                  linux_raid_member 1.2      ubuntu-server:0 6040f909-0167-0a98-9cc1-04a004314751                  
│ └─md0                                                                                                                  
│   └─md0p1             ext4              1.0                      71c30a6f-1959-45fe-af28-87e2f9dd1686    664.2M    26% /boot
├─sdb2                  vfat              FAT32                    7C84-932D                                             
└─sdb3                  linux_raid_member 1.2      ubuntu-server:1 165f65a3-e340-e148-2cc6-49793096a0dd                  
  └─md1                 LVM2_member       LVM2 001                 gjFgdM-xopC-Ttjz-eWNL-r3WQ-g2sY-Co4f8D                
    ├─vg0-lv--0--root   ext4              1.0                      f61876de-b5fe-499e-b276-032df93e987f    168.8G     9% /
    └─vg0-lv--0--shares ext4              1.0                      cedeeea7-b280-4ae8-bcc8-64a5f0e5ac4f      1.2T    19% /shares
```

### How do you use 'onedrive'

OneDrive is used on a server with access to the folders from multiple Linux machines via Samba.

### Steps to reproduce the behaviour

To delete a folder with a large amount of files and immediately copy (locally) a similar folder from a backup with different versions of the same files.

### Complete Verbose Log Output

```shell
The log only shows files that are being deleted, followed by the upload of the remaining parts of the files.
```

**Comment by abraunegg** [comment] 2023-08-25 22:59
@pablobass 
Essentially you are causing a *race* condition here - and the application is stepping though your actions, still finding data that it thinks it has to delete - even though you have already put this back.

Now .. here is the next interesting item - you are running Ubuntu - and you are manually compiling the software.

*If* you have *any* older version on your system (skilion, Ubuntu package or other) - any other version running in the background - it 100% will be this old version that is causing this situation.

**Actions for you:**
1. Ensure you have absolutely zero Ubuntu Universe package installed.
2. Ensure you have absolutely zero falsely installed systemd service installed.
3. Remove all 'self compiled 'onedrive' binaries
4. Remove all 'Ubuntu 'onedrive' package installs
5. Install the application on Ubuntu following the *correct* process using the OpenSuSE Build Service packages: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

Once you have done this & validated that you are using the *correct* Ubuntu package + ensure that your *entire* Ubuntu system has zero other 'onedrive' binary lurking around, please can you re-test this scenario.

If post you doing the above, you are still having an issue, I am *not* going to work on this issue as a bug for v2.4.25 as you are causing the race condition yourself.

What I do ask is that when v2.5.0-alpha-0 drops (1-2 weeks from now) you revisit your testing using a *test account* and *test data*

**Comment by abraunegg** [comment] 2023-08-26 06:45
@pablobass 
> When a complete folder with many files and subfolders is deleted and immediately copied (locally) from a backup with different versions of the same files

An additional aspect I would like to understand here is - what do you classify as a 'complete folder with many files and sub folders' size wise? How many folders / files are you talking about here?

By default the application will prevent you from performing a 'mass online delete' if a folder is >1000 items (files and folders). This capability was introduced in v2.4.0.

**Comment by pablobass** [comment] 2023-08-26 17:46
> @pablobass Essentially you are causing a _race_ condition here - and the application is stepping though your actions, still finding data that it thinks it has to delete - even though you have already put this back.
> 
> Now .. here is the next interesting item - you are running Ubuntu - and you are manually compiling the software.
> 
> _If_ you have _any_ older version on your system (skilion, Ubuntu package or other) - any other version running in the background - it 100% will be this old version that is causing this situation.

I don't have, I was especially concerned about this

> **Actions for you:**
> 
> 1. Ensure you have absolutely zero Ubuntu Universe package installed.
> 2. Ensure you have absolutely zero falsely installed systemd service installed.
> 3. Remove all 'self compiled 'onedrive' binaries
> 4. Remove all 'Ubuntu 'onedrive' package installs
> 5. Install the application on Ubuntu following the _correct_ process using the OpenSuSE Build Service packages: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md
> 
> Once you have done this & validated that you are using the _correct_ Ubuntu package + ensure that your _entire_ Ubuntu system has zero other 'onedrive' binary lurking around, please can you re-test this scenario.

Okay, I'm going to follow each item step by step again and recompile from the link you sent me. To compile, I used the specific instructions for Ubuntu 22.04

> 
> If post you doing the above, you are still having an issue, I am _not_ going to work on this issue as a bug for v2.4.25 as you are causing the race condition yourself.
> 
> What I do ask is that when v2.5.0-alpha-0 drops (1-2 weeks from now) you revisit your testing using a _test account_ and _test data_

**Comment by pablobass** [comment] 2023-08-26 17:49
> @pablobass
> 
> > When a complete folder with many files and subfolders is deleted and immediately copied (locally) from a backup with different versions of the same files
> 
> An additional aspect I would like to understand here is - what do you classify as a 'complete folder with many files and sub folders' size wise? How many folders / files are you talking about here?
> 
> By default the application will prevent you from performing a 'mass online delete' if a folder is >1000 items (files and folders). This capability was introduced in v2.4.0.

The folders I deleted did not have more than 50 files each, and there were only three or four of them in total.

**Comment by abraunegg** [comment] 2023-08-26 19:58
@pablobass 
> Okay, I'm going to follow each item step by step again and recompile from the link you sent me.

Please do not try and compile the application.

Use the OpenSuSE Build Service packages.

> The folders I deleted did not have more than 50 files each, and there were only three or four of them in total.

This is a very small number of files|folders ..... I 100% suspect that there is a race condition going on with your system.

**Comment by abraunegg** [comment] 2023-08-30 19:17
@pablobass 
Please can you give me an *exact* sequence of what you did to trigger this and/or provide a script + folders of data that triggers this.

I have been attempting to try and replicate this situation, however I am 100% unable to do so.

**Comment by pablobass** [comment] 2023-08-30 22:16
> @pablobass Please can you give me an _exact_ sequence of what you did to trigger this and/or provide a script + folders of data that triggers this.
> 
> I have been attempting to try and replicate this situation, however I am 100% unable to do so.

First, I used the command "onedrive --synchornice" to synchronize about 400GB of data to the cloud in three folders, including many subfolders and files.

Second, I configured OneDrive to run in the background using the commands "systemctl --user enable onedrive.service" and "systemctl --user start onedrive.service".

After that, the synchronization started working perfectly.

A few days later, I deleted a subfolder with about 100 files of approximately 5MB each and replaced it with a backup of the same folder instantly, with modifications to some files.

That's when the "race" began and the client started deleting files indiscriminately, including both the files that had been deleted first from the folder and also part of the new ones that I had copied.

I hope you find the information I am providing useful.

If you need more data, I am available.

For the time being, I resolved the issue by disabling "onedrive --monitor" with the commands "systemctl --user stop onedrive.service" and "systemctl --user disable onedrive.service" and putting "onedrive --synchronize" in the crontab to run daily at 3AM, thus avoiding the "race."

**Comment by abraunegg** [comment] 2023-08-30 22:48
@pablobass 
OK I will try an replicate your process.

One item that *does* stick out with your configuration is the following:
```
Config option 'monitor_interval'             = 90
Config option 'monitor_fullscan_frequency'   = 100
```
With `'monitor_interval'             = 90`, you are checking OneDrive online for changes every 90 seconds ... this is highly ill-advised. You should be using a value of 300 or greater .. not something less than 300 seconds. What this means is the application is *constantly* trying to scan OneDrive online for changes and discarding any local inotify changes. This is potentially a root cause for your issue and potentially why I cannot replicate this issue thus far.

With `'monitor_fullscan_frequency'   = 100` you are then forcing a full scan of your data every 100 iterations of a check of OneDrive.

My advice here is that you change your 'config' file back to the defaults for these values and perform your testing again.

**Comment by abraunegg** [comment] 2023-09-01 21:49
@pablobass 
Please can you advise on your updated testing when using the correct application values & defaults.

**Comment by pablobass** [comment] 2023-09-01 23:24
> @pablobass Please can you advise on your updated testing when using the correct application values & defaults.

For the time being and due to time constraints, I am keeping "onedrive --synchronize" in the crontab at 3AM.

I have already changed the options you recommended in the configuration file.

As soon as I have the opportunity, I will test it and let you know the results, hopefully next week.

Sorry for the delay.

**Comment by abraunegg** [comment] 2023-09-11 22:49
@pablobass 
Any update here on your local testing?

**Comment by pablobass** [comment] 2023-09-12 02:26
> @pablobass Any update here on your local testing?

The problem occurred on the client's server, not on my PC. For the moment, they are happy with the result using the crontab and prefer that I do not touch it.

I apologize, if I ever find a way to do the test, I will do it.

**Comment by abraunegg** [comment] 2023-09-12 02:36
No problem - as such I am closing this issue:
* Using a non standard 'monitor_interval' value
* Unable to reproduce

**Closed by abraunegg** 2023-09-12 02:36 UTC
Labels: Wontfix - Short Term, Local Environment Issue, Waiting on Response, Unable to reproduce

**Comment by abraunegg** [comment] 2023-09-20 01:27
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
