### ISSUE TITLE
Unable to download any files from a shared folder

### ISSUE THREAD

**Issue by jswails** [abraunegg/onedrive#635] opened 2019-09-01 10:36 UTC
I am running the latest version on ubuntu 19.04
I started with running the basic synchronize. that downloaded from the drive and created the folder. the one thing I had not in a folder it downloaded. everything else was just a folder.

so i tried a single directory attempt:
```
onedrive --single-directory "Audio Books" --download-only  -v+++ --synchronize

Using Config Dir: /home/nope/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/nope/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.8-9-g219fce2
Account Type: personal
Default Drive ID: b1d4fa35ef5f1f0f
Default Root ID: B1D4FA35EF5F1F0F!101
Remaining Free Space: 5368311037
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: Audio Books
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: B1D4FA35EF5F1F0F!123
Applying changes of Path ID: D8C0CBAD315FF555!28517
Processing 20 changes
```

Here is the verbose error I get when I dont do single directory:
```
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
```

**Comment by abraunegg** [comment] 2019-09-01 19:14
@jswails 
Please can you update your post above with all the details as required as per https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md

You are missing from your first post:
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Application configuration: Output of `onedrive --display-config`
*   Curl Version: Output of `curl --version`
*   Steps to reproduce
*   Complete verbose log output
*   Debug log output sent via email

**Comment by abraunegg** [comment] 2019-09-02 00:49
@jswails 
Unable to reproduce. Please provide required information to enable diagnosis as to what is going on.

**Comment by jswails** [comment] 2019-09-02 15:03
Hi there I appreciate the response. This appears to be a very interesting product.

Hopefully this answers your requests. 

Its a desktop so a gui.

DMD64 D Compiler v2.087.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

onedrive version                    = v2.3.8-9-g219fce2
Config path                         = /home/nope/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/nope/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false

curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

**I showed you the steps to reproduce above in my original post so not sure I can put much more there. I installed it per your readme. I ran the commands already previously mentioned and tried ita few different ways.**

**Here is the entire output of the debug log. Its not very much.**

019-Sep-01 06:33:57.4406801 Initializing the OneDrive API ...
2019-Sep-01 06:33:57.677659 Opening the item database ...
2019-Sep-01 06:33:57.6803514 All operations will be performed in: /home/jadmin/OneDrive
2019-Sep-01 06:33:57.6807363 Initializing the Synchronization Engine ...
2019-Sep-01 06:33:58.534077 Application version: v2.3.8-9-g219fce2
2019-Sep-01 06:33:58.5342361 Account Type: personal
2019-Sep-01 06:33:58.5343187 Default Drive ID: b1d4fa35ef5f1f0f
2019-Sep-01 06:33:58.5343985 Default Root ID: B1D4FA35EF5F1F0F!101
2019-Sep-01 06:33:58.5344785 Remaining Free Space: 5368311037
2019-Sep-01 06:33:58.5345385 Fetching details for OneDrive Root
2019-Sep-01 06:33:58.7253261 OneDrive Root exists in the database
2019-Sep-01 06:33:58.7254978 Syncing changes from OneDrive ...
2019-Sep-01 06:33:58.7255679 Applying changes of Path ID: B1D4FA35EF5F1F0F!101
2019-Sep-01 06:33:59.1788414 Syncing OneDrive Shared Folder: Aquaculture
2019-Sep-01 06:33:59.1789024 Applying changes of Path ID: D8C0CBAD315FF555!9405
2019-Sep-01 06:33:59.6622473 Processing 26 changes
2019-Sep-01 06:33:59.6650451 Syncing OneDrive Shared Folder: Homesteading
2019-Sep-01 06:33:59.6651299 Applying changes of Path ID: D8C0CBAD315FF555!10103
2019-Sep-01 06:34:00.3441999 Processing 200 changes
2019-Sep-01 06:34:00.6567875 Processing 12 changes
2019-Sep-01 06:34:00.6586208 Syncing OneDrive Shared Folder: Health & Medical
2019-Sep-01 06:34:00.6587177 Applying changes of Path ID: D8C0CBAD315FF555!9513
2019-Sep-01 06:34:02.3752973 Processing 200 changes
2019-Sep-01 06:34:03.0268885 Processing 78 changes
2019-Sep-01 06:34:03.1813467 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:03.3361559 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:03.5047498 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:03.6600071 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:03.8158306 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:03.985606 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.1420386 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.2972095 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.4622509 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.6199339 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.7763387 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:04.9308384 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.1044036 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.2558437 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.4156532 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.577555 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.7519716 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:05.9139187 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.11066 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.2735758 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.4407442 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.6200166 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.7812495 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:06.9373087 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:07.1106273 Remote change discarded - not in --single-directory scope
2019-Sep-01 06:34:07.110744 Syncing OneDrive Shared Folder: Structures
2019-Sep-01 06:34:07.110779 Applying changes of Path ID: D8C0CBAD315FF555!9694
2019-Sep-01 06:34:07.5130713 Processing 48 changes
2019-Sep-01 06:34:07.5148903 Syncing OneDrive Shared Folder: Recipes
2019-Sep-01 06:34:07.5149398 Applying changes of Path ID: D8C0CBAD315FF555!9695
2019-Sep-01 06:34:08.0379559 Processing 94 changes

Thanks!

**Comment by jswails** [comment] 2019-09-02 15:13
I had lost internet with storms so wasnt able to post that last night. Today I tried on a different box to see if I could get a new result.

Ubuntu 18.04 - headless server. no gui. latest patches and updates.
Freshly installed all preqs

This time I ran everything as root to just see.
You can see I just installed dmd and set it as source for compile.

(**dmd-2.088.0**)root@quamquam:~/onedrive# onedrive --display-config
onedrive version                    = v2.3.9
Config path                         = /root/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /root/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
(dmd-2.088.0)root@quamquam:~/onedrive# onedrive --synchronize --verbose --dry-run

**here is the install of curl** 

url 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

here is the output of this run to download -only running this command
**onedrive --download-only --synchronize --verbose --dry-run**
Its strange that it sees everything and knows what to process yet does nothing.
Its this message being what seems to stop all the processing.

> Remote change discarded - not in --single-directory scope

(dmd-2.088.0)root@quamquam:~# onedrive --download-only --synchronize --verbose --dry-run
Using Config Dir: /root/.config/onedrive
No config file found, using application defaults
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.9
Account Type: personal
Default Drive ID: b1d4fa35ef5f1f0f
Default Root ID: B1D4FA35EF5F1F0F!101
Remaining Free Space: 5368311037
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: B1D4FA35EF5F1F0F!101
Processing 18 changes
Creating directory: Pictures
Creating directory: Documents
Downloading file Getting started with OneDrive.pdf ... done.
Creating directory: Aquaculture
Creating directory: Homesteading
Creating directory: Health & Medical
Creating directory: Structures
Creating directory: Recipes
Creating directory: Economic
Creating directory: Bushcraft
Creating directory: Energy
Creating directory: Terra
Creating directory: Science
Creating directory: Prophecy
Creating directory: Mythology
Creating directory: Communications
Creating directory: Audio Books
Syncing OneDrive Shared Folder: Aquaculture
Applying changes of Path ID: D8C0CBAD315FF555!9405
Processing 26 changes
Syncing OneDrive Shared Folder: Homesteading
Applying changes of Path ID: D8C0CBAD315FF555!10103
Processing 200 changes
Processing 12 changes
Syncing OneDrive Shared Folder: Health & Medical
Applying changes of Path ID: D8C0CBAD315FF555!9513
Processing 200 changes
Processing 78 changes
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Remote change discarded - not in --single-directory scope
Syncing OneDrive Shared Folder: Structures
Applying changes of Path ID: D8C0CBAD315FF555!9694
Processing 48 changes
Syncing OneDrive Shared Folder: Recipes
Applying changes of Path ID: D8C0CBAD315FF555!9695
Processing 94 changes
Syncing OneDrive Shared Folder: Economic
Applying changes of Path ID: D8C0CBAD315FF555!9966
Processing 12 changes
Syncing OneDrive Shared Folder: Bushcraft
Applying changes of Path ID: D8C0CBAD315FF555!10196
Processing 59 changes
Syncing OneDrive Shared Folder: Energy
Applying changes of Path ID: D8C0CBAD315FF555!10261
Processing 47 changes
Syncing OneDrive Shared Folder: Terra
Applying changes of Path ID: D8C0CBAD315FF555!10270
Processing 61 changes
Syncing OneDrive Shared Folder: Science
Applying changes of Path ID: D8C0CBAD315FF555!28669
Processing 69 changes
Syncing OneDrive Shared Folder: Prophecy
Applying changes of Path ID: D8C0CBAD315FF555!27836
Processing 17 changes
Syncing OneDrive Shared Folder: Mythology
Applying changes of Path ID: D8C0CBAD315FF555!28188
Processing 21 changes
Syncing OneDrive Shared Folder: Communications
Applying changes of Path ID: D8C0CBAD315FF555!28387
Processing 15 changes
Syncing OneDrive Shared Folder: Audio Books
Applying changes of Path ID: D8C0CBAD315FF555!28517
Processing 20 changes

**Comment by abraunegg** [comment] 2019-09-02 18:26
@jswails 
Thanks - OK .. based on the above I am currently assuming that there is something 'wrong' with your OneDrive Account configuration - data that should be received on certain API calls is not being sent.

To validate this assumption, please can you follow the directions as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

This will provide debug log details to see exactly what is being sent from OneDrive on each API call and how the client is interpreting this.

Additionally, it 'may' be worth testing PR #473 as this has an updated API response handling:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/473/head:pr473
git checkout pr473
make clean; make;
```

If you can perform the debug log & test the PR (and provide the debug log) that would be greatly appreciated.

**Comment by abraunegg** [comment] 2019-09-02 18:59
@jswails 
As a comparison, below is a verbose log file using a OneDrive Personal account that responds correctly, syncing folders & data from the account and shared folders:

```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Application version: v2.3.9
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5344852778
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 23 changes
Creating directory: Architecture Layres
Creating directory: shared
Creating directory: Images
Downloading file Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Creating directory: Images/PNG
Creating directory: Images/JPG
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-08-24-18-09-36.png ... done.
Downloading file Images/PNG/CentOS - iSCSI & NFS Mount Example System-2014-10-24-11-48-10.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-08-24-18-12-09.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-07-12.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-20-06.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-31-43.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-32-50.png ... done.
Downloading file Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-08-19.png ... done.
Downloading file Images/JPG/IMG_2920.JPG ... done.
Downloading file Images/JPG/IMG_2921.JPG ... done.
Downloading file Images/JPG/IMG_2919.JPG ... done.
Downloading file Images/JPG/IMG_2923.JPG ... done.
Downloading file Images/JPG/IMG_2924.JPG ... done.
Downloading file Images/JPG/IMG_2922.JPG ... done.
Downloading file Images/JPG/IMG_2926.JPG ... done.
Downloading file Images/JPG/IMG_2925.JPG ... done.
Syncing OneDrive Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
Processing 7 changes
Creating directory: shared/Cisco VDI Whitepaper
Creating directory: shared/SMPP
Downloading file shared/SMPP/SMPP-IF-SPEC_v3_3-24858.pdf ... done.
Downloading file shared/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Downloading file shared/Cisco VDI Whitepaper/campover.pdf ... done.
Downloading file shared/SMPP/SMPP_v3_4_Issue1_2-24857.pdf ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing shared
The directory has not changed
Processing shared
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing SMPP
The directory has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing Images
The directory has not changed
Processing PNG
The directory has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-09-36.png
The file has not changed
Processing CentOS - iSCSI & NFS Mount Example System-2014-10-24-11-48-10.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-12-09.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-07-12.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-20-06.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-31-43.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-32-50.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-08-19.png
The file has not changed
Processing JPG
The directory has not changed
Processing IMG_2920.JPG
The file has not changed
Processing IMG_2921.JPG
The file has not changed
Processing IMG_2919.JPG
The file has not changed
Processing IMG_2923.JPG
The file has not changed
Processing IMG_2924.JPG
The file has not changed
Processing IMG_2922.JPG
The file has not changed
Processing IMG_2926.JPG
The file has not changed
Processing IMG_2925.JPG
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing OneDrive Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
```

As you are not seeing 'similar' responses but 'Remote change discarded - not in --single-directory scope' this tells me that the API response you are getting is not complete.

**Comment by jswails** [comment] 2019-09-02 21:17
that makes sense with the api with how that error was coming out. I will compile the debug and do the PR and get back to you. might be a few days. I do appreciate the replies.

**Comment by jswails** [comment] 2019-09-02 22:37
Hi, I was able to work on this tonight. Please find attached the debug log. I cut it off when it started being repetitive. I am trying to download a lot of data so I just cut a good chunk to show the messages.
[onedrive-issue.txt](https://github.com/abraunegg/onedrive/files/3567168/onedrive-issue.txt)

this log is from the pr that you asked me to do.  I cleared out all of my other installs of the app and started from scratch with the PR to be clean.
I am wondering if my scenario is perhaps different than most. I am starting from fresh with none of the data locally. I have it all on the drive and I just want to download it all. Looking at the messages in the logs it would appear that it is skipping downloading because it does not find a copy locally to compare. 
Or could be I have a broken onedrive account with my access. Hard to say.

**Comment by abraunegg** [comment] 2019-09-02 22:46
@jswails 
Please can you send the entire debug log via email - not just cut it off where you think it is being repetitive. The log file you have attached here shows downloading / creating some local folders but then that is it. Please provide the full log file.

**Comment by jswails** [comment] 2019-09-03 09:17
ok here is the full log.
[download-only-afterPR.log](https://github.com/abraunegg/onedrive/files/3568775/download-only-afterPR.log)

**Comment by abraunegg** [comment] 2019-09-03 09:31
OK .. thanks .. that log is much better, although this is against the PR.

Will generate a new PR that pulls in some of those changes around the pattern matching, but not for the OneDrive Business Shared Folders as that is slightly more complex & still incomplete.

Just to confirm what your 'expecting' to occur - for example - you have a Shared Folder your syncing from, this folder is called 'Audio Books' (one of many your syncing from) and and example file your expecting to download 'TheSurrenderExperiment_ep6_mzZEhzuYo6QCjqZfE7buvIu1ZS4LE1V8fwn3SgrUGV4lOLO2ZKYv-jXC0YsoVQ.mp3'

**Comment by jswails** [comment] 2019-09-03 09:34
Yes sir

**Comment by abraunegg** [comment] 2019-09-03 09:43
To also assist with this, can you email to support@mynas.com.au the `items.sqlite3` file?

I want to compare this with what 'should' be stored & compare this against the valid account tests I have been making to assist with validating a fix

**Comment by abraunegg** [comment] 2019-09-03 21:06
@jswails 
Please can you rebuild your client with the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/637/head:pr637
git checkout pr637
make clean; make;
```

As I cannot replicate this issue (downloading files from shared folders works for me) this may require some constant testing on your behalf to get this right.

When running the above PR, please run in the following manner:
```
./onedrive --synchronize --verbose --verbose --resync
```

This will ensure that:
1. The local state database gets replaced
2. verbose debug logging is used

At the end of the sync - regardless of if this is successful or not, please email me the the resulting log file for analysis.

**Comment by abraunegg** [comment] 2019-09-04 00:04
Flagging this also as an API regression - refer to https://github.com/OneDrive/onedrive-api-docs/issues/1131

**Comment by jswails** [comment] 2019-09-04 09:25
here is the output of pr637. thanks!
[debug_pr637.log](https://github.com/abraunegg/onedrive/files/3573751/debug_pr637.log)

**Comment by abraunegg** [comment] 2019-09-04 09:33
Thanks - will go over that later tonight / tomorrow morning

**Comment by abraunegg** [comment] 2019-09-04 11:58
@jswails 
Can you please rebuild your client using the updated PR & provide an updated debug log

**Comment by jswails** [comment] 2019-09-05 00:28
here you go I did a redo of pr637. Is that not the one I should have done? 
[pr637.log](https://github.com/abraunegg/onedrive/files/3576922/pr637.log)
![Screenshot from 2019-09-04 20-21-58](https://user-images.githubusercontent.com/10682189/64302700-7fce3880-cf52-11e9-9bf0-2f11fb9cf923.png)

**Comment by abraunegg** [comment] 2019-09-05 00:43
I will check the log, but best 'delete' the code directory of 'onedrive' and clone again.

**Comment by abraunegg** [comment] 2019-09-05 00:54
That log is the original PR, not with the latest updates.

**Comment by abraunegg** [comment] 2019-09-06 04:05
@jswails 
Any update on testing the updated PR?

**Comment by abraunegg** [comment] 2019-09-06 21:20
@jswails
Any update on testing the updated PR?

**Comment by jswails** [comment] 2019-09-07 08:28
looks like that pr fixed it. Its going to run a while now as it was a lot of data but the output looks good so far. I will attach the full debug log when its done.

**Comment by abraunegg** [comment] 2019-09-07 08:42
Thanks for the feedback & thanks for the patience whilst getting this bug fixed. Will mark this as fixed once you confirm your sync finished sucessfully.

**Comment by jswails** [comment] 2019-09-07 09:47
Thank you for working on this. That was most helpful. No problem on testing as thats what we are all here for with this opensource.
[fixed-debug.log](https://github.com/abraunegg/onedrive/files/3586474/fixed-debug.log)

here is the full output.

**Comment by abraunegg** [comment] 2019-09-09 02:32
Closing issue as PR #637 merged into Master

**Closed by abraunegg** 2019-09-09 02:32 UTC
Labels: Bug, Fixed, OneDrive API Regression, OneDrive Personal - Shared Folders, Unable to reproduce
