### ISSUE TITLE
Bug: Constantly uploading "modified" binary files when nothing has changed

### ISSUE THREAD

**Issue by dtip** [abraunegg/onedrive#1260] opened 2021-02-06 09:16 UTC
### Bug Report Details ###
**Describe the bug**

My Onedrive contains a few binary files in a shared folder. These files were added by a Windows 10 user. Whenever onedrive syncs, it claims these binary files have been modified and uploads them, which causes constant sync activity for all users of the shared folder.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
```
Ubuntu 20.4
Linux hostname 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
Headless
*   OneDrive Account Type
Business
*   Did you build from source or install from a package?
Problem happens with apt package and latest build from master branch.
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
dmd-2.095.0
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.9-13-ge163d57
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.9-13-ge163d57
Config path                            = /home/dtip/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dtip/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=16353368k,nr_inodes=4088342,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3289352k,mode=755)
/dev/mapper/vgubuntu-root on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=33268)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/var/lib/snapd/snaps/authy_4.snap on /snap/authy/4 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-28-1804_145.snap on /snap/gnome-3-28-1804/145 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core18_1932.snap on /snap/core18/1932 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-34-1804_60.snap on /snap/gnome-3-34-1804/60 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-28-1804_128.snap on /snap/gnome-3-28-1804/128 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/authy_5.snap on /snap/authy/5 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-34-1804_66.snap on /snap/gnome-3-34-1804/66 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/discord_119.snap on /snap/discord/119 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/discord_120.snap on /snap/discord/120 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1514.snap on /snap/gtk-common-themes/1514 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1513.snap on /snap/gtk-common-themes/1513 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snapd_10707.snap on /snap/snapd/10707 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core18_1944.snap on /snap/core18/1944 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snap-store_498.snap on /snap/snap-store/498 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snapd_10492.snap on /snap/snapd/10492 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snap-store_518.snap on /snap/snap-store/518 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/sdb2 on /boot type ext4 (rw,relatime)
/dev/sdb1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3289348k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
NAME                  FSTYPE      LABEL   UUID                                   FSAVAIL FSUSE% MOUNTPOINT
loop0                 squashfs                                                         0   100% /snap/authy/4
loop1                 squashfs                                                         0   100% /snap/gnome-3-28-1804/128
loop2                 squashfs                                                         0   100% /snap/gnome-3-28-1804/145
loop3                 squashfs                                                         0   100% /snap/core18/1932
loop4                 squashfs                                                         0   100% /snap/gnome-3-34-1804/60
loop5                 squashfs                                                         0   100% /snap/authy/5
loop6                 squashfs                                                         0   100% /snap/gnome-3-34-1804/66
loop7                 squashfs                                                         0   100% /snap/discord/119
loop8                 squashfs                                                         0   100% /snap/discord/120
loop9                 squashfs                                                         0   100% /snap/gtk-common-themes/1514
loop10                squashfs                                                         0   100% /snap/gtk-common-themes/1513
loop11                squashfs                                                         0   100% /snap/snapd/10707
loop12                squashfs                                                         0   100% /snap/core18/1944
loop13                squashfs                                                         0   100% /snap/snap-store/498
loop14                squashfs                                                         0   100% /snap/snapd/10492
loop15                squashfs                                                         0   100% /snap/snap-store/518
sda                                                                                             
└─sda1                ntfs        Archive 3268D51168D4D4A7                                      
sdb                                                                                             
├─sdb1                vfat                9B2D-DC60                               503.2M     2% /boot/efi
├─sdb2                ext4                27252cae-4bbf-472d-b530-4dc623562f88    392.4M    37% /boot
└─sdb3                crypto_LUKS         c09a50f6-c310-4f3c-b626-d042cb26df00                  
  └─sda3_crypt        LVM2_member         a823jm-iHTy-vhoJ-2ZNZ-BvIf-MFKb-S0cBvE                
    ├─vgubuntu-root   ext4                65ddcbad-3bf7-48da-9a40-07ddb5c91c1d    288.9G    31% /
    └─vgubuntu-swap_1 swap                2ceec448-45e4-4a72-b14a-cb962c73def0                  [SWAP]
sdc                                                                                             
├─sdc1                vfat                BA25-A3B4                                             
├─sdc2                                                                                          
├─sdc3                ntfs                F26628B16628788D                                      
└─sdc4                ntfs                32D62526D624EBB3                                      
nvme0n1                                                                                         
├─nvme0n1p1           vfat                BEC2-3EA9                                             
├─nvme0n1p2                                                                                     
├─nvme0n1p3           ntfs                343EC2E63EC2A06A                                      
└─nvme0n1p4           ntfs                20E62C57E62C3008
```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
As above - folder is shared with multiple Windows 10 users.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Boot computer
2.  `systemctl` starts onedrive
3.  onedrive immediately starts syncing "modified" binary files which have not changed

**Complete Verbose Log Output**
N/A

Application Log Output:
N/A

**Screenshots**
N/A

**Additional context**
N/A

### Bug Report Checklist ###
* [x] Detailed description
* [x] Application and Operating System Details provided in full
* [x] Reproduction steps (if applicable)
* [ ] Verbose Log Output from your error
* [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-02-06 09:37
@dtip 
> onedrive immediately starts syncing "modified" binary files which have not changed

Something *will* be modifying the files.

In the past, it has been found that broken Ubuntu packages and desktop software *was* indeed modifying the timestamps of the files, thus, causing the files to be re-uploaded as *modified* - specifically binary files. Please refer to: https://github.com/abraunegg/onedrive/issues/824 - specifically, after looking at debug log files - https://github.com/abraunegg/onedrive/issues/824#issuecomment-603469431

As you have not submitted or provided a verbose log or verbose debug log as per the support requirements, I cannot provide any further details at this stage.

Until you provide more details via a debug log, I am flagging this as a local environment issue & not a bug.

**Comment by dtip** [comment] 2021-02-06 10:08
Here's a minimal output of the verbose log showing the problem:
```
Processing [file].bpn
[DEBUG] skip_file evaluation for: [file].bpn
The file last modified time has changed
The file content has changed
Uploading modified file [file].bpn
```

`ls -l` shows the file was last modified on 4th Feb. onedrive has uploaded it approx 100 time since then - looks like it uploads every time it syncs.

`stat` shows file was last modified 4th Feb and last accessed 2 hours ago (onedrive has uploaded it multiple times since then).
```
  File: [file].bpn
  Size: 50678240  	Blocks: 98984      IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 8652923     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/    dtip)   Gid: (  100/   users)
Access: 2021-02-06 08:22:26.339641054 +0000
Modify: 2021-02-04 20:37:36.000000000 +0000
Change: 2021-02-04 20:40:11.187741221 +0000
 Birth: -
```

Does that provide the info you're looking for?

**Comment by abraunegg** [comment] 2021-02-06 10:24
@dtip 
Without seeing the FULL debug log, it is hard to tell you what and why - however - something *is* telling the client that the file has been modified - but what?

There are 2 places that data comes from - your file system and OneDrive.

You will need to debug your filesystem first and trace each and every file access ... something outside this client is triggering this even though your `stat` does not show this. 

I can generate a PR that adds even more vebose details, but I highly doubt this will be helpful and the modified timestamp is coming from the file itself - thus ... why is your filesystem misreporting this?

**Comment by dtip** [comment] 2021-02-06 10:27
I'd love to, but can't redact a full debug log!

How do you recommend tracing file access? What are the possible reasons for onedrive thinking a file has changed over and above what's measured by `stat`?

**Comment by abraunegg** [comment] 2021-02-06 10:35
@dtip 
> I'd love to, but can't redact a full debug log!

Please stop being overly paranoid ... if you want me to sign a confidentiality agreement - fine, no issue ..

> How do you recommend tracing file access?

Suggest that you speak to your OS vendor support folk or the LUKS support team given you are running encryption.

**Comment by dtip** [comment] 2021-02-06 10:55
I guess the reason I'm asking you specifically is because I'm trying to understand why your immediate reaction is that this is a problem with the Ubuntu filesystem rather than with the way onedrive is checking for file modifications.

**Comment by abraunegg** [comment] 2021-02-06 11:18
@dtip 

> I guess the reason I'm asking you specifically is because I'm trying to understand why your immediate reaction is that this is a problem with the Ubuntu filesystem rather than with the way onedrive is checking for file modifications.

Because the code, makes a system call to get the file statistics and it is these that it uses to determine if the file has been modified. Your log file extract tells me enough - the client  when checking the file, found it to be modified based on its timestamp.

If this *was* a bug - and there *were* bugs like this especially with the skilion client which were fixed many releases ago, and if this was a current issue with the current codebase it would be a *very* hot topic and there would be many reports of this issue well before you raising this issue.

**Comment by dtip** [comment] 2021-02-06 11:55
I added some extra logging and rebuilt onedrive:
```
The local item has a different modified time 2021-Feb-06 10:02:10Z when compared to modified time 2021-Jan-20 16:39:15Z
```

The `itemModifiedTime` is clearly wrong (as well as the `localModifiedTime`). They should either both be 20th Jan or both be 6th Feb. This file has been uploaded to onedrive >10 times already today (6th Feb) and shown by the web interface. Any ideas what could cause that?

**Comment by abraunegg** [comment] 2021-02-06 20:11
> I added some extra logging and rebuilt onedrive:
> 
> ```
> The local item has a different modified time 2021-Feb-06 10:02:10Z when compared to modified time 2021-Jan-20 16:39:15Z
> ```

Useful - but you are *missing* (or you have removed and not used) the piece of critical data here - what is the *source* of where the timestamp is coming from. The original line comes from 2758 in sync.d and includes this piece of data.

> 
> The `itemModifiedTime` is clearly wrong (as well as the `localModifiedTime`). They should either both be 20th Jan or both be 6th Feb. This file has been uploaded to onedrive >10 times already today (6th Feb) and shown by the web interface. Any ideas what could cause that?

As I has said before, to assist you further, a FULL, unredacted debug log is needed to help you work out what is going on. I am not discounting a bug - but all evidence & my experience tells me something on your Ubuntu platform is causing this.

Steps for you do perform:
1. Find all 'onedrive' binaries and make sure you only have one binary, being the latest 'master' version or latest Ubuntu PPA package built binary present on your platform
    * You are running Ubuntu. You could have installed an older package from the Universe, maybe then from the PPA & finally installed from source. You potentially could have 3 different versions lurking around - check this and confirm this is *not* your problem. Upgrading the Ubuntu packages (Universe -> PPA) does *not* remove the old version correctly because they were packaged differently.
2. Perform a file system trace on all application access to the file(s) that are being impacted by this issue
    * You need to do this to *rule out* that no other application is *mangling* your file timestamp data. As per #824 3 different tools were found to be messing with the 'binary' files, causing this sort of situation you are seeing
3. Make sure you have ZERO file system bugs or ZERO kernel issues
    * Issue #1216 was caused by 'mdadm' and a kernel bug. The raid member would be out of sync, thus, when rebooting, the local item database was out of sync, because the filesystem had not flushed the data correctly, and on reboot, the alternate raid member was then being used = data loss. I suspected right away that this was potentially an issue, and days later the user confirmed that this *was* the case. To resolve this, the user had to upgrade their kernel - Kernel 5.10.2 can cause trouble with LVM2, BTRFS and MDADM, which is fixed by Kernel 5.10.8. You are running Kernel 5.8.0-41 but does this Kernel have the same bugs are Kernel 5.10.2 ? Potentially .... Do some research & find out
4. Provide a FULL unredacted debug log
    * This needs to show the multiple file uploads for the file(s) in question to track this through as to what is occurring. It would be good to compare this with other files that right now are also not impacted by this issue you are seeing
    * If you do not want to send the debug log, track the file through yourself, see what the code is doing, what the return responses from the API is doing as, depending on Account Type / location (eg SharePoint) the responses are different and Microsoft modifies your file post upload. The API response is then saved to the local database to future reference.
    * If you wont send the log, I cannot help you any more than I have. As said before I am prepared to sign any confidentiality agreement regarding information disclosure that you are paranoid about. I am not prepared to jeopardise my professional background by leaking someones debug log information and destroying my professional integrity.
5. Build a *brand new system* using a different distribution (do not use Ubuntu) - Debian, Arch, CentOS / RHEL and does the *exact same issue* occur?
    * If yes, then this would confirm that this is a bug of some sort, but, without the FULL debug log I cannot track down where this might be
    * If no, then, this would 100% confirm that this issue is 100% environmental to your setup, not an issue, not a bug and nothing that I can assist with further

**Comment by abraunegg** [comment] 2021-02-09 21:54
@dtip 
Any update on your testing in regards to the 5 points above to work out *why* you are seeing this sort of action only for a single file type?

Additionally, a `.bpn` file is an autosaved backup file automatically created at regular intervals by ArchiCAD, when the backup option is set. I spoke with the ArchiCAD support folk locally, and they are surprised that this file is causing an issue. It is also not used at all within the application or day-to-day use.

As such, a work around for your specific issue would be to exclude this type of file from sync operations by adding the following to your client configuration file:
```
skip_file = "*.bpn"
```
This will ensure that this file type is skipped from sync operations.

**Comment by sweharris** [comment] 2021-02-10 00:44
FWIW, I'm seeing similar.  My local machine is CentOS 7.9, and I'm using onedrive v2.4.9-10-g3b87602

Very frequently I can take a picture on my phone, which uploads to onedrive, and then I see it download and upload.

e.g.
`Feb 07 12:24:42 mercury7.spuddy.org onedrive[1268]: Downloading file Pictures/Camera Roll/IMG_20210207_122356.jpg ... done.
Feb 07 12:24:49 mercury7.spuddy.org onedrive[1268]: Uploading differences of Pictures/Camera Roll/IMG_20210207_122356.jpg
Feb 07 12:24:49 mercury7.spuddy.org onedrive[1268]: Uploading new items of Pictures/Camera Roll/IMG_20210207_122356.jpg
`

This also happens with files I edit with O365

`Feb 09 19:31:54 mercury7.spuddy.org onedrive[9091]: Downloading file tmp/tst.xlsx ... done.
Feb 09 19:32:01 mercury7.spuddy.org onedrive[9091]: Uploading differences of tmp/tst.xlsx
Feb 09 19:32:01 mercury7.spuddy.org onedrive[9091]: Uploading new items of tmp/tst.xlsx
`

In my case my ~/OneDrive is on an NFS share.  Not sure if this is relevant or not (attribute caching?)

I'm not obviously noticing any data corruption, just the unnecessary data transfer.

**Comment by abraunegg** [comment] 2021-02-10 01:06
@sweharris 
If you can generate a verbose debug log for this situation, this can be then investigated. Without the verbose debug log, it is hard to say exactly *why* this is occurring. I cannot replicate this situation locally.

**Comment by sweharris** [comment] 2021-02-10 01:23
I've sent an email support@mynas.com.au with what I think is the relevant extract.

I think something is triggering on the `IN_CLOSE_WRITE` event created by the act of writing out the new file!

**Comment by sweharris** [comment] 2021-02-10 01:52
If it helps and that debug file isn't good enough, I've set up a minimal test environment which can demonstrate the problem with a new account and no files, so it's pretty clean ;-)

```
Downloading file tst1 ... done.
Uploading differences of ./tst1
Uploading new items of ./tst1
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete

```

**Comment by abraunegg** [comment] 2021-02-10 02:13
@sweharris 
As confirmed via email - your issue is a logging output inconsistency issue, not the same issue as the original item that was raised.

PR #1265 will resolve this logging output inconsistency.

**Comment by sweharris** [comment] 2021-02-10 02:19
Hmm... compiling from fix-issue-1260 branch looks better.

Still some unnecessary directory upload alerts, but the file itself doesn't get flagged.

```
% onedrive --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Downloading file tst1 ... done.
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive
```

**Comment by abraunegg** [comment] 2021-02-10 02:22
@sweharris 
That actually now looks 100% normal, as, when `--synchronize` is used, the process is:
* Sync changes from OneDrive
* Check database entries to process all current items to detect local change
   * This is where `Uploading differences of ~/OneDrive` is printed
* Perform a inverse match to the previous to capture all *new* files 
   * This is where `Uploading new items of ~/OneDrive` is printed


So what you are seeing is 100% normal operation.

**Comment by sweharris** [comment] 2021-02-10 02:23
Then I guess it's good :-)

**Comment by sweharris** [comment] 2021-02-10 02:30
Although that branch is causing other issues... maybe my test environment is bad?

```
$ onedrive --synchronize
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive

$ onedrive --monitor --monitor-interval 30
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Retry sync count: 1: ~/OneDrive: No such file or directory
Retry sync count: 2: ~/OneDrive: No such file or directory
Giving up on sync after three attempts: ~/OneDrive: No such file or directory
std.file.FileException@/FastData/local/dmd2/linux/bin64/../../src/phobos/std/file.d(2051): ~/OneDrive: No such file or directory
```

**Comment by abraunegg** [comment] 2021-02-10 02:33
@sweharris 
Yes - this is a different issue ...

**Comment by sweharris** [comment] 2021-02-10 02:34
OK :-)  As long as you're aware :-)

**Comment by abraunegg** [comment] 2021-02-10 02:39
reverted commit to fix your issue - can you open a new issue for your logging problem, and revert to using 'master' for the moment. Master is `onedrive v2.4.9-17-g1bfd995`

**Comment by sweharris** [comment] 2021-02-10 02:47
See https://github.com/abraunegg/onedrive/issues/1266

**Comment by abraunegg** [comment] 2021-02-12 20:23
@dtip 
Please can you respond

**Comment by dtip** [comment] 2021-02-12 20:29
Still working on debugging - it's been a busy week

**Comment by abraunegg** [comment] 2021-02-17 19:41
@dtip 
Any update on your debugging?

**Comment by abraunegg** [comment] 2021-02-21 07:02
Closing issue for the following reasons:
* All evidence & my experience tells me this is something local to your system
  * Single file having the issue - if a bug, it would be *all* files impacted
  * Prior raised issues highlighted other influencing factors that created issue being seen
* The results for the above 5 areas of debugging have not been provided in a timely fashion
* No application debug log file has been provided as per request, which would provide a concrete answer to your issue
* Lack of response

**Closed by abraunegg** 2021-02-21 07:02 UTC
Labels: Local Environment Issue, More Information Needed, Not a bug, Waiting on Response, Workaround Available
