### ISSUE TITLE
Bug: Retry uploading always fails

### ISSUE THREAD

**Issue by priv** [abraunegg/onedrive#2306] opened 2023-02-17 09:43 UTC
### Describe the bug

From two days ago, I found a 3GB file cannot be uploaded correctly.

In the log it always says "The uploaded fragment has already been received."

Is it due to onedrive API change?

### Operating System Details

```shell
alvin@alvin-WS-E500:~/OneDrive/Backup$ uname -a
Linux alvin-WS-E500 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
alvin@alvin-WS-E500:~/OneDrive/Backup$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.23-2-g3acb6c1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.23-2-g3acb6c1
Config path                                  = /home/alvin/.config/onedrive
Config file found in config path             = true
Config option 'sync_dir'                     = /home/alvin/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp|*.swp|*.swx
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0 librtmp/2.3
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=20396068k,nr_inodes=5099017,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=4086752k,mode=755,inode64)
/dev/nvme0n1p2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=548)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/nvme2n1p1 on /mnt/intel660p type ext4 (rw,nosuid,nodev,relatime)
/dev/nvme1n1p1 on /mnt/sx8200pnp type ext4 (rw,nosuid,nodev,relatime)
/dev/sdb1 on /mnt/ct1000mx500 type ext4 (rw,nosuid,nodev,relatime)
/dev/sda1 on /mnt/st1000dm010 type ext4 (rw,nosuid,nodev,relatime)
/var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core18_2667.snap on /snap/core18/2667 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core18_2679.snap on /snap/core18/2679 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core20_1778.snap on /snap/core20/1778 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core20_1822.snap on /snap/core20/1822 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/firefox_2311.snap on /snap/firefox/2311 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/firefox_2356.snap on /snap/firefox/2356 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/gnome-3-38-2004_119.snap on /snap/gnome-3-38-2004/119 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_24239.snap on /snap/lxd/24239 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_24323.snap on /snap/lxd/24323 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/snap-store_599.snap on /snap/snap-store/599 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/snap-store_638.snap on /snap/snap-store/638 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/snapd_17950.snap on /snap/snapd/17950 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/snapd_18357.snap on /snap/snapd/18357 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/dev/nvme0n1p2 on /var/snap/firefox/common/host-hunspell type ext4 (ro,noexec,noatime,errors=remount-ro)
/var/lib/snapd/snaps/snapd-desktop-integration_43.snap on /snap/snapd-desktop-integration/43 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/snapd-desktop-integration_49.snap on /snap/snapd-desktop-integration/49 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide,x-gvfs-hide)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=4086748k,nr_inodes=1021687,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=4086752k,mode=755,inode64)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
nsfs on /run/snapd/ns/snapd-desktop-integration.mnt type nsfs (rw)
tmpfs on /var/snap/lxd/common/ns type tmpfs (rw,relatime,size=1024k,mode=700,inode64)
nsfs on /var/snap/lxd/common/ns/shmounts type nsfs (rw)
nsfs on /var/snap/lxd/common/ns/mntns type nsfs (rw)
nsfs on /run/snapd/ns/snap-store.mnt type nsfs (rw)
KeePassXC-2.7.1-x86_64_576dab8f950a606d804c98151fa0e60a.AppImage on /tmp/.mount_KeePasemozMM type fuse.KeePassXC-2.7.1-x86_64_576dab8f950a606d804c98151fa0e60a.AppImage (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000)
KeePassXC-2.7.1-x86_64_576dab8f950a606d804c98151fa0e60a.AppImage on /tmp/.mount_KeePasJ4fAcR type fuse.KeePassXC-2.7.1-x86_64_576dab8f950a606d804c98151fa0e60a.AppImage (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME        FSTYPE   FSVER LABEL       UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0                                                                             0   100% /snap/bare/5
loop1                                                                             0   100% /snap/core18/2667
loop2                                                                             0   100% /snap/core18/2679
loop3                                                                             0   100% /snap/core20/1778
loop4                                                                             0   100% /snap/core20/1822
loop5                                                                             0   100% /snap/firefox/2311
loop6                                                                             0   100% /snap/firefox/2356
loop7                                                                             0   100% /snap/gnome-3-38-2004/119
loop8       squashfs 4.0                                                          0   100% /snap/gtk-common-themes/1535
loop9       squashfs 4.0                                                          0   100% /snap/lxd/24239
loop10      squashfs 4.0                                                          0   100% /snap/lxd/24323
loop11      squashfs 4.0                                                          0   100% /snap/snap-store/599
loop12      squashfs 4.0                                                          0   100% /snap/snap-store/638
loop13      squashfs 4.0                                                          0   100% /snap/snapd/17950
loop14      squashfs 4.0                                                          0   100% /snap/snapd/18357
loop15      squashfs 4.0                                                          0   100% /snap/snapd-desktop-integration/43
loop16      squashfs 4.0                                                          0   100% /snap/snapd-desktop-integration/49
sda                                                                                        
└─sda1      ext4     1.0   st1000dm010 9e71ffee-ffcd-402d-8379-f34573e44f19  434.8G    47% /mnt/st1000dm010
sdb                                                                                        
└─sdb1      ext4     1.0   ct1000mx500 f30bdd28-a6eb-4c64-b4e7-1984ae3324bf  685.3G    20% /mnt/ct1000mx500
sdc                                                                                        
sr0                                                                                        
nvme0n1                                                                                    
├─nvme0n1p1 vfat     FAT32             126C-8EA5                             505.7M     1% /boot/efi
└─nvme0n1p2 ext4     1.0               58b60262-455e-4768-8978-8a5e98d4c643    131G    39% /var/snap/firefox/common/host-hunspell
                                                                                           /
nvme2n1                                                                                    
└─nvme2n1p1 ext4     1.0   intel660p   5aa6aaba-2fae-4442-a4f5-8bf4a230a72c  523.7G    39% /mnt/intel660p
nvme1n1                                                                                    
└─nvme1n1p1 ext4     1.0   SX8200PNP   2427e06c-927a-47d9-a2be-5fb5d9991acc    1.5T    12% /mnt/sx8200pnp
```

### How do you use 'onedrive'

Use as systemd user unit
```
alvin@alvin-WS-E500:~/OneDrive/Backup$ systemctl status onedrive --user
○ onedrive.service - OneDrive Free Client
     Loaded: loaded (/usr/lib/systemd/user/onedrive.service; enabled; preset: enabled)
     Active: inactive (dead)
       Docs: https://github.com/abraunegg/onedrive

Feb 17 10:56:44 alvin-WS-E500 onedrive[464753]: Starting a sync with OneDrive
Feb 17 10:56:44 alvin-WS-E500 onedrive[464753]: Syncing changes and items from OneDrive ...
Feb 17 10:56:45 alvin-WS-E500 onedrive[464753]: Performing a database consistency and integrity check on locally stored data due to fullscan requirement ...
Feb 17 10:56:53 alvin-WS-E500 onedrive[464753]: Uploading modified file Backup/mailbackup.tar.gz ...
Feb 17 10:58:13 alvin-WS-E500 onedrive[464753]: [671B blob data]
Feb 17 10:58:13 alvin-WS-E500 onedrive[464753]: Shutting down the HTTP instance
Feb 17 10:58:13 alvin-WS-E500 systemd[1634]: Stopping OneDrive Free Client...
Feb 17 10:58:13 alvin-WS-E500 onedrive[464753]: Shutting down db connection and merging temporary data
Feb 17 10:58:14 alvin-WS-E500 systemd[1634]: Stopped OneDrive Free Client.
Feb 17 10:58:14 alvin-WS-E500 systemd[1634]: onedrive.service: Consumed 1min 21.529s CPU time.
```

### Steps to reproduce the behaviour

Synchronize the folder with a big file until it timeouts.

### Complete Verbose Log Output

```shell
Uploading new items of ~/OneDrive                                   
Uploading new file ./Backup/mailbackup.tar.gz ...                                                                                        
Uploading   2% |oo                                      |   ETA   00:06:20 Internet connectivity to Microsoft OneDrive service has been restored                                                                                                                                   

Fragment upload failed - received an exception response from OneDrive                                                                    

ERROR: Microsoft OneDrive API returned an error with the following message:                                                              
  Error Message:    HTTP request returned status code 416 ()                                                                             
  Calling Function: upload()                                        

Retrying fragment upload                                            
Retry to upload fragment failed                                     

ERROR: Microsoft OneDrive API returned an error with the following message:                                                              
  Error Message:    HTTP request returned status code 416 ()                                                                             
  Error Reason:     The uploaded fragment has already been received.                                                                     
  Calling Function: upload()                                        

File upload session failed - invalid response from OneDrive                                                                              
Skipping item - excluded by skip_file config: ./Work/pool/2022-05-19/KX204-0200/~$Accessory_Certcificate_Data_is_garbled.xlsx                                                                                                                                                      
Applying changes of Path ID: 3D9D041A324CB7A5!621                                                                                        
Updated Remaining Free Space: 1045107815606                                                                                              
Number of items from OneDrive to process: 1                                                                                              
Sync with OneDrive is complete
```

**Comment by abraunegg** [comment] 2023-02-17 10:47
@priv 
> Is it due to onedrive API change?

Not in this case.

What is happening is that OneDrive is throwing a 416 error which is not an application error.

How to resolve

In your config folder there will be a file that tracks partial uploads. What will need to be done is:

1. Stop any applicable service
2. Remove the upload tracking file
3. Restart the applicable service

**Comment by abraunegg** [comment] 2023-02-17 20:24
Closing this issue as it is not an application bug.

> `The uploaded fragment has already been received`

The *only* other thought here that I have is this - your application version `onedrive v2.4.23-2-g3acb6c1`

Could it be 'possible' that you have 2 'onedrive' clients running on your system *somehow* - like an older self compiled version and/or maybe an older PPA version still lurking *somewhere* ?

An client version less than v2.4.17 and below would not have the database locking being performed. As such the following could happen:

* If the older client is started first, and then the newer client, both will operate at the same time. The newer client will output `The database is currently locked by another process - cannot sync` as an error message however
* If the newer client is started first, and then the older client, the older client *should* refuse to start citing that `An internal database error occurred: database is locked`

Now in that first case (and I have tested with running v2.4.17 and v2.4.23 at the same time) when adding a large file for upload:
* Both clients attempt to upload the same file at the same time
* Whilst I did not get any error, this sort of 'race' condition could explain your 416 response from the OneDrive API

Please can you check your entire system to ensure that there is no other 'onedrive' client binary lurking on your system.

Additionally, given that you are *also* using Ubuntu - you could also be hit with the Ubuntu packaging bug that existed for a long time - where a secondary systemd service was installed and created and it *is* running in the background - see: https://github.com/abraunegg/onedrive/issues/1274

The resolution is listed here: https://github.com/abraunegg/onedrive/issues/1274#issuecomment-813846904

This issue is *fixed* in the OpenSuSE Build Service Packages. It is strongly recommended that you use this repository to install the client on Ubuntu. Please check your system for the erroneous systdmd service link.

Please clean up your system fully and use these packages to install the client on your platform.

**Closed by abraunegg** 2023-02-17 20:24 UTC
Labels: Not a bug, OneDrive API Inconsistency

**Comment by priv** [comment] 2023-02-23 04:10
1. Does not seem like duplicated onedrive copy or upload tracking issues.
2. This can still be reproduced if I run in command line.(onedrive --resync --synchronize -v+)

This is most likely network issues but since retry won't succeed, I can only prevent to upload big files for now.

**Comment by abraunegg** [comment] 2023-02-26 22:47
@priv 

> 1. Does not seem like duplicated onedrive copy or upload tracking issues, there's no other onedrive copy and I do ps -aux before running tests.
> 2. This can still be reproduced if I run in command line.(onedrive --resync --synchronize -v+)
> 
> This is most likely network issues but since retry won't succeed, I can only prevent to upload big files for now.


Given that no-one else is reporting this, and that I am 100% unable to reproduce this - I 100% this issue is 100% localised | related to your environment.

**Comment by abraunegg** [comment] 2023-03-06 02:01
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
