### ISSUE TITLE
std.json.JSONException@std/json.d(540): Key not found: driveType 

### ISSUE THREAD

**Issue by AxelSally2** [abraunegg/onedrive#485] opened 2019-05-02 21:47 UTC
### Bug Report Details ###
**Description**
In Debian testing buster, if you suspend the syncing process and continue it after taking your laptop on Hibernation mode and changing your network (Wifi or LAN), you will have a

``std.json.JSONException@std/json.d(540): Key not found: driveType``

and you won't be able to do syncing again instead of **doing a git clone again and reinstalling**

**Application and Operating System Details:**
*   OS: Debian testing Buster
*   GUI: pantheon-desktop
*   OneDrive office 365 for Student
*   DMD64 D Compiler v2.085.1
*   Application configuration: not configure yet
*   Curl Version: 7.64.0

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  ``onedrive --synchronize``
2.  During the sync do ``^Z`` (**Control + Z**)
3.  Then put your laptop in Hibernation mode
4.  move your laptop to another WiFi area
5.  Turn on your laptop
6.  Connect your laptop to the new WiFi
7.  Continue the syncing process in the terminal ``fg [your_onedrive_job_id...]``
8.  See Error

**Fixing**
To fix it, I have just clonig the repo again and reinstall onedrive and syncing my files without suspend it.

**Comment by abraunegg** [comment] 2019-05-02 21:52
@AxelSally2 
Please can you test your scenario using PR #484 please and provide feedback

**Comment by abraunegg** [comment] 2019-05-02 21:55
Duplicate of #483

**Comment by abraunegg** [comment] 2019-05-03 18:32
@AxelSally2
Any update from your side as to testing the PR against your issue?

**Comment by AxelSally2** [comment] 2019-05-04 19:11
ok this resolve it. But now I must first re-execute the command with ``onedrive --synchronise --download-only`` option after the **fg** command because when the program come on foreground, it try to continue the syncing but it goes on a timeout. If I execute the command without ``--download-only`` , the program will sync my locaI files with the remote and suppress the files on the repo that isn't in my local. I think it's normal because It's a syncing.

**Comment by abraunegg** [comment] 2019-05-05 10:53
@AxelSally2 
Yes - this would be normal to re-execute because:
1. you ctrl-z the application
2. you change wifi AP / networks and the authentication information MS has about your connection is now invalid

I don't know why your even wanting to suspend the application before hibernating the application as well - the init.d / systemd scripts work with system hibernation and correctly re-execute the application on system resume.

Closing this issue as:
1. resolved
2. local environmental issue (your forcing the application to suspend which breaks the MS authentication)

**Closed by abraunegg** 2019-05-05 10:53 UTC
Labels: Duplicate, Waiting on Response
