### ISSUE TITLE
allow configurable time of log message in monitor mode

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#378] opened 2019-02-14 20:06 UTC
As discussed in https://github.com/abraunegg/onedrive/pull/376 it might be nice to be able to configure how often an alive message is sent to the log/stdout. By now we do this unconditionally on every sync (by default every 45sec), but it might be a nice to have a configurable time interval.

**Comment by abraunegg** [comment] 2019-02-14 21:16
Potentially the easiest option here is a new flag '--minimal-logging'

If not true, do the log output as intended.

That could be used then in monitor and or standalone modes to really supress output everywhere

**Comment by norbusan** [comment] 2019-02-14 21:51
Sounds like a good plan, but let me think a bit about it.

**Comment by abraunegg** [comment] 2019-02-26 20:21
Closing as PR #391 merged

**Closed by abraunegg** 2019-02-26 20:21 UTC
