### ISSUE TITLE
Client stuck at Continuing the upload session

### ISSUE THREAD

**Issue by Unknown-Guy** [abraunegg/onedrive#494] opened 2019-05-08 19:54 UTC
### Bug Report Details ###
**Describe the bug**
```bash
 % journalctl --user-unit onedrive -f
-- Logs begin at Sat 2018-04-28 00:04:14 EEST. --
May 07 21:13:00 monstrs onedrive[20694]: [197B blob data]
May 07 21:13:46 monstrs onedrive[20694]: Continuing the upload session ...
May 07 21:14:47 monstrs onedrive[20694]: [197B blob data]
May 07 21:15:33 monstrs onedrive[20694]: Continuing the upload session ...
May 07 21:18:25 monstrs onedrive[20694]: [208B blob data]
May 07 21:18:25 monstrs systemd[20683]: Stopping OneDrive Free Client...
May 07 21:18:25 monstrs systemd[20683]: Stopped OneDrive Free Client.
May 08 21:32:44 monstrs systemd[23401]: Started OneDrive Free Client.
May 08 21:32:46 monstrs onedrive[23412]: Initializing the Synchronization Engine ...
May 08 21:32:49 monstrs onedrive[23412]: Continuing the upload session ...
May 08 21:33:57 monstrs onedrive[23412]: [181B blob data]
May 08 21:33:57 monstrs onedrive[23412]: OneDrive monitor interval (seconds): 45
May 08 21:34:44 monstrs onedrive[23412]: Continuing the upload session ...
May 08 21:35:48 monstrs onedrive[23412]: [197B blob data]
May 08 21:36:33 monstrs onedrive[23412]: Continuing the upload session ...
May 08 21:42:05 monstrs onedrive[23412]: [197B blob data]
May 08 21:42:50 monstrs onedrive[23412]: Continuing the upload session ...
May 08 21:44:59 monstrs onedrive[23412]: [197B blob data]
```

Running it this way just exits after like 5 minutes:
```bash
 % onedrive --synchronize --verbose
Using Config Dir: /home/monstrs/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /data/Family
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: [redacted]
Default Root ID: [redacted]
Remaining Free Space: 1099004754743
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
Continuing the upload session ...
Uploading   4% |oo                                      |   ETA   --:--:--:%      

% echo $?
141                                                                                                    
```

So next tried this, exited much faster with same exit code:
```bash
% rm ~/.config/onedrive/resume_upload
% onedrive --synchronize -vvv
[skipped]
[DEBUG] Checking file: ./Pictures/mikes/mikes pics/IMAG0338.jpg
[DEBUG] Checking file: ./Pictures/mikes/mikes pics/IMAG0351.jpg
[DEBUG] Checking file: ./Pictures/mikes/mikes pics/IMAG0359.jpg
[DEBUG] Checking file: ./Pictures/mikes/mikes pics/VIDEO0031.mp4
Uploading new file ./Pictures/mikes/mikes pics/VIDEO0031.mp4 ...
Uploading   4% |oo                                      |   ETA   --:--:--:% 
```

Has happened to other files, noticed that they all have been more than ~4MB in size, this one is 82MB, all files I could move or open just fine. For now I just put them in subdir with `.nosync`. Also upload % ranges from 4% to 100%. One did successfully upload after renaming.

**Application and Operating System Details:**
*   OS: `Linux monstrs 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   no gui
*   personal
*   DMD64 D Compiler v2.086.0
*   Application configuration:
```
onedrive version                    = v2.3.3-5-gaf43b77
Config path                         = /home/monstrs/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = true
Config option 'sync_dir'            = /data/Family
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```
*   Curl Version: `curl 7.58.0`

**Comment by abraunegg** [comment] 2019-05-08 20:10
@Unknown-Guy 
Will need a full debug https log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support unredacted and sent via email capturing this issue

**Comment by Unknown-Guy** [comment] 2019-05-08 21:41
Interestingly, it successfully uploaded the file it was stuck when running with HTTP debug and output redirection. Let it run like 15 minutes and did not fail.

Stopped, moved the files it previously failed to upload back, had no issues uploading. Sync is still running fine.

Will leave it running like this, getting too late here. There's 50GB total so I would expect it to fail as there was 5 fails uploading first GB.

**Comment by abraunegg** [comment] 2019-05-08 21:44
Thanks for the update. It sounds like maybe one of the following:
* OneDrive was spitting an internal error for something and the client was silently exiting
* Internet connectivity issues upstream from you during upload caused interuption thus caused the connection to time out

**Comment by abraunegg** [comment] 2019-05-09 10:13
@Unknown-Guy 
Any update from your side as to recurrence of your issue?

**Comment by Unknown-Guy** [comment] 2019-05-09 19:39
Sent logs just now. Had two errors.

This one looks like the original one I had:
```
< HTTP/1.1 100 Continue
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
* stopped the pause stream!
* Closing connection 2
```

The "unauthenticated" one is new to me.

**Comment by abraunegg** [comment] 2019-05-09 19:49
@Unknown-Guy 
OK ... most 'likely' there is some sort of SSL issue between your Linux host and Microsoft - depending on your ISP - they may be doing some sort of SSL inspection analysis as well.

As this error is coming from your Linux OS OpenSSL libraries - I would go investigate that as this is not a bug with this client. The 'upload error' is just the result of the SSL failure.

Closing issue, not a bug, SSL Library issue.

**Closed by abraunegg** 2019-05-09 19:49 UTC
Labels: More Information Needed, OneDrive Personal, Waiting on Response

**Comment by Unknown-Guy** [comment] 2019-05-09 20:01
Thanks, will investigate further on my own. Will add here if find cause for this.
