### ISSUE TITLE
Bug: Can't sync at all

### ISSUE THREAD

**Issue by vickariofillis** [abraunegg/onedrive#2040] opened 2022-07-12 21:22 UTC
### Describe the bug

I have tried multiple times using both --synchronize and --synchronize --resync but there is no change in the OneDrive folder. It remains empty. I have removed and installed the application multiple times, reauthorized, as well as sign out and authorize from scratch.

### Operating System Details

```shell
The OS is Ubuntu 22.04.

uname -a: Linux Lab-Desktop 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Client Installation Method

From Distribution Package

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.19-1+np1

### What is your OneDrive Application Configuration

```shell
onedrive version                             = v2.4.19-1+np1
Config path                                  = /home/vic/.config/onedrive
Config file found in config path             = false
Config option 'sync_dir'                     = /home/vic/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 5
Config option 'monitor_fullscan_frequency'   = 12
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_2'                 = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = true
sync_list contents:
# sync_list supports comments
#
# The ordering of entries is highly recommended - exclusions before inclusions
#
# Exclude temp folders under Documents
!Documents/temp*
# Exclude my secret data
!/Pictures/
!/Travel/
!/Documents/SEGA
!/Documents/Sports Interactive
!/Documents/Save Games
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=16343804k,nr_inodes=4085951,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3275700k,mode=755,inode64)
/dev/nvme0n1p2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=22609)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2409.snap on /snap/core18/2409 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1405.snap on /snap/core20/1405 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1518.snap on /snap/core20/1518 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core22_188.snap on /snap/core22/188 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/firefox_1498.snap on /snap/firefox/1498 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/firefox_1551.snap on /snap/firefox/1551 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-28-1804_161.snap on /snap/gnome-3-28-1804/161 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-34-1804_77.snap on /snap/gnome-3-34-1804/77 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-38-2004_112.snap on /snap/gnome-3-38-2004/112 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-38-2004_99.snap on /snap/gnome-3-38-2004/99 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1534.snap on /snap/gtk-common-themes/1534 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/inkscape_10417.snap on /snap/inkscape/10417 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/onenote-desktop_17.snap on /snap/onenote-desktop/17 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/signal-desktop_388.snap on /snap/signal-desktop/388 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/slack_63.snap on /snap/slack/63 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/slack_64.snap on /snap/slack/64 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snap-store_575.snap on /snap/snap-store/575 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snap-store_582.snap on /snap/snap-store/582 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_16010.snap on /snap/snapd/16010 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_16292.snap on /snap/snapd/16292 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd-desktop-integration_10.snap on /snap/snapd-desktop-integration/10 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd-desktop-integration_14.snap on /snap/snapd-desktop-integration/14 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/spotify_60.snap on /snap/spotify/60 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/sublime-text_112.snap on /snap/sublime-text/112 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/teams_7.snap on /snap/teams/7 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/telegram-desktop_4024.snap on /snap/telegram-desktop/4024 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/vlc_2344.snap on /snap/vlc/2344 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/zoom-client_170.snap on /snap/zoom-client/170 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3275700k,mode=755,inode64)
nsfs on /run/snapd/ns/snapd-desktop-integration.mnt type nsfs (rw)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3275696k,nr_inodes=818924,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
nsfs on /run/snapd/ns/signal-desktop.mnt type nsfs (rw)
nsfs on /run/snapd/ns/snap-store.mnt type nsfs (rw)
nsfs on /run/snapd/ns/telegram-desktop.mnt type nsfs (rw)
nsfs on /run/snapd/ns/spotify.mnt type nsfs (rw)
nsfs on /run/snapd/ns/slack.mnt type nsfs (rw)
nsfs on /run/snapd/ns/firefox.mnt type nsfs (rw)
/home/vic/Documents/ripes.AppImage on /tmp/.mount_ripes.xdBErZ type fuse.ripes.AppImage (ro,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME       FSTYPE   FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0      squashfs 4.0                                                    0   100% /snap/core18/2409
loop1      squashfs 4.0                                                    0   100% /snap/bare/5
loop2      squashfs 4.0                                                    0   100% /snap/core20/1405
loop3      squashfs 4.0                                                    0   100% /snap/core20/1518
loop4      squashfs 4.0                                                    0   100% /snap/core22/188
loop5      squashfs 4.0                                                    0   100% /snap/firefox/1498
loop6      squashfs 4.0                                                    0   100% /snap/firefox/1551
loop7      squashfs 4.0                                                    0   100% /snap/gnome-3-28-1804/161
loop8      squashfs 4.0                                                    0   100% /snap/gnome-3-38-2004/112
loop9      squashfs 4.0                                                    0   100% /snap/gnome-3-34-1804/77
loop10     squashfs 4.0                                                    0   100% /snap/gnome-3-38-2004/99
loop11     squashfs 4.0                                                    0   100% /snap/gtk-common-themes/1534
loop12     squashfs 4.0                                                    0   100% /snap/gtk-common-themes/1535
loop13     squashfs 4.0                                                    0   100% /snap/inkscape/10417
loop14     squashfs 4.0                                                    0   100% /snap/onenote-desktop/17
loop15     squashfs 4.0                                                    0   100% /snap/signal-desktop/388
loop16     squashfs 4.0                                                    0   100% /snap/slack/63
loop17     squashfs 4.0                                                    0   100% /snap/slack/64
loop18     squashfs 4.0                                                    0   100% /snap/snap-store/575
loop19     squashfs 4.0                                                    0   100% /snap/snap-store/582
loop20     squashfs 4.0                                                    0   100% /snap/snapd/16010
loop21     squashfs 4.0                                                    0   100% /snap/snapd/16292
loop22     squashfs 4.0                                                    0   100% /snap/snapd-desktop-integration/10
loop23     squashfs 4.0                                                    0   100% /snap/snapd-desktop-integration/14
loop24     squashfs 4.0                                                    0   100% /snap/spotify/60
loop25     squashfs 4.0                                                    0   100% /snap/sublime-text/112
loop26     squashfs 4.0                                                    0   100% /snap/teams/7
loop27     squashfs 4.0                                                    0   100% /snap/telegram-desktop/4024
loop28     squashfs 4.0                                                    0   100% /snap/vlc/2344
loop29     squashfs 4.0                                                    0   100% /snap/zoom-client/170
sr0                                                                                 
nvme0n1                                                                             
├─nvme0n1p1
│          vfat     FAT32       CB73-A156                             484.3M     5% /boot/efi
└─nvme0n1p2
           ext4     1.0         532c9dec-a961-4e3f-9d76-5210fa8c9d44  183.3G    16% /
```

### How do you use 'onedrive'

I have OneDrive installed in two other Windows laptops. Whether they are turned on or off makes no difference. I had some issues in the past with files named with the name of the Linux PC, but syncing worked.

### Steps to reproduce the behaviour

Running onedrive --synchronize, onedrive --synchronize --resync and onedrive --synchronize --download-only.

### Complete Verbose Log Output

```shell
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/vic/OneDrive
Application version: v2.4.19-1+np1
Account Type: personal
Default Drive ID: 6ae3de0f6baa6e58
Default Root ID: 6AE3DE0F6BAA6E58!133
Remaining Free Space: 6185234294
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 6AE3DE0F6BAA6E58!133
Updated Remaining Free Space: 6185234294
Processing 246 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Document.docx
Skipping item - excluded by sync_list config: Games
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: Desktop
Skipping item - excluded by sync_list config: Documents
Skipping item - excluded by sync_list config: University
Processing 323 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 317 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 317 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 320 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 320 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 326 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 326 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 326 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 322 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 235 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 220 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 225 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 236 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: University
Processing 222 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: University
Processing 229 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Linux
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: Documents
Skipping item - excluded by sync_list config: University
Processing 216 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: Documents
Skipping item - excluded by sync_list config: University
Processing 325 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Pictures
Skipping item - excluded by sync_list config: Documents
Skipping item - excluded by sync_list config: University
Processing 323 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 323 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 325 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 324 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 329 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: University
Processing 314 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Skipping item - excluded by sync_list config: University
Processing 220 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 211 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 217 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 214 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 220 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 220 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 228 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 216 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 217 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
Processing 216 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documents
^C
```

### Additional context

It seems that onedrive thinks that all folders are excluded. I have definitely not excluded the Documents/ and the University/ folders, as verbose output suggests.

**Comment by abraunegg** [comment] 2022-07-12 21:26
@vickariofillis 
Potentially this is user configuration error:
```
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = true
sync_list contents:
# sync_list supports comments
#
# The ordering of entries is highly recommended - exclusions before inclusions
#
# Exclude temp folders under Documents
!Documents/temp*
# Exclude my secret data
!/Pictures/
!/Travel/
!/Documents/SEGA
!/Documents/Sports Interactive
!/Documents/Save Games
```

You are explicitly telling the client to exclude directories, but include nothing ... so nothing will be synced ...

Please check your configuration and retest by adding `--dry-run`

**Comment by vickariofillis** [comment] 2022-07-12 21:34
Is it possible to include everything by default (without specifically mentioning each one of them) and just exclude certain directories?

Thanks.

**Comment by abraunegg** [comment] 2022-07-12 21:57
@vickariofillis 

> Is it possible to include everything by default (without specifically mentioning each one of them) and just exclude certain directories?
> 
> Thanks.
> 
> EDIT: Nevermind. * works. Some excluded directories were created, but they are empty.

This is a classic case of not reading the documentation. Please read:
* https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-sync-via-sync_list-file

Closing issue, should have been a discussion, not a bug.

**Closed by abraunegg** 2022-07-12 21:57 UTC
Labels: More Information Needed, Not a bug, Local Environment Issue, Waiting on Response

**Comment by abraunegg** [comment] 2022-07-20 02:37
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
