### ISSUE TITLE
upload and monitoring fails

### ISSUE THREAD

**Issue by 366Cobra** [abraunegg/onedrive#624] opened 2019-08-21 09:13 UTC
Hi,

I have tried using the app for a couple of weeks now and it seems to fail after several hours.
sometimes after 1h, sometimes after 17h.
when uploading only, the app dies silently without error.
when using monitoring it dies with a 401 after 3 retries.
i always run in verbal mode to see what is going on.

here is the output when monitoring:
```
#onedrive --verbose --upload-only --monitor
Uploading new file ./home/E6C/F4E89D864F3238AB5A84633581A30 ...Giving up on sync after three attempts: HTTP request returned status code 401 (Unauthorized)
{
    "error": {
        "code": "unauthenticated",
        "innerError": {
            "date": "2019-08-20T11:24:15",
            "request-id": "1e294a7e-6963-45d1-bd39-98eb224d6c45"
        },
        "message": "Access Denied"
    }
}
onedrive.OneDriveException@src/onedrive.d(826): HTTP request returned status code 401 (Unauthorized)
{
    "error": {
        "code": "unauthenticated",
        "innerError": {
            "date": "2019-08-20T11:24:15",
            "request-id": "1e294a7e-6963-45d1-bd39-98eb224d6c45"
        },
        "message": "Access Denied"
    }
}
----------------
src/onedrive.d:51 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x56301dd84662]
src/onedrive.d:578 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x56301dd83ae5]
src/onedrive.d:250 std.json.JSONValue onedrive.OneDriveApi.simpleUpload(immutable(char)[], immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x56301dd82151]
src/sync.d:2127 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x56301dd98bc6]
src/sync.d:1912 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x56301dd97c41]
src/sync.d:1896 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x56301dd97a9c]
src/sync.d:1896 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x56301dd97a9c]
src/sync.d:1896 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x56301dd97a9c]
src/sync.d:1380 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x56301dd95b2d]
src/main.d:620 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x56301dd7fb3c]
src/main.d:506 _Dmain [0x56301dd7f33f]
```
i am logging begin and end times of the runs as well.
```
begin: Thu 15 Aug 22:50:14 AEST 2019
end:   Thu 15 Aug 23:08:16 AEST 2019
begin: Fri 16 Aug 18:00:05 AEST 2019
end:   Fri 16 Aug 18:47:06 AEST 2019
begin: Fri 16 Aug 20:13:56 AEST 2019
end:   Fri 16 Aug 20:56:07 AEST 2019
begin: Sat 17 Aug 00:01:41 AEST 2019
end:   Sat 17 Aug 00:17:53 AEST 2019
begin: Sat 17 Aug 08:54:26 AEST 2019
end:   Sat 17 Aug 09:03:15 AEST 2019
begin: Sat 17 Aug 18:29:21 AEST 2019
end:   Sun 18 Aug 03:30:35 AEST 2019
begin: Sun 18 Aug 11:02:31 AEST 2019
end:   Mon 19 Aug 01:03:25 AEST 2019
begin: Mon 19 Aug 18:09:32 AEST 2019
end:   Tue 20 Aug 03:11:07 AEST 2019
begin: Tue 20 Aug 17:20:36 AEST 2019
end:   Tue 20 Aug 21:24:15 AEST 2019
```
i cannot seem to find a way to increase the number of retries.
i do upload a tonne of very small files

would be great if you let me know what else to try.

```
Linux wepwawet 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
no GUI
```

**Application and Operating System Details:**
*   `Linux 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 `GNU/Linux
Ubuntu
*   no GUI
*   OneDrive Account Type - personal
*   DMD64 D Compiler v2.087.1
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.8-2-g893e235
Config path                         = /home/wepwawet/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /mnt/data/dataEnc
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
```

**Comment by abraunegg** [comment] 2019-08-21 09:34
Thanks for the bug report - will look at this shortly.

Also as an FYI - --upload-only cannot be used with --monitor .. it is ignored by design .. but this is not the cause of your problem

**Comment by abraunegg** [comment] 2019-08-21 19:58
@366Cobra 
> i do upload a tonne of very small files

Please can you provide some further details here - how many files / file size are you talking about here? I have tested many times uploading 50K random files and the upload always has been successful so it would be good to get an idea of the type of files. Currently running this again on a Ubuntu test server and so far also zero issues.

Can you also update your curl version - you also need to provide what it is compiled with - for example:
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

Also, to assist in debugging this issue, given you can replicate this consistently and at present I cannot, please can you generate a verbose debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

The command you would be looking to use to validate the 'upload only' part as well would be:
```
onedrive --synchronize --verbose --verbose --upload-only > debug_output.log 2>&1
```

**Comment by abraunegg** [comment] 2019-08-21 22:03
@366Cobra 
To assist with generating the debug log as requested above, please can you use the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/625/head:pr625
git checkout pr625
make clean; ./configure; make;
```

This should fix the application exception causing the unhandled exit, but at the moment will not fix why, half way through your uploading, OneDrive tells you that your now 'Unauthorised'

**Question:** Do you / have you also enabled NTP on your Linux system to ensure that the local time clock is as accurate as possible? It could be that a time 'skew' is causing the OneDrive API to invalidate your session because your local clock skews

**Comment by 366Cobra** [comment] 2019-08-22 12:13
Thanks for the quick reply.

the files are 32Ks in size and once I am done there will be about 2.5M of them.

i am using the most up to date version of curl for my ubuntu version.  i have just kicked off another sync with the above mentioned sources (and running debug log) and if that fails as well, then i will grab the latest curl.

Automatic date and time, including automatic time zone had already been set.

**Comment by 366Cobra** [comment] 2019-08-22 12:16
this is probably not the place to ask, but is there a way to increase the speed of the upload?
i have 20MBit upload speed, but only about 1x 32KB file is transferred per second.

**Comment by abraunegg** [comment] 2019-08-22 20:56
@366Cobra 
> the files are 32Ks in size and once I am done there will be about 2.5M of them.

Thanks - will see if I can trigger this with this sort of combination.

> Automatic date and time, including automatic time zone had already been set.

Yes .. but how is your Ubuntu OS keeping in time sync? Have you enabled NTP? On a stock standard Ubuntu install there is no time sync by default to ensure the local clock does not drift (as it can and does). If your local clock is drifting even by a few seconds, then the OneDrive session could be failing because of this clock drift. Refer to https://vitux.com/how-to-install-ntp-server-and-client-on-ubuntu/ to enable NTP on your system to rule this out as a cause of why your getting `HTTP request returned status code 401 (Unauthorized)` all the time.

> this is probably not the place to ask, but is there a way to increase the speed of the upload?
The client is not multi-threaded at present. Refer to #157 and #232 for further details

**Comment by abraunegg** [comment] 2019-08-23 20:45
@366Cobra 
After running the client through ~100K files and running for ~18hrs with the PR, finally able to replicate this:
```
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file904.data ... done.
Remaining free space: 4690224151
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file955.data ...ERROR: OneDrive returned a 'HTTP 401 - Unauthorized' - gracefully handling error
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file812.data ... done.
Remaining free space: 4690210807
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file203.data ... done.
Remaining free space: 4690180224
```

The good news here is that the PR handles the response and continues without the crash.

**Comment by abraunegg** [comment] 2019-08-24 05:55
Closing as PR #625 is merged into master which resolves this issue

**Closed by abraunegg** 2019-08-24 05:55 UTC
Labels: Bug, Fixed

**Comment by 366Cobra** [comment] 2019-08-24 09:00
great that it has been solved.  my upload is still going as well.
the log file is already 83MB ;)

**Comment by abraunegg** [comment] 2019-08-24 09:56
@366Cobra 
Glad to hear that it is also resolved for you. Suggest that you also rebuild from the latest master to pick up all the other changes / updates merged today.
