### ISSUE TITLE
Unkown key in config file: rate_limit

### ISSUE THREAD

**Issue by programhlpr** [abraunegg/onedrive#1268] opened 2021-02-10 15:58 UTC
### Bug Report Details ###
I have copied the config file from the FAQ to my local filesystem at ~/.config/onedrive/config. I can remove the # to uncomment and enable the logging and log location without issue. However, when I tried to move the # before `rate_limit = "131072" ` and change the value to "104857600", the program no longer understands the configuration file. When running the command:
`onedrive --display-config`
I get the following response:
`Unknown key in config file: rate_limit
Configuration file has errors - please check your configuration`

uname -a: SMP PREEMPT Sun, 07 Feb 2021 22:42:17 +0000 x86_64 GNU/Linux
OS: ARCH system with mate GUI installed. 
AUR Package Installed: onedrive-abraunegg-2.4.9-1
AUR DMD compiler: dmd-1:2.095.0-1
Installed via yay -S which builds the package from source
OneDrive Plan: OneDrive - 1TB of space on a Office365 family plan

With the rate_limit variable commented out, I have the following config per the output of this command `onedrive --display-config:`
```
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.9
Config path                            = /home/myuser/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/myuser/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
If I uncomment the rate_limit variable and leave it as the default value per this config file:
```
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the li>
# For explanations of all config options below see docs/USAGE.md or the man pa>
#
# sync_dir = "~/OneDrive"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "300"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
# enable_logging = "true"
# force_http_11 = "false"
# force_http_2 = "true"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
# classify_as_big_delete = "1000"
# user_agent = ""
# remove_source_files = "false"
# skip_dir_strict_match = "false"
# application_id = ""
# resync = "false"
# bypass_data_preservation = "false"
# azure_ad_endpoint = ""
# azure_tenant_id = "common"
# sync_business_shared_folders = "false"
# sync_dir_permissions = "700"
# sync_file_permissions = "600"
rate_limit = "131072"
```
I get this output when running `onedrive --display-config`
```
Unknown key in config file: rate_limit
Configuration file has errors - please check your configuration
```
I'm not sure if I'm doing something wrong or if it's not working correctly so I've submitted this as a bug report. Please let me know if you want me to do any testing.

**Comment by abraunegg** [comment] 2021-02-10 16:56
@programhlpr 
This is not a bug - sorry. This issue is because you have installed via the AUR package `onedrive-abraunegg-2.4.9-1`, and the 'rate_limit' config option was added post the v2.4.9 release, thus, not included in the package you are using.

You only have 2 options here:
* Wait for v2.4.10 release
* Build from source

**Comment by programhlpr** [comment] 2021-02-10 16:59
Perfect! Thank you for that super quick attention and update.

**Comment by abraunegg** [comment] 2021-02-10 17:08
Closing issue, question answered

**Closed by abraunegg** 2021-02-10 17:08 UTC
Labels: Answer Provided, Not a bug
