### ISSUE TITLE
Again (not) disappearing files when changes are done on web

### ISSUE THREAD

**Issue by norbusan** [abraunegg/onedrive#732] opened 2019-11-22 10:51 UTC
All with 
```
onedrive version                    = v2.3.11-6-gdb5cecc
Config path                         = /home/norbert/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/norbert/OneDrive
Config option 'skip_dir'            = GpsMaps/Maps|GpsMaps/MapPrograms|Desktop|Pictures/Archive
Config option 'skip_file'           = desktop.ini|metadata.db-journal
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

Today I moved a **lot** of images (3000 or so) via the web interface from `Pictures/Eigene Aufnahmen` to `Pictures/Archive/201904-201910`.

After that I run a --sync, nothing was removed.

I checked the web, the files were all moved, correctly.

After that I removed the files locally in `Pictures/Eigene Aufnahmen` and started another --sync run, which ended with all the files having been removed from `Pictures/Archive/201904-201910`.

Fortunately, there is the WasteBasket and Restore All on the web interface.

Now I am scared to run **anything** onedrive related on my computer ...

**Comment by norbusan** [comment] 2019-11-22 10:55
PS I dared to run a --resync, just to see lots and lots of dead mommies getting resurrected ... files that have been deleted but now reappeared :-(

**Comment by abraunegg** [comment] 2019-11-22 19:56
@norbusan 
Do you have a debug log or anything ? Will try and replicate this locally ...

**Comment by abraunegg** [comment] 2019-11-22 20:46
@norbusan 
> Today I moved a lot of images (3000 or so) via the web interface from Pictures/Eigene Aufnahmen to Pictures/Archive/201904-201910.

> After that I run a --sync, nothing was removed.

I replicated your config and (hopefully) process .. and the following is rather telling as to why the images where not moved:

```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.11-7-g133c45e
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5345924817
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 58 changes
Skipping item - excluded by skip_dir config match: Pictures/Archive
Uploading differences of .
Processing root
The directory has not changed
Processing Pictures
The directory has not changed
Processing Eigene Aufnahmen
The directory has not changed
```

Your 'Archive' directory being skipped due to config!

**Comment by abraunegg** [comment] 2019-11-22 21:11
@norbusan 
When I look at the individual file move under debug:
```
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 16 of 17
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzo2NkQ1M0JFOEE1MDU2RUNBITE1OTM4OS4yNTc","eTag":"aNjZENTNCRThBNTA1NkVDQSExNTkzODkuNw","file":{"hashes":{"quickXorHash":"kRh59IBbDSuwdT5aMmC\/20vyXAo=","sha1Hash":"AC7DFB6D904204AACEB9CE3E2F526787DC6F5E94"},"mimeType":"image\/png"},"fileSystemInfo":{"createdDateTime":"2019-11-22T20:32:18.27Z","lastModifiedDateTime":"2019-11-22T21:00:02.386Z"},"id":"66D53BE8A5056ECA!159389","name":"image9.png","parentReference":{"driveId":"66d53be8a5056eca","driveType":"personal","id":"66D53BE8A5056ECA!159482","name":"201904-201910","path":"\/drive\/root:\/Pictures\/Archive\/201904-201910"},"size":231250}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 66D53BE8A5056ECA!101
[DEBUG] 'search id'                                          = 66D53BE8A5056ECA!101
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = 66D53BE8A5056ECA!159482
[DEBUG] syncFolderName                                       = root
[DEBUG] syncFolderPath                                       = 
[DEBUG] syncFolderChildPath                                  = 
[DEBUG] thisItemId                                           = 66D53BE8A5056ECA!159389
[DEBUG] thisItemPath                                         = /drive/root:/Pictures/Archive/201904-201910
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemPath' contains 'syncFolderChildPath'        = true
[DEBUG] 'thisItemPath' contains search 'id'                  = false
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] This item was previously synced / seen by the client
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 17 of 17
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"aYzo2NkQ1M0JFOEE1MDU2RUNBITE1OTM5Mi4yNTc","eTag":"aNjZENTNCRThBNTA1NkVDQSExNTkzOTIuNw","file":{"hashes":{"quickXorHash":"nccxM8tvAzEiJGyllE61xoywClw=","sha1Hash":"9AC8B87DDE5F4EB4EACF15C22A3DFFFFEBFCC863"},"mimeType":"image\/png"},"fileSystemInfo":{"createdDateTime":"2019-11-22T20:32:23.14Z","lastModifiedDateTime":"2019-11-22T21:00:02.47Z"},"id":"66D53BE8A5056ECA!159392","name":"image12.png","parentReference":{"driveId":"66d53be8a5056eca","driveType":"personal","id":"66D53BE8A5056ECA!159482","name":"201904-201910","path":"\/drive\/root:\/Pictures\/Archive\/201904-201910"},"size":231248}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 66D53BE8A5056ECA!101
[DEBUG] 'search id'                                          = 66D53BE8A5056ECA!101
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = 66D53BE8A5056ECA!159482
[DEBUG] syncFolderName                                       = root
[DEBUG] syncFolderPath                                       = 
[DEBUG] syncFolderChildPath                                  = 
[DEBUG] thisItemId                                           = 66D53BE8A5056ECA!159392
[DEBUG] thisItemPath                                         = /drive/root:/Pictures/Archive/201904-201910
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemPath' contains 'syncFolderChildPath'        = true
[DEBUG] 'thisItemPath' contains search 'id'                  = false
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] This item was previously synced / seen by the client
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
```

So essentially the same fix that was done for sync_list is needed here as well.

**Comment by abraunegg** [comment] 2019-11-22 21:26
@norbusan 
Please can you validate this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/733/head:pr733
git checkout pr733
./configure; make clean; make;
```

**Comment by abraunegg** [comment] 2019-11-22 21:35
@norbusan 
With the PR, and moving files from A -> B using the web interface:
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.11-8-g186b245
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5345924817
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 11 changes
Skipping item - excluded by skip_dir config match: Pictures/Archive
Trying to delete item Pictures/Eigene Aufnahmen/image12.png
Deleting item Pictures/Eigene Aufnahmen/image12.png
Trying to delete item Pictures/Eigene Aufnahmen/image9.png
Deleting item Pictures/Eigene Aufnahmen/image9.png
Trying to delete item Pictures/Eigene Aufnahmen/image8.png
Deleting item Pictures/Eigene Aufnahmen/image8.png
Trying to delete item Pictures/Eigene Aufnahmen/image7.png
Deleting item Pictures/Eigene Aufnahmen/image7.png
Trying to delete item Pictures/Eigene Aufnahmen/image6.png
Deleting item Pictures/Eigene Aufnahmen/image6.png
Trying to delete item Pictures/Eigene Aufnahmen/image5.png
Deleting item Pictures/Eigene Aufnahmen/image5.png
Uploading differences of .
Processing root
The directory has not changed
Processing Pictures
The directory has not changed
Processing Eigene Aufnahmen
The directory has not changed
Processing image0.png
The file has not changed
Processing image1.png
The file has not changed
Processing image2.png
The file has not changed
Processing image3.png
```

**Comment by abraunegg** [comment] 2019-11-22 21:36
@norbusan 
I guess this 'regression' would have been caught if #711 was done!

**Comment by abraunegg** [comment] 2019-11-23 00:21
Closing issue as PR #733 merged

**Closed by abraunegg** 2019-11-23 00:21 UTC
Labels: Bug, Fixed, Regression
