### ISSUE TITLE
get-O365-drive-id does not give detail as to which share is which

### ISSUE THREAD

**Issue by jasonblewis** [abraunegg/onedrive#1348] opened 2021-03-16 23:50 UTC
when I run `onedrive --get-O365-drive-id 'myorg'` the output does not make clear which ID relates to which shared library.

I expect it to show some indication of which drive-id relates to which shared library

eg

```
jason@quartz:~/.config/onedrive$ onedrive --get-O365-drive-id 'myorg'
Configuration file successfully loaded
Configuring Global Azure AD Endpoints


Office 365 Library Name Query: myorg
SiteName: myorg
drive_id: b!<redacted>
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com
SiteName: myorg
drive_id: b!<redacted> 
URL:      https://myorg.sharepoint.com

jason@quartz:~/.config/onedrive$ onedrive --version
onedrive v2.4.10-16-g6bec0dd

```
built from source on debian bullseye today.

```
jason@quartz:~/.config/onedrive$ onedrive --display-config
Configuration file successfully loaded
onedrive version                       = v2.4.10-16-g6bec0dd
Config path                            = /home/jason/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/jason/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

```
(dmd-2.096.0)jason@quartz:~/.config/onedrive$ dmd --version
DMD64 D Compiler v2.096.0
Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

**Comment by abraunegg** [comment] 2021-03-17 00:17
@jasonblewis 
> I expect it to show some indication of which drive-id relates to which shared library

The output does .. so I am unsure what the issue is here ... also your totally 'redacted' output basically tells me nothing of your issue. 

For example:

**output when site name cannot be found:**
```
./onedrive --confdir '~/.config/onedrive-business-test/' --get-O365-drive-id 'blah'  
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: blah

ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site.

The following SharePoint site names were returned:
 * Communication site
 * Community
 * PointPublishing Hub Site
 * Team Site
 * testteamsite2
 * testteamsite
 * All Company
 * mynasau3
 * test site
 * Data Production
```

**searching for 'testteamsite':**
```
./onedrive --confdir '~/.config/onedrive-business-test/' --get-O365-drive-id 'testteamsite'
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: testteamsite
SiteName: testteamsite
drive_id: <redacted>
URL:      https://mynasau3.sharepoint.com/sites/testteamsite
```
**Notes:**
* The site name is listed
* The unique drive_id is listed
* The unique URL of the SharePoint site is listed

You should be able to tell which drive_id is associated with what sitename & URL from the application output without issue.

If you have named *all* your SharePoint sites the *same* name - that is something I cannot assist with .........

**Comment by abraunegg** [comment] 2021-03-17 00:17
Closing issue, not a bug or issue

**Closed by abraunegg** 2021-03-17 00:17 UTC

**Comment by jasonblewis** [comment] 2021-03-17 01:34
We have 2 Shared Libraries, and 7 "Document Libraries" within one of the shared libraries.

The output I pasted above is exactly as is except I redacted the drive ids. 

![Screenshot from 2021-03-17 12-26-59](https://user-images.githubusercontent.com/129165/111400759-1a006680-871c-11eb-91f6-2024939c74c1.png)


the output from `onedrive --get-O365-drive-id 'OT'` does not indicate which document library relates to a drive ID.

```
jason@quartz:~/ot/general/PDF$ onedrive --get-O365-drive-id 'OT'
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Office 365 Library Name Query: OT
SiteName: OT
drive_id: b!<part of drive id redacted>iFhtfUTJQ60CfXRuEl
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>owE8TomKUQgtfqTs
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>_BpBDXSLpwYLEpqRLQ
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>3fkm9aRYSbQrB6-w53
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>UeQj9SRIPGRJBv3Cqa
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>C8mC0pRr0fuzSaOIC_
URL:      https://myorg.sharepoint.com
SiteName: OT
drive_id: b!<part of drive id redacted>AzfIMTQoynD2gN2NKM
URL:      https://myorg.sharepoint.com
```
Each of the drive id's output by the command do relate to the shared libraries, and seem to be in the same order as they appear in the screenshot. they just don't show any indicator as to the name.

**Comment by abraunegg** [comment] 2021-03-17 03:08
@jasonblewis 
> the output from onedrive --get-O365-drive-id 'OT' does not indicate which document library relates to a drive ID.

There lies your issue.

The `--get-O365-drive-id` switch as documented in https://github.com/abraunegg/onedrive/blob/master/docs/SharePoint-Shared-Libraries.md is for getting the drive_id for your 'OT' Shared Library.

It is *not* for getting / listing the document / folders under that Shared Library - however I do find it interesting that it is listing those when you use that configuration option ... as I am unable to replicate that sort of behavior.

This being said, the client option *is* functioning as expected and as documented.
