### ISSUE TITLE
Unable to sync folder called 'App_Code' or 'App_Data'

### ISSUE THREAD

**Issue by brindleoak** [abraunegg/onedrive#200] opened 2018-10-15 19:18 UTC
Synchronize has stopped working. I updated to latest version - same result

Processing 08-We Are The Dead.aif
The file has not changed
Processing .directory
The file has not changed
uploading new items of .
std.json.JSONException@std/json.d(1470): Unexpected character '<'. (Line 1:1)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}

.
.
.

----------------
/home/simon/dlang/dmd-2.082.1/linux/bin64/../../src/phobos/std/json.d:740 pure @safe void std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions).error(immutable(char)[]) [0x5af208]
/home/simon/dlang/dmd-2.082.1/linux/bin64/../../src/phobos/std/json.d:1140 pure @safe void std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions).parseValue(ref std.json.JSONValue) [0x5afffe]
/home/simon/dlang/dmd-2.082.1/linux/bin64/../../src/phobos/std/json.d:1146 pure @safe std.json.JSONValue std.json.parseJSON!(char[]).parseJSON(char[], int, std.json.JSONOptions) [0x5af16b]
src/onedrive.d:491 std.json.JSONValue onedrive.OneDriveApi.perform() [0x5ae959]
src/onedrive.d:326 std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x5adfa6]
src/onedrive.d:192 std.json.JSONValue onedrive.OneDriveApi.getPathDetails(const(immutable(char)[])) [0x5ad3c3]
src/sync.d:1282 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x5bcf36]
src/sync.d:1134 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc4ce]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:1125 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x5bc3c5]
src/sync.d:840 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x5bb011]
src/main.d:447 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x59db03]
src/main.d:312 _Dmain [0x59d380]

**Comment by brindleoak** [comment] 2018-10-15 19:30
log file uploaded...

[onedrive.log](https://github.com/abraunegg/onedrive/files/2480240/onedrive.log)

**Comment by abraunegg** [comment] 2018-10-15 19:33
The log file does not show any crash at the end

**Comment by brindleoak** [comment] 2018-10-15 19:40
second attempt. apologies - I'm quite new to this...

[onedrive.log](https://github.com/abraunegg/onedrive/files/2480275/onedrive.log)

**Comment by abraunegg** [comment] 2018-10-15 19:59
OK - you have an issue with this file / path:

```
.%2FCode%2FVisual%20Studio%202008%2FWebSites%2FWCFService1%2FApp_Code%2FIService.cs
```

Which translates to:

```
./Code/Visual Studio 2008/WebSites/WCFService1/App_Code/IService.cs
```

Which does not indicate any weird character.

Will have to diagnose / look at this later - it is potentially a MS Graph issue

**Comment by brindleoak** [comment] 2018-10-15 20:28
You must be right - I added 'Code' to the skip entry in config, and it all seems to be working now.
Thanks so much for your help...

**Comment by abraunegg** [comment] 2018-10-16 19:34
@brindleoak 
The client is failing because of the 'App_Code', which is the same as the issue I raised around 'App_Data' queries failing:

https://github.com/OneDrive/onedrive-api-docs/issues/914

**Comment by abraunegg** [comment] 2018-11-17 21:02
@brindleoak, @arbasel 
A fix is currently being rolled out by Microsoft to resolve this issue. Once confirmed that the fix is available, this can be re-tested and if all OK, closed off.

**Comment by abraunegg** [comment] 2018-12-11 19:34
@brindleoak, @arbasel
The fix for Microsoft Graph has been done which was the blocker here. I have tested with OneDrive Personal and OneDrive Business accounts:

**OneDrive Personal**
```
Loading config ...
Using Config Dir: /home/alex/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709111
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Uploading differences of .
Processing root
The directory has not changed
Processing App_Data
The directory has not changed
Processing 1.txt
The file has not changed
Uploading new items of .
OneDrive Client requested to create remote path: ./App_Code
The requested directory to create was not found on OneDrive - creating remote directory: ./App_Code
Successfully created the remote directory ./App_Code on OneDrive
Uploading file ./App_Code/2.txt ... done.
Remaining free space: 5368709102
OneDrive Client requested to create remote path: ./App_Code/1
The requested directory to create was not found on OneDrive - creating remote directory: ./App_Code/1
Successfully created the remote directory ./App_Code/1 on OneDrive
Uploading file ./App_Code/1/qasdf.asdf ... done.
Remaining free space: 5368709093
Applying changes of Path ID: <redacted>
```
**OneDrive Business**
```
Loading config ...
Using Config Dir: /home/alex/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1099511150131
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Downloading file Document.docx ... done.
Downloading file text.txt ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing text.txt
The file has not changed
Processing Document.docx
The file has not changed
Uploading new items of .
OneDrive Client requested to create remote path: ./App_Data
The requested directory to create was not found on OneDrive - creating remote directory: ./App_Data
Successfully created the remote directory ./App_Data on OneDrive
Uploading file ./App_Data/1.txt ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                                                                                             
 done.
Remaining free space: 1099511150122
OneDrive Client requested to create remote path: ./App_Code
The requested directory to create was not found on OneDrive - creating remote directory: ./App_Code
Successfully created the remote directory ./App_Code on OneDrive
Uploading file ./App_Code/2.txt ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                                                                                             
 done.
Remaining free space: 1099511150113
OneDrive Client requested to create remote path: ./App_Code/1
The requested directory to create was not found on OneDrive - creating remote directory: ./App_Code/1
Successfully created the remote directory ./App_Code/1 on OneDrive
Uploading file ./App_Code/1/qasdf.asdf ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:                                                                                                             
 done.
Remaining free space: 1099511150104
Applying changes of Path ID: <redacted>
```

**Comment by abraunegg** [comment] 2018-12-11 19:35
Closing due to MS Graph implementing fix

**Closed by abraunegg** 2018-12-11 19:35 UTC
Labels: Fixed, OneDrive API Blocker, OneDrive Business, OneDrive Personal
