### ISSUE TITLE
Database is currently locked by another user

### ISSUE THREAD

**Issue by Tasty213** [abraunegg/onedrive#481] opened 2019-04-29 14:57 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When running
```
onedrive --synchronize
```
it will continue fine but randomyl throw the following error
```
core.exception.AssertError@src/itemdb.d(362): Assertion failure
----------------
??:? _d_assertp [0x12b7ff74]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x12b50032]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6afcb]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x12b6b305]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6b10f]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x12b6b305]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6b10f]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x12b6b305]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6b10f]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x12b6b305]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6b10f]
??:? void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x12b6b305]
??:? void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x12b6b10f]
??:? void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x12b6ae29]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x12b5857f]
??:? _Dmain [0x12b57935]
[tasty@tasty-laptop OneDrive]$ onedrive --synchronize
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Processing 58 changes
Processing 15 changes
Processing 12 changes
Processing 12 changes
Processing 15 changes
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
```

**Application and Operating System Details:**
*   OS: Linux tasty-laptop 4.20.17-1-MANJARO #1 SMP PREEMPT Tue Mar 19 18:07:36 UTC 2019 x86_64 GNU/Linux, Manjaro linux KDE on the latest update
*   Wih Gui
*   Onedrive business/enterprise (university provided)
*   DMD64 D Compiler v2.085.0
*   Application configuration: Output of `onedrive --display-config`
```
[tasty@tasty-laptop ~]$ onedrive --display-config
onedrive version                    = 2.3.3
Config path                         = /home/tasty/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/tasty/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
[tasty@tasty-laptop ~]$ curl --version
curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.1 nghttp2/1.36.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Once the full degug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was sucessful in resolving your issue.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash: 
Attempt to sync

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by Tasty213** [comment] 2019-04-29 14:57
the program is now running again but will likely crash ( i normally have to run multiple times anyway)

**Comment by abraunegg** [comment] 2019-04-29 20:18
@Tasty213 
When you are receiving this error:
```
The database is currently locked by another process - cannot sync
```

Please can you identify how many 'onedrive' binaries are actually executing on your system. There should only ever be one copy running (unless you have multiple configurations each with their own confdir set).

The only way this message can be reached is if the database is locked via another process.

As for the assertion failure, your error message shows something going on with the database. I suggest that you:
1. Stop any systemd / init.d service and ensure that you have no 'onedrive' rogue process running
2. Remove your items `items.sqlite3` file from your configuration directory
3. Run a manual sync using `onedrive --synchronize --verbose` so that a log can be captured.

> the program is now running again but will likely crash ( i normally have to run multiple times anyway)
This is *NOT* normal - thus there is something environmental going on

**Comment by Tasty213** [comment] 2019-04-29 21:15
I realised it was because the manual sync was conflicting with a monitor that constantly ran in the background (every 45 seconds) and they both wanted to change things. While this will most likely only be an issue when you do large manual sync would it be possible to add a feature where the background --monitor is paused whilst the manual sync is run?

**Comment by abraunegg** [comment] 2019-04-29 21:24
> I realised it was because the manual sync was conflicting with a monitor that constantly ran in the background (every 45 seconds) and they both wanted to change things. While this will most likely only be an issue when you do large manual sync would it be possible to add a feature where the background --monitor is paused whilst the manual sync is run?

That will not be possible.

What I will look at is if there is a capability to identify if there is another process / PID with the same name running - which will only be valid for the current user - wont be valid for other users using the 'same' configuration files - then prevent the execution of the new process whilst the other is running.

**Comment by abraunegg** [comment] 2019-04-29 21:24
Closing issue, not a bug, not an issue.

**Closed by abraunegg** 2019-04-29 21:24 UTC
Labels: Local Environment Issue, More Information Needed, Not a bug
