### ISSUE TITLE
Enhancement Request: Configure specific File and Folder Permissions

### ISSUE THREAD

**Issue by bradsoto** [abraunegg/onedrive#1100] opened 2020-10-20 05:16 UTC
The default permissions are drwxr-xr-x for directories. This is too permissive for my environment. Could we add a configuration line for file and folder permissions?

**Comment by abraunegg** [comment] 2020-10-20 07:02
@bradsoto 
Can you provide a little more information here around your issue?

The default directory that gets created, inherits the permissions from the parent directory - so .. if the parent directory has this, inheritance will be in play. For example:
```
drwxrwxr-x.   2 alex alex         6 Oct 20 17:58 OneDrive
drwxrwxr-x.   2 alex alex         6 Oct 20 17:59 OneDrive_new
drwxrwxr-x.   5 alex alex        68 Aug  8 07:51 OneDrive_old
```

* Folder `OneDrive` created via the application 
* Folder `OneDrive_new` created via `mkdir OneDrive_new`

The same permissions are used ... this is not something that can easily be changed - as the folder permissions are being inherited.

That the folder permissions are 'too permissive' .. potentially you need to look at your top level folder permissions & security inheritance?

Please provide more information.

**Comment by bradsoto** [comment] 2020-10-20 22:00
You can see the parent dir's permissions, and then once files and folders come in...
```
drwx------    8 brad brad       7 Oct 20 16:27 ..
-rw-r--r--    1 brad brad       0 Oct 13 19:41 Network.txt
drwxr-xr-x    3 brad brad       2 Oct 20 20:46 Processes

**Comment by abraunegg** [comment] 2020-10-21 09:39
@bradsoto 
OK .. thanks ..

So will have to flag this as an enhancement request for the next version, as technically, it is not a bug.

**Comment by abraunegg** [comment] 2020-10-24 02:10
@bradsoto 
Please can you test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/1108/head:pr1108
git checkout pr1108
./configure; make clean; make;
```

This is a work-in-progress (WIP) at present.

When running this PR, your application version (at the moment) should be: `onedrive v2.4.6-11-gad46c47`

The default permissions are set at:
* New Directory: 755
* New File: 644

To change the 'defaults', add the following to a config file in your `~/.config/onedrive/` directory:
```
sync_dir_permissions = "755"
sync_file_permissions = "644"
```

Update the modes as required - '000' -> '777' is valid.

Please can you test and provide feedback. In the testing I have done thus far, new files and folders downloaded from OneDrive are created with the desired permissions.

Existing files / folders are not touched permission wise.

**Comment by abraunegg** [comment] 2020-10-25 21:39
@bradsoto 
The PR has been updated with a couple of tweaks, and default permissions now set to:
* Directories: 700
* Files: 600

If you can provide some feedback that would be greatly appreciated.

**Comment by abraunegg** [comment] 2020-10-26 19:30
@bradsoto 
Any update in testing the PR?

**Comment by bradsoto** [comment] 2020-10-29 20:37
Verified working! Thank you.

**Closed** 2020-10-29 21:00 UTC
Labels: Enhancement, PR Provided - Needs Testing

**Comment by abraunegg** [comment] 2020-10-29 21:33
@bradsoto 
Thanks for the confirmation, PR merged into master
