### ISSUE TITLE
Support for create share link

### ISSUE THREAD

**Issue by eloii23** [abraunegg/onedrive#1219] opened 2021-01-11 10:14 UTC
This is not exactly a Bug, I only want to know if it is possible to get o create a share link from a file uploaded from Business Shared Folders. I tried with --create-share-link but I get ERROR: The requested path to query was not found on OneDrive and also tried --get-file-link but I get File has not been synced with OneDrive. I’m not sure if it is not possible or I need to write the URL in other way.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
CentOS 7
Linux stepsjiraitopre 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?
NO GUI
*   OneDrive Account Type
Business
*   Did you build from source or install from a package?
From source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
Dmd-2.095.0
*   OneDrive Application Version: Output of `onedrive --version`
onedrive v2.4.9-3-g96d3e68
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.9-3-g96d3e68
Config path                            = /home/adminjira/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /app/OneDriveTest/
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = true
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
General
Historificación JIRA LATAM
```
*   Provide the version of curl you are using: Output of `curl --version`
```
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
Local directory
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
XFS
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time
We have a business OneDrive account with some Shared Folders (SharePoint). In this folders we need to upload a lot of files and be able to share every file with it’s responsible.

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  I have this folder structure /app/OneDriveTest (this is the root folder), under that I Have folder General (that is called like the shared folder on OneDrive.
2.  I configured onedrive client to sync shared folder General
3.  When I do a onedrive --synchronize --sync-shared-folders --upload-only --remove-source-files --no-remote-delete, the file is uploaded to the shared folder correctly
4.  But when I do onedrive --synchronize --sync-shared-folders --upload-only --remove-source-files --no-remote-delete --get-file-link "./General/test4.txt", the file is not uploaded and I don’t get it’s link.
5. In other way, when I do onedrive --synchronize --sync-shared-folders --upload-only --remove-source-files --no-remote-delete --create-share-link "./General/test4.txt", it says that the path is not correct, but I tried some ways and I don’t know how I need to insert a shared path.

**Comment by abraunegg** [comment] 2021-01-11 18:53
@eloii23 
Based on your workflow, this is not a bug or issue.

Both `--get-file-link` and `--create-share-link` are separate functions and both rely on the file to be uploaded & present before being used. They cannot be used with `--synchronize` operations.

For you, the correct workflow should be:
1. Upload your data: `onedrive --synchronize --sync-shared-folders --upload-only --remove-source-files --no-remote-delete`
2. Create or get filelink:
    * Create file link: `onedrive --create-share-link './General/test4.txt'`
    * Get file link: `onedrive --get-file-link './General/test4.txt'`

Please can you try this to resolve your issue.

**Comment by eloii23** [comment] 2021-01-12 07:56
Hi @abraunegg ,
Ok I understand that the commands should be executed separetly, but I still have the same problem:
![image](https://user-images.githubusercontent.com/61405335/104285143-755f6f80-54b3-11eb-9ac9-82240c238548.png)

How I have to put the URL of a Business Shared Folder so that it recognize it? In my OneDrive I have a Business Shared Folder called "Historificación de proyectos - Steps JIRA" and the file uploaded is under the folder General so I tried this:

![image](https://user-images.githubusercontent.com/61405335/104285405-dedf7e00-54b3-11eb-8656-66f90671a2e2.png)

But still doesn't working :(

Regards!

**Comment by abraunegg** [comment] 2021-01-12 08:10
@eloii23 
What is the full path, on the local disk, relative to the configured 'sync_dir' ?

**Example:**
* sync_dir = '~/OneDrive'
* Full path to file to sync inc directory = '~/OneDrive/Historificación de proyectos - Steps JIRA/file.txt'
* Command to use: `onedrive --create-share-link 'Historificación de proyectos - Steps JIRA/file.txt'`

Please can you test this.

If this is not working, please provide a full verbose debug log via email:
* `onedrive --create-share-link 'Historificación de proyectos - Steps JIRA/file.txt' --verbose --verbose`

**Comment by eloii23** [comment] 2021-01-12 08:27
Hi @abraunegg ,
thanks for your fast reply! My local structure is like that:
* sync_dir = /app/OneDriveTest"
* Full path to file = /app/OneDriveTest/General/test4.txt
I don't have a folder named "Historificación de proyectos - Steps JIRA" because it is not really a folder on OneDrive, this is a shared library:

![image](https://user-images.githubusercontent.com/61405335/104288143-b8234680-54b7-11eb-84b4-6eb49ba1dfc4.png)

Let me get you some extra info:

![image](https://user-images.githubusercontent.com/61405335/104288222-cf623400-54b7-11eb-9489-5e90f0573404.png)

Y configured this "General" in my Business Shared Folders file and the client recognize it and upload the file correctly but still not working using:

![image](https://user-images.githubusercontent.com/61405335/104288490-2962f980-54b8-11eb-9800-ae6f25fb4cc8.png)

With all that info, let me know if you need a verbose log of a specific command.

Thank you so much!
Regards,
Eloi.

**Comment by abraunegg** [comment] 2021-01-12 19:34
@eloii23 
You can only get / create a file link of the actual path of a file that exists in the location provided. OneDrive does not support the concept of symbolic links.

You cannot create a 'link' to a file in a Sharepoint Library from your OneDrive folder the way you are thinking. The file actually has to *exist* in the target location - thus, in your example, you would have to:
1. Create a new configuration to sync the Sharepoint library 'Historificación de proyectos - Steps JIRA'
2. Upload the file to the Sharepoint library
3. Use `--create-share-link` or `--get-file-link` to get the URL for the file

**Comment by eloii23** [comment] 2021-01-13 08:00
Hi @abraunegg ,
sorry but I don't understand you :( 

Actually, my configuration is synced to the Sharepoint library "Historificación de proyectos - Steps JIRA" because when do a synchronization, the file are uploaded to the Shared library, and I don't have a symbolic link to my OneDrive.

![image](https://user-images.githubusercontent.com/61405335/104422252-cb4c1a00-557c-11eb-884d-e40343a06484.png)

So I undrestand that a symbolic link of General in my OneDrive wouldn't work to create the link (already I tried this xD), but I don't understand the workarround your are proposing.

Can you recreate an example with my folder structure?
![image](https://user-images.githubusercontent.com/61405335/104422804-85438600-557d-11eb-880e-bc7cedbe3cef.png)

Thank you for your patience!
Best regards,
Eloi.

**Comment by abraunegg** [comment] 2021-01-14 20:25
@eloii23 
As your original question / issue has been answered, closing this issue.

If use `--create-share-link` or `--get-file-link` to get the URL for the file that you have uploaded is not working, or you feel there is an issue, please follow the correct support process by opening a new ticket and providing all the details including verbose debug logging.

**Closed by abraunegg** 2021-01-14 20:25 UTC
Labels: Answer Provided, Not a bug, Question

**Comment by eloii23** [comment] 2021-01-15 10:46
Hi @abraunegg,
as i said on the last reply, I didn't understand what I need to do because I think that I'm already doing what you suggested. Can you help me to achieve the feature that I'm trying?

Best regards,
Eloi.
