### ISSUE TITLE
Repeatedly "Giving up on sync after three attempts: Key not found: name"

### ISSUE THREAD

**Issue by leofontenelle** [abraunegg/onedrive#644] opened 2019-09-06 00:21 UTC
For a few months now, onedrive hasn't syncronized anymore: it keeps reinitializing. Originally I meant to paste the relevant entries from journald, but they were superseeded by the output requested in the instructions on how to report a bug. I'm using onedrive 2.3.9 from Arch Linux's AUR non-git package. onedrive is being initialized automatically by systemd, but the system is not headless: it runs GNOME and onedrive cyclically emits notification on initialization. My account is a business one; I'm a professor at a university which uses OneDrive from Microsoft Live, and would like to be able to access it from home.

```bash
$ uname -a

Linux prata 5.2.11-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 29 08:09:36 UTC 2019 x86_64 GNU/Linux

$ dmd --version

DMD64 D Compiler v2.087.1
[...]

$ onedrive --display-config

onedrive version                    = v2.3.9
Config path                         = /home/leonardof/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/leonardof/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false

$ curl --version

curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**To Reproduce**

No special directions, it happens all the time.

```bash
$ onedrive --synchronize --verbose
Using Config Dir: /home/leonardof/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/leonardof/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.9
Account Type: business
Default Drive ID: b!tXySWGMpq0-aQsJR9o8em2kogp8_v49ApU-KjAbs5PuZBzc428YfT7VNC6kVwAOE
Default Root ID: 01ZLALTSV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098613516174
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01ZLALTSV6Y2GOVW7725BZO354PWSELRRZ
Processing 31 changes
Retry sync count: 1: Key not found: name
Syncing changes from OneDrive ...
Applying changes of Path ID: 01ZLALTSV6Y2GOVW7725BZO354PWSELRRZ
Processing 31 changes
Retry sync count: 2: Key not found: name
Syncing changes from OneDrive ...
Applying changes of Path ID: 01ZLALTSV6Y2GOVW7725BZO354PWSELRRZ
Processing 31 changes
Giving up on sync after three attempts: Key not found: name
std.json.JSONException@std/json.d(538): Key not found: name
----------------
??:? pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5615296711a3]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x56152972456d]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x5615296e14d1]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x56152969f24a]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x56152969e625]
??:? void sync.SyncEngine.applyDifferences() [0x56152969d2e0]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x56152968b2a6]
??:? _Dmain [0x56152968a5b9]
```

**Comment by abraunegg** [comment] 2019-09-06 00:22
@leofontenelle 
Please can you follows these directions to generate a debug log:

https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by leofontenelle** [comment] 2019-09-06 00:26
Sorry I didn't mention it, I emailed the debug log in tandem, with the number of the bug report in the subject line.

**Comment by abraunegg** [comment] 2019-09-06 00:31
@leofontenelle 
No problem - received the debug log.

So it appears that this issue is occuring when you have deleted items on OneDrive - can you confirm this?

**Comment by leofontenelle** [comment] 2019-09-06 00:36
It probably started after I deleted files from OneDrive using Windows or the Web interface. It is hard to know for sure, I don't use this computer system on a daily basis. But whatever caused it, the problem simply persisted, I'm not sure I was able to sync once since then.

**Comment by abraunegg** [comment] 2019-09-06 00:38
@leofontenelle 
No problem - I have tracked down the issue, working on a fix at the moment

**Comment by abraunegg** [comment] 2019-09-06 00:48
@leofontenelle 
As I cannot reproduce this - my OneDrive Business test accounts return all the correct API responses / details - your account seems to not do that for deleted items, can you please test the following PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/645/head:pr645
git checkout pr645
make clean; make;
```

**Comment by leofontenelle** [comment] 2019-09-06 00:53
I don't think it worked...

````bash
$ make clean; make
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
````

Isn't some "_configure_ & make" necessary?

After that, do I install it or run locally?

**Comment by abraunegg** [comment] 2019-09-06 00:54
@leofontenelle 
ahh yes - .. bad copy / paste

**Comment by abraunegg** [comment] 2019-09-06 00:56
@leofontenelle 
> After that, do I install it or run locally?

Just run locally first before install to validate that the fix works, or does not work, or if there is still a further issue.

**Comment by leofontenelle** [comment] 2019-09-06 01:05
It worked!!!

I'm staggered. You fixed this bug more quickly than people usually reply to an SMS.

Thank you, for the bug fix and for maintaining the onedrive client for Linux in general!

**Comment by abraunegg** [comment] 2019-09-06 01:06
@leofontenelle 
no problem and thanks for the feedback :)

**Comment by abraunegg** [comment] 2019-09-06 02:31
Closing issue as PR #645 merged into master

**Closed by abraunegg** 2019-09-06 02:31 UTC
Labels: Bug, Fixed, OneDrive API Regression
