### ISSUE TITLE
'AADSTS9002313: Invalid request. Request is malformed or invalid.' when attempting to authorize client

### ISSUE THREAD

**Issue by ziopatrizio** [abraunegg/onedrive#802] opened 2020-02-26 16:02 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

The client was working just fine. Once migrated from Ubuntu 18.04 to elementary os 5.1, re-doing the authorization/authentication one drive client stopped to work. More in details, it hasn't been any longer possible to authorize/authenticate through the office.com website. I've tried to remove rights to the app, to logout from office365, to delete cookies. Nothing worked.

**Application and Operating System Details:**

uname -a result:
```
Linux aleatico 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
running elementary 5.1 with gui, microsoft 365 business account

dmd-2.090.1
```
onedrive version                       = v2.3.13-18-g27d0b96
Config path                            = /home/dazzi/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/dazzi/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
full debug log sent by email
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
Application Log Output:
```
onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "OMITTED",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: <omitted>\r\nCorrelation ID: OMITTED\r\nTimestamp: 2020-02-26 15:41:54Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-02-26 15:41:54Z",
    "trace_id": "OMITTED"
}
----------------
src/onedrive.d:52 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x56082f5d9b58]
src/onedrive.d:560 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x56082f5da1a6]
src/onedrive.d:425 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x56082f5d84c5]
src/onedrive.d:410 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x56082f5d83aa]
src/onedrive.d:208 bool onedrive.OneDriveApi.authorize() [0x56082f5d6ef1]
src/onedrive.d:150 bool onedrive.OneDriveApi.init() [0x56082f5d6998]
src/main.d:431 _Dmain [0x56082f5d2bb1]
```

**Comment by abraunegg** [comment] 2020-02-26 21:37
@ziopatrizio 

Unable to reproduce the crash or error when authenticating against OneDrive Business.

Can you please help test the following PR which should prevent the 'crash' above:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/804/head:pr804
git checkout pr804
./configure; make clean; make;
```

As for why you are getting `AADSTS9002313: Invalid request` when attempting to initialise - unknown at this point in time.

Do you have any HTTPS / URL filtering between you and OneDrive?

**Comment by abraunegg** [comment] 2020-02-27 00:27
@ziopatrizio 

In regards to the `AADSTS9002313: Invalid request` error you are receiving, best refer to the following: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes

> InvalidRequest - Request is malformed or invalid. - The issue here is because there was something wrong with the request to a certain endpoint. The suggestion to this issue is to get a fiddler trace of the error occurring and looking to see if the request is actually properly formatted or not.

If after using the PR version above and you are still getting this error, please follow the directions for generating a HTTPS debug log (https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support) which will show what is being sent & received between the client and OneDrive.

**Comment by ziopatrizio** [comment] 2020-02-27 09:40
Thank you for your support.
Unfortunately, the problem is still there.
Please find attached the debug log. For privacy, I omitted the authorization string.

Bests

[debug_output.log](https://github.com/abraunegg/onedrive/files/4260763/debug_output.log)

**Comment by ziopatrizio** [comment] 2020-02-27 09:42
One more detail: Despite the error received, inside the list of the authorized apps on Office365, I can see OneDrive Free Client. However, when I run onedrive it asks me again to authorize the client. Is there a way to avoid this step, given the fact that it has been already authorized ?

**Comment by CodeOhms** [comment] 2020-02-27 12:27
I am also having this issue. However, the steps to reproduce are different in my case.
Previously, I have installed the AUR version on another PC. I have no problems with that particular installation. Today I attempted to replicate the installation , using AUR, on my laptop and received a similar error as above. The error is as follows:

onedrive.OneDriveException@src/onedrive.d(874): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "****",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: ****\r\nCorrelation ID: ****\r\nTimestamp: 2020-02-27 12:18:21Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-02-27 12:18:21Z",
    "trace_id": "****"
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5561547c4df8]
??:? std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5561547c5446]
??:? void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x5561547c3765]
??:? void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5561547c364a]
??:? bool onedrive.OneDriveApi.authorize() [0x5561547c2191]
??:? bool onedrive.OneDriveApi.init() [0x5561547c1c38]
??:? _Dmain [0x5561547bde9b]

**Comment by CodeOhms** [comment] 2020-02-27 12:39
[Here is the debug log](https://pastebin.com/W7Uj1CKK)

**Comment by abraunegg** [comment] 2020-02-27 19:27
> One more detail: Despite the error received, inside the list of the authorized apps on Office365, I can see OneDrive Free Client. However, when I run onedrive it asks me again to authorize the client. Is there a way to avoid this step, given the fact that it has been already authorized ?

No - as this is what is required each and every time when obtaining the authentication key.

As this issue is most likely an Microsoft Azure issue, please try the following:

* Close all browsers and all running instances of OneDrive - Windows clients / Linux etc
* Clear browser cache
* Change your OneDrive password
* Re-authenticate the Linux client

If this still does not solve the `AADSTS9002313` you need to open a case with Microsoft support and provide them with the HTTPS Debug Log as this provides the details needed.

This application does not change or do anything with the Azure authentication response it receives when you authenticate the client - so if MS Azure is unable to interpret the response, then this has to be investigated by Microsoft. As you have an Office 365 account - you have Business Support, so please investigate that avenue.

**Comment by abraunegg** [comment] 2020-02-27 19:32
@ziopatrizio , @CodeOhms 

In terms of the crash however, please can you retest with the updated PR as this crash has to be fixed regardless - please can you test that and report back.

**Comment by petersaints** [comment] 2020-02-27 20:15
I'm running the latest master version with the #804 pull request and I still get a crash.

I think that I'm facing the same problem that has been reported here.

If I run OneDrive onto a custom config directory for my Office 365/OneDrive Business account (I'm using the default one for a private account), I get an URL that I paste into the browser, I login to authorize the access to my account (I even tried from a different browser with the cache and sessions completely cleaned just to be sure) and once I copy the resulting URL that led me to a blank page I get an error that is similar to the ones posted above.

I should also notice that for my personal Microsoft/Outlook.com account the returned URL has a much shorter authorization code. 

Here is the result that I get on my terminal:
```
onedrive --confdir=~/.config/onedrive-ips
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<750_CHARACTERS_LONG_STRING_OMITTED_DUE_TO_PRIVACY_CONCERNS&session_state=<36_CHARACTERS_LONG_STRING_OMITTED_DUE_TO_PRIVACY_CONCERNS>
onedrive.OneDriveException@src/onedrive.d(888): HTTP request returned status code 400 (Bad Request)
{
    "correlation_id": "e1260ff9-2e9a-4720-b95b-da132cdbb43d",
    "error": "invalid_grant",
    "error_codes": [
        9002313
    ],
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 71ffe653-6d79-48e6-93b3-40e5e62d3600\r\nCorrelation ID: e1260ff9-2e9a-4720-b95b-da132cdbb43d\r\nTimestamp: 2020-02-27 19:59:57Z",
    "error_uri": "https:\/\/login.microsoftonline.com\/error?code=9002313",
    "timestamp": "2020-02-27 19:59:57Z",
    "trace_id": "71ffe653-6d79-48e6-93b3-40e5e62d3600"
}
----------------
src/onedrive.d:52 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5597ebaf43cc]
src/onedrive.d:574 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x5597ebaf4a1a]
src/onedrive.d:439 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x5597ebaf2d39]
src/onedrive.d:424 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x5597ebaf2c1e]
src/onedrive.d:222 bool onedrive.OneDriveApi.authorize() [0x5597ebaf1763]
src/onedrive.d:150 bool onedrive.OneDriveApi.init() [0x5597ebaf10f4]
src/main.d:431 _Dmain [0x5597ebaed30d]
```

And here it is the full debug log:
[debug.log](https://github.com/abraunegg/onedrive/files/4263891/debug.log)

**Comment by abraunegg** [comment] 2020-02-27 20:22
@petersaints 

Please can you confirm you are running this version:
```
onedrive v2.3.13-20-g81a1384
```

This should have the crash fixed - please confirm

**Comment by petersaints** [comment] 2020-02-27 20:24
@abraunegg 
Yes, I am!
`onedrive --version` says:
`onedrive v2.3.13-20-g81a1384`

**Comment by abraunegg** [comment] 2020-02-27 20:25
OK ... thanks .. so the test for catching the crash is - for whatever reason - not detecting & picking that up .. weird.

**Comment by abraunegg** [comment] 2020-02-27 20:54
@petersaints 
Please can you update your client to 'onedrive v2.3.13-21-g6aa13ad' - see if that now captures the crash correctly ...

**Comment by abraunegg** [comment] 2020-02-27 21:04
Submitted API query here: https://github.com/OneDrive/onedrive-api-docs/issues/1229

**Comment by petersaints** [comment] 2020-02-28 18:20
> @petersaints
> Please can you update your client to `onedrive v2.3.13-21-g6aa13ad` - see if that now captures the crash correctly ...

The crash is now captured correctly:
```
onedrive --confdir=~/.config/onedrive-ips --synchronize
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=Files.ReadWrite%20Files.ReadWrite.all%20Sites.ReadWrite.All%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<OMITTED>&session_state=<OMITTED>
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)

ERROR: OneDrive returned a 'HTTP 401 Unauthorized' - Cannot Initialize Sync Engine
ERROR: Check your configuration as your access token may be empty or invalid
```
However, the authorization problem still persits. There must have been some change to the OneDrive API that is causing this issue. Here it is a full debug log:
[debug.log](https://github.com/abraunegg/onedrive/files/4268443/debug.log)

**Comment by abraunegg** [comment] 2020-02-28 20:17
@petersaints 
Whilst this is not going to the issue, can you please update your client to `onedrive v2.3.13-22-gc4b4351` as this will provide some extra debugging output so that the details as to why the 400 error is occurring.

The other thing to also try is this:

* Revoke this applications access - https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online#revoking-access

By revoking access, then when you re-auth the client to access your account

**Comment by CodeOhms** [comment] 2020-02-29 12:25
Okay, for some reason I am now able to authorise a second client without updating. I am using version 2.3.13. I have no idea why.

**Comment by abraunegg** [comment] 2020-02-29 18:55
> Okay, for some reason I am now able to authorise a second client without updating. I am using version 2.3.13. I have no idea why.

This is because this issue is not a problem with the client - but with Microsoft and the back end API. They must have made a tweak somewhere and something broke.

As per the original advice, it is best to raise a case with Microsoft to get this fixed.

If you have 1 client working, 1 still not working - assistance in cleaning up the PR so that is presents the reason for failure is greatly appreciated as I cannot replicate this.

**Comment by abraunegg** [comment] 2020-03-02 01:56
Marking this bug fixed, as the bug (application crash) is fixed, however the cause - `AADSTS9002313: Invalid request...` is unable to be fixed as this is a OneDrive API issue.

Need confirmation from users who have experienced this issue that the 'crash' is fixed, and hopefully the API issue has been resolved by Microsoft.

**Comment by abraunegg** [comment] 2020-03-02 01:57
PR #804 merged into master

**Comment by ziopatrizio** [comment] 2020-03-02 07:30
Things are working correctly now! Thanks.
The only issue I am facing now (not before) is that the synchronization does not terminate in one shot. I already issues it several times and after a certain number of file downloaded it raises an error: OneDrive returned a 'HTTP 429 - Too Many Requests' - gracefully handling error

**Comment by abraunegg** [comment] 2020-03-02 07:41
@ziopatrizio 

> Things are working correctly now! Thanks.

Great - thanks for the feedback.

> The only issue I am facing now (not before) is that the synchronization does not terminate in one shot. 

Unsure what you mean here by this.

> I already issues it several times and after a certain number of file downloaded it raises an error: OneDrive returned a 'HTTP 429 - Too Many Requests' - gracefully handling error

This is normal - it means that your OneDrive service is advising too many requests and you need to delay access.

If you think there is an issue going on, please open a new case and provide a HTTPS debug log.

**Comment by abraunegg** [comment] 2020-03-02 08:00
Closing issue as issue (crash) resolved

**Closed by abraunegg** 2020-03-02 08:00 UTC
Labels: Bug, Fixed, OneDrive API Regression, OneDrive Office365, Unable to reproduce
