### ISSUE TITLE
Unwanted automatic deletion of all files in Onedrive server due to error in configuration.

### ISSUE THREAD

**Issue by NoeBarthelemy** [abraunegg/onedrive#675] opened 2019-09-30 18:23 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**

Briefly, I configured my config file like this: 
```
# sync_dir = "/home/nonopov/Bureau/PHD"
# skip_file = "~*|.~*|*.tmp"
# upload_only = "true"
```
Everything else being as by default. I followed the instructions and performed a full --resync after changing the config file. 
Despite my config file being detected, the changes are not applied and my "onedrive --display-config" gives:

```
onedrive version                    = v2.3.9-12-g72467e3
Config path                         = /home/nonopov/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/nonopov/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

Although a "onedrive --synchronize --syncdir /home/nonopov/Directory_to_sync/ --upload-only" works like a charm, the issue mentioned above causes regularly all my files to be deleted from Onedrive. 

Could you tell me why, please, and how to fix it? 
Your help is very much appreciated ! 

Noé

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)

Linux nonopov-CX70-2PF 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
OneDrive for Business

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

DMD64 D Compiler v2.088.0
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

*   Application configuration: Output of `onedrive --display-config`

```
onedrive version                    = v2.3.9-12-g72467e3
Config path                         = /home/nonopov/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/nonopov/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.65.2 (x86_64-conda_cos6-linux-gnu) libcurl/7.65.2 OpenSSL/1.1.1c zlib/1.2.11 libssh2/1.8.2
Release-Date: 2019-07-17
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2019-09-30 19:21
@NoeBarthelemy 

> Briefly, I configured my config file like this:
> 
> ```
> # sync_dir = "/home/nonopov/Bureau/PHD"
> # skip_file = "~*|.~*|*.tmp"
> # upload_only = "true"
> ```
> 
> Everything else being as by default. I followed the instructions and performed a full --resync after changing the config file.
> Despite my config file being detected, the changes are not applied and my "onedrive --display-config" gives:

The issue lies here with your config file ... simply based on the above, you have left the preceding `#` on the configuration lines. This is why:

* Config is detected, but updated configuration is not applied
* Use of what is a 'invalid' config when compared to your CLI command causes your data to be deleted

The easiest fix here is to:

* Uncomment the config lines where you have modified from the default setting.
* Once uncommented, run `onedrive --display-config` to ensure the change has been made

**Comment by abraunegg** [comment] 2019-09-30 19:30
Duplicate of Issue #657

**Comment by abraunegg** [comment] 2019-09-30 21:03
Closing issue as question answered. Please re-open / comment if this does not solve your issue. PR #676 updates the 'config' file and 'usage.md' to be more explicit & clear in the examples of the configuration required to enable option changes such as changing the 'sync_dir' via config file.

**Closed by abraunegg** 2019-09-30 21:03 UTC
Labels: Answer Provided, Documentation, Duplicate, Question

**Comment by NoeBarthelemy** [comment] 2019-10-01 10:09
Hello !

I am so embarrassed, my eyes didn't even realise those # were here ...
Thank you very much anyway!

And by the way, thank you also for all your work on Onedrive for linux users, it's great! 🙂

Noé

________________________________
De : abraunegg <notifications@github.com>
Envoyé : lundi 30 septembre 2019 21:21
À : abraunegg/onedrive <onedrive@noreply.github.com>
Cc : NoeBarthelemy <noe.barthelemy@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [abraunegg/onedrive] Unwanted automatic deletion of all files in Onedrive server due to error in configuration. (#675)


@NoeBarthelemy<https://github.com/NoeBarthelemy>

Briefly, I configured my config file like this:

# sync_dir = "/home/nonopov/Bureau/PHD"
# skip_file = "~*|.~*|*.tmp"
# upload_only = "true"


Everything else being as by default. I followed the instructions and performed a full --resync after changing the config file.
Despite my config file being detected, the changes are not applied and my "onedrive --display-config" gives:

The issue lies here with your config file ... simply based on the above, you have left the preceding # on the configuration lines. This is why:

  *   Config is detected, but updated configuration is not applied
  *   Use of what is a 'invalid' config when compared to your CLI command causes your data to be deleted

The easiest fix here is to:

  *   Uncomment the config lines where you have modified from the default setting.
  *   Once uncommented, run onedrive --display-config to ensure the change has been made
