### ISSUE TITLE
office365 parent folder vs subfolders

### ISSUE THREAD

**Issue by naftahorn** [abraunegg/onedrive#823] opened 2020-03-14 16:38 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
Followed Office365.md instruction.  Straight forward.  I retrieved 15 drive_id replies after running:
onedrive --get-O365-drive-id '<your library name>'
I expected this!  This corresponds to the 15 sub-folders with my office365 shared library.

I am attempting to sync only 3 of the 15 drive_ids.  Therefore i entered those 3 drive_id's into the config file as per the instructions.  All good so far.

Started the onedrive --synchronize --verbose 
during the sync i noticed that the sync did not create the folder names that corresponds to the drive_ids.  Instead the onedrive sync places all the drive_id sub-folders directly into my sync_dir.  This is NOT what I was expecting.

I was expecting that each of the 3 drive_id's that i configured, onedrive sync would create each drive_id's foldername, and all of the sub-folders and files for the drive_id would then show up under that "parent" foldername!

I am not sure if "sync_root_files" needs to be true to create that parent foldername?  Couldn't find a descriptot for that flag.

Not sure if this is a bug.  But wanted to mention ... perhaps a feature request?

**Application and Operating System Details:**
*   OS: Linuxmint 19.3 hostname 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?  No
*   OneDrive Account Type:  Office 365 documentLibrary
*   DMD or LDC compiler version:  DMD64 D Compiler v2.090.0
*   Application configuration: Output of `onedrive --display-config`
```
v2.3.13-22-g63ce6a7
Config path                            = /home/xxxx/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/xxxx/office365
Config option 'skip_dir'               = .*|Music|Movies/FullHD
Config option 'skip_file'              = ~*|.~*|*.tmp|thumbs.db|*.iso
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'drive_id'               = abcdefghi...not-real-drive-id
Config option 'sync_root_files'        = false
Selective sync configured              = false
```
*   Curl Version: curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

NOTE I'M ONLY SHOWING 1 of the 3 drive_id that i mentioned above, as i removed 2 from the config file when i noticed that i was missing the parent folder.

*Log Output*
```
xxxx@XX ~ $ onedrive --synchronize --verbose  --resync
Using Config Dir: /home/xxxx/.config/onedrive
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/xxxx/office365
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
ERROR: Flagging to disable upload space checks - this MAY have undesirable results if a file cannot be uploaded due to out of space.
Application version: v2.3.13-22-g63ce6a7
Account Type: documentLibrary
Default Drive ID: abcdefghi...not-real-drive-id
Default Root ID: zyxwvuts...not-real-root-ID
Remaining Free Space: 0
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: zyxwvuts...not-real-root-ID
Processing 203 changes
...
```

**Comment by abraunegg** [comment] 2020-03-14 19:56
@naftahorn 
Please can you provide via email:
1. Screen shot of your OneDrive / Office365 from a Web Browser showing the shared library / folders
2. Full debug output of your `onedrive --get-O365-drive-id` command by adding `--verbose --verbose` to it
3. Generate a full debug log for a 'clean' sync (ie no local data) that shows the full creation activities you are describing above. To generate the full debug log refer to: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

I can already see 'one' enhancement here - not related to this issue - but when using `onedrive --display-config` and 'drive_id' is configured, there should be a display showing that this is configured.

**Comment by naftahorn** [comment] 2020-03-15 06:43
Ok ... feeling silly ... can't quite figure how to send you a direct message / email .... so just answering here, but have to redact the pic.  As for the full results of bullet 2 ... ok here you go:
`xxxx@HOSTNAME ~ $ onedrive --verbose --get-O365-drive-id 'MyOffice365SharedLibrary'
Using Config Dir: /home/xxxx/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/xxxx/Work/transurban-sharepoint
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
ERROR: Flagging to disable upload space checks - this MAY have undesirable results if a file cannot be uploaded due to out of space.
Application version: v2.3.13-22-g63ce6a7
Account Type: documentLibrary
Default Drive ID: abcdefghi...not-real-drive-id
Default Root ID: zyxwvuts...not-real-root-ID
Remaining Free Space: 0
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Office 365 Library Name Query: MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_1
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_2
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_3
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_4
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_5
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_6
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_7
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_8
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_9
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_10
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_11
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_12
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_13
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_14
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
SiteName: MyOffice365SharedLibrary
drive_id: abcdefghi...not-real-drive-id_15
URL:      https://myoffice365.sharepoint.com/sites/MyOffice365SharedLibrary
`
I'll add that debug_log file you requested shortly .. but i have to redact bits of it as well.

**Comment by abraunegg** [comment] 2020-03-15 06:45
@naftahorn 
For support, refer to https://github.com/abraunegg/onedrive#reporting-issues & the Wiki - email address is listed there.

**Comment by abraunegg** [comment] 2020-03-15 23:21
@naftahorn 
I have responded to your email, please can you read and provide the details requested.

**Comment by abraunegg** [comment] 2020-03-17 07:53
@naftahorn 
Please can you provide the required information so that I can assist in helping you with this issue

**Comment by naftahorn** [comment] 2020-03-18 00:18
Hi Alex,
No longer an issue.  Sometimes I forget the power behind linux and i have onedrive sync doing what is needed.  Thanks for the followup.

    On Tuesday, 17 March 2020, 17:54:05 GMT+10, abraunegg <notifications@github.com> wrote:  
 
 


@naftahorn
Please can you provide the required information so that I can assist in helping you with this issue

**Comment by abraunegg** [comment] 2020-03-18 19:05
Closing issue as not a bug, local environment configuration

**Closed by abraunegg** 2020-03-18 19:05 UTC
Labels: Local Environment Issue, Not a bug
