### ISSUE TITLE
Skipping Item - Invalid Name (Microsoft Name Convention)

### ISSUE THREAD

**Issue by ilpiccoli** [abraunegg/onedrive#1318] opened 2021-03-05 13:55 UTC
Many files in my OneDrive folder (almost all) are not synced, showing the error "Skipping Item - Invalid Name (Microsoft Name Convention)", while everything is ok (and works on my Windows PC sync on OneDrive).
Here it is the screenshot attached.
![2021-03-05](https://user-images.githubusercontent.com/68585608/110124798-d5430a00-7dc2-11eb-8c96-fe10b3f72db9.png)

**Comment by abraunegg** [comment] 2021-03-05 18:10
@ilpiccoli 
Unfortunately this is not a bug or issue. The application checks if an item conforms to Microsoft Naming Conventions, thus this message is 100% correct. 

Refer to:
* https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#invalidcharacters
* https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#invalidfilefoldernames 

Closing issue for the following reasons:
* Not a bug
* Should have been opened as a discussion
* Not using bug report template

**Closed by abraunegg** 2021-03-05 18:10 UTC
