### ISSUE TITLE
Renamed files do not have any file validation tests

### ISSUE THREAD

**Issue by NZKea** [abraunegg/onedrive#922] opened 2020-05-20 02:47 UTC
Using the docker version get:

/bin/bash: /entrypoint.sh: Permission denied

This is after has been running for a few days, named a file with question mark ever since has never worked. Tried uninstalling and reinstall but get stuck at the same error. How do I give it the permission it needs?

Also tried to docker build but got 
/usr/bin/python: can't open file '/usr/bin/yum': [Errno 13] Permission denied

On ubuntu.

Not following the bug template as I hope this is an easy issue that can be fixed with one command, but can do if prefered.

Thanks!

**Comment by abraunegg** [comment] 2020-05-20 02:51
@NZKea 
Please can you provide:
* Exact Ubuntu version
* Every command & in the correct sequence, that you are using to run & build the Docker image.

**Comment by NZKea** [comment] 2020-05-20 03:05
sudo docker pull driveone/onedrive
sudo docker volume create onedrive_conf
onedriveDir="/home/nathan/Documents" 
sudo docker run -it --restart unless-stopped --name onedrive -v onedrive_conf:/onedrive/conf -v "${onedriveDir}:/onedrive/data" driveone/onedrive

Then that returns, /bin/bash: /entrypoint.sh: Permission denied

I also tried the build instructions https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md and got that alternative error.

Ubuntu 20.04 LTS

Thanks!

**Comment by abraunegg** [comment] 2020-05-20 03:38
@NZKea 
Whilst I setup a Ubuntu 20.x system - one item that stands out is why are you using 'sudo' here. This is contrary to the instructions provided here: https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md

**Comment by NZKea** [comment] 2020-05-20 04:08
Okay, so the sudo problem made me realise that I had missed some the docker post-install steps. So I decided to reinstall docker completely. Now it works again!

However, I do not know if that was the problem or something else was fixed on reinstall. The weird part is that it worked fine for 2 days. The naming a file with a question mark could have been the trigger or that may have been a fluke.

Anyway only had Linux for a few days and learning by failure, thanks for the help! Assumed you just had to use sudo for some commands.

**Comment by abraunegg** [comment] 2020-05-20 04:33
@NZKea 
> Okay, so the sudo problem made me realise that I had missed some the docker post-install steps. So I decided to reinstall docker completely. Now it works again!
> 
> However, I do not know if that was the problem or something else was fixed on reinstall. The weird part is that it worked fine for 2 days. The naming a file with a question mark could have been the trigger or that may have been a fluke.
> 
> Anyway only had Linux for a few days and learning by failure, thanks for the help! Assumed you just had to use sudo for some commands.

Glad you have this working again.

What file & where was given a '?' in the filename ?

**Comment by NZKea** [comment] 2020-05-20 06:17
It was a markdown file with a question mark at the end. I made the file, worked on it, and moved to another device where I noticed it was absent. Checked the onedrive log and it had that initial error. 

However, I am unable to reproduce the error with this proper install of docker. Either it produces the error seen below if the question mark is directly after the name or if there is a space before the question mark it says "the resulting response is not a valid JSON object". I can only assume that it was just coincidental timing or a problem that only occurs when docker is not properly installed.

Rather my next problem is the error that just appeared when tried to check logs again  "Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39".

I guess I may need to downgrade docker somehow, but can't do that at the moment.

Thanks! 

![Screenshot from 2020-05-20 17-22-10](https://user-images.githubusercontent.com/20099289/82408143-0e71ee00-9abf-11ea-87da-94b536ea3d4f.png)

**Comment by abraunegg** [comment] 2020-05-20 08:01
@NZKea 

> However, I am unable to reproduce the error with this proper install of docker. Either it produces the error seen below if the question mark is directly after the name or if there is a space before the question mark it says "the resulting response is not a valid JSON object". I can only assume that it was just coincidental timing or a problem that only occurs when docker is not properly installed.

OK - the MS Naming Convention error is 100% normal - not a bug or issue. The 'JSON object' response is not normal. 

Can you profile an exact filename that generates this error - as this needs to be fixed.

**Comment by abraunegg** [comment] 2020-05-21 20:19
@NZKea 
In trying to test file names with '?' in them I am unable to reproduce:
```
The file has not changed
Processing file_tests
The directory has not changed
Uploading new items of .
Skipping item - invalid name (Microsoft Naming Convention): ./file_tests/this is a file with?.md
Skipping item - invalid name (Microsoft Naming Convention): ./file_tests/this is another file ? .md
Skipping item - invalid name (Microsoft Naming Convention): ./file_tests/yet another file ?.md
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

In each instance - file with a '?' and regardless of whether a space character is before or after the '?' the file is correctly handled.

If you are still seeing this error:
```
the resulting response is not a valid JSON object
```

Please provide a verbose debug log for analysis.

**Comment by NZKea** [comment] 2020-05-22 03:54
Still haven't had time to fix the "Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39", so can't check this again.

But here is the screenshot from the other day. I am pretty sure all I did was rename the file with a space before the end.

![rsz_screenshot_from_2020-05-20_17-33-52](https://user-images.githubusercontent.com/20099289/82629497-01cad280-9c44-11ea-9974-f30ac094405a.png)

Thanks

Random extra note the file may have been open by this markdown editor, which allows linking between files. But can't guarantee it. https://obsidian.md/

**Comment by abraunegg** [comment] 2020-05-22 20:49
@NZKea 
OK that image gives me an avenue to explore to replicate - thanks

**Comment by abraunegg** [comment] 2020-05-22 22:54
@NZKea 
The issue of 'renaming files' & causing a JSON error is resolved in the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/929/head:pr929
git checkout pr929
./configure; make clean; make;
```

As you are running this via Docker, you will need to build a specific Docker instance using this PR version to ensure that you are testing this fix.

**Comment by abraunegg** [comment] 2020-05-24 07:40
@NZKea 
Any opportunity to test this PR yet ?

**Comment by abraunegg** [comment] 2020-05-25 00:52
Issue closed as PR merged into 'master'

**Closed** 2020-05-25 00:51 UTC
Labels: Bug, Docker Issue, PR Provided - Needs Testing

**Comment by NZKea** [comment] 2020-05-25 09:58
@abraunegg  Sorry for not getting back have been crazy busy, thanks for the fix!
