### ISSUE TITLE
Sync "Shared with me" OneDrive for Business folders to our local computer

### ISSUE THREAD

**Issue by kurokirasama** [abraunegg/onedrive#193] opened 2018-10-10 18:19 UTC
In OneDrive website there is an option to sync "shared with me" folders to the local computer, but it only works on windows... is there a possibility that you could workaround this feature?...

**Comment by abraunegg** [comment] 2018-10-10 20:03
Duplicate of #5 and PR #104

**Closed by abraunegg** 2018-10-10 20:03 UTC
Labels: Duplicate, Feature Request, Future Work - Planning Required
