### ISSUE TITLE
Bug: Continual configuration error notifications

### ISSUE THREAD

**Issue by Caseyb87** [abraunegg/onedrive#1897] opened 2022-03-22 09:31 UTC
### Describe the bug

The Onedrive app has had its authentication revoked. I was trying it out yesterday and removed permissions in my Microsoft account for a whole bunch of programs (including this). I was intending to re-authenticate today.

This (as to be expected) caused an error notification this morning: `ERROR: Check your configuration as your refresh_token may be empty or invalid. [...]`

However, this notification is appearing every few seconds ~~(presumably based on monitor_interval?)~~. I am literally being spammed with error notifications - I now have hundreds of notifications in my tray. This only occurred today (after a reboot) not yesterday when the app was installed and authentication revoked,

**Expected behaviour:** The app should issue one notification and then handle subsequent failures quietly (i.e. no notification). Perhaps also consider giving up after X numbers of attempts with the same failure.

### Operating System Details

```shell
Linux toshiba-laptop 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.16-1~np1

### What is your OneDrive Application Configuration

```shell
onedrive version                       = v2.4.16-1~np1
Config path                            = /home/usr/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/usr/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

### What is your 'curl' version

```shell
curl 7.78.0 (x86_64-conda-linux-gnu) libcurl/7.78.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2021-07-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=6043588k,nr_inodes=1510897,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1218184k,mode=755)
/dev/sda2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1218180k,mode=700,uid=1000,gid=1000)
/home/.ecryptfs/usr/.Private on /home/usr type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=7f05f2a662c54b81,ecryptfs_sig=2967d2e8dab3b611,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda                                                                   
├─sda1
│    vfat         944A-97F8                             505.8M     1% /boot/efi
└─sda2
     ext4         fa56678f-a4fb-4284-b127-20242cf1faf9  389.8G     6% /
```

### How do you use 'onedrive'

Only installed yesterday - hasn't synced to this machine yet (just performed a dry run). 
Revoked authentication to account yesterday (intending to re-authenticate today).
Personal OneDrive
Is accessed across different machines (mostly Windows)

### Steps to reproduce the behaviour

Installed (via [instructions](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md))
Authenticate
Perform dry run (optional?)
Revoke authentication via Microsoft account online
Reboot

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /home/usr/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/usr/OneDrive

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 400 (Bad Request)
  Error Reason:     AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 35415478-cd01-4b29-9c70-45f711fa4501
Correlation ID: ab73ce8c-1690-4048-8056-25a373697b42
Timestamp: 2022-03-22 09:23:08Z
  Calling Function: acquireToken()


ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    HTTP request returned status code 401 (Unauthorized)
  Error Reason:     Access token is empty.
  Error Timestamp:  2022-03-22T09:23:08
  API Request ID:   8fa842d5-20f6-4004-a5b1-de093e67f40b
  Calling Function: init()


ERROR: Check your configuration as your refresh_token may be empty or invalid. You may need to issue a --reauth and re-authorise this client.

Segmentation fault (core dumped)
```

**Comment by abraunegg** [comment] 2022-03-22 18:42
@Caseyb87 
Unfortunately this is potentially not a bug or issue following reasons:

* You are using a Ubuntu based distribution
* You have installed from the OpenSuSE BUild Service packages
* You are being impacted by the known issues with those packages

**Options to resolve:**
* Do not use a Ubuntu based distribution as this is a significant contributor to your 2 issues
   * There are much better alternatives out there
* Re-read the known issues with using packages for Ubuntu platforms and take the appropriate corrective actions
  * Remove the offending symbolic link as required which will fix your *main* issue, but not your second issue of the core dump when the client exits
* Do not install the client from a package - build and compile from source
  * This will avoid the 2 issues you are having. The main one is the ongoing notifications - this is because the way that Ubuntu packages, it implements an additional systemd service file which is what has started which is the cause of your issue. See: #1274 for details
  * The second issue is the `Segmentation fault (core dumped)` - again - this is due to Ubuntu and the compiler options in their packages. This is flagged here: https://bugs.launchpad.net/ubuntu/+source/ldc/+bug/1895969

Additionally all of this is also clearly detailed here: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#known-issues-with-installing-from-the-above-packages and step 5 of the process when installing the client from those packages is to read and understand these known issues.


Can you please advise if you have already followed the directions regarding the known issues with installing the client from the OpenSuSE Build Service packages.

**Comment by abraunegg** [comment] 2022-03-23 18:27
@Caseyb87 
No problem - closing this issue

**Closed by abraunegg** 2022-03-23 18:27 UTC
Labels: Bug, More Information Needed, Waiting on Response
