### ISSUE TITLE
HTTP request returned status code 413 (Request Entity Too Large), And Caused Application to Crash

### ISSUE THREAD

**Issue by theeggdev** [abraunegg/onedrive#593] opened 2019-07-16 07:28 UTC
Sorry that I come back with another issue...

**Note:** I am running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. 

### Bug Report Details ###
**Describe the bug**
This is not my first time to encounter the error 413. Previously because files were deleted and re-created (as described in  #585), once the error appeared, the error would be avoid in the later retry attempt because a new file created instead. 

After the fixes in #585, as the modified files are uploaded directly now (without being deleted and re-created), the error 413 can no longer be avoided. And it also makes the application crash.

My the file concerned is a .xlsx file of 6,900,277 bytes. 

```
Jul 16 14:43:44 egghkdev onedrive[26154]: Uploading modified file ./project management/A/automated reports/budget/Budget Tracker.xlsx ...Retry sync count: 2: HTTP request returned status code 413 (Request Entity Too Large)
Jul 16 14:43:44 egghkdev onedrive[26154]: {
Jul 16 14:43:44 egghkdev onedrive[26154]:     "error": {
Jul 16 14:43:44 egghkdev onedrive[26154]:         "code": "BadRequest",
Jul 16 14:43:44 egghkdev onedrive[26154]:         "innerError": {
Jul 16 14:43:44 egghkdev onedrive[26154]:             "date": "2019-07-16T06:43:44",
Jul 16 14:43:44 egghkdev onedrive[26154]:             "request-id": "71f5bf8e-285d-4cef-9251-eb8df6ddb450"
Jul 16 14:43:44 egghkdev onedrive[26154]:         },
Jul 16 14:43:44 egghkdev onedrive[26154]:         "message": "Maximum request length exceeded."
Jul 16 14:43:44 egghkdev onedrive[26154]:     }
Jul 16 14:43:44 egghkdev onedrive[26154]: }

```

Although the fixes in #585 "caused" the issue, the fixes there is correctly done and the issue of HTTP error 413 should be deal separately instead. That's why I start a new issue.
For now I will pull from the commit 66764f2 . 

**Application and Operating System Details:**
*   OS: **(Output of `uname -a`)** `Linux Admin 4.15.0-54-generic #/58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` ; **(provide your OS & version)**  `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)`
*   Are you using a headless system (no gui) or with a gui installed? headless system
*   OneDrive Account Type: Sharepoint group drive in Office 365 business
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`: DMD64 D Compiler v2.087.0
*   Application configuration: 
```
onedrive version                    = v2.3.7-17-gb23390c
Config path                         = /home/work/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/work/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = (hidden)
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: 
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  create a >7 MB .xlsx file in OneDrive
2.  modify that file 
3.  let it sync
4.  receive error 413
5.  application crash and restart automatically, crash and restart, ... etc

**Complete Verbose Log Output**

Application Log Output:
```
will send the log output privately if needed
```

### Bug Report Checklist ###
*   [done] Detailed description
*   [done] Reproduction steps (if applicable)
*   [done] Verbose Log Output

Thank you and please let me know if I have missed out anything in this issue report

**Comment by abraunegg** [comment] 2019-07-16 07:34
@theeggdev 
I should be able to reproduce this, however this is all due to the following:
* Files larger than 4Mb need to use session upload (otherwise OneDrive complains)
* When you use session upload, to replace an existing file, on a Sharepoint site, it generates a 404 error post upload completion (why ... no idea - but I suspect this is due to the file is now being 'enriched', thus technically it (what we uploaded) does not exist thus 404 ..)

So we are back to the same scenario - how to handle this?

Option:
1. If file size is < 4Mb, use uploadReplace method
2. If file size is > 4Mb, delete & use session upload

There is no way around the OneDrive Sharepoint stupidity here.

**Comment by theeggdev** [comment] 2019-07-16 07:49
> If file size is < 4Mb, use uploadReplace method
If file size is > 4Mb, delete & use session upload

This sounds cool to me, 
because it can keep as many of the file history as possible, and at the same time avoid the HTTP error 413. (while for .txt and .csv we will always be using uploadReplace method no matter how large it is, just to confirm)

Thank you for looking into my issues and thank you for your incredibly prompt reply :D

**Comment by abraunegg** [comment] 2019-07-16 08:16
@theeggdev 
Please can you test the following PR against your use case:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/594/head:pr594
git checkout pr594
make clean; ./configure; make;
```

The only aspect here is - if a non .csv or .txt file is >4Mb & already exists on OneDrive Sharepoint, this will be deleted before the modified file is uploaded - which re-introduces this scenario for large files:
```
Result on Onedrive: 
Admin deleted List of All Apply-to-all Negatives - B.xlsx
Admin created List of All Apply-to-all Negatives - B.xlsx
Admin deleted List of All Apply-to-all Negatives.xlsx
Admin created List of All Apply-to-all Negatives.xlsx
```

**Comment by abraunegg** [comment] 2019-07-16 09:39
@theeggdev 
Below is just for reference - uploading a locally modified file > 4Mb to Sharepoint & **without** deleting the OneDrive file first & the 404 error it generates + creates a whole host of other problems as well:
```
Using Config Dir: /home/alex/.config/onedrive-sharepoint
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveSharePoint
Initializing the Synchronization Engine ...
Application version: v2.3.7-17-gb23390c
Account Type: documentLibrary
Default Drive ID: b!QMiiVyjynUC_UIBZ4WaV8UveUfEgF9BGseBAWSULEb7n4JeIvgOVR4zlieNatYHC
Default Root ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487755496712
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./eLAB Documentation.doc
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./eLAB Documentation.doc ...
Uploading  50% |oooooooooooooooooooo                    |   ETA   --:--:--:OneDrive returned a 'HTTP 404 - Item not found' - gracefully handling error                                  
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:05                                                                                                              
 done.
ERROR: OneDrive response missing required 'id' element
ERROR: {"error":{"code":"itemNotFound","message":"The resource could not be found."}}
Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Retry sync count: 1: Key not found: size
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
The local item has a different modified time 2019-Jul-16 08:19:41Z remote is 2019-Jul-16 09:35:31Z
The local item has a different hash
Remote item modified time is newer based on UTC time conversion
The local item is out-of-sync with OneDrive, renaming to preserve existing file: eLAB Documentation.doc -> eLAB Documentation-centos7full.doc
Downloading file eLAB Documentation.doc ... 
Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:03                                                                                                            
done.
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Processing eLAB Documentation.doc
The file has not changed
Uploading new items of .
Uploading new file ./eLAB Documentation-centos7full.doc ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:05                                                                                                              
 done.
Remaining free space: 27487749228296
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
```

Refer to https://github.com/abraunegg/onedrive/pull/594 for validation of correct handing via the proposed PR.

**Comment by abraunegg** [comment] 2019-07-16 19:12
PR #594 merged, closing case

**Closed by abraunegg** 2019-07-16 19:12 UTC
Labels: Bug, Fixed
