### ISSUE TITLE
Bug: Local files are not safely backed up 

### ISSUE THREAD

**Issue by JC-comp** [abraunegg/onedrive#2616] opened 2024-01-31 01:26 UTC
### Describe the bug

Local files should be safely backed up when the item is not in sync locally to prevent data loss, whether due to deletion or modification online. The provided steps to reproduce illustrates a modification scenario.

### Operating System Details

```shell
skipped
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

v2.5.0-alpha-5 GitHub version: v2.4.25-54-g1a3724d

### What is your OneDrive Application Configuration

```shell
onedrive version                             = v2.5.0-alpha-5 GitHub version: v2.4.25-54-g1a3724d
Config path                                  = /home/alan/.config/onedrive
Config file found in config path             = false
Config option 'drive_id'                     =
Config option 'sync_dir'                     = ~/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive
Config option 'disable_notifications'        = false
Config option 'skip_dir'                     =
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp|*.swp|*.partial
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 12
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'disable_download_validation'  = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = d50ca740-c83f-4d1b-b616-12c519384f0c
Config option 'azure_ad_endpoint'            =
Config option 'azure_tenant_id'              =
Config option 'user_agent'                   = ISV|abraunegg|OneDrive Client for Linux/v2.5.0-alpha-5
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'dns_timeout'                  = 60
Config option 'connect_timeout'              = 10
Config option 'data_timeout'                 = 240
Config option 'ip_protocol_version'          = 0
Config option 'threads'                      = 8

Selective sync 'sync_list' configured        = true
sync_list config option 'sync_root_files'    = false
sync_list contents:

Config option 'sync_business_shared_items'   = false
Selective Business Shared Items configured   = false

Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
skipped
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
skipped
```

### What are all your local file system partition types

```shell
skipped
```

### How do you use 'onedrive'

skipped

### Steps to reproduce the behaviour
```
$ touch 1.txt
$ onedrive --sync
$ echo "123" > 1.txt
// modify 1.txt online
$ onedrive --sync
// local modification to 1.txt is gone
```
### Complete Verbose Log Output

```shell
Using IPv4 and IPv6 (if configured) for all network operations
Configuring Global Azure AD Endpoints
Fetching items from the OneDrive API for Drive ID: af2b5e52bea96776 ..
Processing 1 applicable changes and items received from Microsoft OneDrive .
Downloading file ./1.txt ... done
Performing a database consistency and integrity check on locally stored data ..
Scanning the local file system '~/OneDrive' for new data to upload .
Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching items from the OneDrive API for Drive ID: af2b5e52bea96776 .
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
```

**Comment by abraunegg** [comment] 2024-02-03 19:51
@JC-comp 
This is a regression which is fixed via: https://github.com/abraunegg/onedrive/pull/2584/commits/627726edd1ff6cd2e03c64f65c6511af3115e539

**Evidence:**
```
Processing OneDrive JSON item batch [1/1] to ensure consistent local state
Number of items to download from OneDrive: 1
The local file to replace (./1.txt) has been modified locally since the last download. Renaming it to avoid potential local data loss.
The local item is out-of-sync with OneDrive, renaming to preserve existing file and prevent local data loss: ./1.txt -> ./1-onedrive-client-dev.txt
Downloading file ./1.txt ... done
```

**Closed by abraunegg** 2024-02-03 19:51 UTC
Labels: Bug, Regression

**Comment by JC-comp** [comment] 2024-02-04 00:49
@abraunegg 
The remote deletion case is still malfunctioning. 
```
$ echo "123" > 1
$ onedrive --sync
// file is directly deleted locally
```
```
Reading configuration file: /home/alan/.config/onedrive/config
Configuration file successfully loaded
Using IPv4 and IPv6 (if configured) for all network operations
Configuring Global Azure AD Endpoints
Fetching items from the OneDrive API for Drive ID: af2b5e52bea96776 ..
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Trying to delete file 1
Deleting file 1
Performing a database consistency and integrity check on locally stored data .
Scanning the local file system '~/OneDrive' for new data to upload .
Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching items from the OneDrive API for Drive ID: af2b5e52bea96776 .
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
```

**Comment by abraunegg** [comment] 2024-02-04 01:32
@JC-comp 
Please explain in more detail ... as your original issue is fixed.

When I use your reproduction steps:
```
$ echo "123" > 1
$ onedrive --sync
// file is directly deleted locally
```
The new local file is uploaded correctly without issue:
```
The directory has not changed

Scanning the local file system '~/OneDrive' for new data to upload .Skipping item - excluded by sync_list config: ./random_25k_files

New items to upload to OneDrive: 1 .Total New Data to Upload:        17 Bytes
Uploading new file ./1.txt ... done.

Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching /delta response from the OneDrive API for Drive ID: 66d53be8a5056eca
Processing API Response Bundle: 1 - Quantity of 'changes|items' in this bundle to process: 2
Finished processing /delta JSON response from the OneDrive API
Processing 1 applicable changes and items received from Microsoft OneDrive .
Processing OneDrive JSON item batch [1/1] to ensure consistent local state
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
Fetching /delta response from the OneDrive API for Drive ID: bc7d88ec1f539dcf
Processing API Response Bundle: 1 - Quantity of 'changes|items' in this bundle to process: 0
Finished processing /delta JSON response from the OneDrive API
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
```

When I use your *original* reproduction steps:

```
$ touch 1.txt
$ onedrive --sync
$ echo "123" > 1.txt
// modify 1.txt online
$ onedrive --sync
// local modification to 1.txt is gone
```
Again .. no issue:

```
[alex@onedrive-client-dev onedrive-v2.5.0-alpha-5]$ ./onedrive -s
Reading configuration file: /home/alex/.config/onedrive/config
The option 'min_notify_changes' has been depreciated and will be ignored. Please read the updated documentation and update your client configuration to remove this option.
The option 'force_http_2' has been depreciated and will be ignored. Please read the updated documentation and update your client configuration to remove this option.
Configuration file successfully loaded

ERROR: Unable to create /var/log/onedrive
ERROR: Please manually create '/var/log/onedrive' and set appropriate permissions to allow write access for your user to this location.
ERROR: The requested client activity log will instead be located in your users home directory

Using IPv4 and IPv6 (if configured) for all network operations
Configuring Global Azure AD Endpoints
Fetching items from the OneDrive API for Drive ID: 66d53be8a5056eca ..
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
Fetching items from the OneDrive API for Drive ID: bc7d88ec1f539dcf .
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Performing a database consistency and integrity check on locally stored data .
Scanning the local file system '~/OneDrive' for new data to upload .
New items to upload to OneDrive: 1 .Uploading new file ./1.txt ... done.

Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching items from the OneDrive API for Drive ID: 66d53be8a5056eca ..
Processing 1 applicable changes and items received from Microsoft OneDrive .
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
Fetching items from the OneDrive API for Drive ID: bc7d88ec1f539dcf .
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
```

modify local & remote 
```
[alex@onedrive-client-dev OneDrive]$ vi 1.txt 
this is the local file modified

~                                   
```
remote:
![image](https://github.com/abraunegg/onedrive/assets/4956234/a3f7dae9-f483-42fd-a9d3-39fcdcb1042a)

```
$ onedrive --sync
```
remote is pulled down, local modified file backed up then uploaded:
```
[alex@onedrive-client-dev onedrive-v2.5.0-alpha-5]$ ./onedrive -s
Reading configuration file: /home/alex/.config/onedrive/config
The option 'min_notify_changes' has been depreciated and will be ignored. Please read the updated documentation and update your client configuration to remove this option.
The option 'force_http_2' has been depreciated and will be ignored. Please read the updated documentation and update your client configuration to remove this option.
Configuration file successfully loaded

ERROR: Unable to create /var/log/onedrive
ERROR: Please manually create '/var/log/onedrive' and set appropriate permissions to allow write access for your user to this location.
ERROR: The requested client activity log will instead be located in your users home directory

Using IPv4 and IPv6 (if configured) for all network operations
Configuring Global Azure AD Endpoints
Fetching items from the OneDrive API for Drive ID: 66d53be8a5056eca ..
Processing 1 applicable changes and items received from Microsoft OneDrive .
The local file to replace (./1.txt) has been modified locally since the last download. Renaming it to avoid potential local data loss.
The local item is out-of-sync with OneDrive, renaming to preserve existing file and prevent local data loss: ./1.txt -> ./1-onedrive-client-dev.txt
Downloading file ./1.txt ... done
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
Fetching items from the OneDrive API for Drive ID: bc7d88ec1f539dcf ..
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Performing a database consistency and integrity check on locally stored data .
Scanning the local file system '~/OneDrive' for new data to upload .
New items to upload to OneDrive: 1 .Uploading new file ./1-onedrive-client-dev.txt ... done.

Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching items from the OneDrive API for Drive ID: 66d53be8a5056eca ..
Processing 1 applicable changes and items received from Microsoft OneDrive .
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
Fetching items from the OneDrive API for Drive ID: bc7d88ec1f539dcf .
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive

Sync with Microsoft OneDrive is complete
[alex@onedrive-client-dev onedrive-v2.5.0-alpha-5]$ 

```

There is no issue .. the issue you had raised is fixed

**Comment by JC-comp** [comment] 2024-02-04 01:38
@abraunegg 
For the remote deletion case that deleting the file online before syncing, the modified file should also be safely backed up.
```
$ echo "123" > 1
// delete 1 online
$ onedrive --sync
// file is directly deleted locally
```

**Comment by abraunegg** [comment] 2024-02-04 01:46
> @abraunegg For the remote deletion case that deleting the file online before syncing, the modified file should also be safely backed up.
> 
> ```
> $ echo "123" > 1
> // delete 1 online
> $ onedrive --sync
> // file is directly deleted locally
> ```

So that is a totally different issue / bug .........

**Comment by abraunegg** [comment] 2024-02-12 01:27
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
