### ISSUE TITLE
Using sync_list without full_scan

### ISSUE THREAD

**Issue by ibrahimacarr** [abraunegg/onedrive#788] opened 2020-01-29 12:11 UTC
Hi @abraunegg I am currently using onedrive with sync_list to sync folders which has lots of files (about 100.000). Currently it takes over 3 minutes to finish a full scan, and about 30 seconds to scan sync_list directories. I read issues about sync list and why you need to do a full scan however in my case my priority will be the speed of the synchronization, I can tolarate missing moved files by running --resync periodically. Is there any way to escape full scan and make synchronization itself faster?

Another question will be: 
Is it possible to run single directory synchronization on a folder which is already in the sync_list of onedirive_service running on background via systemctl?

**Application and Operating System Details:**
*   Linux generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 16.04
*   no gui
*   OneDrive Business
* curl --version -> curl 7.64.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.0

**Comment by abraunegg** [comment] 2020-01-29 20:09
@ibrahimacarr 
> I can tolarate missing moved files by running --resync periodically. Is there any way to escape full scan and make synchronization itself faster?

You have only partially provided all the details needed when submitting an issue - the main 2 items missing is what version your running & how you built it. Several improvement were made in how the scanning function works over the last few releases. If you are also running a 'MUCH' earlier version, who knows - you may be running a version that has the database issues present, or even given your OS & how you installed - the 'skilion' version ... 

> Is it possible to run single directory synchronization on a folder which is already in the sync_list of onedirive_service running on background via systemctl?

You cannot run 2 clients, with the same configuration at the same time - this causes database access issues for the local cache.

**Comment by ibrahimacarr** [comment] 2020-01-29 20:14
Thanks for quick response.
I am running version: onedrive v2.3.12-5-g217d724
I built onedrive with the dmd and followed the instructions of yours. Currently getting local changes in 4-5 minutes or even later.

**Comment by abraunegg** [comment] 2020-01-29 20:25
@ibrahimacarr 
Thanks.

Can you please answer the following questions:

* Is your OneDrive an encrypted volume?
* Is your OneDrive encrypted with LUKS?
* Can you please provide your CPU details - full output of `cat /proc/cpuinfo`
* Can you please provide your disk I/O when performing a full run through / application sync - `iostat -dx 1`

Can you also run an `strace` on the application as it is running:
* `ps -AL |grep process_name`
* `strace -c -p <PID>`

**Example:**
```
[alex@centos7full ~]$ ps -AL | grep onedrive
16753 16753 pts/0    00:00:00 onedrive
[alex@centos7full ~]$ strace -c -p 16753
strace: Process 16753 attached
^Cstrace: Process 16753 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 20.98    0.000823          16        53           nanosleep
 17.31    0.000679         679         1           open
 17.23    0.000676         169         4           sendto
 13.61    0.000534         178         3           stat
 10.32    0.000405           4       102           fcntl
  8.56    0.000336           4        87           poll
  3.77    0.000148           4        38           write
  3.24    0.000127          32         4           fsync
  1.33    0.000052           2        23           lseek
  0.97    0.000038           2        16           recvfrom
  0.59    0.000023          12         2           close
  0.54    0.000021          21         1           unlink
  0.46    0.000018           9         2           read
  0.41    0.000016           8         2         1 access
  0.25    0.000010           3         4           fstat
  0.18    0.000007           7         1           restart_syscall
  0.10    0.000004           2         2           getdents
  0.10    0.000004           4         1           openat
  0.05    0.000002           1         4           lstat
------ ----------- ----------- --------- --------- ----------------
100.00    0.003923                   350         1 total
```

Let strace run for at least 15 / 20 minutes (or at least 1 full sync given your running in monitor mode)

**Comment by ibrahimacarr** [comment] 2020-01-29 21:20
- Not encrypted volume somehow
- Below, output of the cpu:
`processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
stepping	: 4
microcode	: 0x2000065
cpu MHz		: 2500.000
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 ida arat pku
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5000.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
stepping	: 4
microcode	: 0x2000065
cpu MHz		: 2500.000
cache size	: 33792 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 ida arat pku
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5000.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:`


-Output of strace: 

```
strace: Process 7525 attached
^Cstrace: Process 7525 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 62.26    0.224743          12     19189           fdatasync
 14.96    0.054017           0    987962           fcntl
  8.09    0.029217           0    524663           lseek
  6.90    0.024919           0    358455         1 write
  2.99    0.010786           0    175411           read
  2.34    0.008433           0    158168           stat
  1.21    0.004379           1      3906           poll
  1.20    0.004317           0     79711           lstat
  0.01    0.000036           0       154           ftruncate
  0.01    0.000035           0       513           close
  0.01    0.000030           0       641           getdents
  0.01    0.000025           0       512           open
  0.01    0.000025           0       666           fstat
  0.00    0.000000           0        94           brk
  0.00    0.000000           0        58         3 futex
  0.00    0.000000           0         1           restart_syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.360962               2310104         4 total

```
I tracked logs for a while and saw that 'processing XXX File' logs taking too much time. This is mainly because of # of files I am syncing is too much.

**Comment by abraunegg** [comment] 2020-01-29 22:09
@ibrahimacarr 
So something is going on here with your Linux system and flushing the data sync operations:
```
62.26    0.224743          12     19189           fdatasync
```
When the application is performing this function:
```
Processing file1.txt
The file has not changed
Processing file2.txt
The file has not changed
Processing file3.txt
The file has not changed
```

All this is doing is performing a 'read' of the system to determine if a change has been made to a local file.

I strongly suspect you have something else going on, on your system that:
* is causing some sort of disk I/O to consume data sync operations

I will see what I can do to create a dummy file set of ~100K files - but right now, this is not a bug but something wrong with your local system - kernel, filesystem, disk I/O .. you need to performance profile your system to determine what is causing your system to be constantly flushing disk buffers

**Comment by abraunegg** [comment] 2020-01-29 22:44
@ibrahimacarr 
To also assist with this issue, please have a read of this: https://github.com/abraunegg/onedrive/wiki/Generate-system-performance-data-for-performance-related-issues

You may need to rebuild your client to enable the debug symbols, then perform the `perf` steps to determine what is going on.

**Comment by ibrahimacarr** [comment] 2020-01-30 06:14
I am going to observe performance, share results with you.
As I observed from live logs, it is performing fast as you mentioned while logging below logs:

`Processing file1.txt
The file has not changed
Processing file2.txt
The file has not changed
Processing file3.txt
The file has not changed`

Hovewer, what takes time is:

`Processing 206 OneDrive items to ensure consistent state due to sync_list being used
Processing 203 OneDrive items to ensure consistent state due to sync_list being used
Processing 203 OneDrive items to ensure consistent state due to sync_list being used
`
OR
`Ignoring OneDrive account quota details to upload file - this may fail if not enough space on OneDrive 
Ignoring OneDrive account quota details to upload file - this may fail if not enough space on OneDrive
Ignoring OneDrive account quota details to upload file - this may fail if not enough space on OneDrive 
`
OR After logging above it logs `Applying changes of Path ID: 01VBB7ZF56Y2GOVW7725BZO354PWSELRRZ` and waits for a while without logging before log `SYnc with OneDrive is complete`

**Comment by abraunegg** [comment] 2020-01-30 06:20
@ibrahimacarr 
Please get the performance data

When the application is doing this:
```
Processing 206 OneDrive items to ensure consistent state due to sync_list being used
```
This is 'parsing' JSON data back from OneDrive - so there should be very minimal disk activity going on, and if anything, updating the 'cache database' with the data in the JSON - and only update if something has changed.

```
Ignoring OneDrive account quota details to upload file - this may fail if not enough space on OneDrive
```
This is when a file is being uploaded - so, depending on your Internet connectivity, the upload will take time before moving onto the next item.

**Comment by abraunegg** [comment] 2020-01-30 06:24
@ibrahimacarr 
Also, you have only partially provided all the details needed when submitting an issue. Please update your first entry with all the details as per https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md

**Comment by ibrahimacarr** [comment] 2020-01-30 07:54
I am sorry for the late response, however I will not be able to install perf on my system due to kernel conflicts. Here is another thing may be clue what is going on.
Here is the output of logs when no change detected.
```
Jan 30 10:25:29 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:25:55 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:28:29 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:28:58 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:31:05 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:31:32 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:34:13 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:34:39 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:36:46 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:37:13 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:40:11 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:40:39 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:43:55 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
Jan 30 10:44:27 ip-172-31-36-217 onedrive[12453]: Syncing changes from OneDrive ...
```
 If you follow the time time spent on syncing is 30 seconds or 3 minutes even there is no difference. I read on issues, it should be running full scan when using sync_list. In that scenario My synchronization should be delayed for maximum 3 minutes, but in real case it is delaying even ~10 minutes. As I saw it is not processing all changes but giving a full scan before finishing the synchronization, anyway.

**Comment by abraunegg** [comment] 2020-01-30 09:54
@ibrahimacarr 
> I am sorry for the late response, however I will not be able to install perf on my system due to kernel conflicts.

Hrmmm ... suggest then you either upgrade away from Ubuntu 16.x 

When in monitor mode, the process is:

* Light sync x 10
* Full Sync based on last checkpoint

When using sync_list

* Light sync x 10
* Full Sync ignoring last checkpoint (essentially full scan)

Between each scan is a delay configured by `monitor_interval` which defaults to 45 seconds.

Everything I am seeing here is normal operation. Without debug logging or performance data it is hard to assist. Without data, the only things this can be is:
* Kernel / OS issue
* Misconfigured filesystem
* Maybe a mount point to an external SD card or USD thumb drive or USD disk

**Comment by ibrahimacarr** [comment] 2020-01-30 10:23
I am currently try to get information you need, I am gonna let you know if I can get it.

Do you think could be faster if I cancel sync_list and Use full synchronization?
By the way is there any difference between skip_dir or .nosync or sync_list? Does it differ If I configure same selective sync via sync_list or skip_dir or .nosync?

**Comment by abraunegg** [comment] 2020-01-30 20:14
@ibrahimacarr 
> Do you think could be faster if I cancel sync_list and Use full synchronization?

Probably not - as your first post also does not contain the required details, hard to determine your configuration to make a correct evaluation.

> By the way is there any difference between skip_dir or .nosync or sync_list? Does it differ If I configure same selective sync via sync_list or skip_dir or .nosync?

There are pro's and con's of each approach. If you do not use sync_list, then the full scan ignoring last checkpoint would be avoided.

> I did not mentioned but I am running synchronization via systemctl on amazon instance, do you think that might be the reason?

Potentially, but again, not enough data to advise because you cant install the tooling needed, because your using Ubuntu 16.x ....

**Comment by abraunegg** [comment] 2020-02-01 20:28
@ibrahimacarr 
Any update from your side in terms of testing other options / upgrading your OS / attempting to get the performance related items?

If not, will close this case for the following reasons:
* Not enough data / logs to assist with working out what is going on
* Older Ubuntu version in use which has known kernel performance issues
* Running on an AWS instance - so CPU / clock cycles will be throttled by AWS, no information about the instance type provided
* The OS performing `fdatasync` for unknown reason(s) - no diagnostic information provided
* For all information provided thus far, there is zero issue with the client operation

**Suggested Next Steps for you to take:**
* Speak to AWS about why a Linux machine is spending a long time performing `fdatasync`
* Seek support from Ubuntu
* Upgrade your OS to a more modern Ubuntu and see if the issue persists, or install / use a Linux distribution that is a much better alternative to Ubuntu - Debian / Arch / Fedora / CentOS to name a few.

**Comment by abraunegg** [comment] 2020-02-02 19:39
@ibrahimacarr 
Closing issue due to reasons above

**Closed by abraunegg** 2020-02-02 19:39 UTC
Labels: Local Environment Issue, More Information Needed, Not a bug, Waiting on Response
