### ISSUE TITLE
New install, can't connect to OneDrive Service

### ISSUE THREAD

**Issue by seanferd** [abraunegg/onedrive#774] opened 2020-01-13 19:45 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
As stated, I have a new install and I can't connect to OneDrive to begin the authentication process. Receiving error:

Cannot connect to Microsoft OneDrive Service
Reason: SSL peer certificate or SSH remote key was not OK on handle 55695A7580D0

**Application and Operating System Details:**
*   OS: Ubuntu 19.10 - 5.3.0-26-generic
*   gui, but setup from terminal over ssh
*   OneDrive Account Type: free
*   DMD  DMD64 D Compiler v2.089.1
*   Config:
```
onedrive version                       = v2.3.13-7-gb81b969
Config path                            = /home/sean/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /storage/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```

*   Curl Version: curl 7.65.3

Debug output is very small:

```
sean@pacman:~$ onedrive --synchronize --verbose --verbose > debug_output.log 2>&1
sean@pacman:~$ cat debug_output.log 
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/sean
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/sean/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /home/sean/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /storage/OneDrive
Initializing the OneDrive API ...
Cannot connect to Microsoft OneDrive Service
Reason: SSL peer certificate or SSH remote key was not OK on handle 55CF4E60F010
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  run `onedrive`
2.  See error

**Additional context**
I have had this working until maybe 3-4 weeks ago. Trying to debug and get this working, I've completely removed the previous version and config and reinstalled following the instructions in the Readme on this site. I believe I had the skilion version previously - again which was working and stopped. Now I've attempted to setup the abraunegg version with the same result. I have a PiHole at home, but disabling it does not help - further I didn't have to disable it when it worked previously. I have no issues with the Windows OneDrive client on the same network and can get to the OneDrive website on the problem machine. As far as I'm aware, nothing has changed in my network or on this specific computer to cause this.

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2020-01-13 19:58
@seanferd 
It looks like your SSL CA Certificates need to be updated - which is your local OS.

Can you please provide a HTTPS Debug Log as per: https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support - this will at least show what is going on at the HTTPS / Curl level in regards to certificates.

> Readme on this site. I believe I had the skilion version previously - again which was working and stopped.

Double check that you also do not have data loss / corrupt files as a result of previously using the skilion version of the client.

**Comment by seanferd** [comment] 2020-01-13 20:02
The https debug is just as short:

sean@pacman:~$ onedrive --synchronize --verbose --verbose --debug-https > debug_output.log 2>&1
sean@pacman:~$ cat debug_output.log
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/sean
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/sean/.config
[DEBUG] configDirName: Configuring application to use default config path
Using Config Dir: /home/sean/.config/onedrive
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /storage/OneDrive
Initializing the OneDrive API ...
Cannot connect to Microsoft OneDrive Service
Reason: SSL peer certificate or SSH remote key was not OK on handle 55E8DD66DE30

How do you update SSL CA certs? apt-get update / full-upgrade has zero packages to upgrade.

Where would I check for data loss / corruption? I did a sudo make uninstall. I still have my Onedrive files pulled down (but out of date) in the same path I've configured above, would that have an effect?

**Comment by abraunegg** [comment] 2020-01-13 20:20
@seanferd 
On a test Ubuntu 19.04 system, I have the following for the CA Certificates:
```
apt list --installed | grep cert

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ca-certificates/disco,now 20190110 all [installed,automatic]
python3-certifi/disco,now 2018.8.24-1 all [installed,automatic]
```

No issue in running the client:
```
./onedrive --synchronize --verbose
Using Config Dir: /root/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.3.13-7-gb81b969
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709107
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Creating directory: Documents
Downloading file testfile.txt ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing Documents
The directory has not changed
Processing testfile.txt
The file has not changed
Uploading new items of .
Uploading new file ./newfile-centos7full.txt ... done.
Remaining free space: 5368709094
Uploading new file ./aqwerqwerqwerqwerqwrqw.asfd.asdf.asd.f ... done.
Remaining free space: 5368709011
Uploading new file ./newfile.txt ... done.
Remaining free space: 5368708942
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Currently updating that system to 19.10  

> Where would I check for data loss / corruption?

You would need to check and validate all your files on your local OS. The skilion client is horribly broken.

**Comment by seanferd** [comment] 2020-01-13 20:30
Mine are unsurprisingly newer from the eoan branch:
apt list --installed | grep cert

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ca-certificates-java/eoan,eoan,now 20190405ubuntu1 all [installed,automatic]
ca-certificates/eoan,eoan,now 20190110 all [installed,automatic]
python3-certifi/eoan,eoan,now 2018.8.24-1 all [installed,automatic]
ssl-cert/eoan,eoan,now 1.0.39 all [installed,automatic]

I have another 19.10 machine that I've never tried this on and see if it has the same issue. I'm not even positive I had skilion previously, I just assume so. But if the other machine has the same trouble it might make this easier to diagnose.

**Comment by seanferd** [comment] 2020-01-13 20:37
Interestingly the other machine works fine:

sean@seanathome:~/onedrive$ onedrive 
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0...

**Comment by abraunegg** [comment] 2020-01-13 20:47
@seanferd 
I would compare the output of `apt list --installed | grep cert` on both systems, then validate that all your certificates are on your system as per https://packages.ubuntu.com/eoan/all/ca-certificates/filelist

**Comment by seanferd** [comment] 2020-01-13 21:43
Working (I have a webserver here using certbot):
ca-certificates/eoan,eoan,now 20190110 all [installed]
certbot/eoan,eoan,now 0.36.0-1 all [installed]
python-certbot-apache/eoan,eoan,now 0.36.0-1 all [installed]
python3-certbot-apache/eoan,eoan,now 0.36.0-1 all [installed,automatic]
python3-certbot/eoan,eoan,now 0.36.0-1 all [installed,automatic]
python3-certifi/eoan,eoan,now 2018.8.24-1 all [installed,automatic]
ssl-cert/eoan,eoan,now 1.0.39 all [installed,automatic]

Non-working:
ca-certificates-java/eoan,eoan,now 20190405ubuntu1 all [installed,automatic]
ca-certificates/eoan,eoan,now 20190110 all [installed,automatic]
python3-certifi/eoan,eoan,now 2018.8.24-1 all [installed,automatic]
ssl-cert/eoan,eoan,now 1.0.39 all [installed,automatic]

The java one is the only one that sticks out otherwise?

**Comment by abraunegg** [comment] 2020-01-13 21:51
@seanferd 
> Edit: Apparently this is because the non-working machine has LibreOffice installed.

Are you saying that this is why `ca-certificates-java` is installed?

**Comment by abraunegg** [comment] 2020-01-13 21:52
@seanferd 
Please can you also backtick all your output when posting ..

**Comment by seanferd** [comment] 2020-01-13 21:53
> @seanferd
> 
> > Edit: Apparently this is because the non-working machine has LibreOffice installed.
> 
> Are you saying that this is why `ca-certificates-java` is installed?

Yep, I tried to purge it and LibreOffice as the only set of affected packages. 

I will backtick going forward.

**Comment by seanferd** [comment] 2020-01-13 21:57
`The following packages will be REMOVED:  
  ca-certificates-java{p} 
0 packages upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 44.0 kB will be freed.
The following packages have unmet dependencies:
 openjdk-11-jre-headless : Depends: ca-certificates-java (>= 20190405~) but it is not going to be installed
The following actions will resolve these dependencies:

     Remove the following packages:                                                     
1)     default-jre [2:1.11-72 (eoan, now)]                                              
2)     default-jre-headless [2:1.11-72 (eoan, now)]                                     
3)     openjdk-11-jre [11.0.5+10-0ubuntu1.1 (eoan-security, eoan-updates, now)]         
4)     openjdk-11-jre-headless [11.0.5+10-0ubuntu1.1 (eoan-security, eoan-updates, now)]

     Leave the following dependencies unresolved:                                       
5)     libreoffice-base recommends default-jre | sun-java6-jre | java6-runtime | jre`

**Comment by abraunegg** [comment] 2020-01-13 22:05
@seanferd 
My system is now 19.10 updated:
```
root@ubuntu-x64-19:~/code/onedrive# apt list --installed | grep cert

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ca-certificates/eoan,now 20190110 all [installed,automatic]
python3-certifi/eoan,now 2018.8.24-1 all [installed,automatic]
root@ubuntu-x64-19:~/code/onedrive# 
root@ubuntu-x64-19:~/code/onedrive# ./onedrive --synchronize --verbose
Using Config Dir: /root/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.3.13-7-gb81b969
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```
No no issue with a default installation .... what about when installing `ca-certificates-java` & rebuild client just to be sure:

```root@ubuntu-x64-19:~/code/onedrive# 
root@ubuntu-x64-19:~/code/onedrive# apt install ca-certificates-java
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  default-jre-headless java-common libasound2 libasound2-data libnspr4 libnss3 libpcsclite1 openjdk-11-jre-headless
Suggested packages:
  default-jre libasound2-plugins alsa-utils pcscd libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  ca-certificates-java default-jre-headless java-common libasound2 libasound2-data libnspr4 libnss3 libpcsclite1 openjdk-11-jre-headless
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 39.0 MB of archives.
After this operation, 177 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu eoan/main amd64 java-common all 0.72 [6,816 B]
Get:2 http://archive.ubuntu.com/ubuntu eoan/main amd64 libnspr4 amd64 2:4.21-2build1 [107 kB]
Get:3 http://archive.ubuntu.com/ubuntu eoan-updates/main amd64 libnss3 amd64 2:3.45-1ubuntu2.2 [1,165 kB]
Get:4 http://archive.ubuntu.com/ubuntu eoan/main amd64 libasound2-data all 1.1.9-0ubuntu1 [42.0 kB]                                                                              
Get:5 http://archive.ubuntu.com/ubuntu eoan/main amd64 libasound2 amd64 1.1.9-0ubuntu1 [342 kB]                                                                                  
Get:6 http://archive.ubuntu.com/ubuntu eoan/main amd64 libpcsclite1 amd64 1.8.25-2ubuntu1 [21.9 kB]                                                                              
Get:7 http://archive.ubuntu.com/ubuntu eoan-updates/main amd64 openjdk-11-jre-headless amd64 11.0.5+10-0ubuntu1.1 [37.3 MB]                                                      
Get:8 http://archive.ubuntu.com/ubuntu eoan/main amd64 default-jre-headless amd64 2:1.11-72 [3,192 B]                                                                            
Get:9 http://archive.ubuntu.com/ubuntu eoan/main amd64 ca-certificates-java all 20190405ubuntu1 [12.2 kB]                                                                        
Fetched 39.0 MB in 3min 19s (196 kB/s)                                                                                                                                           
Selecting previously unselected package java-common.
(Reading database ... 96086 files and directories currently installed.)
Preparing to unpack .../0-java-common_0.72_all.deb ...
Unpacking java-common (0.72) ...
Selecting previously unselected package libnspr4:amd64.
Preparing to unpack .../1-libnspr4_2%3a4.21-2build1_amd64.deb ...
Unpacking libnspr4:amd64 (2:4.21-2build1) ...
Selecting previously unselected package libnss3:amd64.
Preparing to unpack .../2-libnss3_2%3a3.45-1ubuntu2.2_amd64.deb ...
Unpacking libnss3:amd64 (2:3.45-1ubuntu2.2) ...
Selecting previously unselected package libasound2-data.
Preparing to unpack .../3-libasound2-data_1.1.9-0ubuntu1_all.deb ...
Unpacking libasound2-data (1.1.9-0ubuntu1) ...
Selecting previously unselected package libasound2:amd64.
Preparing to unpack .../4-libasound2_1.1.9-0ubuntu1_amd64.deb ...
Unpacking libasound2:amd64 (1.1.9-0ubuntu1) ...
Selecting previously unselected package libpcsclite1:amd64.
Preparing to unpack .../5-libpcsclite1_1.8.25-2ubuntu1_amd64.deb ...
Unpacking libpcsclite1:amd64 (1.8.25-2ubuntu1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../6-openjdk-11-jre-headless_11.0.5+10-0ubuntu1.1_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.5+10-0ubuntu1.1) ...
Selecting previously unselected package default-jre-headless.
Preparing to unpack .../7-default-jre-headless_2%3a1.11-72_amd64.deb ...
Unpacking default-jre-headless (2:1.11-72) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../8-ca-certificates-java_20190405ubuntu1_all.deb ...
Unpacking ca-certificates-java (20190405ubuntu1) ...
Setting up java-common (0.72) ...
Setting up libasound2-data (1.1.9-0ubuntu1) ...
Setting up libnspr4:amd64 (2:4.21-2build1) ...
Setting up libpcsclite1:amd64 (1.8.25-2ubuntu1) ...
Setting up libasound2:amd64 (1.1.9-0ubuntu1) ...
Setting up libnss3:amd64 (2:3.45-1ubuntu2.2) ...
Setting up default-jre-headless (2:1.11-72) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.5+10-0ubuntu1.1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up ca-certificates-java (20190405ubuntu1) ...
head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
Adding debian:OISTE_WISeKey_Global_Root_GB_CA.pem
Adding debian:USERTrust_RSA_Certification_Authority.pem
Adding debian:T-TeleSec_GlobalRoot_Class_3.pem
Adding debian:OISTE_WISeKey_Global_Root_GA_CA.pem
Adding debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4.pem
Adding debian:CA_Disig_Root_R2.pem
Adding debian:Starfield_Services_Root_Certificate_Authority_-_G2.pem
Adding debian:EC-ACC.pem
Adding debian:GeoTrust_Global_CA.pem
Adding debian:GlobalSign_Root_CA_-_R3.pem
Adding debian:Sonera_Class_2_Root_CA.pem
Adding debian:Go_Daddy_Class_2_CA.pem
Adding debian:DigiCert_Global_Root_CA.pem
Adding debian:Deutsche_Telekom_Root_CA_2.pem
Adding debian:QuoVadis_Root_CA_2.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
Adding debian:COMODO_Certification_Authority.pem
Adding debian:OISTE_WISeKey_Global_Root_GC_CA.pem
Adding debian:GeoTrust_Primary_Certification_Authority_-_G2.pem
Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Adding debian:Taiwan_GRCA.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_ECC.pem
Adding debian:Certum_Trusted_Network_CA.pem
Adding debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem
Adding debian:GeoTrust_Primary_Certification_Authority_-_G3.pem
Adding debian:QuoVadis_Root_CA.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem
Adding debian:EE_Certification_Centre_Root_CA.pem
Adding debian:DigiCert_Trusted_Root_G4.pem
Adding debian:SSL.com_Root_Certification_Authority_ECC.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
Adding debian:GlobalSign_Root_CA.pem
Adding debian:IdenTrust_Public_Sector_Root_CA_1.pem
Adding debian:Certigna.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:TrustCor_RootCert_CA-1.pem
Adding debian:SwissSign_Gold_CA_-_G2.pem
Adding debian:GlobalSign_Root_CA_-_R6.pem
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:Certplus_Class_2_Primary_CA.pem
Adding debian:Certum_Trusted_Network_CA_2.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Adding debian:QuoVadis_Root_CA_3_G3.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem
Adding debian:Security_Communication_Root_CA.pem
Adding debian:NetLock_Arany_=Class_Gold=_FÅ‘tanÃºsÃ­tvÃ¡ny.pem
Adding debian:Security_Communication_RootCA2.pem
Adding debian:Amazon_Root_CA_3.pem
Adding debian:GDCA_TrustAUTH_R5_ROOT.pem
Adding debian:thawte_Primary_Root_CA_-_G2.pem
Adding debian:Comodo_AAA_Services_root.pem
Adding debian:COMODO_ECC_Certification_Authority.pem
Adding debian:Staat_der_Nederlanden_EV_Root_CA.pem
Adding debian:Certinomis_-_Root_CA.pem
Adding debian:Secure_Global_CA.pem
Adding debian:AffirmTrust_Premium.pem
Adding debian:Starfield_Class_2_CA.pem
Adding debian:DigiCert_Assured_ID_Root_CA.pem
Adding debian:Go_Daddy_Root_Certificate_Authority_-_G2.pem
Adding debian:XRamp_Global_CA_Root.pem
Adding debian:Staat_der_Nederlanden_Root_CA_-_G2.pem
Adding debian:AffirmTrust_Networking.pem
Adding debian:Microsec_e-Szigno_Root_CA_2009.pem
Adding debian:Hongkong_Post_Root_CA_1.pem
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:Actalis_Authentication_Root_CA.pem
Adding debian:Amazon_Root_CA_2.pem
Adding debian:thawte_Primary_Root_CA.pem
Adding debian:ISRG_Root_X1.pem
Adding debian:Baltimore_CyberTrust_Root.pem
Adding debian:SSL.com_Root_Certification_Authority_RSA.pem
Adding debian:Buypass_Class_2_Root_CA.pem
Adding debian:GeoTrust_Universal_CA.pem
Adding debian:Izenpe.com.pem
Adding debian:Trustis_FPS_Root_CA.pem
Adding debian:ePKI_Root_Certification_Authority.pem
Adding debian:DigiCert_Global_Root_G3.pem
Adding debian:SwissSign_Silver_CA_-_G2.pem
Adding debian:Entrust_Root_Certification_Authority_-_EC1.pem
Adding debian:Network_Solutions_Certificate_Authority.pem
Adding debian:SecureSign_RootCA11.pem
Adding debian:AddTrust_External_Root.pem
Adding debian:thawte_Primary_Root_CA_-_G3.pem
Adding debian:AffirmTrust_Commercial.pem
Adding debian:GeoTrust_Universal_CA_2.pem
Adding debian:TWCA_Global_Root_CA.pem
Adding debian:Entrust_Root_Certification_Authority.pem
Adding debian:SecureTrust_CA.pem
Adding debian:GlobalSign_Root_CA_-_R2.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R5.pem
Adding debian:VeriSign_Universal_Root_Certification_Authority.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Adding debian:Global_Chambersign_Root_-_2008.pem
Adding debian:Starfield_Root_Certificate_Authority_-_G2.pem
Adding debian:certSIGN_ROOT_CA.pem
Adding debian:Entrust_Root_Certification_Authority_-_G2.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:Chambers_of_Commerce_Root_-_2008.pem
Adding debian:CFCA_EV_ROOT.pem
Adding debian:QuoVadis_Root_CA_3.pem
Adding debian:DST_Root_CA_X3.pem
Adding debian:USERTrust_ECC_Certification_Authority.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R4.pem
Adding debian:TrustCor_ECA-1.pem
Adding debian:DigiCert_Assured_ID_Root_G3.pem
Adding debian:Amazon_Root_CA_4.pem
Adding debian:Amazon_Root_CA_1.pem
Adding debian:GeoTrust_Primary_Certification_Authority.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_RSA_R2.pem
Adding debian:SZAFIR_ROOT_CA2.pem
Adding debian:Buypass_Class_3_Root_CA.pem
Adding debian:AffirmTrust_Premium_ECC.pem
Adding debian:AC_RAIZ_FNMT-RCM.pem
Adding debian:DigiCert_High_Assurance_EV_Root_CA.pem
Adding debian:TrustCor_RootCert_CA-2.pem
Adding debian:Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem
Adding debian:Cybertrust_Global_Root.pem
Adding debian:TWCA_Root_Certification_Authority.pem
Adding debian:LuxTrust_Global_Root_2.pem
Adding debian:Staat_der_Nederlanden_Root_CA_-_G3.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:ACCVRAIZ1.pem
Adding debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
Adding debian:E-Tugra_Certification_Authority.pem
Adding debian:COMODO_RSA_Certification_Authority.pem
done.
Processing triggers for libc-bin (2.30-0ubuntu2) ...
Processing triggers for man-db (2.8.7-3) ...
Processing triggers for ca-certificates (20190110) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
root@ubuntu-x64-19:~/code/onedrive# cd ..
root@ubuntu-x64-19:~/code# ./clone_master.sh 
Cloning into 'onedrive'...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 3663 (delta 33), reused 16 (delta 11), pack-reused 3601
Receiving objects: 100% (3663/3663), 2.26 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (2501/2501), done.
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.087.1
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.0-dev > version ; \
fi
dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
root@ubuntu-x64-19:~/code# cd onedrive
root@ubuntu-x64-19:~/code/onedrive# 
root@ubuntu-x64-19:~/code/onedrive# 
root@ubuntu-x64-19:~/code/onedrive# ./onedrive --synchronize --verbose
Using Config Dir: /root/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.3.13-7-gb81b969
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
root@ubuntu-x64-19:~/code/onedrive# 

```

Again .. no issue at all .. so .. this is a problem with your local system. 

Please seek support with Ubuntu folk as this is not an issue which I can replicate or assist with any further

**Comment by abraunegg** [comment] 2020-01-14 18:14
Closing issue as not a bug, issue with SSL Certificates on local file system, unable to reproduce

**Closed by abraunegg** 2020-01-14 18:14 UTC
Labels: Local Environment Issue, Not a bug, Unable to reproduce
