### ISSUE TITLE
Files with ":" in the name won't be uploaded

### ISSUE THREAD

**Issue by rednag** [abraunegg/onedrive#443] opened 2019-03-28 15:56 UTC
### Bug Report Details ###
I've discovered that a few files, which have a ":" in their names, are not uploaded. If I remove the ":" the files will be staged and uploaded!

Application and Operating System Details:

OS: Linux CX 5.0.2 #1 SMP Sun Mar 17 16:38:08 CET 2019 x86_64 x86_64 x86_64 GNU/Linux
GNOME
OneDrive Personal
DMD64 D Compiler v2.085
onedrive version = onedrive v2.3.1
Config path = /home/CX/.config/onedrive
Config file found in config path = true
Config option 'sync_dir' = /media/CX/OneDrive
Config option 'skip_file' = ~*
Config option 'skip_symlinks' = false
Config option 'monitor_interval' = 500
Config option 'log_dir' = /var/log/onedrive/
Selective sync configured = false
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

**To Reproduce**
I've tried to move the files to a different location and make a manual resync, but only after changing the name the files are uploaded.

**Comment by abraunegg** [comment] 2019-03-29 00:35
@rednag 
This is not a bug or issue as per the following:
```
(dmd-2.083.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 4498492245
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing asdf
The directory has not changed
Uploading new items of .
Skipping item - invalid name (Microsoft Naming Convention): ./asdf/file:name.txt
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by abraunegg** [comment] 2019-03-29 00:36
@rednag 
Closing issue as `:` is an invalid name as per Microsoft Naming Conventions

**Closed** 2019-03-29 00:36 UTC
Labels: Answer Provided, Not a bug
