### ISSUE TITLE
Bug: Uploading fails due to no free space available

### ISSUE THREAD

**Issue by theoware** [abraunegg/onedrive#3005] opened 2024-11-24 13:11 UTC
### Describe the bug

Hi,

for a few days now, the OneDrive client fails to upload anything. Emptying the trash bin doesn't help. I've tried resyncing. I can upload documents through other means (web client)

### Operating System Details

```shell
uname -a
Linux fedora 6.11.8-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 14 20:37:39 UTC 2024 x86_64 GNU/Linux

cat /etc/redhat-release
Fedora release 41 (Forty One)
```

### Client Installation Method

From Source

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

onedrive v2.5.3-9-gc9591b3

### What is your OneDrive Application Configuration

```shell
Reading configuration file: /home/user/.config/onedrive/config
Invalid value for key in config file - using default value: monitor_interval
Configuration file successfully loaded
Application version                          = onedrive v2.5.3-9-gc9591b3
Compiled with                                = LDC 2109
Curl version                                 = libcurl/8.9.1 OpenSSL/3.2.2 zlib/1.3.1 libidn2/2.3.7 nghttp2/1.62.1
User Application Config path                 = /home/user/.config/onedrive
System Application Config path               = /etc/onedrive
Applicable Application 'config' location     = /home/user/.config/onedrive/config
Configuration file found in config location  = true - using 'config' file values to override application defaults
Applicable 'sync_list' location              = /home/user/.config/onedrive/sync_list
Applicable 'items.sqlite3' location          = /home/user/.config/onedrive/items.sqlite3
Config option 'drive_id'                     = 
Config option 'sync_dir'                     = ~/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive
Config option 'disable_notifications'        = false
Config option 'skip_dir'                     = ***
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 12
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'disable_download_validation'  = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = d50ca740-c83f-4d1b-b616-12c519384f0c
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = 
Config option 'user_agent'                   = ISV|abraunegg|OneDrive Client for Linux/v2.5.3-9-gc9591b3
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'dns_timeout'                  = 60
Config option 'connect_timeout'              = 10
Config option 'data_timeout'                 = 60
Config option 'ip_protocol_version'          = 0
Config option 'threads'                      = 8
Config option 'max_curl_idle'                = 120
Compile time option --enable-notifications   = false

Selective sync 'sync_list' configured        = false

Config option 'sync_business_shared_items'   = false

Config option 'webhook_enabled'              = fals
```

### What is your 'curl' version

```shell
curl 8.9.1 (x86_64-redhat-linux-gnu) libcurl/8.9.1 OpenSSL/3.2.2 zlib/1.3.1.zlib-ng libidn2/2.3.7 nghttp2/1.62.1
Release-Date: 2024-07-31
Protocols: file ftp ftps http https ipfs ipns
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz SPNEGO SSL threadsafe UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
/dev/mapper/luks-657ac21f-b0c1-444d-9a14-cd04893ed4ee on / type btrfs (rw,relatime,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/root)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=4096k,nr_inodes=2027890,mode=755,inode64)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=3257544k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/credentials/systemd-cryptsetup@luks\x2d657ac21f\x2db0c1\x2d444d\x2d9a14\x2dcd04893ed4ee.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12765)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,nosuid,nodev,relatime,pagesize=2M)
tmpfs on /run/credentials/systemd-journald.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-network-generator.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-udev-load-credentials.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev-early.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-sysctl.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-tmpfiles-setup-dev.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-cryptsetup@luks\x2d48f8a6c3\x2d67ab\x2d4165\x2d8671\x2db7db68e9241b.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-vconsole-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
/dev/mapper/luks-657ac21f-b0c1-444d-9a14-cd04893ed4ee on /btrfs_pool type btrfs (rw,relatime,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/mapper/luks-657ac21f-b0c1-444d-9a14-cd04893ed4ee on /home type btrfs (rw,relatime,compress=zstd:1,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home)
/dev/nvme0n1p2 on /boot type ext4 (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,size=8143860k,nr_inodes=1048576,inode64)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro)
tmpfs on /run/credentials/systemd-tmpfiles-setup.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
tmpfs on /run/credentials/systemd-resolved.service type tmpfs (ro,nosuid,nodev,noexec,relatime,nosymfollow,size=1024k,nr_inodes=1024,mode=700,inode64,noswap)
/dev/sdb1 on /mnt/23CC30640EFB4643 type fuseblk (rw,nosuid,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,user,x-gvfs-show)
/dev/sdd1 on /mnt/backup type btrfs (rw,relatime,compress=zstd:6,discard=async,space_cache=v2,subvolid=5,subvol=/,x-gvfs-show)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
/dev/mapper/luks-48f8a6c3-67ab-4165-8671-b7db68e9241b on /mnt/main type btrfs (rw,relatime,compress=zstd:6,discard=async,space_cache=v2,subvolid=5,subvol=/,x-gvfs-show)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1628768k,nr_inodes=407192,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME                                          FSTYPE      FSVER LABEL                 UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sda                                                                                                                                       
└─sda1                                        crypto_LUKS 2                           48f8a6c3-67ab-4165-8671-b7db68e9241b                
  └─luks-48f8a6c3-67ab-4165-8671-b7db68e9241b btrfs                                   27e58458-5e22-417c-9172-fd628e2ff951    477G    72% /mnt/main
sdb                                                                                                                                       
└─sdb1                                        ntfs                                    23CC30640EFB4643                        199G    79% /mnt/23CC30640EFB4643
sdc                                                                                                                                       
├─sdc1                                        vfat        FAT32                       64D4-9AF2                                           
└─sdc2                                        ntfs                                    BE8AE4BE8AE473F5                                    
sdd                                                                                                                                       
└─sdd1                                        btrfs                                   7c381ff9-fd13-4372-9704-13f2e9be84f8  228,9G    75% /mnt/backup
sde                                                                                                                                       
zram0                                                                                                                                     [SWAP]
nvme0n1                                                                                                                                   
├─nvme0n1p1                                   vfat        FAT32                       1024-1AA2                             579,5M     3% /boot/efi
├─nvme0n1p2                                   ext4        1.0                         42d3d7b3-e8b2-44e2-8207-7559c96fa49a  475,6M    44% /boot
└─nvme0n1p3                                   crypto_LUKS 2                           657ac21f-b0c1-444d-9a14-cd04893ed4ee                
  └─luks-657ac21f-b0c1-444d-9a14-cd04893ed4ee btrfs             fedora_localhost-live b9675bfe-2d6a-44f8-9a20-aec2cb2fd6ca   59,9G    92% /home
                                                                                                                                          /btrfs_pool
                                                                                                                                          /
```

### How do you use 'onedrive'

I use it to sync files to my pc and edit them locally

### Steps to reproduce the behaviour

Start onedrive using onedrive --sync

### Complete Verbose Log Output

```shell
For privacy reasons, I will only send it by e-mail
```

### Screenshots

![Bildschirmfoto vom 2024-11-24 14-01-03](https://github.com/user-attachments/assets/da2fab66-b6a7-45c8-a22b-b4c973867c74)
![Bildschirmfoto vom 2024-11-24 14-00-46](https://github.com/user-attachments/assets/f6d6afc4-e39a-4912-901e-ba0989658573)

**Comment by abraunegg** [comment] 2024-11-24 18:39
@theoware 

Thank you for raising this issue. Based on the debug log provided:

```
DEBUG: Quota Details: {"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#drives/$entity","quota":{"deleted":55515435065,"remaining":0,"state":"exceeded","total":1099511627776,"used":1254346957908}}
```

Expanded for clarity:
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives/$entity",
	"quota": {
		"deleted": 55515435065,
		"remaining": 0,
		"state": "exceeded",
		"total": 1099511627776,
		"used": 1254346957908
	}
}
```

It appears the root cause is that your OneDrive account has exceeded its storage quota, which is preventing uploads. This is not an issue with the OneDrive Client itself but rather a limitation of the OneDrive service due to your account status.

I’d like to kindly remind you of the guidance provided when opening new issues. Specifically, this issue is more of a question rather than a report of a software bug. A **bug** typically refers to problems like:

- The application crashing unexpectedly.
- Functionality not working as intended, such as incorrect behavior due to a logic error or feature malfunction.
- Errors in application logic that produce incorrect results or unexpected side effects.

In contrast, questions about account limitations or service behavior are better suited for [GitHub Discussions](https://github.com/abraunegg/onedrive/discussions)  


This distinction is clearly outlined:  
- In the README: [Have a question?](https://github.com/abraunegg/onedrive?tab=readme-ov-file#have-a-question) and [Reporting an issue or bug](https://github.com/abraunegg/onedrive?tab=readme-ov-file#reporting-an-issue-or-bug) 
- When opening a new issue, which explicitly advises using Discussions for questions.

For this particular case, I recommend reviewing your OneDrive storage and resolving the quota issue with Microsoft. If you encounter a situation where the OneDrive Client is not behaving correctly outside of such account limitations, please feel free to submit a new issue, providing all relevant details.

Thank you for your understanding and cooperation!

**Closed by abraunegg** 2024-11-24 18:39 UTC
Labels: Bug

**Comment by theoware** [comment] 2024-11-24 19:34
Thank you for your answer. However, I think it is an issue with onedrive, since I don't have this issue with rclone or the web client and the OneDrive web client reports plenty of free storage.

Would it be possible, as a workaround, to disable the free space check?

**Comment by abraunegg** [comment] 2024-11-24 19:37
@theoware 
For clarity:

![image](https://github.com/user-attachments/assets/7df10ba4-c7ec-4bd4-9141-f06c21a1db49)


You have exceeded your Account Quota.

The OneDrive API uses this and prevents your upload - you have zero quota available to upload.

There is *nothing* to fix here.

**Comment by abraunegg** [comment] 2024-11-25 00:28
@theoware 
In addition to this, a change has been implemented to ensure the quota status is clearly displayed.

The messages that will be presented based on the API response to 'quota' are:

#### quota status = nearing
```
WARNING: Your Microsoft OneDrive storage is nearing capacity, with less than 10% of your available space remaining.
         Delete unneeded files or upgrade your storage plan now, as further uploads will not be possible once storage is exceeded
```
#### quota status = critical
```
WARNING: Your Microsoft OneDrive storage is critically low, with less than 1% of your available space remaining.
         Delete unneeded files or upgrade your storage plan now, as further uploads will not be possible once storage is exceeded
```
#### quota status = exceeded
```
******************************************************************************************************************************
CRITICAL: Your Microsoft OneDrive storage limit has been exceeded. You can no longer upload new content to Microsoft OneDrive.
******************************************************************************************************************************
```

This should help folk, like yourself, in the future manage available space online.

**Comment by theoware** [comment] 2024-11-26 18:53
Okay, thank you

**Comment by abraunegg** [comment] 2024-12-04 02:08
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
