### ISSUE TITLE
Issue with syncing OneDrive Business on Fedora 29: "HTTP 5xx Server Side Error"

### ISSUE THREAD

**Issue by mpursiai** [abraunegg/onedrive#445] opened 2019-03-31 14:52 UTC
### Bug Report Details ###
**Describe the bug**

- I got a new laptop and I installed the OneDrive client successfully. However, when I tried to syncronize it the first time it crashed giving the following error: "OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error". This appears only when I'm using my OneDrive Business account, my personal account appears to sync normally. Additionally the same Client version appears to work normally on my previous laptop with slightly different D language version (2.084.1) and Fedora distribution (28, instead of 29).

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
Fedora 29: Linux taivaankansi 5.0.4-200.fc29.x86_64 #1 SMP Mon Mar 25 02:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
gui is installed

*   OneDrive Account Type
Business

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
2.085.0

*   Application configuration: Output of `onedrive --display-config`
onedrive version                    = v2.3.1
Config path                         = /home/mpursiai/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/mpursiai/OneDrive-soton
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 60
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false

*   Curl Version: Output of `curl --version`
curl 7.61.1 (x86_64-redhat-linux-gnu)

**Complete Verbose Log Output**

```bash
onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/mpursiai/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/mpursiai/OneDrive-soton
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!6N1Mt659TEusd5RKylmza9702P55GblPqKvhABPZsZHDUbDSFm8MR4y7hgfkXWDK
Default Root ID: 01Y3WOZYF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5345220232807
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01Y3WOZYF6Y2GOVW7725BZO354PWSELRRZ
OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01Y3WOZYF6Y2GOVW7725BZO354PWSELRRZ
OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
```

**Comment by abraunegg** [comment] 2019-03-31 18:56
@mpursiai 
Please can you follow the directions here (https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support) to create a verbose debug log that includes the HTTPS communication debug

**Comment by abraunegg** [comment] 2019-03-31 20:13
@mpursiai 
Looking at the log files this is most certainly an API issue with OneDrive. It is best for you to open a ticket here: https://github.com/OneDrive/onedrive-api-docs/issues 

Use the following information in the ticket:
```
OneDrive HTTP Server Response: 200
* Connection #1 to host graph.microsoft.com left intact
OneDrive API Response: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives('b%216N1Mt659TEusd5RKylmza9702P55GblPqKvhABPZsZHDUbDSFm8MR4y7hgfkXWDK')\/items\/$entity","fileSystemInfo":{"createdDateTime":"2016-07-11T19:04:15Z","lastModifiedDateTime":"2019-03-29T13:01:56Z"},"folder":{"childCount":27},"id":"01Y3WOZYF6Y2GOVW7725BZO354PWSELRRZ","name":"root","parentReference":{"driveId":"b!6N1Mt659TEusd5RKylmza9702P55GblPqKvhABPZsZHDUbDSFm8MR4y7hgfkXWDK","driveType":"business"},"root":{}}
[DEBUG] Sync Folder Name: root
* Found bundle for host graph.microsoft.com: 0x1779690 [can pipeline]
* Re-using existing connection! (#1) with host graph.microsoft.com
* Connected to graph.microsoft.com (20.190.143.51) port 443 (#1)
> GET /v1.0/drives/b!6N1Mt659TEusd5RKylmza9702P55GblPqKvhABPZsZHDUbDSFm8MR4y7hgfkXWDK/items/01Y3WOZYF6Y2GOVW7725BZO354PWSELRRZ/delta?select=id,name,eTag,cTag,deleted,file,folder,root,fileSystemInfo,remoteItem,parentReference,size HTTP/1.1
Host: graph.microsoft.com
User-Agent: Phobos-std.net.curl/2.085 (libcurl/7.61.1)
Accept: */*

< HTTP/1.1 500 Internal Server Error
< Cache-Control: private
< Transfer-Encoding: chunked
< Content-Type: application/json
< request-id: 8101700f-2429-432e-b89d-de9298dad926
< client-request-id: 8101700f-2429-432e-b89d-de9298dad926
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_2","ADSiteName":"UKS"}}
< Duration: 398.7663
< Strict-Transport-Security: max-age=31536000
< Date: Sun, 31 Mar 2019 19:07:36 GMT
< 
OneDrive HTTP Server Response: 500
```

That will help the API team track down where the problem is on their end.

**Comment by abraunegg** [comment] 2019-03-31 20:14
@mpursiai 
Attempted to reproduce here using a Business account, zero issue syncing / uploading / downloading files, thus can only conclude that the issue is account related & related to the back end infrastructure where the account is being serviced from.

**Comment by helderdaniel** [comment] 2019-04-01 13:51
Hi.
I am having the same issue in the last few days.
Never before.
It is happening quite often and makes onedrive client end.

After a retry, sync resumes where it stopped, but after a while same error happens again.

30 march at 07:09 I installed onedrive version v2.2.5-62-gde0f360.
The first issue I have in the log is at 07:43.

With the previous version I have installed never happened.
I am not quite sure what was the previous version but I installed it  arroun 30 january 2019.
I use Linux and the onedrive folder is stored on a NTFS partition, but this should not be an issue, since with the previous version it never happen.

Below is a list of the error and what was happening before, taken from the log:

2019-Mar-30 07:43:50.2774023 [DEBUG] Sync Folder Name: root
2019-Mar-30 07:43:50.584347 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Mar-30 08:06:31.1230769 [DEBUG] Sync Folder Name: root
2019-Mar-30 08:06:31.4168913 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Mar-30 09:16:10.3032309 The parent for this path is in the local database - adding requested path (./Workbench/libgdx/Apps/MyFirstApp/app/build/intermediates/res/merged/debug/values-ca) to database
2019-Mar-30 09:16:30.4755358 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Mar-30 21:37:37.0363487 [DEBUG] Sync Folder Name: root
2019-Mar-30 21:37:37.4452537 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 10:47:48.7910296 [DEBUG] Sync Folder Name: root
2019-Apr-01 10:47:49.0183749 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 10:49:33.6495223 [DEBUG] Sync Folder Name: root
2019-Apr-01 10:49:33.9561553 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 12:54:55.192543 [DEBUG] Sync Folder Name: root
2019-Apr-01 12:54:55.5005929 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 12:56:08.0263232 [DEBUG] Checking file: ./Works/02-AvaliaçãoDocentes/2016-9/submissãoAddPaperPósPrazo03-20190401.png
2019-Apr-01 12:56:18.9553272 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 12:56:19.2633053 [DEBUG] Sync Folder Name: root
2019-Apr-01 12:56:19.9317918 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 12:57:58.2481876 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/IEEE - Author Digital Tool Box.URL
2019-Apr-01 12:58:08.7295577 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 12:58:09.1392105 [DEBUG] Sync Folder Name: root
2019-Apr-01 12:58:09.4085812 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:02:55.4193726 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/definition of homograph from Oxford Dictionaries Online_files/77744c356b45326b6561384144436c46_002.gif
2019-Apr-01 13:03:15.4837401 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:07:36.7430755 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/definition of homophone from Oxford Dictionaries Online.URL
2019-Apr-01 13:07:47.3278776 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:49:17.7902729 [DEBUG] Sync Folder Name: root
2019-Apr-01 13:49:18.7039757 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:51:06.9581928 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/definition of homophone from Oxford Dictionaries Online_files/cm.gif
2019-Apr-01 13:51:17.4297303 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:51:18.0007788 [DEBUG] Sync Folder Name: root
2019-Apr-01 13:51:18.9228542 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:52:47.6779351 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/definition of homophone from Oxford Dictionaries Online_files/H4sIAAAAAAAAAIWMsQ3CMBBFr4BFELXPRoqUDZjjMBdhySFW002fiGSndiAm.css
2019-Apr-01 13:52:58.1511497 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:52:58.4635726 [DEBUG] Sync Folder Name: root
2019-Apr-01 13:52:58.9023584 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 13:55:13.2977328 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/definition of homophone from Oxford Dictionaries Online_files/soundmanager2.swf
2019-Apr-01 13:55:23.8028996 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:00:00.7279464 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:00:01.7885465 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:03:58.1717724 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/Notes on homographs and homophones/Homograph - Wikipedia, the free encyclopedia_files/load_002.php
2019-Apr-01 14:04:08.5682789 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:04:09.0805634 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:04:09.8305277 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:07:36.5807835 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/PaperV1.0/paperHomographs-v10.doc
2019-Apr-01 14:07:47.0104572 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:07:47.3053896 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:07:52.5208268 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:10:40.3695689 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/PaperV1.0/paperHomographs-v16-notes-hdaniel.doc
2019-Apr-01 14:10:51.139267 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:13:26.5508745 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:13:29.9298295 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:15:09.0937719 [DEBUG] Checking file: ./Works/I&D/02-Formação/03-Doutoramentos/Orientações/Amir/papers/MachineTranslation/PaperV1.0/PaperHomographs-v2.0.doc
2019-Apr-01 14:15:19.908229 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:15:20.2156055 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:15:20.455438 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:21:55.4013485 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:21:56.3020399 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:21:56.7114138 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error
--
2019-Apr-01 14:25:07.5925819 [DEBUG] Sync Folder Name: root
2019-Apr-01 14:25:08.1993146 OneDrive returned a 'HTTP 5xx Server Side Error' - gracefully handling error

**Comment by abraunegg** [comment] 2019-04-01 17:05
@helderdaniel 
Please can you follow the directions here (https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support) to create a verbose debug log that includes the HTTPS communication debug

The client cannot be responsible for server side errors - which is a Microsoft problem.

Also - your client version is *VERY* old, given v2.3.1 was released and v2.3.2 is pending.

**Comment by abraunegg** [comment] 2019-04-01 17:10
@helderdaniel 
Please can you get me the applicable logs ASAP

**Comment by abraunegg** [comment] 2019-04-01 17:10
@mpursiai @helderdaniel 
I have opened the following case with the API team: https://github.com/OneDrive/onedrive-api-docs/issues/1035

**Comment by helderdaniel** [comment] 2019-04-01 18:43
@abraunegg 

> Please can you follow the directions here (https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support) to create a verbose debug log that includes the HTTPS communication debug

Meanwhile I was checking if a resync solve the issue.
I stop it, to get the https logs (I wasn't aware of that kind of logs), and restarted the client, but since the local database was clean earlier, now it will have to be reconstructed.
This will take quite a while since I have around 45 GB on onedrive and more than a hundred thousands of files and folders.

As soon as it ends I will send the logs.
 
> The client cannot be responsible for server side errors - which is a Microsoft problem.

Yes, probably it is a MS server or API problem. Some thing that changed meanwhile.
(Unless it is a malformed request by the client, or some change at the API level made recently by MS that invalidates some request formats, and the Microsoft server is responding wrongly saying it's an Internal error.)

> I have opened the following case with the API team: OneDrive/onedrive-api-docs#1035

Thanks

> Also - your client version is _VERY_ old, given v2.3.1 was released and v2.3.2 is pending.

Yes.
I just realised that now that you mentioned.
I updated the client source and reinstall it on march 30th but I must have done something wrong and reinstalled an old version.

Today I installed the latest (at the time)
onedrive v2.3.1-19-g770456f

**Comment by abraunegg** [comment] 2019-04-01 18:47
@helderdaniel 
Please do not use the v2.3.1 versions - please use v2.3.2 which was just released

**Comment by helderdaniel** [comment] 2019-04-01 19:08
ok I installed 

v2.3.2   f93ed00

and running the https logs with this one

**Comment by helderdaniel** [comment] 2019-04-01 20:44
@abraunegg 

During resync the error did not happened.

After resyncing I did some more tests and could not reproduce the issue.
(I noticed that the sync operation seems faster with this last versions of onedrive than with the old version that I was using)

Since I do not have https logs when the error happens I cannot send you any more info.

Do you think some inconsistency in the local database can be the source of this issue?

**Comment by abraunegg** [comment] 2019-04-01 21:04
@mpursiai @helderdaniel
Microsoft advise they found an issue and have resolved it. Can you confirm please.

**Comment by helderdaniel** [comment] 2019-04-01 21:26
Well as I said before, after resyncing the issue does not happen.

but, ... since MS says it have solved the issue, that may explain why I do not get the error again.

I can confirm that I did about 5 or so syncs after that and I the issue seems solved

**Comment by abraunegg** [comment] 2019-04-01 21:29
Thanks - just wanted to be sure

**Comment by helderdaniel** [comment] 2019-04-01 21:31
@abraunegg 
Thank you for all the help

**Comment by mpursiai** [comment] 2019-04-01 21:32
@abraunegg 

I just attempted to synchronize again and it seems to to be working. I'm not getting the error and both download and upload are working!

Thank you very much for the help!

**Comment by abraunegg** [comment] 2019-04-01 21:32
Closing isse as Microsoft have resolved the issue

**Closed by abraunegg** 2019-04-01 21:32 UTC
Labels: Fixed, Not a bug, OneDrive Business, Unable to reproduce

**Comment by helderdaniel** [comment] 2019-04-02 12:20
Hi,

this issue just happened again.

Ialso posted to the API team:
https://github.com/OneDrive/onedrive-api-docs/issues/1035

Attached is the https log:
[debug_output0.log](https://github.com/abraunegg/onedrive/files/3033834/debug_output0.log)

**Comment by helderdaniel** [comment] 2019-04-02 13:07
Hi,

this issue just happened again.

I also posted to the API team:
https://github.com/OneDrive/onedrive-api-docs/issues/1035

Attached is the https log:
[debug_output.log](https://github.com/abraunegg/onedrive/files/3034019/debug_output.log)

**Comment by abraunegg** [comment] 2019-04-02 19:24
@helderdaniel 
Looks like intermittent network issues inside Microsoft ... 

Also - it would be worth editing all your posts where you have posted log details on the API docs github to start and end with 3 x ` characters - this way all the log details will be formatted and displayed correctly = easier to read

**Comment by helderdaniel** [comment] 2019-04-02 19:47
@abraunegg 
Yeah, probably

The client has been synchronising for about 3 hours. No issues.

I edited the logs.
thanks I was wondering how they could be better formatted.
Well, ... I guess I could have looked up on the log above.

**Comment by abraunegg** [comment] 2019-04-02 19:55
@helderdaniel 
No problem - it certainly sounds like it was a intermittent issue inside Microsoft's network

**Comment by helderdaniel** [comment] 2019-04-02 20:04
Yeah, probably
I am wondering ... the windows onedrive client probably will keep trying until it succeeds, so the error isn't noticed.
I did noticed because I was trying a one time sync: 
```
onedrive --synchronize
```
But if the onedrive client is ran in monitor mode,:
```
onedrive --monitor
```
it will fail on this error and abort or it keeps retrying until succeed?

Thank for the tip on formatting the logs

**Comment by helderdaniel** [comment] 2019-04-02 20:05
@abraunegg 
I am wondering ... the windows onedrive client probably will keep trying until it succeeds, so the error isn't noticed.
I did noticed because I was trying a one time sync: 
```
onedrive --synchronize
```
But if the onedrive client is ran in monitor mode,:
```
onedrive --monitor
```
it will fail on this error and abort or it keeps retrying until succeed?

**Comment by abraunegg** [comment] 2019-04-02 20:13
@helderdaniel 
`onedrive --synchronize` is best suited for a 1 time sync, or when using --dry-run to validate 'what' will happen, or use in a script where you are checking the return code of the application (success|failure) to take further action (email log, error, retry, trigger SNMP .........)

`onedrive --monitor` is best suited for 'service files' - init.d / systemd operations so that in the event of an error, the service restarts and try's to get the sync to continue.

Running `onedrive --monitor` from the CLI manually can be done - it just means that it will only retry 3 times before failing (not running as a service), and when you close the SSH session, terminal window or whatever - the application will stop syncing

**Comment by helderdaniel** [comment] 2019-04-03 06:23
Ok,

Thanks
