### ISSUE TITLE
Bug: Libphobos always breaks

### ISSUE THREAD

**Issue by enipklacus** [abraunegg/onedrive#2483] opened 2023-09-09 04:44 UTC
### Describe the bug

Built from LDC with YAY | Arch Linux Rolling 6.4.12-arch
After updating my OS the software doesn't help. this has been happening for a while with me now (last 4 updates).
Don't ask me how I got it to work until now.
---
(re)Installing ldc and libphobos doesn't seem to work. Purging does not work. Files are present in system but, apparently, software does not recognize them.

### Operating System Details

```shell
Linux HunterRevenge 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

LATEST | BUG BLOCKS ME FROM SEEING IT.

### What is your OneDrive Application Configuration

```shell
standard. BUG BLOCKS ME FROM SEEING IT.
```

### What is your 'curl' version

```shell
standard. BUG BLOCKS ME FROM SEEING IT.
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
standard (~/OneDrive). BUG BLOCKS ME FROM SEEING IT.
```

### What are all your local file system partition types

```shell
NAME   FSTYPE FSVER LABEL    UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sda                                                                              
├─sda1 vfat   FAT32 ESP      86AA-22BB                             412,7M    17% /boot/efi
├─sda2 vfat   FAT32 DIAGS    94E3-D82A                                           
├─sda3 ext4   1.0   Shared   c17c7dd3-a159-4ae9-b96c-7a5b3acaa024  869,2M    94% /home/lucas/Shared
├─sda4 swap   1              418a8671-939c-47fc-973a-b80221d6bdd7                [SWAP]
├─sda5 ext4   1.0            02abb475-8f1b-44c2-a392-e8179fb29280  106,9G    67% /
└─sda6 ext4   1.0   OneDrive 3f7a8c95-81fd-4067-a179-dd21991ae682   62,6G    76% /home/lucas/OneDrive
sdb                                                                              
├─sdb1 vfat   FAT32          F340-D5C1                                           
├─sdb2 ntfs                  602A152B2A14FFA8                                    
└─sdb3 ext4   1.0            8f8b50cf-6702-44cd-8b45-3853caecbdc7              
IT AIN'T MY PARTITIONS.
```

### How do you use 'onedrive'

monitor throughout days. i'm starting to regreat to update this software, bruh. every single time.

### Steps to reproduce the behaviour

I don't know. All dependencies are met and YAY doesn't suck.

### Complete Verbose Log Output

```shell
yeah, it gives me libphobos2-ldc-shared.so.
```

**Comment by abraunegg** [comment] 2023-09-09 04:50
@enipklacus 
You have a packaging issue / packaging bug.

I have zero control over packaging.

As you are using yay | arch linux you are best asking your queation here:
https://aur.archlinux.org/packages/onedrive-abraunegg

Closing this issue as:
* not a bug
* packaging issue

**Closed by abraunegg** 2023-09-09 04:50 UTC
Labels: Bug

**Comment by abraunegg** [comment] 2023-09-17 01:30
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
