### ISSUE TITLE
Can't get notifications when running OneDrive client as a service non-root user via systemd in Ubuntu 18.04

### ISSUE THREAD

**Issue by pablobass** [abraunegg/onedrive#727] opened 2019-11-18 06:19 UTC
Can't get notifications when running OneDrive client as a service non-root user via systemd even when compiling with --enable-notifications option.

onedrive v2.3.11-3-g0445ae0
dmd-2.089.0
libnotify-dev installed

OS: Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
Ubuntu 18.04.3 LTS using default GUI
OneDrive Account Type: Personal
DMD64 D Compiler v2.089.0
Application configuration: 
```
onedrive version                    = v2.3.11-3-g0445ae0
Config path                         = /home/user/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/user/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = *.tmp|*.crdownload
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 15
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

debug log sent to support@mynas.com.au

Thanks.

**Comment by abraunegg** [comment] 2019-11-18 06:30
@pablobass 
Received the debug log file, zero issue.

Please can you review the following issue as well - as this may be your problem: https://github.com/abraunegg/onedrive/issues/718

**Comment by pablobass** [comment] 2019-11-18 07:39
Thanks abraunegg.

I checked installation of notifications-daemon package after reviewing issue #718 and it's installed on my system.

Package: notification-daemon                     
Version: 3.20.0-3
State: installed

Then follow indications in #509 and started using the user level targeted service with command "systemctl --user start onedrive" and notifications start working, but now stop logging,,, (already change permissions to 777 to folder and log files to test)

**Comment by abraunegg** [comment] 2019-11-18 07:43
@pablobass 
OK - please can you provide the following:

1. The exact command you used when you enabled the service at the start
2. The exact command you used when you enabled the service and the notifications are now working

**Comment by pablobass** [comment] 2019-11-18 07:46
> @pablobass
> OK - please can you provide the following:
> 
> 1. The exact command you used when you enabled the service at the start
> 2. The exact command you used when you enabled the service and the notifications are now working

1- systemctl start onedrive@user.service
2- systemctl --user start onedrive

Please check the log line I added in my previous comment.

**Comment by abraunegg** [comment] 2019-11-18 07:59
@pablobass 
OK - thanks.

`systemctl start onedrive@user.service`

This starts `onedrive` as your userid - with your permissions to access files.

`systemctl --user start onedrive`
This starts `onedrive` as 'root' - with 'root' to access files. Any file downloaded will be as 'root', so if you are not intending to log into your system as root / use files as root - dont use this.

> already change permissions to 777 to folder and log files to test

Dont do this - you will screw up your permissions - set things back to what they should be for your user.

> `2019-Nov-18 04:41:03.8732522 Notification (dbus) server not available, disabling`

OK - this is the key piece of information. This means either:

1. The service has not started / enabled when you login via the GUI or whatever
2. The service has not started before the onedrive service
3. OneDrive (when running as your user) does not have the permission to write to the dbus system

Unfortunately, this is all a local system issue that you need to fix / look at - this is not a bug with this client.

The workaround, as suggested of installing `notification-daemon` you have already tried - so this is certainly a user access permission issue on your local system.

See what 'group' dbus is running with, and maybe add your user id to that group.

**Comment by pablobass** [comment] 2019-11-18 15:14
> @pablobass
> OK - thanks.
> 
> `systemctl start onedrive@user.service`
> 
> This starts `onedrive` as your userid - with your permissions to access files.
> 
> `systemctl --user start onedrive`
> 
> This starts `onedrive` as 'root' - with 'root' to access files. Any file downloaded will be as 'root', so if you are not intending to log into your system as root / use files as root - dont use this.
> 
> > already change permissions to 777 to folder and log files to test
> 
> Dont do this - you will screw up your permissions - set things back to what they should be for your user.

Thanks, already revert this. Only changed permissions in onedrive log directory for the sake of this test.

> > `2019-Nov-18 04:41:03.8732522 Notification (dbus) server not available, disabling`
> 
> OK - this is the key piece of information. This means either:
> 
> 1. The service has not started / enabled when you login via the GUI or whatever
> 2. The service has not started before the onedrive service
> 3. OneDrive (when running as your user) does not have the permission to write to the dbus system
> 
> Unfortunately, this is all a local system issue that you need to fix / look at - this is not a bug with this client.
> 
> The workaround, as suggested of installing `notification-daemon` you have already tried - so this is certainly a user access permission issue on your local system.
> 
> See what 'group' dbus is running with, and maybe add your user id to that group.

Tried that and It doesn't seem to work, unless the workaround is adding my user to the 'root' group, and it's not something I want to do for obvious security reasons.

I look at the output of 'ps aux | grep -i dbus' and added my user to group 'gdm' and 'messagebus' (the only ones that 'ps' shows dbus running at that is not 'root' one) and problem persist, even after system restart.

I execute 'systemctl restart onedrive@user.service' so also timing is not an issue.

Then I look at 'syslog' and find this 'dbus' entries for other daemons with working notifications (some examples):

`Nov 18 11:27:01 UserPC dbus-daemon[2191]: [session uid=1000 pid=2191] Activating via systemd: service name='org.gnome.evolution.dataserver.Calendar7' unit='evolution-calendar-factory.service' requested by ':1.28' (uid=1000 pid=2347 comm="/usr/lib/gnome-shell/gnome-shell-calendar-server " label="unconfined")
Nov 18 11:27:01 UserPC dbus-daemon[2191]: [session uid=1000 pid=2191] Successfully activated service 'org.gnome.evolution.dataserver.Calendar7'
Nov 18 11:28:00 UserPC dbus-daemon[1342]: [system] Activating via systemd: service name='org.freedesktop.fwupd' unit='fwupd.service' requested by ':1.179' (uid=1000 pid=2721 comm="/usr/bin/gnome-software --gapplication-service " label="unconfined")
Nov 18 11:28:01 UserPC dbus-daemon[1342]: [system] Successfully activated service 'org.freedesktop.fwupd'
Nov 18 12:06:27 UserPC dbus-daemon[1342]: [system] Activating via systemd: service name='org.bluez' unit='dbus-org.bluez.service' requested by ':1.192' (uid=1000 pid=5380 comm="/opt/google/chrome/chrome     " label="unconfined")
`

and also find the onedrive error in there:
 
`Nov 18 11:26:46 UserPC onedrive[1855]: Notification (dbus) server not available, disabling`

I do some google research and can't get it to work, but I think maybe it has something to do with this:

https://askubuntu.com/questions/1120023/how-to-use-systemd-notify

**Comment by abraunegg** [comment] 2019-11-18 22:39
@pablobass 
After doing some extensive testing this morning, I was able to get the following to work:

1. Disable any `onedive@` service files - eg: 
```
systemctl stop onedrive@alex.service; 
systemctl disable onedrive@alex.service;
```

2. Login via graphical UI as user
3. Enable service as per the following:
```
systemctl --user enable onedrive
systemctl --user start onedrive
```

When debugging this, step 3 above returns the following in systemd logs:
```
Nov 19 09:31:23 arch-gui-testbox onedrive[3986]: dbus init status: true
Nov 19 09:31:23 arch-gui-testbox onedrive[3986]: dbus app name: 555D2D25E2C0
Nov 19 09:31:23 arch-gui-testbox onedrive[3986]: dbus server info: true
Nov 19 09:31:26 arch-gui-testbox onedrive[3986]: Initializing the Synchronization Engine ...
Nov 19 09:31:26 arch-gui-testbox onedrive[3986]: Initializing monitor ...
Nov 19 09:31:26 arch-gui-testbox onedrive[3986]: OneDrive monitor interval (seconds): 45
Nov 19 09:35:16 arch-gui-testbox onedrive[3986]: Syncing changes from OneDrive ...
```
Notifications are received when logged in via the gui


When using the @ service files, this fails with the following:
```
Nov 19 08:41:38 arch-gui-testbox onedrive[3830]: dbus init status: true
Nov 19 08:41:38 arch-gui-testbox onedrive[3830]: dbus app name: 5600433D12C0
Nov 19 08:41:38 arch-gui-testbox onedrive[3830]: dbus server info: false
Nov 19 08:41:38 arch-gui-testbox onedrive[3830]: Notification (dbus) server not available, disabling
Nov 19 08:41:41 arch-gui-testbox onedrive[3830]: Initializing the Synchronization Engine ...
Nov 19 08:41:41 arch-gui-testbox onedrive[3830]: Initializing monitor ...
Nov 19 08:41:41 arch-gui-testbox onedrive[3830]: OneDrive monitor interval (seconds): 45
```

Please can you confirm the above in your system as well.

**Comment by abraunegg** [comment] 2019-11-19 19:33
@pablobass 
Any response to this from your side?

**Comment by abraunegg** [comment] 2019-11-20 20:05
PR to update documentation to clarify what systemd script to use in what scenario

**Comment by abraunegg** [comment] 2019-11-20 20:05
@pablobass 
Any update from your side ?

**Comment by abraunegg** [comment] 2019-11-21 08:11
Closing issue as PR #728 merged into master

**Closed by abraunegg** 2019-11-21 08:11 UTC
Labels: Documentation, Local Environment Issue, Not a bug

**Comment by pablobass** [comment] 2019-11-24 18:36
> @pablobass
> Please can you confirm the above in your system as well.

Sorry I can't reply these days. I was very busy and can't replay or make any more tests.

These method doesn't work for me either.

I disabled `onedive@` service like you said with:
> ```
> systemctl stop onedrive@myuser.service; 
> systemctl disable onedrive@myuser.service;
> ```

Then restarted and re-enabled with:

> ```
> systemctl --user enable onedrive
> systemctl --user start onedrive
> ```

Still no notifications and now onedrive stop logging in /var/log/onedrive even if I set permissions 0777 to this directory for test purposes (without making any config file changes: config files are stored in ~/myuser/.config/onedrive). 

This is weird, because in a previous test commented a few messages above, with this set of commands, notifications start working (only logging stopped). 

Anyway, in this last test, systemd logs returns the following:

> ```
> Nov 24 15:04:16 UserPC systemd[2193]: Started OneDrive Free Client.
>  Nov 24 15:04:16 UserPC onedrive[3221]: Notification (dbus) server not available, disabling
> Nov 24 15:04:19 UserPC onedrive[3221]: Initializing the Synchronization Engine ...
> Nov 24 15:04:19 UserPC onedrive[3221]: Initializing monitor ...
> Nov 24 15:04:19 UserPC onedrive[3221]: OneDrive monitor interval (seconds): 15
> ```

Then reverted changes back to `onedive@` service with:

> ```
> systemctl --user stop onedrive
> systemctl --user disable onedrive
> systemctl enable onedrive@pebas.service
> systemctl start onedrive@pebas.service
> ```

and system logs shows:

`Nov 24 15:06:46 UserPC systemd[1]: Created slice system-onedrive.slice.
Nov 24 15:06:46 UserPC systemd[1]: Started OneDrive Free Client for pebas.
Nov 24 15:06:46 UserPC onedrive[4068]: Notification (dbus) server not available, disabling
Nov 24 15:06:49 UserPC onedrive[4068]: Initializing the Synchronization Engine ...
Nov 24 15:06:49 UserPC onedrive[4068]: Initializing monitor ...
Nov 24 15:06:49 UserPC onedrive[4068]: OneDrive monitor interval (seconds): 15
`
Now, with same systemd config that I started: no logs and no notifications. 
Didn't make any other system modifications in between tests. Not even open the web browser.

I'm astonished with the latest.

**Comment by abraunegg** [comment] 2019-11-24 20:09
@pablobass 
Let's tackle this in 2 parts.
### System Notifications on Ubuntu ###
1. Build & install client and ensure that you *enable* notifications
```
alex@alex-virtual-machine:~/code/onedrive$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
alex@alex-virtual-machine:~/code/onedrive$ 
```
```
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ ./configure --enable-notifications; make clean; make;
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.085.0
checking for curl... yes
checking for sqlite... yes
checking for notify... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.3.12-dev > version ; \
fi
dmd  -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ sudo make install
/usr/bin/install -c -D onedrive /usr/local/bin/onedrive
/usr/bin/install -c -D onedrive.1 /usr/local/share/man/man1/onedrive.1
/usr/bin/install -c -D -m 644 contrib/logrotate/onedrive.logrotate /usr/local/etc/logrotate.d/onedrive
mkdir -p /usr/local/share/doc/onedrive
/usr/bin/install -c -D -m 644 README.md config LICENSE CHANGELOG.md docs/Docker.md docs/INSTALL.md docs/Office365.md docs/USAGE.md /usr/local/share/doc/onedrive
/usr/bin/install -c -d -m 0755 /usr/lib/systemd/user /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive@.service /lib/systemd/system
/usr/bin/install -c -m 0644 contrib/systemd/onedrive.service /usr/lib/systemd/user
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
```
2. Login via your GUI and disable & enable the right service

![service_with_notifications](https://user-images.githubusercontent.com/4956234/69500490-b0b97a80-0f4f-11ea-93b1-7ac644df1a0f.jpg)

As you can see from the graphic - system notifications are enabled and working.

### Logging in /var/log/onedrive ###
Logging to a file is enabled 2 ways:
1. Pass `--enable-logging` into the application at runtime
2. Modify your config file `~/.config/onedrive/config` to enable logging for your specific config.

As your using systemd, the easiest 'user controlled' method here is to modify the user config file

1. Determine if you have an existing config file:
```
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ ls -la ~/.config/onedrive/config
ls: cannot access '/home/alex/.config/onedrive/config': No such file or directory
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 
```
If not, copy one over:
```
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ cp config ~/.config/onedrive/
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ 

```
2. Edit this config file so that `enable_logging` is true:
```
# Configuration for OneDrive Linux Client
# This file contains the list of supported configuration fields
# with their default values.
# All values need to be enclosed in quotes
# When changing a config option below, remove the '#' from the start of the line
# For explanations of all config options below see docs/USAGE.md or the man page.
#
# sync_dir = "~/OneDrive"
# skip_file = "~*|.~*|*.tmp"
# monitor_interval = "45"
# skip_dir = ""
# log_dir = "/var/log/onedrive/"
# drive_id = ""
# upload_only = "false"
# check_nomount = "false"
# check_nosync = "false"
# download_only = "false"
# disable_notifications = "false"
# disable_upload_validation = "false"
enable_logging = "true"
# force_http_11 = "false"
# force_http_2 = "false"
# local_first = "false"
# no_remote_delete = "false"
# skip_symlinks = "false"
# debug_https = "false"
# skip_dotfiles = "false"
# dry_run = "false"
# min_notify_changes = "5"
# monitor_log_frequency = "5"
# monitor_fullscan_frequency = "10"
# sync_root_files = "false"
# user_agent = ""
```

3. Stop your running systemd service
4. Test your new configuration
```
onedrive --synchronize --verbose 
Using Config Dir: /home/alex/.config/onedrive
Using logfile dir: /var/log/onedrive/             <--- Log directory called out
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Application version: v2.3.11-9-g4fcab8f
```

5. Depending on user permissions to /var/log/onedrive/ the log will now be in 2 places - user home directory or /var/log/onedrive/. On my system, I had NOT set the permissions, so it defaults to the user home directory.
```
(dmd-2.085.0)alex@alex-virtual-machine:~/code/onedrive$ cat ~/onedrive.log | more
2019-Nov-25 07:02:09.6695656 Initializing the OneDrive API ...
2019-Nov-25 07:02:09.8925257 Opening the item database ...
2019-Nov-25 07:02:09.8937443 All operations will be performed in: /home/alex/OneDrive
2019-Nov-25 07:02:12.1157327 Application version: v2.3.11-9-g4fcab8f
2019-Nov-25 07:02:12.1163523 Account Type: personal
2019-Nov-25 07:02:12.1165159 Default Drive ID: 66d53be8a5056eca
2019-Nov-25 07:02:12.1166343 Default Root ID: 66D53BE8A5056ECA!101
2019-Nov-25 07:02:12.1167884 Remaining Free Space: 5345924817
2019-Nov-25 07:02:12.1169111 Fetching details for OneDrive Root
2019-Nov-25 07:02:12.3404511 OneDrive Root exists in the database
2019-Nov-25 07:02:12.3406863 Initializing the Synchronization Engine ...
2019-Nov-25 07:02:12.3408249 Syncing changes from OneDrive ...
2019-Nov-25 07:02:12.3409398 Applying changes of Path ID: 66D53BE8A5056ECA!101
2019-Nov-25 07:02:13.2748164 Uploading differences of .
2019-Nov-25 07:02:13.2751715 Processing root
2019-Nov-25 07:02:13.2756368 The directory has not changed
2019-Nov-25 07:02:13.2759336 Processing Pictures
2019-Nov-25 07:02:13.2764519 The directory has not changed
2019-Nov-25 07:02:13.2767635 Processing wC6Pf0zLoCubRNuuGTdTERfU4gf4qnWJ
2019-Nov-25 07:02:13.2773657 The directory has not changed
2019-Nov-25 07:02:13.2782804 Processing image0.png
2019-Nov-25 07:02:13.2788559 The file has not changed
2019-Nov-25 07:02:13.2790309 Processing image1.png
2019-Nov-25 07:02:13.2795264 The file has not changed
```

6. Re-enable systemd service - notifications and user logging should be enabled
![restart_user_services](https://user-images.githubusercontent.com/4956234/69500776-33433980-0f52-11ea-9f8f-c8e4c01deaa3.jpg)
```
(dmd-2.085.0)alex@alex-virtual-machine:~$ tail -f onedrive.log 
2019-Nov-25 07:02:52.8961352 The file has not changed
2019-Nov-25 07:02:52.8962966 Processing image2.png
2019-Nov-25 07:02:52.8968559 The file has not changed
2019-Nov-25 07:02:52.8970134 Processing image23.png
2019-Nov-25 07:02:52.8975388 The file has not changed
2019-Nov-25 07:02:52.897713 Uploading new items of .
2019-Nov-25 07:02:52.935651 Applying changes of Path ID: 66D53BE8A5056ECA!101
2019-Nov-25 07:05:59.1825835 Initializing the Synchronization Engine ...
2019-Nov-25 07:05:59.2283019 Initializing monitor ...
2019-Nov-25 07:05:59.2284585 OneDrive monitor interval (seconds): 45
```

### Conclusion ###
Please check your configuration and your steps - this is all a local environment (your Linux system) issue, and not an issue with this client.

**Comment by pablobass** [comment] 2019-11-24 20:28
> @pablobass
> Let's tackle this in 2 parts.
> 

@abraunegg 
Thanks for taking the time to test and response with such dedication and detailed tutorial.

I was about to update my previous post to tell you that notifications started working after a second restart (¿?) with method `OneDrive service running as root user via systemd` 


> systemctl --user enable onedrive
> systemctl --user start onedrive

That's a go.

Then, after reading your last post, re-check my config file and change the line:

> #enable_logging = "false"

that was commented by default (and working! with method `OneDrive service running as a non-root user via systemd`) to:

> enable_logging = "true"

Don't know why logs work with that line commented in one method and not in the other, but now finally a have working notifications and logging in `/var/log/onedrive` with the correct permissions set.

Again, thank you very much for your help and I hope my feddback was useful to you and other users in any way also.

**Comment by pablobass** [comment] 2019-11-30 01:34
There's another thing to say about this problem that I don't think it's a local enviroment issue (and make some tests a way more clear). 

Notifications only works when you start and stop onedrive service once GUI was loaded. If I leave service configured in this way and restart the SO, then notifications doesn't work with same dbus error `Notification (dbus) server not available, disabling`. I think this is because service start before GUI does, and then I need to restart onedrive service once GUI is loaded to make notifcations work. 

I don't know if there's a way to start a dbus notificacation -before- any user start his session (cause SO doesn't know wich user is going to login) or onedrive service need to be configured to start, in some way, after user who has a onedrive client configured login in his GUI. 

Needles to say what will happen if a user (that's not my case in this box, but I think it's something to think about) has his home encrypted, making onedrive service impossible to read config files or store logs in this type of homes folders.

**Comment by abraunegg** [comment] 2019-12-01 20:19
@pablobass 
> There's another thing to say about this problem that I don't think it's a local enviroment issue

Given that the notifications "do work" and only stop when the system is rebooted / suspended or other, then this really falls into the following categories:
* systemd issue - not restarting services required when resuming / restarting
* operating system issue - not restarting services required in correct order when resuming / restarting

This is why this is a local environment issue - solving systemd or operating system is beyond the remit of this application.

If a tweak or an update to this applications systemd files is needed, then sure .. this will be fixed, but right now no fix needed (or at least to me it is not clear if it is even needed).
