### ISSUE TITLE
"Double deletion command"?

### ISSUE THREAD

**Issue by SRGOM** [abraunegg/onedrive#783] opened 2020-01-22 04:46 UTC
NOTE THIS IS 2.3.12 however, I do not, looking at the release notes, see much which addresses this. However please feel free to discard, I'm already using this for free... :)

### Bug Report Details ###
I accidentally deleted some files (actually `moved` multiple into same named file in OneDrive. 
`mv first blah`, `mv second blah`, and so on. I realized this and restored from one drive. I then turned off my computer before much could happen. Upon turning on the computer, OneDrive recycle bin showed those files and directories as deleted again. 

Steps I did- 
1) Delete multiple files to empty a directory and then delete that directory. Actual deletion commands: `mv first blah`, `mv second blah` `mv third blah` and so on. 
2) Wait a bit and realize mistake. 
3) Restore folder from OneDrive Web. Restoring the folder restored all the files too. Perhaps deletion took some time? (Maybe network speed?)
4) Verify presence in OneDrive Web in the right place
5) Turn off computer
7) Turn on computer
7) Check systemd logs. Doesn't look like it's redownloading
8) FORGOT TO CHECK WHATS UP WITH ONEDRIVE WEB. SORRY!
9) Restart service
10) It's still not redownloading
11) Go to onedrive web, see that the directory is in recycle bin
12) Restore the directory again and all the files are restored too.
13) Verify presence in OneDrive Web in the right place.  Restoring the folder restored all the files too. 

**Application and Operating System Details:**
*   Linux NixDesk 4.19.82 #1-NixOS SMP Wed Nov 6 12:06:31 UTC 2019 x86_64 GNU/Linux
*   Gui Installed
*   Personal
*   DMD version
```
$bin/dmd --version                                                           
DMD64 D Compiler v2.085.1

Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

```
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.12
Config path                         = /home/username/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/username/Library/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.9.0 nghttp2/1.39.2
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

 
**To Reproduce**

1) Delete multiple files to empty a directory and then delete that directory. Actual deletion commands: `mv first blah`, `mv second blah` `mv third blah` and so on. 
2) Wait a bit and realize mistake. 
3) Restore folder from OneDrive Web. 
4) Verify presence in OneDrive Web in the right place.  Restoring the folder restored all the files too. Perhaps deletion took some time? (Maybe network speed?)
5) Turn off computer
7) Turn on computer
7) Check systemd logs. Doesn't look like it's redownloading
8) FORGOT TO CHECK WHATS UP WITH ONEDRIVE WEB. SORRY!
9) Restart service
10) It's still not redownloading
11) Go to onedrive web, see that the directory is in recycle bin
12) Restore the directory again.
13) Verify presence in OneDrive Web in the right place.  Restoring the folder restored all the files too. 

 

**Complete Verbose Log Output**
I have emailed a log with `--monitor -verbose` flags. I know this isn't what you want but I'm scared to try to reproduce the problem. Perhaps if at a quick glance you cannot figure out the problem then I will try and reproduce. Email subject is sha256 of the file- 2aa758e8f082721e18b4125c01c491c6d6c7a7595f02b9185211a9f597926c88

Specifically one folder **`SkyDrive camera roll/Others`**. I do see a single delete instruction for this folder in the logs but not sure how it was deleted again. The files inside were **`WP_20140223_<NUMBER>.jpg`**

dd any other context about the problem here.

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by SRGOM** [comment] 2020-01-22 17:16
I was hoping that quick glance at logs would help you figure out but the fact of the matter is that I failed to reproduce this after multiple tries on an alternative OneDrive account. So closing.

**Comment by abraunegg** [comment] 2020-01-22 20:36
Apologies for the delay on this – day job & life got really hectic over the last 2 days. Looking at the log file you sent this morning.

**Comment by SRGOM** [comment] 2020-01-23 00:44
Oh please no! I should have tried to reproduce before I submitted. (I confess I was lazy but I was hoping that an experienced person could probably guess the error from code knowledge and logs much earlier, I apologize if it was rude).

Since you reopened this I am leaving this open but please feel free to close.

**Comment by abraunegg** [comment] 2020-01-23 20:04
@SRGOM 
Responded via email with info and some findings. Can you please have a look and get back to me.

**Comment by abraunegg** [comment] 2020-01-24 20:35
Provided analysis via email, closing issue as unable to reproduce

**Closed by abraunegg** 2020-01-24 20:35 UTC
Labels: Unable to reproduce

**Comment by SRGOM** [comment] 2020-01-27 07:52
Thank you for looking.
