### ISSUE TITLE
Bug: "Checking Application Version ..." too long time

### ISSUE THREAD

**Issue by GOTHz1** [abraunegg/onedrive#2371] opened 2023-04-06 13:10 UTC
### Describe the bug

After updating the new version, the `onedrive -- synchronize` operation takes a long time (without synchronizing any files, nearly 5 minutes). By executing `onedrive -- synchronize -- verbose`, it was found that there was a long wait after **Checking Application Version...**.This may be my network issue, but I can access [https://api.github.com/repos/abraunegg/onedrive/releases/latest](https://api.github.com/repos/abraunegg/onedrive/releases/latest).

### Operating System Details

```shell
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.23-1+np1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.23-1+np1
Config path                                  = /home/goth/.config/onedrive
Config file found in config path             = true
Config option 'sync_dir'                     = /media/goth/SamsungT5/onedrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
url 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
/media
```

### What are all your local file system partition types

```shell
NAME        FSTYPE   LABEL     UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0       squashfs                                                      0   100% /snap/canonical-livepatch/164
loop1       squashfs                                                      0   100% /snap/bare/5
loop2       squashfs                                                      0   100% /snap/canonical-livepatch/190
loop3       squashfs                                                      0   100% /snap/gnome-3-34-1804/77
loop4       squashfs                                                      0   100% /snap/core18/2721
loop5       squashfs                                                      0   100% /snap/core/14784
loop6       squashfs                                                      0   100% /snap/core20/1822
loop7       squashfs                                                      0   100% /snap/core/14946
loop8       squashfs                                                      0   100% /snap/core20/1852
loop9       squashfs                                                      0   100% /snap/core18/2697
loop10      squashfs                                                      0   100% /snap/gnome-3-34-1804/90
loop11      squashfs                                                      0   100% /snap/gnome-3-38-2004/119
loop12      squashfs                                                      0   100% /snap/gtk-common-themes/1534
loop13      squashfs                                                      0   100% /snap/snapd/18357
loop14      squashfs                                                      0   100% /snap/snapd/18596
loop15      squashfs                                                      0   100% /snap/spotify/63
loop16      squashfs                                                      0   100% /snap/spotify/60
loop17      squashfs                                                      0   100% /snap/gnome-3-28-1804/161
loop18      squashfs                                                      0   100% /snap/gnome-3-38-2004/137
loop19      squashfs                                                      0   100% /snap/gnome-3-28-1804/194
loop20      squashfs                                                      0   100% /snap/gtk-common-themes/1535
sda                                                                                
├─sda1      vfat               D886-D459                                           
└─sda2                                                                             

sdb                                                                                
├─sdb1      exfat    SamsungT5 F588-6159                              99.6G    73% /media/goth/SamsungT5
├─sdb2      vfat               94B5-85D0                               952M     1% /boot/efi
├─sdb3      swap               a0db0e15-f769-4e95-84e0-1adab057fb8a                [SWAP]
└─sdb4      ext4               be83939d-53fc-4dc8-9dd7-b03823265ae6   45.7G    44% /
nvme0n1                                                                            
├─nvme0n1p1 vfat               0009-8FFF                                           
└─nvme0n1p2
```

### How do you use 'onedrive'

android、windows、linux、ios

### Steps to reproduce the behaviour

`onedrive --synchronize --download-only --verbose  `

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /home/goth/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Checking Application Version ...
```

### Other Log Information or Details

```shell
debug_output.log:

[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/goth
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/goth/.config
[DEBUG] configDirName: Configuring application to use default config path
Using 'user' Config Dir: /home/goth/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
[DEBUG] refreshTokenFilePath = /home/goth/.config/onedrive/refresh_token
[DEBUG] deltaLinkFilePath = /home/goth/.config/onedrive/delta_link
[DEBUG] databaseFilePath = /home/goth/.config/onedrive/items.sqlite3
[DEBUG] databaseFilePathDryRun = /home/goth/.config/onedrive/items-dryrun.sqlite3
[DEBUG] uploadStateFilePath = /home/goth/.config/onedrive/resume_upload
[DEBUG] userConfigFilePath = /home/goth/.config/onedrive/config
[DEBUG] syncListFilePath = /home/goth/.config/onedrive/sync_list
[DEBUG] systemConfigFilePath = /etc/onedrive/config
[DEBUG] businessSharedFolderFilePath = /home/goth/.config/onedrive/business_shared_folders
Configuration file successfully loaded
[DEBUG] passed in options: ["onedrive", "--synchronize"]
[DEBUG] note --confdir and --verbose not listed in args
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /media/goth/SamsungT5/onedrive
[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
[DEBUG] Attempting to contact online service
[DEBUG] Shutting down HTTP engine as successfully reached OneDrive Online Service
Checking Application Version ...
[DEBUG] Unable to query GitHub for latest release
[DEBUG] Invalid JSON Object. Setting GitHub 'tag_name' release version to 0.0.0
[DEBUG] Invalid JSON Object. Setting GitHub 'published_at' date to 2018-07-18T18:00:00Z
[DEBUG] applicationVersion:       2.4.23
[DEBUG] latestVersion:            0.0.0
[DEBUG] publishedDate:            2018-Jul-18 18:00:00Z
[DEBUG] currentTime:              2023-Apr-06 11:38:02Z
[DEBUG] releaseGracePeriod:       2018-Aug-18 18:00:00Z
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
...
```

**Comment by abraunegg** [comment] 2023-04-06 20:18
@GOTHz1 
This is not a bug in the application.

You either have:
* Slow DNS
* Slow Internet
* Buggy firewall | Buggy local DNS resolution (you are running ~~Crapbuntu~~ Ubuntu so highly possible)

Specifically for the firewall issue, you may also be experiencing this issue due to a misbehaving DNS Servers and/or Firewall that will only give one reply to a parallel A and AAAA request. This is most prevalent when your system is using IPv4 and IPv6 network address spaces on your system.

This can be fixed by adding the following setting the following option in your `/etc/resolv.conf`:
```
options single-request
```

**Closed by abraunegg** 2023-04-06 20:18 UTC
Labels: Bug

**Comment by abraunegg** [comment] 2023-04-14 01:40
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
