### ISSUE TITLE
Bug:  (nit, UI) synchronization progress does not stop at 100%

### ISSUE THREAD

**Issue by radrow** [abraunegg/onedrive#2396] opened 2023-05-10 10:20 UTC
### Describe the bug

When I run `onedrive --synchronize`, the CLI progress bar for many files does not stop at 100%, but (I guess) the last progress status. This results in a slightly confusing log:

```
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230504_103700.jpg ... 
Downloading  90% |oooooooooooooooooooooooooooooooooooo    |   ETA   00:00:01    
done.
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230504_103442.jpg ... 
Downloading  90% |oooooooooooooooooooooooooooooooooooo    |   ETA   00:00:01    
done.
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230504_103224.jpg ... 
Downloading  95% |oooooooooooooooooooooooooooooooooooooo  |   ETA   00:00:00    
done.
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230503_180906.jpg ... 
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:00:01    
done.
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230503_180905.jpg ... 
Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01    
done.
Downloading file Bilder/Samsung-Katalog/DCIM/Camera/20230503_173225.jpg ... 
Downloading  95% |oooooooooooooooooooooooooooooooooooooo  |   ETA   00:00:01    
done.

``` 

It's mostly visual, but made me worried for a second that something got stuck. 

### Operating System Details

```shell
Linux fedora 6.2.14-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:57:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Gnome terminal, at any screen width. ZSH.
```

### Client Installation Method

From Distribution Package

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.23

### What is your OneDrive Application Configuration

```shell
shouldn't matter, default
```

### What is your 'curl' version

```shell
curl 7.85.0 (x86_64-redhat-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.8 zlib/1.2.12 libidn2/2.3.4 nghttp2/1.51.0
Release-Date: 2022-08-31
Protocols: file ftp ftps http https 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz SPNEGO SSL threadsafe UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
doesn't matter
```

### What are all your local file system partition types

```shell
doesn't matter
```

### How do you use 'onedrive'

`onedrive --synchronize`

### Steps to reproduce the behaviour

Synchronize a fresh drive to a fresh folder

### Complete Verbose Log Output

```shell
Even more:

Downloading file Bilder/Eigene Aufnahmen/20230418_145355_01.mp4 ... done.
Downloading file Bilder/Eigene Aufnahmen/20230419_115125.mp4 ... 
Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:14                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230428_140044.jpg ... 
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230411_171506.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230428_135403.jpg ... 
Downloading  65% |oooooooooooooooooooooooooo              |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/Screenshot_20230409-214021_Nova7.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230428_135343.jpg ... 
Downloading  90% |oooooooooooooooooooooooooooooooooooo    |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230408_160038.jpg ... 
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230428_135249.jpg ... 
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230407_225107.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230408_155703.jpg ... 
Downloading  90% |oooooooooooooooooooooooooooooooooooo    |   ETA   00:00:00                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230428_134445.jpg ... 
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:00:00                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/Screenshot_20230407-171550_Maps.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230407_222412.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230428_134440.jpg ... 
Downloading  95% |oooooooooooooooooooooooooooooooooooooo  |   ETA   00:00:00                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/Screenshot_20230407-113520_Firefox.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230406_114232.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230428_133924.jpg ... 
Downloading  80% |oooooooooooooooooooooooooooooooo        |   ETA   00:00:01                                                                                                                   
done.
Downloading file Bilder/Eigene Aufnahmen/20230405_151413.jpg ... done.
Downloading file Bilder/Eigene Aufnahmen/20230428_133834.jpg ... 
Downloading  90% |oooooooooooooooooooooooooooooooooooo    |   ETA   00:00:00 
```

**Comment by abraunegg** [comment] 2023-05-10 10:56
@radrow 
> the CLI progress bar for many files does not stop at 100%, but (I guess) the last progress status

Can you please check the actual application version you are running via `onedrive --version` as this sounds very much like this issue: https://github.com/abraunegg/onedrive/issues/2054

This was fixed in v2.4.21

As you are running Fedora - the *default* package for Fedora 37 is v2.4.20 - which would contain this bug.

If you are running the updated package fro Fedora 37, you *should* be running v2.4.23:

![image](https://github.com/abraunegg/onedrive/assets/4956234/b4f09218-e54a-4fd1-b1d4-1300a691d697)

Additionally, I am 100% unable to reproduce this issue, even on my own Fedora 37 system - so there is something very quirky by the looks of it.

If you *are* 100% running v2.4.23 - then please provide a verbose debug log following the correct support process: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Comment by radrow** [comment] 2023-05-10 11:10
![image](https://github.com/abraunegg/onedrive/assets/35342116/618b6662-07c5-4143-9dec-55e16285f850)

**Comment by radrow** [comment] 2023-05-10 11:13
I'll generate the log on my next sync

**Comment by radrow** [comment] 2023-05-10 12:29
Hm, just started an upload (with `--local-first`) and it does not reproduce anymore.

**Comment by abraunegg** [comment] 2023-05-10 19:28
@radrow 
> Hm, just started an upload (with `--local-first`) and it does not reproduce anymore.

OK .. bugs are generally not transient.

So - either you originally were running v2.4.20 on Fedora 37 (which has this bug) then upgraded to v2.4.23 (where the bug is fixed), or, you really have found a transient bug in compiled code.

As a result I am going to close this issue for the following reasons:
* Lack of a debug log for a bug as I am 100% unable to reproduce this
* Transient nature of your issue and that it was a known bug that was fixed

If you experience the issue again with v2.4.23  - then please provide a verbose debug log following the correct support process: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

**Closed by abraunegg** 2023-05-10 19:28 UTC
Labels: Bug, More Information Needed, Waiting on Response

**Comment by abraunegg** [comment] 2023-05-18 01:44
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
