### ISSUE TITLE
Monitoring stops after a while

### ISSUE THREAD

**Issue by HenriDeh** [abraunegg/onedrive#753] opened 2019-12-13 15:29 UTC
### Bug Report Details ###
When onedrive --monitor is running, it will eventually stop on its own. 

**Application and Operating System Details:**
*   OS: Linux Mint 19.2
*   OneDrive Account Type: enterprise (with 1To)
*   DMD64 D Compiler v2.089.0
*   Application configuration:
```
onedrive version                    = v2.3.11-3-g0445ae0
Config path                         = /home/dehaybe/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/dehaybe/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 5
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: curl 7.58.0

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run onedrive --monitor
2.  Wait a few hours

See in this screencap, I had to reenter the command because it stopped:
![image](https://user-images.githubusercontent.com/47037088/70811292-998ae180-1dc5-11ea-8dc9-2bccdc8cf9ac.png)

This also happens if it is running in background.

**Comment by abraunegg** [comment] 2019-12-13 19:18
@HenriDeh 
Please upgrade to the latest 'master' version and retest. You are running an old version (`v2.3.11-3-g0445ae0`)

**Comment by abraunegg** [comment] 2019-12-14 19:20
@HenriDeh 
Have you been able to re-test this with the current 'master' ?

**Comment by HenriDeh** [comment] 2019-12-14 19:24
Hi, no not yet, it’s on my work computer so it will have to wait for next week. I’ll come back to you after trying with the updated version. Thanks already.

**Comment by HenriDeh** [comment] 2019-12-16 09:41
I'm sorry I am fairly new to Linux, is there a command to update this package ? If I uninstall and install the latest version I will lose my configuration won't I?

**Comment by abraunegg** [comment] 2019-12-16 10:25
@HenriDeh 
You wont loose your existing configuration if your leave your config directory as is.

To install a new version, refer to https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#building-and-installing-the-onedrive-free-client

**Comment by abraunegg** [comment] 2019-12-17 21:56
@HenriDeh
Any update from your side? Have you been able to re-test this with the current 'master' ?

**Comment by HenriDeh** [comment] 2019-12-18 11:29
Hi, yes it has been running straight for 2 days now, I think we can say that it is solved.
Thank you for your dedication to this package.

**Comment by HenriDeh** [comment] 2019-12-18 16:56
Nevermind, it just stopped again. 

![image](https://user-images.githubusercontent.com/47037088/71106438-a9d4ff00-21bf-11ea-9f27-183f3f3d37b7.png)

I notice that it happened in both screenshots during a file synchronization.

**Comment by abraunegg** [comment] 2019-12-18 19:26
@HenriDeh 
OK - please follow these instructions to generate a HTTPS Debug Log:

https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by HenriDeh** [comment] 2019-12-19 09:33
It's ongoing, I'll mail the log when it stops again.

**Comment by HenriDeh** [comment] 2019-12-19 15:02
I sent the debug log

**Comment by abraunegg** [comment] 2019-12-19 18:53
@HenriDeh 
Thanks for the debug log - greatly appreciated.

OK - based on the log file, there is zero application issue. The upload is failing with the following:
```
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
* Connection died, retrying a fresh connect
* Closing connection 1
```
Refer to https://github.com/curl/curl/issues/4409 for more information.

Potentially something between you and OneDrive had a network outage - and that caused the application to stop. 

Unfortunately, as there is zero error response or exception which can be trapped for, I cannot trap for SSL issues that curl comes up against.

Suggestion would be to upgrade your Curl version so that it is less sensitive to SSL errors.

**Comment by abraunegg** [comment] 2019-12-19 21:04
@HenriDeh 
Adding further weight to a network environment issue, there is this sort of sequence in your log file:
```
OneDrive HTTP Server Response: 200
* Connection #1 to host graph.microsoft.com left intact
OneDrive API Response: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#Collection(driveItem)","@odata.deltaLink":"https:\/\/graph.microsoft.com\/v1.0\/drives\/b!RX5TzURRiU-pxVv0lTQvxG2SnQOSqZ9OnKZ_H2q4DNL5WupfP52gRKjqMw1dhN66\/items\/01A3MCZUN6Y2GOVW7725BZO354PWSELRRZ\/delta?select=id%2cname%2ceTag%2ccTag%2cdeleted%2cfile%2cfolder%2croot%2cfileSystemInfo%2cremoteItem%2cparentReference%2csize&token=MzslMjM0OyUyMzE7Mzs1ZmVhNWFmOS05ZDNmLTQ0YTAtYThlYS0zMzBkNWQ4NGRlYmE7NjM3MTIzNTk4MDk4NjAwMDAwOzMxNjE3Njc3MTslMjM7JTIzOyUyMzQ","value":[]}
[DEBUG] OneDrive Reported no delta changes - Local path and OneDrive in-sync
[DEBUG] syncListConfigured =         false
[DEBUG] fullScanRequired =           false
[DEBUG] syncListConfiguredOverride = true
Applying changes of Path ID: 01A3MCZUN6Y2GOVW7725BZO354PWSELRRZ
* Connection 19 seems to be dead!
* Closing connection 19
* Found bundle for host graph.microsoft.com: 0x561ef6151af0 [can pipeline]
* Re-using existing connection! (#1) with host graph.microsoft.com
* Connected to graph.microsoft.com (20.190.129.98) port 443 (#1)
```

This indicates to me potentially that there may be some sort of TCP connection timeout being enforced - and the device doing this is not honoring established / related connections as so not to close established & related network connections.

If this issue is only occurring at your workplace - you really need to speak to your IT folk.

**Comment by abraunegg** [comment] 2019-12-21 21:58
@HenriDeh 
Closing this issue as this is not a bug with this application

**Closed by abraunegg** 2019-12-21 21:58 UTC
Labels: Local Environment Issue, Not a bug

**Comment by HenriDeh** [comment] 2020-01-16 11:14
There is a workaround for those who would need it: simply use `'while true; do onedrive --monitor; end'`. To make it work as a startup application or with nohup, use `bash -c 'while true; do onedrive --monitor; end'`.
