### ISSUE TITLE
High CPU usage as service

### ISSUE THREAD

**Issue by rednag** [abraunegg/onedrive#347] opened 2019-01-16 13:05 UTC
### Bug Report Details ###
I've installed your fork of skilions onedrive, but it seems to be that the CPU usage of onedrive is always around 20% when it is syncing changes from OneDrive as a systemd service.

**Application and Operating System Details:**
*   OS: Linux CX 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux @ Ubuntu @ 18.04.1
*   GNOME
*   OneDrive Personal
*   DMD64 D Compiler v2.080.1
*   onedrive version                    = v2.2.4-23-g77b32b6
Config path                         = /home/CX/.config/onedrive
Config file found in config path    = true
Config option 'sync_dir'            = /media/CX/OneDrive
Config option 'skip_file'           = ~*
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
*   curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run onedrive as systemd service
2.  Added some new files
3.  Wait until CPU usage is at 25%

or 
1.  Run onedrive as systemd service
2.  Added some new files
3.  Disconnect WiFi/LAN 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```
Jan 16 20:13:34 CX onedrive[5455]: Syncing changes from OneDrive ...
Jan 16 20:18:10 CX onedrive[5455]: Uploading file ./Studium/Master/Data Mining/aufgaben.ipynb ... done.
Jan 16 20:18:59 CX onedrive[5455]: Syncing changes from OneDrive ...
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2019-01-16 18:44
@rednag 
Please can you provide system evidence and detailed verbose log that correlates with system evidence of high CPU. Please can you also update your issue tag with all the requested information as per the readme in terms of what else is required when posting an issue.

20% CPU whilst processing / analysing the system does not seem overly excessive given the issues around the 'skilion' version and high CPU issues.

**Comment by rednag** [comment] 2019-01-16 19:22
I'm running Ubuntu 18.04 on a surface 3 pro. Is journalctl --user-unit onedrive -f enough? At the moment I have 25% while syncing changes from OneDrive.

Version: onedrive v2.2.4-23-g77b32b6

**Comment by abraunegg** [comment] 2019-01-16 19:45
Please can you provide some system evidence here:
* `ps -AL |grep process_name`
* `strace -c -p <PID>`

**Example:**
```
[alex@centos7full ~]$ ps -AL | grep onedrive
16753 16753 pts/0    00:00:00 onedrive
[alex@centos7full ~]$ strace -c -p 16753
strace: Process 16753 attached
^Cstrace: Process 16753 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 20.98    0.000823          16        53           nanosleep
 17.31    0.000679         679         1           open
 17.23    0.000676         169         4           sendto
 13.61    0.000534         178         3           stat
 10.32    0.000405           4       102           fcntl
  8.56    0.000336           4        87           poll
  3.77    0.000148           4        38           write
  3.24    0.000127          32         4           fsync
  1.33    0.000052           2        23           lseek
  0.97    0.000038           2        16           recvfrom
  0.59    0.000023          12         2           close
  0.54    0.000021          21         1           unlink
  0.46    0.000018           9         2           read
  0.41    0.000016           8         2         1 access
  0.25    0.000010           3         4           fstat
  0.18    0.000007           7         1           restart_syscall
  0.10    0.000004           2         2           getdents
  0.10    0.000004           4         1           openat
  0.05    0.000002           1         4           lstat
------ ----------- ----------- --------- --------- ----------------
100.00    0.003923                   350         1 total
```

Let strace run for at least 15 / 20 minutes (or at least 1 full sync given your running in monitor mode)

**Comment by rednag** [comment] 2019-01-16 21:03
strace: Process 5455 attached
^Cstrace: Process 5455 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 83.42  143.484133           3  56613378           pread64
  5.46    9.393838          20    465691         5 stat
  5.45    9.379550           2   3886221           fcntl
  5.28    9.078327          24    376192         2 lstat
  0.17    0.298087          25     11970           openat
  0.09    0.153539           6     24530           getdents
  0.04    0.076923           6     13720           brk
  0.04    0.066927           6     11975           close
  0.03    0.056895           5     11972           fstat
  0.00    0.006620          29       232           nanosleep
  0.00    0.005006          10       484           poll
  0.00    0.001356           3       427        13 read
  0.00    0.000839           4       206           pwrite64
  0.00    0.000782          11        74         7 write
  0.00    0.000243          11        23           fdatasync
  0.00    0.000092          18         5         5 connect
  0.00    0.000077          15         5           getsockopt
  0.00    0.000052          26         2           readlink
  0.00    0.000052          52         1           restart_syscall
  0.00    0.000043           1        30           getpid
  0.00    0.000037           7         5           socket
  0.00    0.000035           7         5           getpeername
  0.00    0.000021          21         1           clone
  0.00    0.000015           3         5           getsockname
  0.00    0.000015           3         5           setsockopt
  0.00    0.000000           0         9           lseek
------ ----------- ----------- --------- --------- ----------------
100.00  172.003504              61417168        32 total

**Comment by abraunegg** [comment] 2019-01-16 21:14
@rednag 
Thanks - so it appears the system is spending a lot of time 'reading' something.

Can you please:
* Update your DMD version to the latest DMD (your building with DMD64 D Compiler v2.080.1) and retest
* When retesting, please rerun strace and provide output
* After strace, please rerun a sync but with `atop` running - you will potentially need to generate screenshots of the atop output. I am curious here as to the I/O performance of your disk on the MS Surface 3. What I am looking for is screenshots showing system activity when 'onedrive; is running to look at the disk I/O performance.

Lastly, to try and replicate this - can you please advise:

* Local disk file system type (EXT3, EXT4, BTRFS, ZFS, something else)
* File & folder structure on the local disk - how many files / folders are you trying to sync / check on OneDrive
* Size of files / total size

**Comment by abraunegg** [comment] 2019-01-16 21:18
@rednag 
Additionally:

Your 'OneDrive' sync directory is this: `/media/CX/OneDrive`

Is this a 'local' folder on your Surface device or is it a 'mount point' for an SD Card, NAS or something else?

Can you please provide the output of:

* `mount`

I want to rule out the "read" delay being caused by your OneDrive path being on an externally mounted system / file system.

**Comment by rednag** [comment] 2019-01-16 21:20
The onedrive in on a exFAT BDE (SDcard) drive, which means it is looped over dislocker. That could be the reason.

The onedrive is around 300GB - syncing files are around 0.1 - 5MB mostly.

**Comment by rednag** [comment] 2019-01-16 21:49
```
strace: Process 19296 attached
^Cstrace: Process 19296 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 86.31   77.333660           3  24348339           pread64
  4.50    4.033520          19    207133         1 stat
  4.48    4.011099           2   1677028           fcntl
  4.43    3.972074          23    174816         1 lstat
  0.14    0.123274          21      5980           openat
  0.07    0.061783           5     12265           getdents
  0.03    0.026430           4      5981           close
  0.03    0.023552           4      5980           fstat
  0.01    0.009717           4      2216           brk
  0.00    0.002043          23        90           nanosleep
  0.00    0.001388          10       133           poll
  0.00    0.000091           1        76         2 read
  0.00    0.000088           6        16           pwrite64
  0.00    0.000037           4         9         1 write
  0.00    0.000031          31         1           readlink
  0.00    0.000000           0         6           getpid
  0.00    0.000000           0         1           socket
  0.00    0.000000           0         1         1 connect
  0.00    0.000000           0         1           getsockname
  0.00    0.000000           0         1           getpeername
  0.00    0.000000           0         1           setsockopt
  0.00    0.000000           0         1           getsockopt
  0.00    0.000000           0         2           fdatasync
------ ----------- ----------- --------- --------- ----------------
100.00   89.598787              26440077         6 total
```

So, do you think it is BDE-drive?

**Comment by abraunegg** [comment] 2019-01-16 22:04
It will be the SD Card + how you are mounting the card in your Surface: 'means it is looped over dislocker'

Any encryption / decryption process is I/O intensive. an SD Card is not the 'fastest' device I/O wise either.

**Comment by abraunegg** [comment] 2019-01-16 22:51
Potentially related:

https://github.com/Aorimn/dislocker/issues/138

If you can test a sync to a non dislocker fuse mounted device and compare the CPU usage that would be greatly appreciated.

Right now, your issue points to dislocker and the SD Card as your perfomance impediment.

**Comment by abraunegg** [comment] 2019-01-17 19:09
@rednag 
Any update as to confirming that your performance issue is related to the use of `dislocker` ?

**Comment by abraunegg** [comment] 2019-01-18 21:40
@rednag 
Any update as to confirming that your performance issue is related to the use of `dislocker` ?

**Comment by abraunegg** [comment] 2019-01-20 18:33
> Sorry, at the moment I'm not able to sync to a non dislocker device.

What you could to is create a 'test' OneDrive account and configure that to a non 'dislocker' local folder, then populate that with random dummy data to upload / sync.

Very quickly you should be able to tell if the system is hitting 25% CPU and using strace see where the system calls are going.

**Comment by rednag** [comment] 2019-01-20 20:01
Yeah, seems to on my local drive it works normal. Service runs every x seconds.

**Comment by abraunegg** [comment] 2019-01-20 20:20
Just as suspected.

Closing this issue as this is a performance related item with `dislocker`. It is best that you open a new case on https://github.com/Aorimn/dislocker or add your findings to https://github.com/Aorimn/dislocker/issues/138

**Closed by abraunegg** 2019-01-20 20:20 UTC
Labels: Local Environment Issue, Not a bug
