### ISSUE TITLE
Delete old files after download from onedrive automatically

### ISSUE THREAD

**Issue by dead0island** [abraunegg/onedrive#1592] opened 2021-07-31 09:08 UTC
I use it on raspberrypi. It is found that it automatically renames old files after each synchronization, such as "example-raspberrypi.mp4". Every time I have to delete it manually, maybe it's a good idea to add a function to automatically delete old files.
The "—remove source files" code is available, but it only applies to upload-only mode, not download-only mode.

**Comment by abraunegg** [comment] 2021-07-31 19:18
@dead0island 
Closing issue as support process not followed - such as using the support template, providing any logs, providing the client version you are using. Please follow the correct support process as detailed here:

* https://github.com/abraunegg/onedrive#have-a-question
* https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug

A few notes:
> I use it on raspberrypi. It is found that it automatically renames old files after each synchronization, such as "example-raspberrypi.mp4"

Increase application verbosity to understand why this is occuring. This is also a 'skilion' bug, so also 'check' your application version.

> Every time I have to delete it manually, maybe it's a good idea to add a function to automatically delete old files.

 Once you understand the 'why' you may need to investigate 'bypass_data_preservation' within the configuration file to prevent these files from being created.

**Closed by abraunegg** 2021-07-31 19:18 UTC

**Comment by dead0island** [comment] 2021-08-01 04:05
> @dead0island
> Closing issue as support process not followed - such as using the support template, providing any logs, providing the client version you are using. Please follow the correct support process as detailed here:
> 
> * https://github.com/abraunegg/onedrive#have-a-question
> * https://github.com/abraunegg/onedrive#reporting-an-issue-or-bug
> 
> A few notes:
> 
> > I use it on raspberrypi. It is found that it automatically renames old files after each synchronization, such as "example-raspberrypi.mp4"
> 
> Increase application verbosity to understand why this is occurring. This is also a 'skilion' bug, so also 'check' your application version.
> 
> > Every time I have to delete it manually, maybe it's a good idea to add a function to automatically delete old files.
> 
> Once you understand the 'why' you may need to investigate 'bypass_data_preservation' within the configuration file to prevent these files from being created.

Sorry for my question. It was successfully fixed by adding the "bypass_data_preservation" in config file. Thank you again for your effort.

**Comment by abraunegg** [comment] 2021-08-01 07:29
@dead0island 
> Sorry for my question.

By all means ask questions - however raising an issue = bug ... and a question should be raised in the 'Discussions' area which is why this exists - please take note of this.

> It was successfully fixed by adding the "bypass_data_preservation" in config file. Thank you again for your effort.

Glad you have resolved your issue, however hopefully you determined first why this issue is occurring in the first place - and understand the cause, before you enabled that option as you are removing your safeguard to avoid data loss.
