### ISSUE TITLE
Delete behaviour incorrect when using sync_list

### ISSUE THREAD

**Issue by pcolmer** [abraunegg/onedrive#723] opened 2019-11-11 09:34 UTC
### Bug Report Details ###
I'm using `sync_list` to limit how much the `onedrive` client syncs. I use it to upload files from a Linux system to one specific folder on OneDrive. I then use the OneDrive web interface to move those files elsewhere on OneDrive for later use, or delete them from the OneDrive synced folder once I've used them.

When re-syncing, I observe the following:

* Files that have been moved elsewhere in the OneDrive tree are correctly deleted from the Linux client.

* Files that have not been moved but are deleted from OneDrive do **not** get deleted from the Linux client.

**Application and Operating System Details:**
*   OS: Ubuntu 18.04

`Linux hackbox2 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed? Headless
*   OneDrive Account Type: personal
*   DMD or LDC compiler version

```
DMD64 D Compiler v2.087.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

*   Application configuration:

```
onedrive version                    = v2.3.11-5-ga390410
Config path                         = /home/philip.colmer/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/philip.colmer/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /home/philip.colmer/.config/onedrive/log/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Video
```

Note that this does happen with the master branch as well.

*   Curl Version:

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**To Reproduce**
See description above.

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output (sent by email)

**Comment by abraunegg** [comment] 2019-11-12 01:44
@pcolmer 
Please can you help validate & test the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/724/head:pr724
git checkout pr724
./configure; make clean; make;
```

**Comment by pcolmer** [comment] 2019-11-12 07:39
@abraunegg If I've built this correctly, I now have version v2.3.11-3-g96b735f and, unfortunately, it hasn't worked. The client still says "The file has not changed", I'm afraid.

**Comment by abraunegg** [comment] 2019-11-12 18:26
@pcolmer 
Thanks for the feedback - for moves - this certainly works, but for deletes, yes - not working.

**Comment by abraunegg** [comment] 2019-11-12 19:49
@pcolmer 
Please can you update via rebuilding the PR - you should get `onedrive v2.3.11-5-g05e4621` as the version when testing.

I have confirmed that:
* Files moved into sync_list scope are downloaded
* Files moved out of sync_list scope are removed
* Folders that are moved into sync_list scope are created & downloaded
* Folders that are moved out of sync_list scope are removed
* Files and folders that are in sync_list scope and are then deleted via OneDrive are then removed locally

**Comment by pcolmer** [comment] 2019-11-13 08:43
@abraunegg I've updated to the new PR branch - onedrive is now reporting `v2.3.11-6-gdfbd85c`.

Unfortunately, local files that have previously been synced to OneDrive and then deleted via OneDrive are still not getting removed locally.

Would you like a debug log sent to you?

**Comment by abraunegg** [comment] 2019-11-13 09:52
@pcolmer 
> Unfortunately, local files that have previously been synced to OneDrive and then deleted via OneDrive are still not getting removed locally.

A delete event is *only* ever sent once by OneDrive.

If you are expecting 'previously' deleted items on OneDrive to now be deleted, the local client cache DB thinks this file is still valid, as this is in the DB - thus this is why previously deleted files are not being deleted.

Can you please retest with a "new file" - uploaded (can be a dummy file) then deleted via OneDrive and as per my testing, this should be deleted.

If this does not occur, then a full verbose debug log via email would be great.

**Example below:**
Upload / sync using 'master'
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.11-2-gc876b9c
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5367208266
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 10 OneDrive items to ensure consistent state due to sync_list being used
Skipping item - excluded by sync_list config: Intel
Uploading differences of .
Processing root
The directory has not changed
Processing Video
The directory has not changed
Processing testsrc.mp4
The file has not changed
Processing testsrc.mpg
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Delete file using OneDrive WebUI & sync again with master - expected result is file is NOT deleted
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.11-2-gc876b9c
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5367998794
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 9 OneDrive items to ensure consistent state due to sync_list being used
Skipping item - excluded by sync_list config: Intel
Uploading differences of .
Processing root
The directory has not changed
Processing Video
The directory has not changed
Processing testsrc.mp4
The file has not changed
Processing testsrc.mpg
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Switch to using PR codebase and sync - previously deleted file STILL remains
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.11-6-gdfbd85c
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5367998794
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing Video
The directory has not changed
Processing testsrc.mp4
The file has not changed
Processing testsrc.mpg
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

Unfortunately right now, there is no easy way to 'clean up' the local state as compared to OneDrive because of using 'sync_list' and how the DB / feature was implemented way back by 'skilion' & how the delete 'change' is only ever sent once by OneDrive.

Issuing a `--resync` here is also not really an option - as OneDrive is not going to tell you that 'file x' is not supposed to exist locally, and the client will naturally assume that any file that is local, that is not in the database needs to be uploaded.

**Comment by pcolmer** [comment] 2019-11-13 10:38
Thanks for the explanation/clarification, @abraunegg.

Retested and confirmed fixed. Thanks again for brilliant work.

**Comment by abraunegg** [comment] 2019-11-21 08:59
Closing issue as PR #724 merged into master

**Closed by abraunegg** 2019-11-21 08:59 UTC
Labels: Bug, Fixed
