### ISSUE TITLE
HTTP request returned status code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by anishmittal2020** [abraunegg/onedrive#133] opened 2018-08-20 12:56 UTC
I tried to download contents of my Onedrive to my harddrive. It did download some data, but after a while I am getting this error: 

```
Onedrive.OneDriveException@src/onedrive.d(597): HTTP request returned status code 429 (Too Many Requests)
----------------
src/onedrive.d:28 void onedrive.OneDriveApi.checkHttpCode() [0x4a42ac78]
src/onedrive.d:395 void onedrive.OneDriveApi.download(const(char)[], immutable(char)[], long) [0x4a42a2d8]
src/onedrive.d:131 void onedrive.OneDriveApi.downloadById(const(char)[], const(char)[], immutable(char)[], long) [0x4a428d12]
src/sync.d:648 void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x4a436026]
src/sync.d:594 void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x4a435b7b]
src/sync.d:568 void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x4a435a27]
src/sync.d:432 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x4a434f46]
src/sync.d:200 void sync.SyncEngine.applyDifferences() [0x4a434065]
src/main.d:401 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x4a4199f2]
src/main.d:269 _Dmain [0x4a41927b]
```

1. How long should I wait? 
2. Or is there any workaround?
3. Does changing IP helps?
  -  I am in a subnetwork, and changing IP didn't help me!

**Comment by anishmittal2020** [comment] 2018-08-20 22:15
After I had to synchronize after 8 hours of the reported incident. Nothing happens. Am I blocked?

```
$ onedrive --download --verbose --synchronize --syncdir /mnt/Home2/Cloud/Onedrive
Loading config ...
Using Config Dir: /home/nikhil/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /mnt/Home2/Cloud/Onedrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 4a7e951eb443e856
Default Root ID: 4A7E951EB443E856!101
Remaining Free Space: -871582681854
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 4A7E951EB443E856!101
```

**Comment by abraunegg** [comment] 2018-08-23 20:41
@anishmittal2020 
Can you please provide some additional details here as your bug report is incomplete, specifically:

* Application version: Output of onedrive --version
* OneDrive Account Type

Additionally what country are you located in?

**Comment by abraunegg** [comment] 2018-08-23 20:44
Further to this, it seems that the issue is being hit when attempting to download files. Are you seeing this issue when uploading files?

**Comment by anishmittal2020** [comment] 2018-08-24 07:43
`$ onedrive --version`
`onedrive v2.1.1-4-g448b624`

Account type: Premium version expired. But have access to data upto October.

`onedrive --resync --download --verbose --synchronize --syncdir /xxxx/xxx/xxxxx/Onedrive`

I am just downloading the files.

**Comment by anishmittal2020** [comment] 2018-08-24 09:06
Germany

**Comment by abraunegg** [comment] 2018-08-24 09:10
Thanks.

First suggestion, there is no real reason to use --resync for your task.

What that is doing - is each time you run the application - is it deletes the local database. Therefor the client will make many more requests revalidating each and every file. This will be a contributing factor for you

**Comment by abraunegg** [comment] 2018-08-24 22:14
@anishmittal2020 
Can you please rebuild your client and validate the fix for your issue by using this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/138/head:pr138
git checkout pr138
make
make install
```

If you can help test and provide feedback that would be greatly appreciated as I am unable to trigger a 429 event locally.

**Comment by abraunegg** [comment] 2018-08-27 00:28
@anishmittal2020 
Any further update on this issue?

**Comment by abraunegg** [comment] 2018-08-27 01:05
PR merged

**Closed** 2018-08-28 20:08 UTC
Labels: Bug, Fixed, Waiting on Response

**Comment by anishmittal2020** [comment] 2018-09-05 07:31
Hi, I installed latest version today. After 20 minutes of download I get this message "OneDrive returned a 'HTTP 429 - Too Many Requests' - gracefully handling error"

**Comment by abraunegg** [comment] 2018-09-05 07:34
Please can you provide a verbose log of the error.

Is it still failing and stopping syncing or is it gracfully continuing?

**Comment by anishmittal2020** [comment] 2018-09-05 07:38
I get message when I do this `onedrive --resync --download --verbose --synchronize --syncdir /mnt/Home2/Cloud/Onedrive`

**Comment by abraunegg** [comment] 2018-09-05 07:44
Hi - as previously advised - do not use --resync as this deletes your local database and significantly increases the rate of communication with OneDrive.

**Comment by anishmittal2020** [comment] 2018-09-05 07:45
To limit the download I specify only few folders in resync. That's why I was doing that. Is it ok to do it in this case?

**Comment by anishmittal2020** [comment] 2018-09-05 07:47
I do --resync only when I change the `sync_list`

**Comment by abraunegg** [comment] 2018-09-05 07:48
No .. everytime you use --resync it deletes the database thus has no record of what your trying to download and sync. If you are then trying to just sync a couple of folders - you are causing trouble for yourself

Dont use --resync unless your doing a resync of your entire OneDrive

**Comment by anishmittal2020** [comment] 2018-09-05 07:52
But it was mentioned in the README.md `Note: after changing the sync list, you must perform a full synchronization by executing onedrive --resync`. So, better should I leave sync_list blank?

**Comment by abraunegg** [comment] 2018-09-05 07:54
Yes .. that advice is based on the Skilion code base. 

Leave sync_list blank and let it perform a full sync to get your data

**Comment by anishmittal2020** [comment] 2018-09-05 08:14
Actually I have almost 800 GB of Data, which I down't expect to get downloaded in one go. Please say if the following workflow would work: 
1. I start downloading without resync. 
2. When I decide to stop it for a while. I just press `Ctrl+z`
3. Later, when I am available to download I Goto step 1.

**Comment by abraunegg** [comment] 2018-09-06 00:10
> If I restart download, the error gets displayed after downloading 2 or 3 files.

This is because you are using `--resync` - what that option does is deletes the local database, so the client will then revalidate every file you have downloaded thus far.

The Skilion code had no error handling. The advice there was that whenever there was a download issue or changing a configuration item to 'resync' - which all it does is delete the local database so the client has no idea of what you have downloaded - dont use that option.

> When I decide to stop it for a while. I just press Ctrl+z

This is WRONG. CTRL+Z will sleep the process, not stop it. You need to use CTRL-C to stop the program.
