### ISSUE TITLE
Cannot find a drive via --get-O365-drive-id

### ISSUE THREAD

**Issue by lorenzosu** [abraunegg/onedrive#1183] opened 2020-12-16 08:28 UTC
### Bug Report Details ###
An existing O365 dirve id cannot be found via --get-O365-drive-id

**Application and Operating System Details:**
*   **Manjaro - 5.8.18-1-MANJARO**
*   Are you using a headless system (no gui) or with a gui installed? **Desnktop environment**
*   OneDrive Account Type: **O365**
*   Installed via **AUR: aur/onedrive-abraunegg**
*   OneDrive Application Version: **2.4.8**
*   Curl version: **curl 7.73.0**
*   Is your configured 'sync_dir' a local directory or a network mount point? **Local dir**
*   What partition format type does your configured 'sync_dir' reside on? **ext4** 

**To Reproduce**
1.  In terminal `onedrive --get-O365-drive-id "keyword"   [real keyword is of course different, I'll refer to it as 'keyword' also below]

I get an error message "ERROR: The requested SharePoint site could not be found. Please check it's name and your permissions to access the site. The following SharePoint site names were returned: [list of sites]"

This is weird because I can find other (apparently) similar drives which are the 'root' of similarly created, i.e. the 'Documents' (aka drive) of sharepoint 'sites' which were created as 'teams'.

I can actually find the sharepoint site if I try https://graph.microsoft.com/v1.0/sites?search="keyword" in the MS graph explorer.

Any guidance on debugging this would be appreciated.

**Comment by abraunegg** [comment] 2020-12-16 09:26
@lorenzosu 
With this issue, first see what the verbose debug log is telling you.

It will (at least it should be) output the exact JSON response from OneDrive API that is then searched for the entry you are seeking. If you are not seeing the search item in the response, this is why it cant be found, if you can, then this is a search bug.

Can you help clarify what is going on

**Comment by lorenzosu** [comment] 2020-12-16 10:56
@abraunegg the debug log seems to show that the site is in the response. Actually on better checking it is also shown in the list output after "The following SharePoint site names were returned:"

**Comment by abraunegg** [comment] 2020-12-16 19:18
@lorenzosu 
OK .. so the pattern matching is failing.

Please can you provide an exact example, as the pattern matching I use to test (without space, with space) all works 100%

Are you you wrapping your keyword in quotes?

**Example:**
```
onedrive --get-O365-drive-id 'sharepointsitename'
```

```
onedrive --get-O365-drive-id 'sharepoint site name'
```

**Comment by lorenzosu** [comment] 2020-12-17 08:15
@abraunegg sure. Mind if I sent it directly, if so how could I do that?

I tried wrapping keywords in both quotes ('keyword') and double quotes ("keyword")

**Comment by abraunegg** [comment] 2020-12-17 09:19
@lorenzosu 
> Mind if I sent it directly, if so how could I do that?

Please email any details / log files to the support email address as listed under https://github.com/abraunegg/onedrive#reporting-issues

**Comment by lorenzosu** [comment] 2020-12-17 10:48
@abraunegg 
Update: it seems that if I put the exact string that's also in the displayName as returned in the "O365 Query Response" (using debug), the site/drive is actually found, not if I use a substring. I'm a bit puzzled as I'm sure I did this in my tests (I copy/pasted the string from the sharepoint website) but maybe I pasted incorrectly.
I guess if this is the intended behaviour, i.e. that you have to use the exact display name as query string, then I think this bug can be closed and sorry for the noise :-). If not (i.e. this would search also e.g. a substring in the display name), then I can provide the input as you requested above.

**Comment by abraunegg** [comment] 2020-12-17 19:16
@lorenzosu 
> Update: it seems that if I put the exact string that's also in the displayName as returned in the "O365 Query Response" (using debug), the site/drive is actually found, not if I use a substring. I'm a bit puzzled as I'm sure I did this in my tests (I copy/pasted the string from the sharepoint website) but maybe I pasted incorrectly.
> I guess if this is the intended behaviour, i.e. that you have to use the exact display name as query string, then I think this bug can be closed and sorry for the noise :-). If not (i.e. this would search also e.g. a substring in the display name), then I can provide the input as you requested above.

Yes, you must use the exact display name to have the correct match returned.

This is not a bug or issue, closing ticket.

**Closed by abraunegg** 2020-12-17 19:16 UTC
Labels: More Information Needed, Waiting on Response
