### ISSUE TITLE
Feature request: a `--retry`(?) flag

### ISSUE THREAD

**Issue by margual56** [abraunegg/onedrive#1636] opened 2021-09-25 11:24 UTC
## Problem
OneDrive (SharePoint I think, it's from my organization) seems to be "throttling" the downloads. It also happens when I try to download a big folder directly from the browser: OneDrive just stops the download and errors out.

## Possible solution
Implement an option (`--retry` flag or something) that, when the connection errors out, it waits a few seconds and automatically tries again. Maybe with an optional parameter for the max number of tries per minute or something similar, just in case the network really is broken.

## Alternatives
This could be done with a simple bash script, but it would be much nicer, and probably much better implemented, if it was included as an option

## Additional context
This might just be a thing on my organization, but still it would be a nice feature to have in case of non-robust networks, so that you can just leave the program running alone.

**Comment by abraunegg** [comment] 2021-09-25 11:28
@margual56 
What client version are you using?

This client honours the 429 response from OneDrive to 'wait' for the time period prescribed before continuing the operations.

Please investigate what responses you are getting as well via adding --verbose to the command you are using.

**Comment by margual56** [comment] 2021-09-25 22:30
I'm sorry, I cannot provide further information on the error. Te program just suddlenly stops after some time...
It's also somewhat hard to have that error occur (that's why it took me so long to answer).

I have checked the verbose log and the debugging log (`--vv`), but it does not output any errors or anything. It does return an error code tho.

I might be missing something, or as I said before this could be just me and my "setup", but a retry option would still be nice :)

I'll keep investigating and I'll post any further information I can extract.

**Comment by abraunegg** [comment] 2021-09-25 22:35
@margual56 
> I'm sorry, I cannot provide further information on the error. Te program just suddlenly stops after some time...
> It's also somewhat hard to have that error occur (that's why it took me so long to answer).
> ...
> It does return an error code tho.

What is this error code?

Then you need to read this: https://github.com/abraunegg/onedrive/blob/master/docs/known-issues.md#application-stops-running-without-any-visible-reason

This is not a bug or issue with this client - but your Internet connectivity. This is something I cannot solve.

**Comment by abraunegg** [comment] 2021-09-25 22:54
As this 'issue' is most likely dealing with the users Internet access and is *not* this client, the following are appropriate to investigate:

Actions for you - this is an issue you need to solve:
* Dont use Ubuntu, install another Linux OS that is not Ubuntu or Ubuntu based and test using that
  * Dont run the other OS as a VM under Ubuntu - as, you are still using the Ubuntu network stack - build a totally new PC
  * If you still experience the issue on the totally different non-Ubuntu OS, then it is not Ubuntu related .... if you dont encounter the issue - go raise this issue with Ubuntu .. or stop using Ubuntu
* Debug your network and your connection to OneDrive
  * Just because 'other' things work, does not mean you dont have an issue somewhere that other applications do not uncover
* Raise a trouble ticket with the Curl team and get them to assist you.
  * This client relies on the Curl Library - it passes all the 'work' actions to Curl. Your debug output shows that it is Curl that is terminating the action - not this client
* Complain to your ISP about connection drops to OneDrive
* Open an issue ticket with Microsoft


As such, closing this Feature Request as this is nothing that I can solve.

**Closed by abraunegg** 2021-09-25 22:54 UTC
Labels: More Information Needed

**Comment by margual56** [comment] 2021-09-25 23:21
Yes, you are correct. Error code: 141. Thank you for your patience and sorry for the inconvenience.

However, I still think that this **feature request** is still relevant, no matter why my application errors out (this wasn't a bug report), it would be nice to have the aforementioned `--retry` flag.

**Comment by abraunegg** [comment] 2021-09-25 23:26
@margual56 
> Yes, you are correct. Error code: 141. Thank you for your patience and sorry for the inconvenience.
> 
> However, I still think that this **feature request** is still relevant, no matter why my application errors out (this wasn't a bug report), it would be nice to have the aforementioned `--retry` flag.

And that would then also imply that I could:
* Replicate the network environment that creates this situation - which I am never able to do, even when using the OS that causes this (Ubuntu)
* That Curl provides better error handling back to the API that this application uses to call Curl, so that when Curl fails (Curl is the part here that is failing) - this application can detect this failure and do something with this .. ie - do a `--retry` .... no error response back from Curl, means, any dead peer detection does not work, thus `--retry` will not work

Yes - to have a `--retry` would be nice .. but this is *not* something that can be done, this is not something that I can fix.

**Comment by margual56** [comment] 2021-09-25 23:30
Nice explanation! Thank you for taking your time responding :)

PS: I use Arch, but the issue still applies because the drivers of my wifi adapter are sketchy (from the aur, and yes, I know I souldn't xD)

**Comment by abraunegg** [comment] 2021-09-25 23:33
@margual56 
Re wifi drivers - if AUR package is sketchy:
* build latest drivers from source
* rebuild kernel to support your hardware
* submit error to hardware vendor to fix
