### ISSUE TITLE
onedrive --get-O365-drive-id fails with 403

### ISSUE THREAD

**Issue by pahofmann** [abraunegg/onedrive#619] opened 2019-08-08 14:07 UTC
### Bug Report Details ###
When trying to connect a SharePoint group drive, getting the drive ID with `onedrive --get-O365-drive-id 'NAME'` like mentioned in the documentation, fails with a 403 (unauthorized).

The login was successful and the regular onedrive folder is synced though.

**Application and Operating System Details:**
*   OS: Linux  5.2.4-1-MANJARO
*   With GUI (KDE)
*   OneDrive Account Type: Business
*  DMD64 D Compiler v2.087.0
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.8
Config path                         = /home/patrick/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/patrick/documents/work/onedrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
*   Curl Version: Output of `curl --version`
```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

Application Log Output:
```
Using Config Dir: /home/patrick/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/patrick/documents/work/onedrive
Initializing the Synchronization Engine ...
Application version: v2.3.8
Account Type: business
Default Drive ID: <ID>
Default Root ID: <ID>
Remaining Free Space: 1099067253713
Fetching details for OneDrive Root
OneDrive Root exists in the database
onedrive.OneDriveException@src/onedrive.d(813): HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2019-08-08T14:01:54",
            "request-id": "b8eb8feb-b38a-4a75-bff6-3d33fb2a988b"
        },
        "message": "The caller does not have permission to perform the action."
    }
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x55cfb1f277de]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x55cfb1f26753]
??:? std.json.JSONValue onedrive.OneDriveApi.o365SiteSearch(immutable(char)[]) [0x55cfb1f261cb]
??:? void sync.SyncEngine.querySiteCollectionForDriveID(immutable(char)[]) [0x55cfb1f3e8ed]
??:? _Dmain [0x55cfb1f21e56]
```

**Comment by fbegyn** [comment] 2019-08-08 14:27
Same issue here.

**Application and Operating System Details:**

- OS: Linux 5.2.6 Arch Linux
- Sway
- OneDrive Account Type: Business
- Application configuration: Output of `onedrive --display-config`
```
onedrive version                    = v2.3.8
Config path                         = /home/francis/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/francis/OneDrive
Config option 'skip_dir'            = 2018
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
- Curl Version: Output of `curl --version`
```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.36.0
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
- Application Log Output:
```
Using Config Dir: /home/francis/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/francis/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.8
Account Type: business
Default Drive ID: <id>
Default Root ID: <id>
Remaining Free Space: 1096373879364
Fetching details for OneDrive Root
OneDrive Root exists in the database
onedrive.OneDriveException@src/onedrive.d(813): HTTP request returned status code 403 (Forbidden)
{
    "error": {
        "code": "accessDenied",
        "innerError": {
            "date": "2019-08-08T14:22:16",
            "request-id": "0115deed-37a4-49ef-9e9f-6f9be32787c3"
        },
        "message": "The caller does not have permission to perform the action."
    }
}
----------------
??:? void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x55a23f71f83e]
??:? std.json.JSONValue onedrive.OneDriveApi.get(const(char)[], bool) [0x55a23f71e7b3]
??:? std.json.JSONValue onedrive.OneDriveApi.o365SiteSearch(immutable(char)[]) 
??:? [0x55a23f71e22b]
```

**Comment by abraunegg** [comment] 2019-08-08 18:57
@pahofmann, @fbegyn 
Whilst the crash needs to be fixed, the reason for the 403 is that your Sharepoint Administrator has put too restrictive permissions on you accessing the folder / sharepoint site. This cannot be solved in the application and you need to speak to your Sharepoint admins to fix

**Comment by abraunegg** [comment] 2019-08-08 19:54
@pahofmann, @fbegyn 
Whilst the crash is now sorted as per #620, please can you help test this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/620/head:pr620
git checkout pr620
make clean; ./configure; make;
```

In my local testing I do not get a crash, but also it appears that a valid API query is now failing, which is an API regression that needs to be pointed out to the OneDrive API team - as my site below I have all the correct permissions to query:

```
(dmd-2.085.0)[alex@centos7full fix-issue-619]$ ./onedrive --confdir '~/.config/onedrive-business/' --get-O365-drive-id 'od-test'
Initializing the Synchronization Engine ...
Office 365 Library Name Query: od-test
ERROR: Query of OneDrive for Office 365 Library Name failed
Error Message: HTTP request returned status code 403 (Forbidden)
Error Reason:  The caller does not have permission to perform the action.
(dmd-2.085.0)[alex@centos7full fix-issue-619]$ 
```

**Comment by abraunegg** [comment] 2019-08-08 20:04
Posted an API regression issue here: https://github.com/OneDrive/onedrive-api-docs/issues/1119

**Comment by fbegyn** [comment] 2019-08-08 21:48
@abraunegg I've tested the PR and LGTM. Thanks for the fast replies!
```
Using Config Dir: /home/francis/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/francis/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.8-2-g0fb8879
Account Type: business
Default Drive ID: <ID>
Default Root ID: <ID>
Remaining Free Space: 1096373879364
Fetching details for OneDrive Root
OneDrive Root exists in the database
Office 365 Library Name Query: <PATH>
OneDrive returned a 'HTTP 403 - Forbidden' - gracefully handling error
ERROR: Query of OneDrive for Office 365 Library Name failed
Error Message: HTTP request returned status code 403 (Forbidden)
Error Reason:  The caller does not have permission to perform the action.
```

**Comment by abraunegg** [comment] 2019-08-08 23:17
@fbegyn 
Thanks for the feedback. Can you please rebuild the PR based on the latest version, and issue a `--logout` on your client please. When running the new PR build, and after issuing a `--logout` & reauth of the client, the query now works as per expectation:

```
(dmd-2.085.0)[alex@centos7full fix-issue-619]$ ./onedrive --confdir '~/.config/onedrive-business/' --get-O365-drive-id 'od-test'
Initializing the Synchronization Engine ...
Office 365 Library Name Query: od-test
SiteName: od-test
drive_id: b!QMiiVyjynUC_UIBZ4WaV8UveUfEgF9BGseBAWSULEb7n4JeIvgOVR4zlieNatYHC
URL:      https://mynasau2.sharepoint.com/sites/od-test
(dmd-2.085.0)[alex@centos7full fix-issue-619]$ 
```

**Comment by fbegyn** [comment] 2019-08-09 00:17
Had some issues (mainly my side), but after checking out out the `business-shared-folders` branch and rebuilding, everything seems to be in order!. Thank you for the speedy fix!

**Comment by abraunegg** [comment] 2019-08-09 08:15
@pahofmann @fbegyn 
Closing issue as PR #620 is merged into master. Will update #473 shortly.

**Closed by abraunegg** 2019-08-09 08:15 UTC
Labels: Bug, Fixed, OneDrive API Regression, OneDrive Business, OneDrive Office365
