### ISSUE TITLE
Cant upload

### ISSUE THREAD

**Issue by Hato626** [abraunegg/onedrive#1430] opened 2021-05-03 01:51 UTC
### Bug Report Details ###
**Describe the bug**
I cant upload anything

**Application and Operating System Details:**
*  Linux localhost 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   no gui
*   Office 365 operated by 21Vianet in China
*   build from source
*   DMD64 D Compiler v2.096.1
*   onedrive v2.4.11-5-gb7eedbd
*   onedrive --display-config:
```
Using config option for Azure AD China operated by 21Vianet
Configuration file successfully loaded
onedrive version                       = v2.4.11-5-gb7eedbd
Config path                            = /root/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /root/OneDrive
Config option 'skip_dir'               =
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*  curl version:
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   'sync_dir' is local path
*   ext4
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time  ####  i dont know what is mean

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  enter "onedrive --synchronize --upload-only" in shell
2.  See error

**Complete Verbose Log Output**
```
root@localhost:~# onedrive --synchronize --upload-only --verbose
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Using config option for Azure AD China operated by 21Vianet
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring AD China operated by 21Vianet
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.11-5-gb7eedbd
Account Type: business
Default Drive ID: 
Default Root ID: 
Remaining Free Space: 4402630150633
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing mp4rec
The directory has not changed
Uploading new items of ~/OneDrive
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/AAA.TXT
Skipping uploading this new file: /root/OneDrive/AAA.TXT
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/mp4rec/【Apex】无口打枪_20210206072643471.flv.mp4
Skipping uploading this new file: /root/OneDrive/mp4rec/【Apex】无口打枪_20210206072643471.flv.mp4
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/debug_output.log
Skipping uploading this new file: /root/OneDrive/debug_output.log
root@localhost:~#
```

Application Log Output:
```bash
root@localhost:~# onedrive --synchronize --upload-only --verbose
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Using config option for Azure AD China operated by 21Vianet
Configuration file successfully loaded
Initializing the OneDrive API ...
Configuring AD China operated by 21Vianet
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.11-5-gb7eedbd
Account Type: business
Default Drive ID: 
Default Root ID: 
Remaining Free Space: 4402630150633
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing mp4rec
The directory has not changed
Uploading new items of ~/OneDrive
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/AAA.TXT
Skipping uploading this new file: /root/OneDrive/AAA.TXT
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/mp4rec/【Apex】无口打枪_20210206072643471.flv.mp4
Skipping uploading this new file: /root/OneDrive/mp4rec/【Apex】无口打枪_20210206072643471.flv.mp4
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/debug_output.log
Skipping uploading this new file: /root/OneDrive/debug_output.log
root@localhost:~#
```

**Screenshots**
![image](https://user-images.githubusercontent.com/63497854/116835389-d8a51700-abf4-11eb-97ba-03014c81112b.png)

**Additional context**

### Bug Report Checklist ###
*   [X] Detailed description
*   [X] Application and Operating System Details provided in full
*   [X] Reproduction steps (if applicable)
*   [X] Verbose Log Output from your error
*   [X] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-05-04 20:48
@Hato626 
Please provide the output of the following command:
```
tree /root/OneDrive/
```

**Comment by Hato626** [comment] 2021-05-06 14:08
> @ Hato626
> 请提供以下命令的输出：
> 
> ```
> tree /root/OneDrive/
> ```

```
oot@localhost:~# tree /root/OneDrive/
/root/OneDrive/
├── AAA.TXT
├── debug_output.log
└── mp4rec
    └── 【Apex】无口打枪_20210206072643471.flv.mp4

1 directory, 3 files
root@localhost:~#
```

**Comment by abraunegg** [comment] 2021-05-06 19:54
@Hato626 
There must be something else going on here, as the client is determining that there are duplicate files.

Please try this:
```
onedrive --synchronize --upload-only --verbose --resync --dry-run
```

**Comment by Hato626** [comment] 2021-05-06 22:22
> @ Hato626
> 由于客户端确定存在重复文件，因此这里还必须进行其他操作。
> 
> 请尝试以下方法：
> 
> ```
> onedrive --synchronize --upload-only --verbose --resync --dry-run
> ```
```
root@localhost:~# onedrive --synchronize --upload-only --verbose --resync --dry-runUsing 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Using config option for Azure AD China operated by 21Vianet
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring AD China operated by 21Vianet
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.11-5-gb7eedbd
Account Type: business
Default Drive ID: b!Y5UDdc8aAUKKpFb5sFBDnXu9AuaooLhGtNBp-s4JLY8PCD4yJJ4mQryiuVgznFKI
Default Root ID: 01VFUOBSV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 3617773815642
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Uploading new items of ~/OneDrive
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/AAA.TXT
Skipping uploading this new file: /root/OneDrive/AAA.TXT
OneDrive Client requested to create remote path: ./mp4rec
ERROR: Current directory has a 'case-insensitive match' to an existing directory on OneDrive
ERROR: To resolve, rename this local directory: /root/OneDrive/mp4rec
ERROR: Remote OneDrive directory: root
Skipping: /root/OneDrive/mp4rec
ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
ERROR: Increase logging verbosity to assist determining why.
ERROR: A local file has the same name as another local file.
ERROR: To resolve, rename this local file: /root/OneDrive/debug_output.log
Skipping uploading this new file: /root/OneDrive/debug_output.log
root@localhost:~#
```

**Comment by abraunegg** [comment] 2021-05-06 22:30
> > @ Hato626
> > 由于客户端确定存在重复文件，因此这里还必须进行其他操作。
> > 请尝试以下方法：
> > ```
> > onedrive --synchronize --upload-only --verbose --resync --dry-run
> > ```
> 
> ```
> root@localhost:~# onedrive --synchronize --upload-only --verbose --resync --dry-run
> Using 'user' Config Dir: /root/.config/onedrive
> Using 'system' Config Dir: /etc/onedrive
> Using config option for Azure AD China operated by 21Vianet
> Configuration file successfully loaded
> DRY-RUN Configured. Output below shows what 'would' have occurred.
> Deleting the saved status ...
> Initializing the OneDrive API ...
> Configuring AD China operated by 21Vianet
> Opening the item database ...
> All operations will be performed in: /root/OneDrive
> Application version: v2.4.11-5-gb7eedbd
> Account Type: business
> Default Drive ID: b!...
> Default Root ID: 01...
> Remaining Free Space: 3617773815642
> Fetching details for OneDrive Root
> OneDrive Root does not exist in the database. We need to add it.
> Added OneDrive Root to the local database
> Initializing the Synchronization Engine ...
> Syncing changes from local path only - NOT syncing data changes from OneDrive ...
> Uploading differences of ~/OneDrive
> Processing .
> The directory has not changed
> Uploading new items of ~/OneDrive
> ERROR: A local file has the same name as another local file.
> ERROR: To resolve, rename this local file: /root/OneDrive/AAA.TXT
> Skipping uploading this new file: /root/OneDrive/AAA.TXT
> OneDrive Client requested to create remote path: ./mp4rec
> ERROR: Current directory has a 'case-insensitive match' to an existing directory on OneDrive
> ERROR: To resolve, rename this local directory: /root/OneDrive/mp4rec
> ERROR: Remote OneDrive directory: root
> Skipping: /root/OneDrive/mp4rec
> ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
> ERROR: Increase logging verbosity to assist determining why.
> ERROR: A local file has the same name as another local file.
> ERROR: To resolve, rename this local file: /root/OneDrive/debug_output.log
> Skipping uploading this new file: /root/OneDrive/debug_output.log
> root@localhost:~#
> ```

OK ... very odd.

Please can you uninstall the application and recompile.

When recompiling, please use LDC rather than DMD when installing and activating the compiler.

I suspect that something in the compilation process has created a binary which is not working right for you.

**Comment by Hato626** [comment] 2021-05-07 16:09
> > > @ Hato626
> > > 由于客户端确定存在重复文件，因此这里还必须进行其他操作。
> > > 请尝试以下方法：
> > > ```
> > > onedrive --synchronize --upload-only --verbose --resync --dry-run
> > > ```
> > 
> > 
> > ```
> > root@localhost:~# onedrive --synchronize --upload-only --verbose --resync --dry-run
> > Using 'user' Config Dir: /root/.config/onedrive
> > Using 'system' Config Dir: /etc/onedrive
> > Using config option for Azure AD China operated by 21Vianet
> > Configuration file successfully loaded
> > DRY-RUN Configured. Output below shows what 'would' have occurred.
> > Deleting the saved status ...
> > Initializing the OneDrive API ...
> > Configuring AD China operated by 21Vianet
> > Opening the item database ...
> > All operations will be performed in: /root/OneDrive
> > Application version: v2.4.11-5-gb7eedbd
> > Account Type: business
> > Default Drive ID: b!...
> > Default Root ID: 01...
> > Remaining Free Space: 3617773815642
> > Fetching details for OneDrive Root
> > OneDrive Root does not exist in the database. We need to add it.
> > Added OneDrive Root to the local database
> > Initializing the Synchronization Engine ...
> > Syncing changes from local path only - NOT syncing data changes from OneDrive ...
> > Uploading differences of ~/OneDrive
> > Processing .
> > The directory has not changed
> > Uploading new items of ~/OneDrive
> > ERROR: A local file has the same name as another local file.
> > ERROR: To resolve, rename this local file: /root/OneDrive/AAA.TXT
> > Skipping uploading this new file: /root/OneDrive/AAA.TXT
> > OneDrive Client requested to create remote path: ./mp4rec
> > ERROR: Current directory has a 'case-insensitive match' to an existing directory on OneDrive
> > ERROR: To resolve, rename this local directory: /root/OneDrive/mp4rec
> > ERROR: Remote OneDrive directory: root
> > Skipping: /root/OneDrive/mp4rec
> > ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
> > ERROR: Increase logging verbosity to assist determining why.
> > ERROR: A local file has the same name as another local file.
> > ERROR: To resolve, rename this local file: /root/OneDrive/debug_output.log
> > Skipping uploading this new file: /root/OneDrive/debug_output.log
> > root@localhost:~#
> > ```
> 
> 好吧...很奇怪。
> 
> 请您可以卸载该应用程序并重新编译。
> 
> 重新编译时，在安装和激活编译器时，请使用LDC而不是DMD。
> 
> 我怀疑编译过程中的某些内容创建了一个二进制文件，该二进制文件不适用于您。

i try to recompile the application by LDC but also have error

**Comment by Hato626** [comment] 2021-05-07 16:21
i try to use onedrive in global rather than onedrive in china,then the error is gone
maybe the problem in this?

**Comment by Hato626** [comment] 2021-05-07 16:22
i try to use onedrive in global rather than onedrive in china,then the error is gone
maybe the problem in this?

**Comment by abraunegg** [comment] 2021-05-07 21:59
> just a moment ago, i try to login by "onedrive in global"" rather than "onedrive by 21vienr in china",
> then the error is gone
> maybe the problem in this?

Quite likely the case.

Can you send, via email the following debug when using 'Azure AD China operated by 21Vianet':
```
onedrive --synchronize --upload-only --verbose --verbose --resync --debug-https --dry-run
```

It would be interesting to see how / why the CN version of OneDrive API is responding ... it *should* not be responding in the manner that would cause this issue ......

**Comment by Hato626** [comment] 2021-05-08 16:49
have emailed to you
Please check the annex

**Comment by abraunegg** [comment] 2021-05-08 22:49
@Hato626 
Thanks for the updated debug log.

OK .. the CN OneDrive API is being 100% inconsistent with query responses. This is nothing that I can solve for.

As you have already determined, using the 'global' configuration resolves your issue. If you need to use the CN OneDrive API, you need to open a case with Microsoft or the API provider.

Closing this issue, as not a bug, but API issue, specifically with CN hosted instance of OneDrive.

**Closed by abraunegg** 2021-05-08 22:49 UTC
Labels: Investigating, More Information Needed, Unable to reproduce, Waiting on Response
