### ISSUE TITLE
Key not found: cTag

### ISSUE THREAD

**Issue by astralspurs** [abraunegg/onedrive#512] opened 2019-05-29 18:47 UTC
### Bug Report Details ###
All of a sudden getting 'key not found: cTag' errors, is that related to authentication? Nothing that I can recall has been changed on my system since yesterday when I was syncing with no problem.

**Application and Operating System Details:**
*   OS: `Linux dellbuntu 5.0.0-15-generic #16pop0-Ubuntu SMP Wed May 15 14:41:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
*   OneDrive personal
*   Application configuration: Output of `onedrive --display-config:
```
onedrive version                    = v2.3.3-13-g239085f
Config path                         = /home/astralspurs/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /media/veracrypt1/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ._*|~*|*.md~|thumbs.db|sync.ffs_db
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```
**Complete Verbose Log Output**
```bash
onedrive --synchronize --verbose
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Uploading modified file Planner/todo.txt ... done.
Retry sync count: 1: Key not found: cTag
Syncing changes from OneDrive ...
Uploading modified file Planner/todo.txt ... done.
Retry sync count: 2: Key not found: cTag
Syncing changes from OneDrive ...
Uploading modified file Planner/todo.txt ... done.
Giving up on sync after three attempts: Key not found: cTag
std.json.JSONException@std/json.d(540): Key not found: cTag
----------------
/home/astralspurs/dlang/dmd-2.086.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x55a4d7dc46b7]
??:? pure @safe inout(std.json.JSONValue)* std.exception.enforce!(std.json.JSONException).enforce!(inout(std.json.JSONValue)*).enforce(inout(std.json.JSONValue)*, lazy const(char)[], immutable(char)[], ulong) [0x55a4d7e5aa72]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x55a4d7e13849]
src/sync.d:1535 void sync.SyncEngine.uploadFileDifferences(itemdb.Item, immutable(char)[]) [0x55a4d7debc24]
src/sync.d:1323 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x55a4d7dead56]
src/sync.d:1343 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x55a4d7deaf19]
src/sync.d:1320 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x55a4d7dead23]
src/sync.d:1343 void sync.SyncEngine.uploadDirDifferences(itemdb.Item, immutable(char)[]) [0x55a4d7deaf19]
src/sync.d:1320 void sync.SyncEngine.uploadDifferences(itemdb.Item) [0x55a4d7dead23]
src/sync.d:1252 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x55a4d7deaa3d]
src/main.d:616 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x55a4d7dd7713]
src/main.d:389 _Dmain [0x55a4d7dd6ac9]
```

**Comment by abraunegg** [comment] 2019-05-29 19:56
@astralspurs 
Thanks for the bug report - can you update your post with the following:

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
*   Curl Version: Output of `curl --version`

**Note:** If curl version is >= 7.62.0 please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Once the full debug log has been generated & emailed, please retry your sync by adding `--force-http-1.1`. If this is successful, please advise in issue ticket that `--force-http-1.1` was successful in resolving your issue.

Most likely this will be a OneDrive API change, however need to also validate this is not a 'curl' issue as well.

**Comment by abraunegg** [comment] 2019-05-29 20:15
@astralspurs 
Whilst unable to reproduce, it appears that potentially your upload response does not have the right elements. Developing a fix at the moment.

**Comment by abraunegg** [comment] 2019-05-29 20:27
@astralspurs 
Please can you validate the following PR to resolve your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/513/head:pr513
git checkout pr513
make clean; ./configure; make;
```

**Comment by abraunegg** [comment] 2019-05-30 20:00
@astralspurs 
PR #513 merged, marking as fixed. Please can you help test the latest 'master' in your environment.

**Comment by astralspurs** [comment] 2019-05-30 21:06
Thanks abraunegg. I will have some time this weekend to test the fix and I'll be sure to reply. Cheers.

**Comment by abraunegg** [comment] 2019-06-01 19:27
Closing issue as bug fixed & PR merged

**Comment by astralspurs** [comment] 2019-06-01 19:30
Seemed to fix the problem of uploading and syncing. I didn't have verbose output on, but I did get this error still:

```
ERROR: OneDrive response missing required 'id' elementERROR: {"error
":{"code":"notAllowed","innerError":{"date":"2019-06-01T19:25:22","request-id":"813bd504-611f-4932-9258-de5aae6d20b2"},"message":"ETag does not match current item's value"}}
```

**Comment by abraunegg** [comment] 2019-06-01 19:32
@astralspurs 
OK - Thanks for the feedback - will need to update the patch then

**Comment by abraunegg** [comment] 2019-06-01 19:44
@astralspurs 
Please can you rebuild your client with the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/515/head:pr515
git checkout pr515
make clean; ./configure; make;
```

If this errors out again, it will print a very specific line. Please provide this.

**Comment by astralspurs** [comment] 2019-06-02 16:46
No longer syncing successfully. Here's what I get.
```bash
$ ./onedrive --synchronize --verbose
Using Config Dir: /home/astralspurs/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /media/veracrypt1/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: a8159eee3064d16d
Default Root ID: A8159EEE3064D16D!2093
Remaining Free Space: 406306503330
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: A8159EEE3064D16D!2093

A database statement execution error occurred: attempt to write a readonly database
```

**Comment by abraunegg** [comment] 2019-06-02 19:01
@astralspurs 
Is this when running PR #515 ?

Generally that message will 'only' occur in the following situations:
* You have another 'onedrive' process running - maybe via `--monitor` or via service that is not stopped
* Your permissions for your `~/.config/onedrive` is messed up somehow

Can you provide the output of the following:
* `ps aufx | grep onedrive`
* `ls -la ~/.config/onedrive` or whatever directory you are using as your configuration directory

**Comment by astralspurs** [comment] 2019-06-02 21:13
Yes, this was after following your instruction to clone PR #515. Oh, but the issue may have been because I didn't run onedrive with sudo because I'm accessing an external hard drive... Anyways, it is syncing now. Not getting an error. Good to go.

```
(ins)[~]$ ps aufx | grep onedrive
astralspurs    13558  0.0  0.0  17480   904 pts/4    S+   14:07   0:00  |       \_ grep --color=always onedrive
(ins)[~]$ ls -la ~/.config/onedrive
total 14760
drwxr-xr-x  2 astralspurs astralspurs     4096 Jun  2 09:44 .
drwx------ 32 astralspurs astralspurs     4096 Jun  1 12:12 ..
-rwx------  1 astralspurs astralspurs      110 May 24 12:18 config
-rw-r--r--  1 root  root  15060992 Jun  1 12:54 items.sqlite3
-rw-r--r--  1 astralspurs astralspurs    32768 Jun  2 09:44 items.sqlite3-shm
-rw-r--r--  1 astralspurs astralspurs        0 Jun  2 09:44 items.sqlite3-wal
-rw-r--r--  1 astralspurs astralspurs      389 Jun  2 09:44 refresh_token
```

**Comment by abraunegg** [comment] 2019-06-02 22:22
Thanks for the feedback on the updated PR

Will merge later today.

**Comment by abraunegg** [comment] 2019-06-03 00:44
Closing issue as PR is merged and issue is resolved

**Closed by abraunegg** 2019-06-03 00:44 UTC
Labels: Bug, Fixed, Unable to reproduce
