### ISSUE TITLE
There was a problem in accessing the Microsoft OneDrive server - Internet connectivity issue?

### ISSUE THREAD

**Issue by yepimalex** [abraunegg/onedrive#552] opened 2019-06-22 06:00 UTC
### Bug Report Details ###
After authorizing onedrive and copying the resulting url I received the following error:
```
There was a problem in accessing the Microsoft OneDrive service - Internet connectivity issue?

Cannot authorize with Microsoft OneDrive Service
Could not initialize the OneDrive API
```

Also of note, the resultant url only lead to a blank white screen. Not sure if that matters. Also, when logging into microsoft and checking Apps and services access, it does appear in the list.

**Application and Operating System Details:**
*   OS: Linux james-mint 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
            Linux Mint 19.1 Cinnamon 64-bit
*   Are you using a headless system (no gui) or with a gui installed? GUI installed
*   ldc2-1.16.0.linux-x86_64
*   Application configuration: 
```
onedrive version                    = v2.3.5-3-gd939d38
Config path                         = /home/james/.config/onedrive
Config file found in config path    = false
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/james/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version:
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  $ onedrive
2.  Open Link in chrome
3.  Log in to OneDrive and Authorize
4.  Copy resultant URL
5.  Paste into terminal and send it.

Unable to collect verbose log output. (still new to linux so maybe i'm messing it up).
However, here are the results of $ curl https://login.microsoftonline.com and $ nslookup login.microsoftonline.com:

$ curl https://login.microsoftonline.com
```
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://www.office.com/login">here</a>.</h2>
</body></html>
```

$ nslookup login.microsoftonline.com
```
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
login.microsoftonline.com	canonical name = prda.aadg.msidentity.com.
prda.aadg.msidentity.com	canonical name = www.prdtm.aadg.akadns.net.
www.prdtm.aadg.akadns.net	canonical name = www.prd.aa.aadg.akadns.net.
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.70
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.71
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.67
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.73
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.66
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.74
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.65
Name:	www.prd.aa.aadg.akadns.net
Address: 40.126.0.68
;; connection timed out; no servers could be reached
```

**Comment by abraunegg** [comment] 2019-06-22 08:29
@yepimalex 
You have not indicated what type of OneDrive account you are using.

I have tested this with a standard 'Personal' account type - cannot reproduce:
```
[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive-personal
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<redacted>
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709107
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Downloading file file.txt ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing file.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
[alex@centos7full onedrive]$ 
```

**Comment by yepimalex** [comment] 2019-06-22 13:33
Sorry, it's a personal account. Just tried it again using:
$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
```
--synchronize --verbose
Using Config Dir: /home/james/.config/onedrive-personal
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<redacted>

There was a problem in accessing the Microsoft OneDrive service - Internet connectivity issue?

Cannot authorize with Microsoft OneDrive Service
Could not initialize the OneDrive API
```

Same result unfortunately.

Does your response screen also just end up blank?

**Comment by abraunegg** [comment] 2019-06-22 21:56
@yepimalex 
> Does your response screen also just end up blank?

Correct - that is normal.

> It also might be important to note, in case you didn't see it in my uname, that this is pretty much a fresh install of Mint. This is one of the very first thing I've done besides installing Chrome and doing the initial automatic updates.

This should not matter.

Most likely you have some sort of local firewall or some sort of restriction somewhere that is preventing outbound HTTPS connections

Also - from your nslookup:
> ;; connection timed out; no servers could be reached

This indicates to me that you most certainly have some sort of blocking going on.

**Comment by abraunegg** [comment] 2019-06-23 04:48
@yepimalex 
To validate that this is not an issue, I have downloaded and installed Linux Mint 19.1 via `linuxmint-19.1-cinnamon-64bit.iso`

**uname output:**
```
alex@alex-virtual-machine:~$ uname -a
Linux alex-virtual-machine 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
alex@alex-virtual-machine:~$ 
```
**curl version:**
```
curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**application configure and run:**
```
(dmd-2.086.1)alex@alex-virtual-machine:~/onedrive$ ./onedrive 
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: https://login.microsoftonline.com/common/oauth2/nativeclient?code=<redacted>

--synchronize or --monitor missing from your command options or use --help for further assistance

No OneDrive sync will be performed without either of these two arguments being present

(dmd-2.086.1)alex@alex-virtual-machine:~/onedrive$ ./onedrive --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709107
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: <redacted>
Downloading file file.txt ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing file.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

This is not an issue with the client, but your local environment - closing issue.

**Closed by abraunegg** 2019-06-23 04:48 UTC
Labels: Local Environment Issue, Not a bug, Unable to reproduce
