### ISSUE TITLE
Curl certificate error when installing DMD compiler

### ISSUE THREAD

**Issue by NoeBarthelemy** [abraunegg/onedrive#863] opened 2020-04-09 17:59 UTC
Hi ! 
When doing : 
```
curl -fsS https://dlang.org/install.sh -k  | bash -s dmd
```
I obtain the following message : 
```
curl: (77) error setting certificate verify locations:
  CAfile: /home/*username*/anaconda2/ssl/cacert.pem
  CApath: none
```
So it seems that it is an issue linked to anaconda, but nothing online could help me really and I'm not competent enough to find a solution on my own! 

Should I use a different version of curl ? if yes, how? 

Any ideas welcome ! 
Thank you very much :) 
Noé

**Comment by abraunegg** [comment] 2020-04-09 21:27
@NoeBarthelemy 
What OS are you attempting this on ?

**Comment by NoeBarthelemy** [comment] 2020-04-10 10:29
Hi ! Yeah, of course, I forgot: I'm on Ubuntu 18.04 LTS, on a fresh install :)

**Comment by abraunegg** [comment] 2020-04-10 20:03
@NoeBarthelemy 
For Ubuntu 18.x you need to follow either of these depending on your OS CPU architecture:
* [Ubuntu 18.x on i386/i686](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x--lubuntu-18x--debian-9---i386--i686)
* [Ubuntu 18.x on x86_64](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-ubuntu-18x-ubuntu-19x--debian-9-debian-10---x86_64)

In either case, the process for installing and downloading DMD is the same:
```
curl -fsS https://dlang.org/install.sh | bash -s dmd
```
**Example:**
```
alex@alex-virtual-machine:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
alex@alex-virtual-machine:~$ curl -fsS https://dlang.org/install.sh | bash -s dmd
Downloading and unpacking http://downloads.dlang.org/releases/2.x/2.091.0/dmd.2.091.0.linux.tar.xz
######################################################################## 100.0%
Using dub 1.20.0 shipped with dmd-2.091.0

Run `source ~/dlang/dmd-2.091.0/activate` in your shell to use dmd-2.091.0.
This will setup PATH, LIBRARY_PATH, LD_LIBRARY_PATH, DMD, DC, and PS1.
Run `deactivate` later on to restore your environment.
alex@alex-virtual-machine:~$ 
```

I have no idea where you got this instruction to include `-k` when downloading DMD as this is incorrect.

**Comment by NoeBarthelemy** [comment] 2020-04-11 13:50
Oh, my bad, I just tried with -k but originally I followed carefully the "Ubuntu 18.x on x86_64" procedure, which led to the error message I got. 
curl -fsS https://dlang.org/install.sh | bash -s dmd
curl: (77) error setting certificate verify locations:
  CAfile: /home/*username*/anaconda2/ssl/cacert.pem
  CApath: none

I don't really know what to give you to help you helping me though!

**Comment by abraunegg** [comment] 2020-04-11 20:54
@NoeBarthelemy 
Unfortunately this is something I cannot assist with as I do not use Ubuntu.

Your best options here are:
* Seek support with Ubuntu as to why this error is occurring - [https://ubuntu.com/support/community-support](https://ubuntu.com/support/community-support)
* Seek support with Curl developers as to why this error is occurring - [https://github.com/curl/curl](https://github.com/curl/curl)
* Try the Ubuntu PPA for this client as per [https://github.com/abraunegg/onedrive/issues/853](https://github.com/abraunegg/onedrive/issues/853) put together by @yann1cks

The remaining question here is - curl, for some reason on your system is broken. What broke it & how - no idea, but you will need it fixed from an SSL perspective to use the client, otherwise the client (which utilises curl) will not work.

**Comment by abraunegg** [comment] 2020-04-12 20:02
Closing issue as:
* Not a bug with this application
* Local OS issue which needs to be resolved via Ubuntu Support or Curl Support

**Closed by abraunegg** 2020-04-12 20:02 UTC
Labels: Answer Provided, Local Environment Issue, Question

**Comment by NoeBarthelemy** [comment] 2020-04-13 13:20
I'll follow these advice, 
Many thanks for your help! 
Have a good day :)
