### ISSUE TITLE
onedrive --monitor keeps one CPU core 100% busy even when idle

### ISSUE THREAD

**Issue by fenryxo** [abraunegg/onedrive#21] opened 2018-06-13 10:37 UTC
Hello. Thanks for wonderful software. However, I cannot let `onedrive --monitor` run in background because it makes one CPU core 100% busy even when onedrive is idle. It is expected?

Vesrion: git master d6b4930d0a9d8bb87b3624707b05eb3e8607d0cf

**Comment by abraunegg** [comment] 2018-06-13 10:46
This appears to be a known issue (https://github.com/skilion/onedrive/issues/318, https://github.com/skilion/onedrive/issues/328, https://github.com/skilion/onedrive/issues/373) with the client & running as a service.

For the moment I would suggest running the client as a cronjob at the desired frequency (5 mins or so) rather than the way the current client operates.

I will look at this in the future, but not right now.

**Comment by meskaya** [comment] 2018-07-21 09:17
Hi abraunegg, onedrive has been packaged for Ubuntu (using "skilion" code) and as far as I can remember I was not having any cpu usage issues when I was running it as a service. Maybe looking at Ubuntu source package can help you fix this issue https://packages.ubuntu.com/source/bionic/onedrive It seems code is compiled using gdc on Ubuntu but I have no idea if this can explain what we are experiencing here.
Hope this helps :) and thanks a lot for your work (and the workaround ;) ).

**Comment by abraunegg** [comment] 2018-08-03 10:46
@meskaya 
Thanks for the pointer to the Ubuntu package. The package you have linked to is from the 'skilion' codebase & somewhere inbetween v1.0.1 and v1.1.0 releases. The monitor parts of that codebase has not changed in all the skilion version or my branch at present. I suspect that potentially all the database issues which are present in the 'skilion' version but fixed here could be culprit, but I do not know. Additionally, the commit referenced in the first post was a rollback commit, so I have no current data or metrics as to how monitor mode is operating right now except for the prior issues raised on the skilion codebase.

My plan of action here is to get some data to validate the CPU activities of the client in the current state to qualify this issue.

@fenryxo 
Can you re-run with the latest master codebase & provide some data around CPU usage when running in monitor mode when idle?

**Comment by noskillahh** [comment] 2018-08-09 08:46
Hi Abraunegg,
am experiencing the same issue. Just updated to the latest codebase, no difference atleast with whatever was available about 10 days ago. Let me know if I can send you any specifics. Am running a clean kubuntu 18.04.

**Comment by abraunegg** [comment] 2018-08-09 09:47
@meskaya 
This commit added 2 days ago has updates to the monitor logic:
https://github.com/abraunegg/onedrive/commit/e922a7d85e291a3b514855804d09132f60082c65

Can you test using the latest master? You can change the interval frequency from the default 45 seconds to something more sane - like 300 seconds or whatever suirs

**Comment by petobens** [comment] 2018-08-15 22:41
Hi @abraunegg I'm using the latest master with the default 45 seconds interval and I'm also getting 100% cpu usage when using `onedrive --monitor`. Changing the interval is expected to fix this? If  that's the case, can I simply add the monitor interval setting override to my local `~/.config/onedrive` file or do you I need the other settings as well (i.e the `sync_dir`; `skip_file`, etc) in order for the config to be valid?

**Comment by abraunegg** [comment] 2018-08-15 22:53
@petobens 
You should be able to just add the following into `~/.config/onedrive`:

```
monitor_interval = "300"
```

To have the application service run every 5 minutes. The `monitor_interval` is in number of seconds between sync's.

>Changing the interval is expected to fix this?

No it is not expected to fix this - however depending on your environment / filesystem & so on, and how you are monitoring CPU usage, a 45 second 'gap' between sync's would not necessarily be noticable.

My aim is to look at this issue in more depth, as so far with my testing I am not seeing 100% cpu being utilised.

@fenryxo, @meskaya, @noskillahh, @petobens 
Can you please provide the following details of your system:
* Operating system & version
* Kernel version
* How you built the client - DMD, GDC, LDC & what version

**Comment by petobens** [comment] 2018-08-16 17:12
@abraunegg I changed the monitor interval and the resync /logged in and I cannot reproduce this anymore. No idea what was going on. Sorry for not being of any further help.

**Comment by petobens** [comment] 2018-08-16 20:16
Ignore the previous comment. I'm still seeing the problem :( . Will try to debug a bit when I have time.

**Comment by abraunegg** [comment] 2018-08-16 23:11
@petobens
As a start can you please provide the requested environmental details so we can try and work out what is going on / attempt to replicate

**Comment by noskillahh** [comment] 2018-08-17 09:50
I am currently not actively using the system (its my traveling machine). If I find time and remember in the weekend Ill make sure to recompile and post back the exact specs. Im running the latest Kubuntu LTS and am using Office 365 business Onedrive account. Its a Toshiba Tecra A50 machine with a dual core i7-6500U cpu and an m2 ssd. Please excuse me for the details, Ill follow up later.

**Comment by abraunegg** [comment] 2018-08-22 10:27
@petobens, @noskillahh 
Any update from your side?

**Comment by abraunegg** [comment] 2018-08-24 22:29
@petobens, @noskillahh
Any update from your side to provide the requested information?

**Comment by petobens** [comment] 2018-08-25 13:06
Hi @abraunegg sorry for the delay. I switched laptop and I cannot reproduce this consistently anymore.

**Comment by meskaya** [comment] 2018-08-29 13:52
Hi all,
Sorry I just came back from holiday :)
Just built onedrive 2.1.2 and monitoring is still eating 100% of CPU :(

**Operating system & version**
Ubuntu 18.04.1
**Kernel version**
4.15.0-33
**How you built the client - DMD, GDC, LDC & what version**
DMD 2.081.1-0 installed for d-apt repo (deb http://netcologne.dl.sourceforge.net/project/d-apt/ d-apt main #APT repository for D (NetCologne - SourceForge) )
**OneDrive Account Type**
OneDrive for Business
**Local File System (ext2, ext3, ext4, xfs, btrfs, zfs and so on)**
LVM ext4
**ldd output of onedrive client**
	linux-vdso.so.1 (0x00007fff09aee000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007ff7b28a0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff7b2681000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff7b22e3000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff7b20db000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff7b1ed7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff7b1cbf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff7b18ce000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff7b3112000)

**Total size of your OneDrive sync directory**
15G
**Total number of files in your OneDrive sync directory**
17380
**A breakdown of the types of files - text files, code, office documents, ISO images, video files, DVD images**
text files, shell scripts, office documents, ISO 
**output of lscpu**
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
Stepping:            9
CPU MHz:             929.713
CPU max MHz:         3900.0000
CPU min MHz:         400.0000
BogoMIPS:            5808.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            4096K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

Hope this helps :)

**Comment by abraunegg** [comment] 2018-08-29 18:52
@meskaya 
Can you please try the following:
1. Uninstall DMD package
2. Install DMD via the instructions in the readme (ie don't use a package)
```
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
curl -fsS https://dlang.org/install.sh | bash -s dmd
```
3. Rebuild the client & check the ldd output & post here
4. Run the rebuilt client & see if that makes a difference
5. Uninstall DMD by removing folder


Repeat then the above 5 steps by using the LDC compiler:

```
sudo apt install build-essential
sudo apt install libcurl4-openssl-dev
sudo apt install libsqlite3-dev
curl -fsS https://dlang.org/install.sh | bash -s ldc
```

I currently suspect that the "linking" of the Linux libraries is what is causing this issue.

**Comment by meskaya** [comment] 2018-08-30 08:14
**Using DMD installed following instructions in the readme**
ldd output:
→ ldd onedrive
	linux-vdso.so.1 (0x00007ffec46ad000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fda28e4a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fda28c2b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fda2888d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fda28685000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fda28481000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fda28269000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fda27e78000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fda296bc000)

onedrive process still eating 100% CPU

**Using LDC**

make DC=/home/fraiar01/dlang/ldc-1.11.0/bin/ldc2
ldd output
→ ldd onedrive
	linux-vdso.so.1 (0x00007ffdbc5c2000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007eff9dcb7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007eff9daaf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007eff9d8ab000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007eff9d68c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007eff9d2ee000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007eff9d0d6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007eff9cce5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007eff9e35f000)

onedrive process is also eating 100% CPU

make DC=/home/fraiar01/dlang/ldc-1.11.0/bin/ldmd2
→ ldd onedrive
	linux-vdso.so.1 (0x00007ffefb3d3000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fe75fa70000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe75f868000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe75f664000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe75f445000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe75f0a7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe75ee8f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe75ea9e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe760118000)

onedrive process is also eating 100% CPU

I tried to compile the code using GDC (like Ubuntu package) but it's not working.
There are patches to make Makefile working with GDC here https://packages.ubuntu.com/source/bionic/onedrive but I was still having errors.
Do you think you can add GDC support so we can try to compile onedrive using it ?

Hope this helps :)

**Comment by abraunegg** [comment] 2018-08-30 09:47
How are you running the application - via command line or service file?

Can you check if cgroups is potentially limiting the process?

**Comment by meskaya** [comment] 2018-08-30 13:01
I tried both each time, console and service.
I don't know how to check cgroups, can you explain ?

**Comment by abraunegg** [comment] 2018-09-10 01:07
@fenryxo, @meskaya, @noskillahh, @petobens
Can you help test the following PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/165/head:pr165
git checkout pr165
make
make install
```

**Comment by abraunegg** [comment] 2018-09-12 08:12
@fenryxo, @meskaya, @noskillahh, @petobens

Any update on testing this PR?

**Comment by fenryxo** [comment] 2018-09-12 10:58
I cannot reproduce the issue anymore with that PR. Thanks :+1:

**Comment by meskaya** [comment] 2018-09-12 13:06
I am still having the same issue :( (I installed DMD as explained in the README)

**Comment by abraunegg** [comment] 2018-09-12 21:30
@meskaya 
Can you please ensure you are using the #165 PR and provide some logging / system validation that the issue is still present?

**Comment by abraunegg** [comment] 2018-09-12 22:44
PR #165 merged

If there is still an issue, will need to re-open & analyse further.

**Closed by abraunegg** 2018-09-12 22:44 UTC
Labels: Bug, In Progress, Workaround Available

**Comment by nielspeen** [comment] 2018-09-13 09:10
I still experience this issue with the latest patches. Every 45 seconds my CPU fan will become noisy, I'll look at **top**, and see onedrive consuming 100% of one CPU core for 3 or 4 seconds.

This only occurs when I have a sizable number of files and directories in my onedrive folder. If I empty it out and put in a handful of test files the issue does not occur. (Or is not noticeable.)

For now, I've set the interval to 86400, which is good enough for remote changes in my situation. Local changes seem to upload instantly regardless of the interval, I'm assuming thanks to inotify.

**Comment by meskaya** [comment] 2018-09-15 07:34
Sorry for the late answer.
Yes I am using code from the pr165
No I am not using verbose to run in monitor but service defaults.

I have around 17400 files in my OneDrive folder and its size is 16G.

What can I do to help ?

**Comment by noskillahh** [comment] 2018-10-12 13:21
My Onedrive folder is about 7.4GB and counts about 100k files. The load goes up to 100% for the duration of the scan. The scan lasts about a minute for my particular onedrive. After the scan completes the duration goes down. I think it fixed the issue for me, as the process used 100% at any time it was running. Now I know that the scan takes about a minute I will change the interval to like 1,5 minute so the intervals dont overlap. Did you change anything in the monitoring process or was the scanning interval changed from doing stuff 24/7 to periodically? Thanks for your work and Im sorry for the late reply.

**Comment by abraunegg** [comment] 2018-10-12 17:33
@noskillahh 
You are better off running v2.1.4 rather than pr165
