### ISSUE TITLE
Building for openSUSE Leap 15.2 & 15.1 fails

### ISSUE THREAD

**Issue by SchoolGuy** [abraunegg/onedrive#1721] opened 2021-11-24 09:57 UTC
### Bug Report Details ###
**Describe the bug**

I am not quite sure but tldr is maybe that the minimum required version of dmd is out of date?

Details: Package builds for openSUSE Tumbleweed and 15.3 quite fine, it does not for 15.2 & 15.1.

Output of the build:

```
[   53s] + make -j8 onedrive
[   53s] if [ -f .git/HEAD ] ; then \
[   53s] 	git describe --tags > version ; \
[   53s] else \
[   53s] 	echo v2.4.14 > version ; \
[   53s] fi
[   53s] dmd  -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/arsd/cgi.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive
[   60s] src/arsd/cgi.d(4229): Error: function `onedrive.OneDriveWebhook.handle` is not accessible from module `cgi`
[   60s] src/arsd/cgi.d(4164): Error: template instance `arsd.cgi.doThreadHttpConnectionGuts!(Cgi, handle, false)` error instantiating
[   60s] src/arsd/cgi.d(3571):        instantiated from here: `doThreadHttpConnection!(Cgi, handle)`
[   60s] src/onedrive.d(166):        instantiated from here: `serveEmbeddedHttp!(handle, Cgi, 5000000L)`
[   64s] make: *** [Makefile:102: onedrive] Error 1
[   64s] error: Bad exit status from /var/tmp/rpm-tmp.KAsfdY (%build)
```

dmd is available in version 2.085.1 according to [this](https://software.opensuse.org/package/dmd) overview.

**Application and Operating System Details:**
*   Provide your OS & version: openSUSE 15.2
*   Are you using a headless system (no gui) or with a gui installed? - Not applicable
*   OneDrive Account Type - Not applicable
*   Did you build from source or install from a package? - Source
*   If you installed from source, what is your DMD or LDC compiler version: 2.085.1
*   OneDrive Application Version: 2.4.14
*   OneDrive Application Configuration: Not applicable
*   Provide the version of curl you are using: Not applicable
*   Is your configured 'sync_dir' a local directory or a network mount point? - Not applicable
*   If *not* local, provide all the mountpoints in your system: Not applicable
*   What partition format type does your configured 'sync_dir' reside on? - Not applicable
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  https://build.opensuse.org/package/show/home:SchoolGuy:branches:network/onedrive
2.  [The build log](https://build.opensuse.org/package/live_build_log/home:SchoolGuy:branches:network/onedrive/openSUSE_Leap_15.2/x86_64)
3.  Scroll down to the end of the page
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**

Not applicable

**Screenshots**

Not applicable

**Additional context**

Not applicable

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output from your error
*   [ ] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-11-24 10:06
@SchoolGuy 
> I am not quite sure but tldr is maybe that the minimum required version of dmd is out of date?

Potentially.

I test with dmd-2.097.0 at present - so distributions using older version may face an issue - maybe.

**Comment by SchoolGuy** [comment] 2021-11-24 10:10
@abraunegg Yeah that that version works is clear by the fact that I can compile for Tumbleweed but it would be nice if we could stay backwards compatible at least for two years (you may pick another timeframe, just a suggestion) of compiler versions. Leap 15.2 was released in July 2020 which is not even two years old.

**Comment by abraunegg** [comment] 2021-11-24 10:32
@SchoolGuy 
Just tested with DMD v 2.093.1 which was released on Jul 7, 2020:
```
Cloning into 'onedrive'...
remote: Enumerating objects: 5192, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (330/330), done.
remote: Total 5192 (delta 337), reused 328 (delta 182), pack-reused 4665
Receiving objects: 100% (5192/5192), 3.75 MiB | 3.23 MiB/s, done.
Resolving deltas: 100% (3581/3581), done.
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.093.1
checking for curl... yes
checking for sqlite... yes
checking for notify... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.14 > version ; \
fi
dmd  -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/arsd/cgi.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive
onedrive v2.4.14
```

**Comment by abraunegg** [comment] 2021-11-24 10:35
@SchoolGuy 
Tested with  v 2.092.0 which was released on May 11, 2020:
```
Cloning into 'onedrive'...
remote: Enumerating objects: 5192, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (324/324), done.
remote: Total 5192 (delta 337), reused 333 (delta 188), pack-reused 4665
Receiving objects: 100% (5192/5192), 3.75 MiB | 3.32 MiB/s, done.
Resolving deltas: 100% (3581/3581), done.
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.092.0
checking for curl... yes
checking for sqlite... yes
checking for notify... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.14 > version ; \
fi
dmd  -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/arsd/cgi.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive
onedrive v2.4.14
```

**Comment by abraunegg** [comment] 2021-11-24 10:36
@SchoolGuy 
Just tested with DMD v 2.091.1 which was released on Apr 18, 2020:
```
Cloning into 'onedrive'...
remote: Enumerating objects: 5192, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (330/330), done.
remote: Total 5192 (delta 337), reused 328 (delta 182), pack-reused 4665
Receiving objects: 100% (5192/5192), 3.75 MiB | 2.85 MiB/s, done.
Resolving deltas: 100% (3581/3581), done.
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.091.1
checking for curl... yes
checking for sqlite... yes
checking for notify... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.14 > version ; \
fi
dmd  -w -g -O -J. -version=NoPragma -version=NoGdk -version=Notifications -L-lcurl -L-lsqlite3 -L-lnotify -L-lgdk_pixbuf-2.0 -L-lgio-2.0 -L-lgobject-2.0 -L-lglib-2.0 -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d src/arsd/cgi.d src/notifications/notify.d src/notifications/dnotify.d -ofonedrive
onedrive v2.4.14
```

**Comment by SchoolGuy** [comment] 2021-11-24 10:38
Okay I guess the problem is then on our side as we are using 2.085.1 which appears to be older. I guess then the last thing to do is to document the new minimal dmd version. You have that documented here: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#building-from-source---high-level-requirements

**Comment by abraunegg** [comment] 2021-11-24 10:38
@SchoolGuy 
Your DMD version was released on  Apr 6, 2019 ...

Maybe get your SuSE 15.x packages updated ?

**Comment by SchoolGuy** [comment] 2021-11-24 10:38
So in theory what I did is valid according to your docs.

**Comment by SchoolGuy** [comment] 2021-11-24 10:38
@abraunegg Yeah I agree. I will try to see what I can do about that...

**Comment by abraunegg** [comment] 2021-11-24 10:40
@SchoolGuy 
> Okay I guess the problem is then on our side as we are using 2.085.1 which appears to be older. I guess then the last thing to do is to document the new minimal dmd version. You have that documented here: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#building-from-source---high-level-requirements

yes - good catch - will need to update this and work out what the new oldest version is

**Comment by Sebo-moz** [comment] 2021-11-24 17:17
Same problem here with a raspbian arm 32bit and ldmd2 version:
 - the LLVM D compiler (1.12.0):
  based on DMD v2.082.1 and LLVM 6.0.1
  built with LDC - the LLVM D compiler (1.12.0)
  Default target: armv6-unknown-linux-gnueabihf
  Host CPU: cortex-a72
  http://dlang.org - http://wiki.dlang.org/LDC

I believe this is the version that is suggested to use by the docs..?

**Comment by abraunegg** [comment] 2021-11-24 18:04
@Sebo-moz
> the LLVM D compiler (1.12.0)

You are actually *not* following the correct process for ARMHF platforms: https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md#dependencies-raspbian-armhf

Suggest that you please follow the correct build process and use the *right* compiler version for ARMHF.

**Comment by Sebo-moz** [comment] 2021-11-24 18:20
> Suggest that you please follow the correct build process and use the _right_ compiler version for ARMHF.

Indeed, I was wrong- sorry!
v1.12.0 is provided by the raspbian buster repository… and shows the above error. 
v1.17.0 is suggested by the docs and works just fine! Thanks

**Comment by abraunegg** [comment] 2021-11-24 19:07
@SchoolGuy 
Documentation has been updated and minimum application versions have been raised:

DMD version >= 2.087.0 or LDC version >= 1.17.0 is required to compile this application

I have confirmed and validated that these are the minimum application versions now due to the inclusion of webhook support.

**Comment by abraunegg** [comment] 2021-11-24 19:08
Closing this issue

**Closed by abraunegg** 2021-11-24 19:08 UTC

**Comment by SchoolGuy** [comment] 2021-11-24 20:18
@abraunegg thanks for the detailed & quick collaboration
