### ISSUE TITLE
moving files into different folders in the synchronized client should not result in reupload of the files again.

### ISSUE THREAD

**Issue by charleshsu168** [abraunegg/onedrive#876] opened 2020-04-18 22:54 UTC
My problem is if I move my  photo files in my desktop computer to another folder, the app will attempt to synchronize again by deleting the original files in the old file location **in the cloud** and re-upload the files again from the desktop's destination folder. This is not efficient. For example, if I move a 1 GB of photo files from folder A to folder B in my desktop computer, the app will attempt to synchronize again by deleting the moved files in Folder A in the cloud and re-upload all the file again from folder B in the desktop folder into the cloud. This is very slow to upload 1 GB of photos when it's already in the cloud. A better way would be to just move the cloud files from Folder A to Folder B in the same way as the desktop client so there is no need to re-upload again.

**Describe the solution you'd like**
The idea solution will be to just move the files in the cloud  to a different folder the same way the desktop move the files into a different folder.

**Describe alternatives you've considered**
None. I don't think there is any other alternative.

**Additional context**

**Comment by abraunegg** [comment] 2020-04-18 23:09
@charleshsu168 
Please can you provide some more details here - like what version of the client you are running and its configuration.

The application utilises move location correctly, so I really need:

* application version details
* application configuration
* verbose debug file

**Comment by abraunegg** [comment] 2020-04-18 23:43
@charleshsu168 
Unable to even reproduce this sort of behavior.

initial local directory view:
```
[alex@centos7full OneDrivePersonal]$ tree -dl
.
├── random_files -> /home/alex/OneDrive/random_files/
├── random_images -> /home/alex/OneDrive/random_images/
│   ├── 2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C
│   ├── aLAn3kJxe5BSzwqzwwKQ1a7Geg181zl2
│   ├── Bd7FJhTdX7QEmeFDe6gFYhCoc5TvW9rt
│   ├── Dzit1grJuyh4Zpmot3byiugB8XCSpHGx
│   ├── g0QoQpyS31H5Yg6aBwSvhVeZ4pIBoOqL
│   ├── JXWE73JI8vspteiyxzRSIYI5b3kU8Q3Z
│   ├── NG42nmfTP805bfImlD4NHFHqSgGlID8s
│   ├── sx6Ugst5705ITtxmkuapU4HZuybVxtUo
│   ├── WNWBW2lIyAkucseNRsKKB4plccFZwXhq
│   └── YhA5Eq4rwi32pHaHK5Ks8LapeDoUWnPZ
└── random_videos -> /home/alex/OneDrive/random_videos/

13 directories
[alex@centos7full OneDrivePersonal]$ 
```

make a new local directory and move:
```
[alex@centos7full OneDrivePersonal]$ mkdir new_location
[alex@centos7full OneDrivePersonal]$ mv random_images/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C ./new_location/
[alex@centos7full OneDrivePersonal]$ tree -dl          
.
├── new_location
│   └── 2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C
├── random_files -> /home/alex/OneDrive/random_files/
├── random_images -> /home/alex/OneDrive/random_images/
│   ├── aLAn3kJxe5BSzwqzwwKQ1a7Geg181zl2
│   ├── Bd7FJhTdX7QEmeFDe6gFYhCoc5TvW9rt
│   ├── Dzit1grJuyh4Zpmot3byiugB8XCSpHGx
│   ├── g0QoQpyS31H5Yg6aBwSvhVeZ4pIBoOqL
│   ├── JXWE73JI8vspteiyxzRSIYI5b3kU8Q3Z
│   ├── NG42nmfTP805bfImlD4NHFHqSgGlID8s
│   ├── sx6Ugst5705ITtxmkuapU4HZuybVxtUo
│   ├── WNWBW2lIyAkucseNRsKKB4plccFZwXhq
│   └── YhA5Eq4rwi32pHaHK5Ks8LapeDoUWnPZ
└── random_videos -> /home/alex/OneDrive/random_videos/

14 directories
[alex@centos7full OneDrivePersonal]$ 

```

Coresponding move location:
```
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Sync with OneDrive is complete
Monitor directory: ./new_location
[M] Directory created: ./new_location
Uploading differences of ./new_location
Uploading new items of ./new_location
OneDrive Client requested to create remote path: ./new_location
The requested directory to create was not found on OneDrive - creating remote directory: ./new_location
Successfully created the remote directory ./new_location on OneDrive
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 6 changes
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 52 changes
Sync with OneDrive is complete
Monitor directory: new_location/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C
[M] Item moved: random_images/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C -> new_location/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C
Moving random_images/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C to new_location/2rmdTCIFQArp7EvaoNFFTb2cafCSOK6C
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 6 changes
Sync with OneDrive is complete
```

Files moved to new location without re-upload

So I really need from you:

* application version details
* application configuration
* verbose debug file


Most likely this is an old code / skilion code issue as well ... I have no idea unless you can provide the details I am requesting.

**Comment by charleshsu168** [comment] 2020-04-18 23:49
I forgot to mention that big delete was detected. So I used --force command in order to synchronize which is probably why the files are deleted instead of updating locations

**Comment by abraunegg** [comment] 2020-04-18 23:53
@charleshsu168 
Please can you update your first post and convert this to bug report, provide all the details as per the bug report template: https://github.com/abraunegg/onedrive/issues/new?template=bug_report.md

I also really need from you:

* application version details
* application configuration
* verbose debug file

**Comment by charleshsu168** [comment] 2020-04-19 00:03
$ onedrive --display-config
onedrive version                       = v2.4.0-9-gc41adda
Config path                            = /home/rootchuck/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/rootchuck/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false

I did not used debug-verbose when I initially found this problem. So I do not have debug log. May need to recreate again this problem to generate new debug log

**Comment by abraunegg** [comment] 2020-04-19 06:08
Able to reproduce this - this is a VERY corner edge case however:

* Use `--synchronize` for a manual sync
* Ensure system is in-sync
* Move local folder from A -> B
* Use `--synchronize` for a manual sync

Technically, the client is 'working' correctly, as, when moving files, you are 'deleting' them from the current location, but copying them to the 'new location'. As the client is running in manual sync mode, there is no way to track what OS operations have been done when the client is not running - thus, this is why the 'delete and upload' is occurring.

Investigating how best to solve this, as, if you have millions of folders, searching for a moved folder if it is still present, is not really a good way to solve this.

**Comment by abraunegg** [comment] 2020-04-19 06:09
If using `--monitor` this issue does not exist, as, the move is detected and used correctly.

**Comment by abraunegg** [comment] 2020-04-20 02:36
After discussions offline, marking this as not a bug, not an issue, workaround available

**Closed** 2020-04-20 02:37 UTC
Labels: Not a bug, Workaround Available
