### ISSUE TITLE
--no-remote-delete flag being ignored when using --monitor

### ISSUE THREAD

**Issue by id2test2** [abraunegg/onedrive#702] opened 2019-10-26 21:00 UTC
Hello,

### Bug Report Details ###
Using flags:  --upload-only --no-remote-delete

**Application and Operating System Details:**
Reproduces with several versions of OneDrive, also the latest, for several OS-es

Steps to reproduce the behavior if not causing an application crash:
1.  Create a new file
2.  Log file shows: uploading new file <folder/filename> ... done.
3.  Delete the file
4.  Log file shows: Deleting item from OneDrive: <folder/filename>

--no-remote-delete means: Do not delete local file 'deletes' from OneDrive when using --upload-only
But the file gets deleted anyway?

onedrive is running as a user service:
```
ExecStart=/home/user/Programs/onedrive/onedrive --upload-only --no-remote-delete --syncdir /home/user/userFiles --enable-logging --log-dir /home/user/Temp/OneDriveLogs/ --monitor
```
```
onedrive --version
onedrive v2.3.10-12-g585b357
```
```
2019-Oct-27 12:19:16.5527075 Initializing the OneDrive API ...
2019-Oct-27 12:19:16.627076 Opening the item database ...
2019-Oct-27 12:19:16.6282758 All operations will be performed in: /home/user/userFiles
2019-Oct-27 12:19:18.1440947 Application version: v2.3.10-12-g585b357
...
2019-Oct-27 12:21:51.1931215 [M] File changed: SpecFileCreating_files/newtextfile.txt
2019-Oct-27 12:21:51.1933496 Uploading differences of SpecFileCreating_files/newtextfile.txt
2019-Oct-27 12:21:51.1936085 Uploading new items of SpecFileCreating_files/newtextfile.txt
2019-Oct-27 12:21:51.9574599 Uploading new file SpecFileCreating_files/newtextfile.txt ... done.
2019-Oct-27 12:21:52.423285 Remaining free space: 12307526951
2019-Oct-27 12:22:12.9265711 [M] Item deleted: SpecFileCreating_files/newtextfile.txt
2019-Oct-27 12:22:12.92738 Deleting item from OneDrive: SpecFileCreating_files/newtextfile.txt
...
2019-Oct-27 12:23:05.830985 [M] File changed: NFS/newtextfile.txt
2019-Oct-27 12:23:05.8310943 Uploading differences of NFS/newtextfile.txt
2019-Oct-27 12:23:05.8313031 Uploading new items of NFS/newtextfile.txt
2019-Oct-27 12:23:06.5601561 Uploading new file NFS/newtextfile.txt ... done.
2019-Oct-27 12:23:07.1442879 Remaining free space: 12307526951
2019-Oct-27 12:23:11.1450667 [M] Item deleted: NFS/newtextfile.txt
2019-Oct-27 12:23:11.1454052 Deleting item from OneDrive: NFS/newtextfile.txt
```

Thx for looking into this.
Regards, Ids.

**Comment by abraunegg** [comment] 2019-10-26 21:22
@id2test2 
Please can you update your first post above with all the required information that is needed when submitting an issue as per https://github.com/abraunegg/onedrive/blob/master/README.md#reporting-issues as you have not filled in the issue report using the template.

You also have not provided any verbose log or debug log.

Please update your post and provide the required information.

**Comment by abraunegg** [comment] 2019-10-26 21:32
@id2test2 
Unable to reproduce - so this is issue is invalid until you can provide the details as per requested:

**initial upload**
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --upload-only --no-remote-delete
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-13-ge99872e
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Uploading new file ./newfile.txt ... done.
Remaining free space: 5368709108
(dmd-2.085.0)[alex@centos7full onedrive]$ 
```
issue file delete locally

**sync again**
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --upload-only --no-remote-delete
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-13-ge99872e
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709108
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of .
Processing root
The directory has not changed
Processing newfile.txt
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
Uploading new items of .
(dmd-2.085.0)[alex@centos7full onedrive]$ 
```

File still exists on OneDrive:
![upload-no-remote-delete](https://user-images.githubusercontent.com/4956234/67626234-40f29a00-f894-11e9-8c69-a9fae8370fa9.jpg)

**Comment by id2test2** [comment] 2019-10-27 12:13
Added part of verbose log file in initial post.
File was created and deleted without stopping onedrive in between.

**Comment by id2test2** [comment] 2019-10-27 15:19
I just did a new clone/build on another machine.
D compiler version is 2.088.1.
This shows the same behavior:
./onedrive --upload-only --no-remote-delete --syncdir /home/user/Temp --monitor
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Uploading modified file test.txt ... skipped.
Uploading modified file ./test.txt ... done.
Deleting item from OneDrive: ./test.txt

**Comment by id2test2** [comment] 2019-10-27 15:28
If I do not run with '--monitor', but with '--synchronize' 2 times and delete the file between the 2 runs, the '--no-remote-delete' switch works as expected:
```
Processing test.txt
The file has been deleted locally
Skipping remote file delete as --upload-only & --no-remote-delete configured
```
So the issue is related to onedrive's monitoring feature.

**Comment by abraunegg** [comment] 2019-10-27 18:44
@id2test2 
Thanks for the extra details. In monitor mode, the calls to delete are direct, based on the inotify call.

Please can you test the following PR:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/703/head:pr703
git checkout pr703
./configure; make clean; make;
```

Also, please note - this now changes also the behavior of --monitor mode when using those flags - if your creating any file, even the temporary file that gets created will be uploaded and not deleted. This potentially means you 'may' get many unwanted files hanging around.

**Comment by id2test2** [comment] 2019-10-27 20:23
Thx for the quick update.

The fix works perfectly:
```
2019-Oct-27 21:11:51.2577224 Uploading new file ./Hide-Tabbar/newtextfile.txt ... done.
2019-Oct-27 21:11:51.8521459 Remaining free space: 12303772188
2019-Oct-27 21:12:30.8979541 [M] Item deleted: Hide-Tabbar/newtextfile.txt
2019-Oct-27 21:12:30.8983143 Skipping remote delete as --upload-only & --no-remote-delete configured

```
The file remains on onedrive.
I do exclude temporary directories and temporary files to prevent these from getting uploaded.

Thank you very much for the quick solution and explanation.
Regards, Ids.

**Comment by abraunegg** [comment] 2019-10-29 18:10
@id2test2 
Closing issue as PR #703 merged into master

**Closed by abraunegg** 2019-10-29 18:10 UTC
Labels: Bug, Fixed
