### ISSUE TITLE
src/itemdb.d(346): Assertion failure - invalid token?

### ISSUE THREAD

**Issue by shoffmeister** [abraunegg/onedrive#199] opened 2018-10-15 11:51 UTC
### Bug Report Details ###
**Describe the bug**

Assertion failure: core.exception.AssertError@src/itemdb.d(346): Assertion failure
Probably should be a real exception.

**Application and Operating System Details:**
- Fedora 28
- Console
- onedrive v2.1.4-3-g1c23d01

- OneDrive Business
- dmd-2.082.1

**To Reproduce**
* have existing OneDrive directory, onedrive self-compiled, worked
// implies existing token
* run onedrive --synchronize
// assertion failure
* rm ~/.config/onedrive/refresh_token
* run onedrive --synchronize
// asks for auth, comply, do
// synchronizes

It would seem as if a stale token may lead to such a situation; I recall having had to (re)register my device on the corporate portal (thus losing the token, in a way); on top, the token must have been some weeks old.

In any event, it would seem that terminating was right, but the diagnostic not fully enabling insight what was going on. 

**Additional context**
```
(dmd-2.082.1)[me@localhost onedrive]$ ./onedrive --synchronize

Unable to create /var/log/onedrive/ 
Please manually create /var/log/onedrive/ and set appropriate permissions to allow write access
The client activity log will be located in the users home directory

Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
core.exception.AssertError@src/itemdb.d(346): Assertion failure
----------------
??:? _d_assertp [0x5cc61d]
src/itemdb.d:347 immutable(char)[] itemdb.ItemDatabase.getDeltaLink(const(char)[], const(char)[]) [0x5997f4]
src/sync.d:362 void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x5b8d9f]
src/sync.d:223 void sync.SyncEngine.applyDifferences() [0x5b8715]
src/main.d:443 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x59daea]
src/main.d:312 _Dmain [0x59d380]
(dmd-2.082.1)[me@localhost onedrive]$ source ~/dlang/dmd-2.082.1/activate^C
(dmd-2.082.1)[me@localhost onedrive]$ ./onedrive --synchronize
```
### Bug Report Checklist ###
- [x] Detailed description
- [x] Reproduction steps (if applicable)
- [ ] Verbose Log Output

**Comment by abraunegg** [comment] 2018-10-15 12:05
Unable to reproduce this at the moment - will look at this a little more tomorrow

**Comment by abraunegg** [comment] 2018-10-18 20:05
> It would seem as if a stale token may lead to such a situation; I recall having had to (re)register my device on the corporate portal (thus losing the token, in a way); on top, the token must have been some weeks old.

Looking & walking through the code, I don't believe this is / was the case. I suspect that your connection to OneDrive did not return some valid responses, but provided enough of a response at initialisation that key value pairs were present but without data - but as you ran without the `--verbose` flag there is no evidence of what was returned.

The code currently checks to ensure that a valid response was provided however, so the only other question when it comes database issues is - were you originally using the 'skilion' codebase and upgraded to this codebase?

The 'skilion' codebase has horrid database entry completeness - so it if plausible that if the local cache file did not get upgraded correctly, then when querying an entry this failed at your first run.

As I can't reproduce this at all in any way shape or form under Fedora 28, I am closing this case.

Yes - it should not crash in the way it did (yes that is a bug) - but the code already checks to ensure there is valid entry points of data, so this points to the local DB cache not being upgraded thus causing the crash.

**Closed by abraunegg** 2018-10-18 20:05 UTC
Labels: Investigating

**Comment by kirmonkey** [comment] 2018-10-27 10:50
I had this issue. It was due to my changing my OneDrive password.

**Comment by shoffmeister** [comment] 2018-10-27 12:31
To add - I have always been running this codebase off git master, always self-compiled, always on Fedora 28.

Some code path seems to not be perfectly covered, thus leading to an assert (and I am actually sort of ok with asserts, much better than silent failure leading to god-knows-what).

**Comment by abraunegg** [comment] 2018-10-27 20:02
> Some code path seems to not be perfectly covered, thus leading to an assert

If you get issues - please let me know so it can be fixed
