### ISSUE TITLE
skip_dir skipping relative folders

### ISSUE THREAD

**Issue by hugomilan** [abraunegg/onedrive#699] opened 2019-10-24 21:40 UTC
### Bug Report Details ###
When you write skip_dir = "Documents|something else", onedrive will skip all Documents folders, even if they are in a subdirectory, for example, "important/Documents".

**Application and Operating System Details:**
*   OS: Linux pop-os 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
*   GNOME 3.32.2
*   OneDrive Account Type: Personal
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`: dmd-2.088.1
*   Application configuration: Output of `onedrive --display-config`:
```
onedrive version                    = v2.3.10-14-g6b04763
Config path                         = /home/hugomilan/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/hugomilan/OneDrive
Config option 'skip_dir'            = *_site*|Anexos de email|Computação|Cornell/Fall 2015-2016|Cornell/2016*|Cornell/2017*|Cornell/2018*|Cornell/2019 S*|Cornell/Artigos|Cornell/Fields for minor|Cornell/Others/Alex/22 ICB/website/Freelancer/website_*|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/html|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/latex|Cornell/Publications/2018/Piglets 2013/code|Documentos|Documents|Doutorado|MaiaFR|Mestrado|Outros/Experimento Julho 2016|Imagens/Imagens da Câmera/HVL|Imagens/Imagens da Câmera/200*|Imagens/Imagens da Câmera/2010|Imagens/Imagens da Câmera/2011|Imagens/Imagens da Câmera/2012|Imagens/Imagens da Câmera/2013|Imagens/Imagens da Câmera/2014|Imagens/Imagens da Câmera/2015|Imagens/Imagens da Câmera/2016|Imagens/Imagens da Câmera/2017|Imagens/Imagens da Câmera/2018|Imagens/Imagens da Câmera/Outros|Imagens/Imagens da Câmera/photogrammetry|Imagens/Capturas de tela|Imagens/Imagens salvas
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

*   Curl Version: Output of `curl --version`:
```
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

debug sent.

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Configure skip_dir = "Documents|something else"
2. Create folders "Documents" and "Important/Documents"
3. Onedrive skips both folders.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
The output of grep might help:
```bash
grep "Documents" debug_output.log
[DEBUG] skip_dir: *_site*|Anexos de email|Computação|Cornell/Fall 2015-2016|Cornell/2016*|Cornell/2017*|Cornell/2018*|Cornell/2019 S*|Cornell/Artigos|Cornell/Fields for minor|Cornell/Others/Alex/22 ICB/website/Freelancer/website_*|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/html|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/latex|Cornell/Publications/2018/Piglets 2013/code|Documentos|Documents|Doutorado|MaiaFR|Mestrado|Outros/Experimento Julho 2016|Imagens/Imagens da Câmera/HVL|Imagens/Imagens da Câmera/200*|Imagens/Imagens da Câmera/2010|Imagens/Imagens da Câmera/2011|Imagens/Imagens da Câmera/2012|Imagens/Imagens da Câmera/2013|Imagens/Imagens da Câmera/2014|Imagens/Imagens da Câmera/2015|Imagens/Imagens da Câmera/2016|Imagens/Imagens da Câmera/2017|Imagens/Imagens da Câmera/2018|Imagens/Imagens da Câmera/Outros|Imagens/Imagens da Câmera/photogrammetry|Imagens/Capturas de tela|Imagens/Imagens salvas
Processing Other Documents.docx
[DEBUG] Checking file: ./Cornell/Others/Job application/Nebraska/position/Other Documents.docx
[DEBUG] Checking path: ./Cornell/Others/Alex/JTEE/Edital 2020/V01/Documents
Skipping item - excluded by skip_dir config: ./Cornell/Others/Alex/JTEE/Edital 2020/V01/Documents
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by abraunegg** [comment] 2019-10-24 21:45
This is not a bug - as you have configured to skip 'Documents' of which both match and are skipped as per directed. Will see if there is a workaround

**Comment by hugomilan** [comment] 2019-10-24 21:46
What if we specify the base directory? For example, "~/Documents"?

**Comment by abraunegg** [comment] 2019-10-25 19:20
@hugomilan 
Will have to think on this issue and whiteboard it - as, the existing use case is to skip any match or full path match of each entry. What you are suggesting here is to only make it a relative / full path match, which would break the existing use cases.

**Comment by abraunegg** [comment] 2020-01-07 05:54
@hugomilan 
Please can you test the following PR against your use case:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/768/head:pr768
git checkout pr768
./configure; make clean; make;
```

To use strict matching when using skip_dir, utilise `--skip-dir-strict-match` or configure the applicable option in the updated config file.

**Example: **
```
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ ./onedrive ./onedrive --confdir '~/.config/onedrive-personal/' --display-config
onedrive version                       = v2.3.13-6-g38aa7f0
Config path                            = /home/alex/.config/onedrive-personal/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alex/OneDrivePersonal
Config option 'skip_dir'               = Documents|something else
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ 
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.13-6-g38aa7f0
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Skipping item - excluded by skip_dir config: ./Documents
OneDrive Client requested to create remote path: ./Important
The requested directory to create was not found on OneDrive - creating remote directory: ./Important
Successfully created the remote directory ./Important on OneDrive
Skipping item - excluded by skip_dir config: ./Important/Documents
Applying changes of Path ID: 66D53BE8A5056ECA!101
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ 
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose --skip-dir-strict-match
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
skipDirStrictMatch = true
Application version: v2.3.13-6-g38aa7f0
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing Important
The directory has not changed
Uploading new items of .
Skipping item - excluded by skip_dir config: ./Documents
OneDrive Client requested to create remote path: ./Important/Documents
The requested directory to create was not found on OneDrive - creating remote directory: ./Important/Documents
Successfully created the remote directory ./Important/Documents on OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
(dmd-2.085.0)[alex@centos7full fix-issue-699]$ 
```

**Comment by hugomilan** [comment] 2020-01-08 01:49
I am sorry but I am unable to perform such tests in the foreseeable future.

**Comment by abraunegg** [comment] 2020-01-29 05:38
Closing issue as PR #768 merged into master

**Closed by abraunegg** 2020-01-29 05:38 UTC
Labels: Enhancement, Implemented, Not a bug
