### ISSUE TITLE
Bug: Moving folders does not get synced when target is excluded by 'skip_dir'

### ISSUE THREAD

**Issue by RimuruChan** [abraunegg/onedrive#2292] opened 2023-01-16 13:07 UTC
### Describe the bug

I have a shared folder on Onedrive. One of the folders in the shared folder was moved out of the shared folder via the website to a folder that skipped sync, but the act of moving it out was not synced on my server. Logically, this folder should be deleted on the server, but on my server, the folder I moved out of the shared folder is still in that shared folder and the path has not changed. If I manually delete this folder on the server, it instead deletes the folder located in the new location in Onedrive.

### Operating System Details

```shell
Linux [private] 5.15.74-1-lts #1 SMP Sat, 15 Oct 2022 06:43:47 +0000 x86_64 GNU/Linux
```

### Client Installation Method

From Distribution Package

### OneDrive Account Type

Business | Office365

### What is your OneDrive Application Version

onedrive v2.4.22

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.22
Config path                                  = /root/.config/onedrive
Config file found in config path             = true
Config option 'sync_dir'                     = /root/OneDrive
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = TheSharedFolder/AFolderIDontWantToSync|TheFolderIMovedInto
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 60
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0
Release-Date: 2022-08-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=1001448k,nr_inodes=250362,mode=755,inode64)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)
/dev/vda1 on / type ext4 (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11981)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,size=1012256k,nr_inodes=1048576,inode64)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=202448k,nr_inodes=50612,mode=700,inode64)
```

### What are all your local file system partition types

```shell
NAME   FSTYPE  FSVER            LABEL    UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
sr0    iso9660 Joliet Extension config-2 2022-07-05-16-36-05-00                              
vda                                                                                          
└─vda1 ext4    1.0                       659e6f89-71fa-463d-842e-ccdf2c06e0fe   22.4G    50% /
```

### How do you use 'onedrive'

I have a server, and my Windows PC, each with an Onedrive client. After I moved a folder inside the shared folder to outside the shared folder (another skip synced folder) via the website, there is no sync on my server.

### Steps to reproduce the behaviour

1. Create a shared folder a, create a folder b in a, and deposit some files
2. Create a general folder c, side by side with a, and set c as an unsynchronized folder in the configuration
3. move b from a to c

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /root/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Checking Application Version ...

WARNING: Your onedrive client version is obsolete and unsupported. Please upgrade your client version.
Application version: 2.4.22
Version available:   2.4.23

Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
Opening the item database ...
All operations will be performed in: /root/OneDrive
Application version: v2.4.22
Account Type: business
Default Drive ID: [private]
Default Root ID: [private]
Remaining Free Space: 5383180713160
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Applying changes of Path ID: [private]
Updated Remaining Free Space: 5383180713160
Processing 252 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config: TheFolderIMovedInto
Moving TheSharedFolder to ./TheSharedFolder
Destination is in sync and will be overwritten
Skipping item - excluded by skip_dir config: TheSharedFolder/AFolderIDontWantToSync
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDrive
Processing .
The directory has not changed
Processing TheSharedFolder
The directory has not changed
Processing TheSharedFolder/TheFolderIMovedOut
The directory has not changed
Processing TheSharedFolder/TheFolderIMovedOut/SomeFiles
The file has not changed
Uploading new items of ~/OneDrive
Applying changes of Path ID: [private]
Updated Remaining Free Space: 5383180713160
Sync with OneDrive is complete
```

**Comment by abraunegg** [comment] 2023-01-16 21:13
@RimuruChan 
I have tried to reproduce this, and I am unable to reproduce the same scenario and situation you are seeing.

**Files Online:**
![image](https://user-images.githubusercontent.com/4956234/212765372-2536b8ad-5add-493f-b388-00e82820f4e0.png)

![image](https://user-images.githubusercontent.com/4956234/212765428-2d70e29f-4bf5-400e-819c-b67ee25b98b8.png)


**Client Configuration:**
```
Configuration file successfully loaded
onedrive version                             = v2.4.23-1-gc10870a
Config path                                  = /home/alex/.config/onedrive-business
Config file found in config path             = true
Config option 'sync_dir'                     = /home/alex/OneDriveBusiness
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = target_excluded
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

**Objective:**
Move 'folder_b' from /source -> /target_excluded online

What I am seeing however, is that the 'online' move is 'skipped' because the new 'parent' is skipped by 'skip_dir'. This is 100% correct behavior.

```
Using 'user' Config Dir: /home/alex/.config/onedrive-business
Configuration file successfully loaded
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.23-1-gc10870a
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1096595508634
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1096595508634
Number of items from OneDrive to process: 3
Skipping item - excluded by skip_dir config: target_excluded     <-- THIS IS THE MOVE CHANGE
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Processing source
The directory has not changed
Processing source/folder_a
The directory has not changed
Processing source/folder_a/solaris crash.docx
The file has not changed
Processing source/folder_a/Remove Ubuntu Package.docx
The file has not changed
Processing source/folder_b
The directory has not changed
Processing source/folder_b/Remove Ubuntu Package.pdf
The file has not changed
Processing source/folder_b/Rebrickable inventory for 928-1_ Space Cruiser And Moonbase _ Brickset_ LEGO set guide and database.pdf
The file has not changed
Uploading new items of ~/OneDriveBusiness
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Updated Remaining Free Space: 1096595508634
Sync with OneDrive is complete

```

When looking at the debug logs this is evident:
```
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 3 of 3
[DEBUG] OneDrive Change: {"@odata.etag":"\"{ACCC3099-3EEA-4735-B5B1-6820BC45E251},8\"","@odata.type":"#microsoft.graph.driveItem","cTag":"\"c:{ACCC3099-3EEA-4735-B5B1-6820BC45E251},0\"","eTag":"\"{ACCC3099-3EEA-4735-B5B1-6820BC45E251},8\"","fileSystemInfo":{"createdDateTime":"2023-01-16T20:39:13Z","lastModifiedDateTime":"2023-01-16T21:10:14Z"},"folder":{"childCount":2},"id":"01WIXGO5UZGDGKZ2R6GVD3LMLIEC6ELYSR","name":"folder_b","parentReference":{"driveId":"b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA","driveType":"business","id":"01WIXGO5Q47SNDPE3BU5CIGWXZES5PZGBE","path":"\/drives\/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA\/root:\/target_excluded"},"size":4832575}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
[DEBUG] 'search id'                                          = 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
[DEBUG] id == defaultRootId                                  = true
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = 01WIXGO5Q47SNDPE3BU5CIGWXZES5PZGBE
[DEBUG] search criteria: syncFolderName                      = root
[DEBUG] search criteria: syncFolderPath                      = 
[DEBUG] search criteria: syncFolderChildPath                 = 
[DEBUG] thisItemId                                           = 01WIXGO5UZGDGKZ2R6GVD3LMLIEC6ELYSR
[DEBUG] thisItemParentPath                                   = /drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA/root:/target_excluded
[DEBUG] thisItemFullPath                                     = /drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA/root:/target_excluded/folder_b
[DEBUG] 'item id' matches search 'id'                        = false
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemParentPath' contains 'syncFolderChildPath'  = true
[DEBUG] 'thisItemParentPath' contains search 'id'            = false
[DEBUG] Change matches search criteria to apply
[DEBUG] Flagging as unwanted: find(item.parentId).length != 0
[DEBUG] This item was previously synced / seen by the client
[DEBUG] Skipping OneDrive change as this is determined to be unwanted
```


What you are seeing is a *quirk* of 'client side filtering'. 

OneDrive was written with the major assumption that whatever is done online is 100% done local, however with this client we have 'client side filtering' through a number of options such as 'skip_file', 'skip_dir' and 'sync_list' - this means that what OneDrive sends as commands and items to perform are not, depending on client configuration, performed locally.

Technically, as you are using 'skip_dir' to exclude the destination of your folder move online, the client *should* be correctly excluding any operation that matches a 'skip_dir' rule. As the 'move' does not happen (it is excluded), the data remains locally.

### What I need from you:
1. Better reproduction steps
2. Debug logs

If this is is not possible, then this issue cannot be looked at any further.

Right now, I am going to classify this as not a bug (an operational gotcha - yes, but not a bug).

### Your options to fix
#### Option 1
1. Stop any applicable client from running
2. Remove the offending local directory|directories locally
3. Perform a resync using `--resync`

#### Option 2
1. Stop any applicable client from running
2. Run the client manually using `--synchronize --verbose --download-only --cleanup-local-files --resync`:
```
Using 'user' Config Dir: /home/alex/.config/onedrive-business
Configuration file successfully loaded

The use of --resync will remove your local 'onedrive' client state, thus no record will exist regarding your current 'sync status'
This has the potential to overwrite local versions of files with potentially older versions downloaded from OneDrive which can lead to data loss
If in-doubt, backup your local data first before proceeding with --resync

Are you sure you wish to proceed with --resync? [Y/N] y

Deleting the saved application sync status ...
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.23-1-gc10870a
Account Type: business
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 1096595508634
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
WARNING: Application has been configured to cleanup local files that are not present online.
WARNING: Local data loss MAY occur in this scenario if you are expecting data to remain archived locally.
Syncing changes and items from OneDrive ...
Applying changes of Path ID: <redacted>
Updated Remaining Free Space: 1096595508634
Processing 9 OneDrive items to ensure consistent local state
Skipping item - excluded by skip_dir config: target_excluded
Searching local filesystem for extra files and folders which need to be removed
Removing local directory as --download-only & --cleanup-local-files configured
Removing local file: ./source/folder_b/Remove Ubuntu Package.pdf
Removing local file: ./source/folder_b/Rebrickable inventory for 928-1_ Space Cruiser And Moonbase _ Brickset_ LEGO set guide and database.pdf
Removing local directory: ./source/folder_b
Sync with OneDrive is complete
```

**Comment by RimuruChan** [comment] 2023-01-17 00:28
Thank you for your answer. Personally, I would like to have the folder automatically deleted after other clients move it to the skipped folder. Is it possible to add any option to change this behavior?

**Comment by abraunegg** [comment] 2023-01-17 01:00
> Thank you for your answer. Personally, I would like to have the folder automatically deleted after other clients move it to the skipped folder. Is it possible to add any config option to change this behavior?

Can you:

* Provide debug logs
* Provide clearer reproduction steps

**Comment by RimuruChan** [comment] 2023-01-17 04:49
> > Thank you for your answer. Personally, I would like to have the folder automatically deleted after other clients move it to the skipped folder. Is it possible to add any config option to change this behavior?
> 
> Can you:
> 
> * Provide debug logs
> * Provide clearer reproduction steps

> What I am seeing however, is that the 'online' move is 'skipped' because the new 'parent' is skipped by 'skip_dir'. This is 100% correct behavior.

Sorry but as you said, this is not a bug. It's a correct behavior.

> I would like to have the folder automatically deleted after other clients move it to the skipped folder. Is it possible to add any config option to change this behavior?

Maybe I should recreate a feature request ?

**Comment by abraunegg** [comment] 2023-01-17 05:39
@RimuruChan 
> Maybe I should recreate a feature request ?

Given that there already is this capability as per 'Option 2' above to clean up residual local files, that feature request would be rather redundant.

The whole point of *not* automatically deleting data, is to ensure data integrity & avoid data loss situations.

Having files | folders automatically deleted locally, because they were moved online, to a directory that is specifically being skipped locally is a highly undesirable position.

Closing this issue.

**Closed by abraunegg** 2023-01-17 05:39 UTC
Labels: Investigating, More Information Needed, Workaround Available, Not a bug, Waiting on Response, Unable to reproduce

**Comment by abraunegg** [comment] 2023-01-25 01:50
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
