### ISSUE TITLE
ERROR: Unable to query OneDrive to initialize application

### ISSUE THREAD

**Issue by ronnyon** [abraunegg/onedrive#795] opened 2020-02-11 08:21 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When trying to run onedrive sync first time (with or without dryrun), I am getting ERROR: Unable to query OneDrive to initialize application.

**Application and Operating System Details:**
*   OS: Ubuntu 18.04
Linux N-PF1L4Q48 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
*   Are you using a headless system (no gui) or with a gui installed?  
GUI
*   OneDrive Account Type
Office365
*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
dmd-2.090.1
*   Application configuration: Output of `onedrive --display-config`
```
onedrive version                       = v2.3.13-13-g1f6c568
Config path                            = /home/ronon/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/ronon/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 45
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync configured              = false
```

*   Curl Version: Output of `curl --version`
```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
```

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to onedrive
2.  Run "onedrive --synchronize --verbose --dry-run --enable-logging"
4.  See error

[debug_output.log](https://github.com/abraunegg/onedrive/files/4184654/debug_output.log)
**Complete Verbose Log Output**
See attached debug log

**Comment by abraunegg** [comment] 2020-02-11 08:47
@ronnyon 
Most likely this will be a firewall / network related issue.

To verify this - please generate a HTTPS debug log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by ronnyon** [comment] 2020-02-11 08:56
See attached HTTPS debug log
[debug_output.log](https://github.com/abraunegg/onedrive/files/4184758/debug_output.log)

**Comment by ronnyon** [comment] 2020-02-11 08:59
See attached log without the authorization ...
[debug_output.log](https://github.com/abraunegg/onedrive/files/4184770/debug_output.log)

**Comment by abraunegg** [comment] 2020-02-11 09:08
@ronnyon 
Thanks - so in the logs you are getting this:
```
< HTTP/1.1 429 
< Cache-Control: private
< Content-Type: application/json
< Retry-After: 120
< request-id: 24d38501-ffe1-4d11-8f00-092ec87d971e
< client-request-id: 24d38501-ffe1-4d11-8f00-092ec87d971e
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"000","RoleInstance":"AGSFE_IN_44"}}
< Strict-Transport-Security: max-age=31536000
< Date: Tue, 11 Feb 2020 08:55:12 GMT
< Content-Length: 236
< 
OneDrive HTTP Server Response: 429
```
This means essentially - too many requests in a certain time window.

Essentially your requests are being blocked for the moment. As this is in the 'initial account auth' process, not much else can be done, except wait your time because you are somehow giving yourself a DoS attack.

What can be done - increased messaging in the application if a 429 is received to make the reason for failure clearer - other than that, not much else can be done.

**Comment by abraunegg** [comment] 2020-02-11 09:36
PR #796 created to add more details around initialization failure when a HTTPS 429 error is received

**Comment by ronnyon** [comment] 2020-02-11 09:38
Thanks for the feedback.
From the searches I did for HTTP response 429, I will wait 24 hours to see if it will be solved.

**Comment by abraunegg** [comment] 2020-02-11 19:17
@ronnyon 
PR #796 merged into master, so if you rebuild your client from 'master' you should now get a different error message if this issue is persisting.

**Comment by abraunegg** [comment] 2020-02-12 07:08
@ronnyon 
Any update on your issue ?

**Comment by ronnyon** [comment] 2020-02-12 08:03
After 24 hours passed, I am still getting the same error:

OneDrive HTTP Server Response: 429
* Connection #1 to host 10.144.1.10 left intact
ERROR: Unable to query OneDrive to initialize application

**Comment by abraunegg** [comment] 2020-02-12 08:08
@ronnyon 
As you have an Office365 account, please raise this with Microsoft.

**Comment by abraunegg** [comment] 2020-02-12 21:09
@ronnyon 
The other aspect is in your logs you have the following:
```
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
*   Trying 10.144.1.10...
* TCP_NODELAY set
* Connected to 10.144.1.10 (10.144.1.10) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to login.microsoftonline.com:443
> CONNECT login.microsoftonline.com:443 HTTP/1.1
Host: login.microsoftonline.com:443
User-Agent: OneDrive Client for Linux v2.3.13-13-g1f6c568
Proxy-Connection: Keep-Alive

< HTTP/1.1 200 Connection Established
< Proxy-Agent: Fortinet-Proxy/1.0
```

Potentially another reason why this is breaking is you have some sort of HTTPS proxy in-between you and the Microsoft service.

You potentially need to also speak to whoever is managing this device, or if this is you - speak to the vendor and collect debug logs from this device to determine why this is failing.

I would also read https://maulwuff.de/research/ssl-debugging.html to ensure that there is something not broken with the HTTPS proxy side of things.

Closing this issue as this is not a bug with the client, some sort of upstream device (proxy) potentially performing the DoS against the Microsoft OneDrive service which is creating the situation. None of which I can solve.

**Closed by abraunegg** 2020-02-12 21:09 UTC
Labels: Enhancement, Local Environment Issue, Not a bug
