### ISSUE TITLE
Skipping item - Insufficient space

### ISSUE THREAD

**Issue by sve-odoo** [abraunegg/onedrive#455] opened 2019-04-07 07:28 UTC
### Bug Report Details ###

Empty files are refused for upload, and here is the error message I get in the logs:

Skipping item './testservice.txt' due to insufficient free space available on OneDrive

Although empty files do not hold much important information, sometimes the existence of a file is an information in itfself, that can be useful in some of my use cases :)

**Application and Operating System Details:**
*   OS: Ubuntu 16.04
*   Headless
*   Sharepoint library - Business account ( Office 365 )
*   DMD version: dmd-2.085.1
*   Curl Version: 7.47.0

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run `touch testservice.txt`
2.  Wait for monitor to try syncing this file
3.  See the following error message
4.  The file is not uploaded to sharepoint/onedrive

**Complete Verbose Log Output**
Apr  7 07:15:48 ip-10-20-20-188 onedrive[21779]: Skipping item './testservice.txt' due to insufficient free space available on OneDrive

Thanks in advance!

**Comment by abraunegg** [comment] 2019-04-07 07:33
@sve-odoo 
Please can you provide a proper verbose debug log as per: https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support

You have also not provided the output of the application configuration or application version you are running.

**Comment by abraunegg** [comment] 2019-04-07 08:31
@sve-odoo 
Unable to reproduce using latest release & master using an Office 365 / SharePoint account:
```
[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-business' --monitor --verbose    
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/Documents
Initializing the Synchronization Engine ...
Account Type: documentLibrary
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 27487775215681
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
[M] File changed: ./testservice.txt
Uploading differences of ./testservice.txt
Uploading new items of ./testservice.txt
Uploading new file ./testservice.txt ... done.
Remaining free space: 27487775215681
Applying changes of Path ID: <redacted>
Uploading differences of .
Processing root
The directory has not changed
Processing testservice.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: <redacted>
```

**Comment by abraunegg** [comment] 2019-04-08 08:41
@sve-odoo 
Please can you respond with the requested information

**Comment by sve-odoo** [comment] 2019-04-08 09:06
Hello,
I just sent you an email with my log.
Thanks again for your feedback!

**Comment by sve-odoo** [comment] 2019-04-08 09:08
And here is my display-config output:

onedrive version                    = v2.3.2-2-gea2e4a9
Config path                         = /home/knime/.config/onedrive-documentation
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /onedrive/documentation
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/documentation/
Config option 'drive_id'            = b!eod1TAw2WU6_rHjciBQffI63ZOsc9QlIm2ZxjOo_bNO6qK0tQ-nxTZM-0R2hKp2s
Selective sync configured           = false

**Comment by abraunegg** [comment] 2019-04-08 09:13
Thanks

OK .. so the application is working 100% as normal.

What your Sharepoint account however is not doing, is sending back in the responses what the remaining space available on your account is - so this is why this is not working, and I am surprised that any file is actually being uploaded at all.

So - I strongly suggest the following:
* speak with your sharepoint administrator and ask why the size data is being restricted
* speak with Microsoft and ask why for your sharepoint account the size data is being restricted

**Comment by sve-odoo** [comment] 2019-04-08 09:23
The problem is a bit different.

The sharepoint size is *not* restricted. All files are correctly uploaded, except the empty files.

**Comment by abraunegg** [comment] 2019-04-08 09:35
@sve-odoo 
In your provided log file you have this:
```
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/knime
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/knime/.config
[DEBUG] configDirName: CLI override to set configDirName to: /home/knime/.config/onedrive-documentation
Loading config ...
Using Config Dir: /home/knime/.config/onedrive-documentation
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /onedrive/documentation
Initializing the OneDrive API ...
Opening the item database ...
[DEBUG] Using database file: /home/knime/.config/onedrive-documentation/items.sqlite3
All operations will be performed in: /onedrive/documentation
[DEBUG] Configuring skip_dir ...
[DEBUG] skip_dir: 
[DEBUG] Configuring skip_file ...
[DEBUG] skip_file: ~*|.~*|*.tmp
Initializing the Synchronization Engine ...
Account Type: documentLibrary
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 0     <-- THIS IS A PROBLEM
[DEBUG] documentLibrary account type - flagging to disable upload validation checks due to Microsoft SharePoint file modification enrichments
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
```
This is the problem:

```
Remaining Free Space: 0
```

Your Microsoft account is not providing the remaining space available, thus, it should even fail to upload data - so that is potentially another issue - but that your OneDrive account is not providing the details at all at the start - that is a problem.

Can you generate a HTTPS Debug Log with your account so that this can be further identified:

https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

**Comment by abraunegg** [comment] 2019-04-09 21:30
@sve-odoo 
Please can you respond and provide the requested HTTPS Debug Log

**Comment by abraunegg** [comment] 2019-04-10 20:52
@sve-odoo
Please can you respond and provide the requested HTTPS Debug Log

**Comment by abraunegg** [comment] 2019-04-11 20:28
@sve-odoo
Please can you respond and provide the requested HTTPS Debug Log

**Comment by abraunegg** [comment] 2019-04-12 22:04
@sve-odoo 
Without the logs I have worked through replicating the issue and generated a fix. Please can you help validate this PR:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/466/head:pr466
git checkout pr466
make clean; make;
```

**Comment by abraunegg** [comment] 2019-04-12 22:59
Closing issue as PR #466 merged

**Closed by abraunegg** 2019-04-12 22:59 UTC
Labels: Bug, Fixed
