### ISSUE TITLE
Error configuring multiple accounts

### ISSUE THREAD

**Issue by firebone-be** [abraunegg/onedrive#1221] opened 2021-01-12 15:03 UTC
I am trying to configure my personal onedrive and my onedrive for business.

Placed a config under ~/.config/onedrive and another config under ~/.config/OfB
Both have seperate sync_dir

When I try `onedrive --confdir="~/.config/OfB" --synchronize --verbose --dry-run`
or `onedrive --confdir="~/.config/onedrive" --synchronize --verbose --dry-run`
I get the following error:

````
~ $ onedrive --confdir="~/.config/onedrive" --synchronize --verbose --dry-run
Using 'user' Config Dir: /home/****/.config/onedrive
Using 'system' Config Dir:
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55C8BC5A9D90
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service, unable to initialize application
````

**Comment by abraunegg** [comment] 2021-01-12 19:25
@firebone-be 
>```
>Unable to reach Microsoft OneDrive API service, unable to initialize application
>```

You most likely have a firewall blocking HTTPS / DNS requests. The client cannot resolve or connect to the required services that it needs to use, to determine if the service is reachable.

This is not a bug or issue with the client, but an issue with your Linux system, your local network, your local security policies.

To diagnose your issue further, you can use:
```
curl -I --connect-timeout 60 --max-time 60 https://login.microsoftonline.com
```
If the site is reachable, something like the following will be returned:
```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Length: 149018
Content-Type: text/html; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
X-DNS-Prefetch-Control: on
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 9e4014b7-d7ab-4b3c-b9e8-90cd15d30100
x-ms-ests-server: 2.1.11397.10 - SEASLR1 ProdSlices
Set-Cookie: fpc=Ag3BdGWv6h5Hhyj3iQ9XZ-4; expires=Thu, 11-Feb-2021 19:13:04 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAABeStGSRwwnTq2vHplZ9KL4ytg81iXsrrQ1yUHVGZXn5WvXq2FBtm_sC1rpeDQrfGMRmBdFwMUmqJZMJxx1mzRMGbZKwV9AF9E0r6j1RdCs2aum2Ery7qMcxpTuHQU7XOkLXZAKz8yQ9x_1JLWuXEmVS3ZzGOjYQjGcf6MoIvcnaR6AMpjfuOWs9qA6FrDR764gAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Tue, 12 Jan 2021 19:13:04 GMT
```

If HTTPS is blocked, the curl response will be similar to the following:
```
curl: (7) Failed connect to login.microsoftonline.com:443; Operation now in progress
```

If DNS is blocked, the curl response will be similar to the following:
```
curl: (6) Could not resolve host: login.microsoftonline.com; Unknown error
```

**Comment by firebone-be** [comment] 2021-01-13 07:08
@abraunegg 
Thank you for the answer. I tried the CURL command and got the correct output I presume:
`curl -I --connect-timeout 60 --max-time 60 https://login.microsoftonline.com`
```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Length: 149016
Content-Type: text/html; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
X-DNS-Prefetch-Control: on
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 581a0140-34c2-42e1-84e9-ec5ca0db0600
x-ms-ests-server: 2.1.11384.6 - WEULR2 ProdSlices
Set-Cookie: fpc=ApjO-jPOss9Eq5UTTBuj6Gg; expires=Fri, 12-Feb-2021 07:03:32 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAABeStGSRwwnTq2vHplZ9KL4vTZVYW-2bQOu50YYlJPydxSrBqAOrkRwH41b49Zwd0VaBzqKwFUOqluEbJ5U_z-PmKxHMtecmAPsEvOklZtOBffZWy-n9Tt3vKluCGY57hfmGAp1R4iBcYuCOxGHCr_nGSyV_kLiCgUNwRjlHMmmFwUehJGWo0Jxquncq0e0utYgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Wed, 13 Jan 2021 07:03:32 GMT
```
However when I try `onedrive --confdir="~/.config/onedrive" --monitor --verbose`
I still get the following:
```
Using 'user' Config Dir: /home/bone/.config/onedrive
Using 'system' Config Dir:
Configuration file successfully loaded
Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55F62FF76B20
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service at this point in time, re-trying network tests

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55F62FF76B20
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55F62FF76B20
  Calling Function: testNetwork()

Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55F62FF76B20
  Calling Function: testNetwork()
```
When I tried the dry run for both accounts they however succeeded?

**Comment by abraunegg** [comment] 2021-01-13 07:53
@firebone-be 
So something in your network is allowing 'curl' as a network client, but blocking the application itself. The 'timeout' for the actual  application / network test is 5 seconds.

Can you please try:
```
curl -I --connect-timeout 10 --max-time 10 https://login.microsoftonline.com
```
and decrease from 10 -> 1, eg:
```
curl -I --connect-timeout 9 --max-time 9 https://login.microsoftonline.com
```
...
```
curl -I --connect-timeout 1 --max-time 1 https://login.microsoftonline.com
```

If this works, even at 1 second interval, then potentially something in your network is performing HTTP User Agent blocking or something else - such as *really* slow Internet access.

**Comment by firebone-be** [comment] 2021-01-13 09:33
Thank you for pointing me in the right direction. It was indeed a DNS issue with a timeout of 5 seconds. I had to add option timeout:1 to my /etc/resolve.conf

**Comment by abraunegg** [comment] 2021-01-13 09:46
@firebone-be 
Glad you found the issue with your local environment. Closing issue as resolved.

**Closed by abraunegg** 2021-01-13 09:46 UTC
Labels: Answer Provided, Local Environment Issue, Not a bug, Question

**Comment by firebone-be** [comment] 2021-01-13 09:49
I also have an issue with the automation of the syncing. I tried following the steps of [advanced usage](https://github.com/abraunegg/onedrive/blob/master/docs/advanced-usage.md) and created
- onedrive@.service
- OfB@.service
in `/lib/systemd/system`
I adjusted the ExecStart but I struggle to start and enable the service:
`systemctl enable OfB@.service` gives me an error: `Failed to enable unit: Unit file OfB@.service does not exist.`

**Comment by abraunegg** [comment] 2021-01-13 10:20
@firebone-be 
When using the '@' systemd service files, you need to use your username when enabling the service:
```
systemctl --user enable onedrive-my-new-config@myusername.service
systemctl --user start onedrive-my-new-config@myusername.service
```

So in your example:
```
systemctl --user enable onedrive@yourusername.service
systemctl --user start onedrive@yourusername.service

systemctl --user enable OfB@yourusername.service
systemctl --user start OfB@yourusername.service
```

**Comment by firebone-be** [comment] 2021-01-13 11:08
@abraunegg 

Sorry to bother you again and thank you for your patience but I still am unable to start and enable it

```
systemctl --user enable OfB@bone.service
Failed to enable unit: Unit file OfB@bone.service does not exist.
```

**Comment by abraunegg** [comment] 2021-01-13 11:52
@firebone-be 

> Sorry to bother you again and thank you for your patience but I still am unable to start and enable it

This is a support process exists: https://github.com/abraunegg/onedrive#reporting-issues

What is missing from your issue is all the initial details when opening an issue, such as, version of the application you are running, what Linux OS are you using and the like.

The cause of your current issue is one of:
* systemd file is not in the right place
* systemd not recognising the file
* typo in the file
* Using a Linux OS that does not support --user systemd @ type service files

Please seek support for this error with who ever provides support for Linux OS. I am unable to assist further at this point in time.

**Comment by abraunegg** [comment] 2021-01-24 23:17
Initial issue re network connection now listed in FAQ: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#cannot-connect-to-microsoft-onedrive-service---network-connection-issue
