### ISSUE TITLE
OneDrive returning error on --synchronize

### ISSUE THREAD

**Issue by robertoshimizu** [abraunegg/onedrive#1150] opened 2020-11-17 17:10 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
All of sudden, when commanding a onedrive --synchronize, it started to return the following Error message:
```
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 5639D4696420
```
My first instinct was to upgrade the onedrive to latest version, logout and login again, but unfortunately the issue persisted.

**Application and Operating System Details:**
*   Provide your OS & version (CentOS 6.x, Ubuntu 18.x etc) and the output of: `uname -a`
```
Linux roberto-81jb 5.4.74-1-MANJARO #1 SMP PREEMPT Sun Nov 1 13:43:13 UTC 2020 x86_64 GNU/Linux
```
*   Are you using a headless system (no gui) or with a gui installed?
*   OneDrive Account Type
Microsoft 365 Family
*   Did you build from source or install from a package?
from source
*   If you installed from source, what is your DMD or LDC compiler version: `dmd --version` or `ldmd2 --version`
```
DMD64 D Compiler v2.094.0
LDC - the LLVM D compiler (1.23.0):
  based on DMD v2.093.1 and LLVM 10.0.1
  built with LDC - the LLVM D compiler (1.22.0)
```
*   OneDrive Application Version: Output of `onedrive --version`
```
onedrive v2.4.7-13-g0d5b004
```
*   OneDrive Application Configuration: Output of `onedrive --display-config`
```
Configuration file successfully loaded
onedrive version                       = v2.4.7-13-g0d5b004
Config path                            = /home/rober/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/rober/OneDrive
Config option 'skip_dir'               = /home/rober/OneDrive/online_courses
Config option 'skip_file'              = ~*|.~*|*.tmp|*.mov|*.mp4|*.jpg|*.wav
Config option 'skip_dotfiles'          = true
Config option 'skip_symlinks'          = true
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`
curl 7.73.0 (x86_64-pc-linux-gnu)
*   Is your configured 'sync_dir' a local directory or a network mount point?
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time

**Note:** Please generate a full debug log whilst reproducing the issue as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Application and Operating System Details provided in full
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output from your error
*   [] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2020-11-17 19:15
@robertoshimizu 
>```
>ERROR: OneDrive returned an error with the following message:
>Error Message: Timeout was reached on handle 5639D4696420
>```

This error message indicates that you have one or more of the following issues:
* Flaky Internet connectivity between you and OneDrive
* Your host OS (Manjaro) was unable to perform DNS resolution for the OneDrive services


This is not something I can solve for or fix.

**Comment by abraunegg** [comment] 2020-11-18 18:34
Closing issue, not a bug

**Closed by abraunegg** 2020-11-18 18:34 UTC
Labels: Local Environment Issue, Not a bug
