### ISSUE TITLE
@prefix@ not replaced in onedrive.service

### ISSUE THREAD

**Issue by xdarklight** [abraunegg/onedrive#474] opened 2019-04-23 20:13 UTC
**Describe the bug**
daemon doesn't start with systemd anymore, journalctl shows:
```
Apr 23 07:54:44 hostname systemd[937]: /usr/lib/systemd/user/onedrive.service:7: Neither a valid executable name nor an absolute path: prefix@/bin/onedrive
Apr 23 07:54:44 hostname systemd[937]: onedrive.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

**Application and Operating System Details:**
*  uname -a: ``Linux hostname 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux``
* Arch Linux
* KDE desktop
* OneDrive Account Type: company account
* Arch Linux package version ``1:2.085.1-1``
* Application configuration: (happens with any configuration)
* curl Version:
  * curl 7.64.1 (x86_64-pc-linux-gnu) libcurl/7.64.1 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.1 nghttp2/1.36.0
  * Release-Date: 2019-03-27
  * Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
  * Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. update to c8e47a47ff9cb1b1103a05e3559b8529b87cb3e9
2. ``sudo systemctl daemon-reload``
3. ``systemctl --user daemon-reload``
4. ``systemctl --user restart onedrive`` (this fails)
5. (check the journalctl output)
6. check ``/usr/lib/systemd/user/onedrive.service`` - line 7 contains ``@prefix@/bin/onedrive`` instead of ``/usr/bin/onedrive``

**Complete Verbose Log Output**
n/a

Application Log Output:
n/a

**Screenshots**
n/a

**Additional context**
This worked fine with an older version (I don't remember the exact version but something around efaaaadce26e989b835356783e6d8c50e02e5396)

**Comment by xdarklight** [comment] 2019-04-23 20:13
CC: @norbusan

**Comment by abraunegg** [comment] 2019-04-23 20:25
@xdarklight 
Are you using the Arch Linux package? if yes, which one?

**Comment by xdarklight** [comment] 2019-04-23 20:26
yes, I'm using this one specifically: [https://aur.archlinux.org/packages/onedrive-abraunegg-git/] (not a package but PKGBUILD from which you build your own package)

**Comment by abraunegg** [comment] 2019-04-23 20:31
@xdarklight 
Duplicate of #472
Please make sure you use the right PKGBUILD file - this is a packaging issue.  If there are still packaging issues, please post an issue on the AUR site for the package maintainer to resolve.

**Comment by xdarklight** [comment] 2019-04-23 20:32
thank you for the hint - I'll test that tomorrow morning

**Comment by abraunegg** [comment] 2019-04-23 22:01
@xdarklight 
OK - so tracked this back as well - this is a side product of not running / using `./configure` as part of the build process. PR #475 resolves this issue.

**Comment by abraunegg** [comment] 2019-04-23 23:15
PR #475 merged

**Closed by abraunegg** 2019-04-23 23:15 UTC
Labels: Bug, Duplicate, Fixed

**Comment by norbusan** [comment] 2019-04-23 23:40
Not a bug. Please use `./configure`
The Makefile needs to be removed from git. Sent PR.
