### ISSUE TITLE
ERROR: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?

### ISSUE THREAD

**Issue by rugubara** [abraunegg/onedrive#665] opened 2019-09-17 10:12 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

### Bug Report Details ###
**Describe the bug**
When there is no internet connection or the connection is behind a captive portal, the log is spammed with messages:
Sep 15 09:43:02 139.28.219.76 logger: сен 15 09:43:00 PF16W6Y2 onedrive[4928]: ERROR: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?

Sep 15 09:43:04 139.28.219.76 logger: сен 15 09:43:02 PF16W6Y2 onedrive[4928]: ERROR: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?

Sep 15 09:43:04 139.28.219.76 logger: сен 15 09:43:02 PF16W6Y2 onedrive[4928]: ERROR: onedrive.viewChangesById call returned an invalid JSON Object

This series repeats every 3-5 seconds. I have a total of over 20k lines in one day when I was not able to get past the captive portal due to a technical issue on the provider side.

**Application and Operating System Details:**
*   OS: PF16W6Y2 ~ # uname -a
Linux PF16W6Y2 5.2.14-gentoo #1 SMP PREEMPT Thu Sep 12 08:22:07 MSK 2019 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux
*   Gnome 3.30 GUI
*   OneDrive Account Type: personal
*   PF16W6Y2 ~ # dmd --version
DMD64 D Compiler v2.082.1
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright

*   Application configuration: anton@PF16W6Y2 ~ $ onedrive --display-config
onedrive version                    = v2.3.9
Config path                         = /home/anton/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/anton/OneDrive
Config option 'skip_dir'            = 
Config option 'skip_file'           = ~Exchange
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 300
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false

*   Curl Version: anton@PF16W6Y2 ~ $ curl --version
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: HTTPS-proxy IPv6 Largefile libz NTLM SSL TLS-SRP UnixSockets

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  start ondedrived service
2.  Connect to wifi with captive portal
3.  watch errors pour in the log

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

**Screenshots**

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2019-09-17 17:01
@rugubara 
Whilst this may seem like a bug to you, this is not a bug. 

Patches welcome if you want to look at implementing a change to reduce the volume of logging in this sort of scenario.

**Comment by abraunegg** [comment] 2019-09-19 07:04
Closing issue as not a bug

**Closed by abraunegg** 2019-09-19 07:04 UTC
Labels: Answer Provided, Not a bug, Will Not Fix
