### ISSUE TITLE
onedrive fails with "No such file or directory"

### ISSUE THREAD

**Issue by GalaxyCurse** [abraunegg/onedrive#222] opened 2018-11-08 09:56 UTC
### Bug Report Details ###
**Describe the bug**
Onedrive fails with "No such file or directory"
It just started suddenly yesterday. Before it worked perfectly. I've tried to re-install onedrive and tried to delete the "offending files" via onedrive webpage, but then the same error just comes with the next file.

**Application and Operating System Details:**
- OS: Linux curzed 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
- Application version: onedrive v2.1.4-6-geb2cbfd
- OneDrive Account Type: Personal
- DMD or LDC compiler version: DMD64 D Compiler v2.083.0

**To Reproduce**
Open terminal and type: onedrive --synchronize

**Complete Verbose Log Output**

[curse@curzed ~]$ onedrive --synchronize --verbose
Loading config ...
Using Config Dir: /home/curse/.config/onedrive
No config file found, using defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/curse/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 31e13e9d438559ec
Default Root ID: 31E13E9D438559EC!122
Remaining Free Space: 1099422736099
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 31E13E9D438559EC!122
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
ASG/Dreams 11-03-2017 23-20.zip: No such file or directory
Syncing changes from OneDrive ...
Applying changes of Path ID: 31E13E9D438559EC!122
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
ASG/Dreams 11-03-2017 23-20.zip: No such file or directory
Syncing changes from OneDrive ...
Applying changes of Path ID: 31E13E9D438559EC!122
Downloading file ASG/Dreams 11-03-2017 23-20.zip ... done.
std.file.FileException@/usr/include/dlang/dmd/std/file.d(1556): ASG/Dreams 11-03-2017 23-20.zip: No such file or directory

??:? @trusted bool std.file.cenforce!(bool).cenforce(bool, scope const(char)[], scope const(char)*, immutable(char)[], ulong) [0x7b7368c]
??:? @safe void std.file.setTimes!(immutable(char)[]).setTimes(immutable(char)[], std.datetime.systime.SysTime, std.datetime.systime.SysTime) [0x7b83e76]
??:? void sync.SyncEngine.downloadFileItem(itemdb.Item, immutable(char)[]) [0x7bb753f]
??:? void sync.SyncEngine.applyNewItem(itemdb.Item, immutable(char)[]) [0x7bb6eab]
??:? void sync.SyncEngine.applyDifference(std.json.JSONValue, immutable(char)[], bool) [0x7bb6d41]
??:? void sync.SyncEngine.applyDifferences(immutable(char)[], const(char)[]) [0x7bb622f]
??:? void sync.SyncEngine.applyDifferences() [0x7bb5261]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool) [0x7b9a5ea]
??:? _Dmain [0x7b99e80]
[curse@curzed ~]$

**Comment by abraunegg** [comment] 2018-11-08 10:42
Duplicate of #220

**Closed by abraunegg** 2018-11-08 10:42 UTC
Labels: Duplicate
