### ISSUE TITLE
onedrive doesn't delete locally when remote file moved to non-synced folder when using sync_list

### ISSUE THREAD

**Issue by pcolmer** [abraunegg/onedrive#603] opened 2019-07-24 03:31 UTC
### Bug Report Details ###
**Describe the bug**
The `onedrive` client is successfully synchronising files from the local computer to the remote OneDrive service. However, when files are moved on remote OneDrive to a folder that is **not** in the sync list, the `onedrive` client does not delete the files on the local system.

**Application and Operating System Details:**
*   OS:

```
Linux hackbox2 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

*   Are you using a headless system (no gui) or with a gui installed?

Headless

*   OneDrive Account Type

Personal

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`

DMD64 D Compiler v2.086.1

*   Application configuration:

```
onedrive version                    = v2.3.7-20-g21e5047
Config path                         = /home/philip.colmer/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/philip.colmer/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /home/philip.colmer/.config/onedrive/log/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
Video
```

*   Curl Version:

```
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Run `onedrive --synchronize --verbose`.
2.  Create a file locally in `OneDrive/Video`.
3.  Run `onedrive --synchronize --verbose` to sync the new file to the remote.
4.  Using a web browser to the remote OneDrive, **move** the synced file to a folder that is not the `Video` folder.
5.  Run `onedrive --synchronize --verbose`.

At this point, I would expect the local file to be deleted because it is no longer in the remote `Video` folder. However, the file is not deleted. I suspect this might be because the file does still exist on OneDrive but the `onedrive` client isn't checking the path to the file to make sure that it is within a synced folder.

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
$ onedrive --synchronize --verbose
Using Config Dir: /home/philip.colmer/.config/onedrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/philip.colmer/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.7-20-g21e5047
Account Type: personal
Default Drive ID: 42b71883c19fddae
Default Root ID: 42B71883C19FDDAE!353
Remaining Free Space: 640469675607
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 42B71883C19FDDAE!353
Processing 9 changes
Uploading differences of .
Processing root
The directory has not changed
Processing Video
The directory has not changed
Processing Clangers - s03e03 - Medal.srt
The file has not changed
Processing Shaun the Sheep - s04e21 - The Intruder.mp4
The file has not changed
Processing Shaun the Sheep - s04e21 - The Intruder.srt
The file has not changed
Processing Clangers - s03e03 - Medal.mp4
The file has not changed
Processing Keeping Faith - s01e01 - Episode 1.mp4
The file has not changed
Processing Keeping Faith - s01e01 - Episode 1.srt
The file has not changed
Processing Keeping Faith - s01e02 - Episode 2.mp4
The file has not changed
Processing Keeping Faith - s01e02 - Episode 2.srt
The file has not changed
Processing Keeping Faith - s01e03 - Episode 3.mp4
The file has not changed
Processing Keeping Faith - s01e03 - Episode 3.srt
The file has not changed
Processing Keeping Faith - s01e04 - Episode 4.mp4
The file has not changed
Processing Keeping Faith - s01e04 - Episode 4.srt
The file has not changed
Processing Keeping Faith - s01e05 - Episode 5.mp4
The file has not changed
Processing Keeping Faith - s01e05 - Episode 5.srt
The file has not changed
Processing Keeping Faith - s01e06 - Episode 6.mp4
The file has not changed
Processing Keeping Faith - s01e06 - Episode 6.srt
The file has not changed
Processing Keeping Faith - s01e07 - Episode 7.mp4
The file has not changed
Processing Keeping Faith - s01e07 - Episode 7.srt
The file has not changed
Processing Keeping Faith - s01e08 - Episode 8.mp4
The file has not changed
Processing Keeping Faith - s01e08 - Episode 8.srt
The file has not changed
Processing Keeping Faith - s02e02 - Episode 2.mp4
The file has not changed
Processing Keeping Faith - s02e02 - Episode 2.srt
The file has not changed
Processing Keeping Faith - s02e03 - Episode 3.mp4
The file has not changed
Processing Keeping Faith - s02e03 - Episode 3.srt
The file has not changed
Processing Keeping Faith - s02e04 - Episode 4.mp4
The file has not changed
Processing Keeping Faith - s02e05 - Episode 5.mp4
The file has not changed
Processing Keeping Faith - s02e06 - Episode 6.mp4
The file has not changed
Processing Keeping Faith - s02e01 - Episode 1.mp4
The file has not changed
Processing Keeping Faith - s02e01 - Episode 1.srt
The file has not changed
Processing Clangers - s03e04 - Strange Music.mp4
The file has not changed
Processing Shaun the Sheep - s04e22 - Bitzer for the Day.mp4
The file has not changed
Processing Shaun the Sheep - s04e22 - Bitzer for the Day.srt
The file has not changed
Processing Clangers - s03e04 - Strange Music.srt
The file has not changed
Uploading new items of .
Applying changes of Path ID: 42B71883C19FDDAE!353
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Reproduction steps (if applicable)
*   [x] Verbose Log Output

**Comment by pcolmer** [comment] 2019-07-24 03:35
As an extra problem related to this, if I manually delete the files from `OneDrive/Video` and then run `onedrive --synchronize`, the tool deletes the files from the folder that I had moved the files into on OneDrive, i.e. it deletes the files even though they are not in the Video folder.

**Comment by abraunegg** [comment] 2019-07-25 20:57
@pcolmer 
I have been spending a few days looking into this to respond appropriately.

**Issue 1:** Moving a file to a new location on OneDrive does not delete the file locally
This is a side impact of using `sync_list`. What you are telling the client to do is essentially only sync changes - both local and remote, that are ONLY for this particular folder. This is why, if you move the file on OneDrive to a location that is not covered by `sync_list` the client is ignoring the move because of:
* The new folder is not synced locally (parent excluded in scope)
* The target folder exists locally, but is specifically excluded as new target by `sync_list`

Thus the change is ignored and dropped. As a point of reference, I also checked the original 'skilion' client code and this issue is also present, so this is not something that has been introduced by this fork.

**Issue 2:** Manually delete the file locally, deletes the file from the moved location 
This is essentially a by-product of the above scenario. The 'delete' is issued by telling OneDrive to delete an item by it's 'id' - so that file, where ever it now exists, is what will be deleted. The [API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_delete?view=odsp-graph-online) for deleting does not give any other option other than to use the 'item id'. 

**Potential workaround:**
As your only using `sync_list` with a single folder, a workaround may be not not use 'sync_list' at all but to use the following:
```
--single-directory ARG
      Specify a single local directory within the OneDrive root to sync.
```

This acts 'slightly differently to 'sync_list' when it comes to change matching & handling. I am yet to test / try this against your use case, but I am also wanting to test this with the updated change pattern matching used in #473 that greatly enhances handling 'changes that should be handled' but are discarded without doing the extra checks. This updated 'discard' pattern matching will not help with using 'sync_list' however.

Will have to add this 'corner use case' to a wiki / documentation to ensure this 'corner case' is captured. Patches welcome if you feel you can work out a way to fix this as well.

**Comment by pcolmer** [comment] 2019-07-26 01:46
Thank you for taking the time to research this.

I *think* that I've come up with an approach that would actually solve this but I haven't been able to confirm my logic because using `--dry-run` is giving me an error:

```
$ onedrive --synchronize --single-directory Video --dry-run
DRY-RUN Configured. Output below shows what 'would' have occurred.

An internal database error occurred: database disk image is malformed
```

```
$ onedrive --dry-run --synchronize
DRY-RUN Configured. Output below shows what 'would' have occurred.

An internal database error occurred: database disk image is malformed
```

and yet taking out that option doesn't produce an error:

```
$ onedrive --synchronize --single-directory Video
Initializing the Synchronization Engine ...
Syncing changes from selected OneDrive path ...
```

Anyway ... here is my thinking ...

Firstly, the following *only* has to be done when there is a sync_list. Without a sync_list file, the onedrive code just works as it does normally. We're just trying to solve this specific situation.

Secondly, I'm working on the presumption that the sqlite database holds the details of all of the folders and all of the files and therefore the onedrive code can figure out the full path to a file. I think that is a safe presumption because there are calls like `itemdb.computePath(item.driveId, item.id)` in `sync.d`.

Moving a file to another folder on OneDrive, I think, results in a change entry that tells you the new parent ID. (This is why I wanted to use `--dry-run` with `--verbose`, so that I could see what messages are being received)

If I'm right then all the code needs to do is check the path for the new parent ID and see if that path is in the sync_list file. If it is not, then the onedrive code *deletes* the local copy because it has now fallen out of scope. Deleting the local copy then avoids the second edge case where the user deleting the file causes the OneDrive copy to be deleted regardless of where it is in the system.

Does that logic make sense? Does it seem viable?

I've tried to read through `sync.d` to see where this would need to be done. I *think* that `applyDifference` would seem to be the sanest place and definitely ahead of the call to `applyChangedItem` ... but I'm not entirely sure :)

**Comment by ThoundsN** [comment] 2019-07-26 01:54
I have the same error as above , however I cannot provide useful suggestions. 

`No config file found, using application defaults
DRY-RUN Configured. Output below shows what 'would' have occurred.
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /root/OneDrive
Initializing the Synchronization Engine ...
Application version: v2.3.7-22-gf111eab
Account Type: personal
Default Drive ID: 31634960a255de1e
Default Root ID: 31634960A255DE1E!101
Remaining Free Space: 1013351063128
Fetching details for OneDrive Root

A database statement execution error occurred: database disk image is malformed
`

this is what I got

**Comment by pcolmer** [comment] 2019-07-26 02:01
One other thing that occurs to me: when using the sync_list file, I'm not sure whether or not the code is remembering the IDs for everything on OneDrive or just the folders and child items specified by the sync_list file.

If it is the latter then the code would need to change so that all of the folder IDs and associated paths are stored in the database so that a OneDrive move to a parent that isn't in sync_list can then be appropriately handled.

**Comment by abraunegg** [comment] 2019-07-26 03:45
@pcolmer 
RE: this

```
An internal database error occurred: database disk image is malformed
```

Unable to reproduce this at all using the latest master - are you sure your permissions for the `~/.config/onedrive/` directory are OK?

**Comment by pcolmer** [comment] 2019-07-26 03:48
> are you sure your permissions for the ~/.config/onedrive/ directory are OK?

Everything is owned by me and I have read-write access.

**Comment by abraunegg** [comment] 2019-07-26 04:02
@pcolmer 
> If I'm right then all the code needs to do is check the path for the new parent ID and see if that path is in the sync_list file. If it is not, then the onedrive code deletes the local copy because it has now fallen out of scope. Deleting the local copy then avoids the second edge case where the user deleting the file causes the OneDrive copy to be deleted regardless of where it is in the system.

Whilst the change that is sent from OneDrive - yes it does contain the new parent ID, there is no correlation data to its old item id or old parent ID - it would be really difficult to determine which is the right file to delete. Happy to test / try something however

**Comment by abraunegg** [comment] 2019-07-26 04:22
> > are you sure your permissions for the ~/.config/onedrive/ directory are OK?
> 
> Everything is owned by me and I have read-write access.

OK .. well the only way this would occur would be:
1. The original sqlite DB is mangled for some reason (possible)
2. No permission to copy the database file to a temporary file or the file is in-use / open

I cannot reproduce this error even on the same version of Ubuntu your running .. so that has to be something more environmental to your Linux system

**Comment by pcolmer** [comment] 2019-07-26 04:40
> I cannot reproduce this error even on the same version of Ubuntu your running .. so that has to be something more environmental to your Linux system

I think it might be because I forgot to do `--resync` after removing `sync_list`. I'm doing that now so, hopefully, I'll then be able to use `--dry-run` after I've moved some files in OneDrive.

> Whilst the change that is sent from OneDrive - yes it does contain the new parent ID, there is no correlation data to its old item id or old parent ID - it would be really difficult to determine which is the right file to delete.

I thought that the rename/move change was associated with the underlying affected file, by specifying the file's ID? I'm still trying to figure out what the `sync.d` code is doing and I'm hoping that running with verbosity and dry-run will help me out here when I get it all working.

**Comment by abraunegg** [comment] 2019-07-29 02:41
@pcolmer 
Please can you test the following PR for resolving your issue:
```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/604/head:pr604
git checkout pr604
make clean; ./configure; make;
```

Tested locally here, and based on the specific reproduction steps, deletes the file now locally if:
* File was previously in-sync with OneDrive
* Moved on OneDrive to a folder that is not in sync_list scope

**Comment by pcolmer** [comment] 2019-07-29 10:45
@abraunegg I have tested this by:

* Adding "Video" back into the `sync_list` file and running `--synchronize --resync`. This uploaded several files to OneDrive

* Re-running `--synchronize` to make sure that `onedrive` was truly in sync with OneDrive

* Moving files out of "Video" on OneDrive

* Re-running `--synchronize` and observing that the moved files got deleted from the local system.

In summary, it all seemed to work as expected. Thank you very much for this.

**Comment by abraunegg** [comment] 2019-07-29 21:03
@pcolmer 
Thanks for confirming the fix. Merged into 'master'

**Closed by abraunegg** 2019-07-29 21:03 UTC
Labels: Bug, Documentation, PR Provided - Needs Testing
