### ISSUE TITLE
Bug: SharePoint client overwrote a shared file, causing data loss

### ISSUE THREAD

**Issue by kendonB** [abraunegg/onedrive#2353] opened 2023-03-25 05:49 UTC
### Describe the bug

I recently installed the client and set up for SharePoint, following the instructions. The client stopped working for about a day then I restarted it today and the client overwrote a file a colleague was working on. I was not working on this file at all and work was lost.

### Operating System Details

```shell
Linux
Ubuntu 22.04.2 LTS
```

### Client Installation Method

From Distribution Package

### OneDrive Account Type

SharePoint

### What is your OneDrive Application Version

v2.4.23-1+np1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.23-1+np1
Config path                                  = /home/kendonb/.config/SharePoint_Clients
Config file found in config path             = true
Config option 'drive_id'                     = 
Config option 'sync_dir'                     = /home/kendonb/SharePoint_Clients
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false

```

### What is your 'curl' version

```shell
7.81.0
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
why do you need this
```

### What are all your local file system partition types

```shell
squashfs
```

### How do you use 'onedrive'

OneDrive folder running using systemctl

SharePoint folder running using systemctl and a confdir.

Standard setup for each

### Steps to reproduce the behaviour

Won't reproduce this as I'm not going to use this again 

### Complete Verbose Log Output

```shell
Again, I won't do this
```

**Comment by abraunegg** [comment] 2023-03-25 08:15
@kendonB 
> I recently installed the client and set up for SharePoint, following the instructions. The client stopped working for about a day then I restarted it today and the client overwrote a file a colleague was working on. I was not working on this file at all and work was lost.

The SharePoint | OneDrive API is what has failed you here - not this client.

The API, for SharePoint essentially *prevents* files from being uploaded correctly, because of the SharePoint file enrichment that occurs. Please refer to https://github.com/OneDrive/onedrive-api-docs/issues/935 for more details.

As such, to upload a file to SharePoint, the file online is deleted, and then replaced with the file that is being uploaded.

*However* .. the file that is deleted - should be in the Recycle Bin online - allowing that file to be recovered - so that your data | file can be recovered.

If you have an issue with this and how the API works - please complain to Microsoft.

You should also try and understand *why* the client stopped working for a day .. however I get the feeling you are 100% not interested at this stage.

> why do you need this

So that I can replicate *your* environment when building / testing / replicating your issue to *fix* your issue.

Bugs occur - and they get fixed - but having *data* that helps illustrate the problem that - through extensive testing and use over the last 5 years - corner cases / corner bugs potentially do exist - however I am fairly certain and confident that the above linked Microsoft Issue is your root cause.

@Microsoft .... Please can you *fix* the OneDrive API & the stupidity with your SharePoint platform.

> Won't reproduce this as I'm not going to use this again
> ..
> Again, I won't do this

Without any logs or anything I cant even advise as to what occurred and what actually happened to your files online so that you *know* exactly what occurred and why.

Closing this issue as it is pointless having this open.

**Closed by abraunegg** 2023-03-25 08:15 UTC
Labels: Bug

**Comment by kendonB** [comment] 2023-03-25 09:34
The client shouldn't be uploading files that I haven't edited locally, which is what occurred in this case. I'm happy to help find the bug in an isolated environment, but I don't believe that's possible. Thank you for the response.

**Comment by kendonB** [comment] 2023-03-25 09:36
Also recommend placing a warning in the SharePoint setup documentation that this can happen. Happy to do a PR if you wish.

**Comment by abraunegg** [comment] 2023-03-25 18:20
@kendonB 
> The client shouldn't be uploading files that I haven't edited locally, which is what occurred in this case.

I can *guarantee* that the client *doe* not arbitrarily just upload data or files without it being modified locally to trigger an upload event.

Lets step through how the client works - both in standalone mode and monitor mode:

**Standalone**
* Read all data online and compare | download all files locally
  * If a file exists in that location it is renamed, preserving the existing local file
* Validates all local data and seeks out all *new* and *changed* files and uploads this data
* Performs a true-up ensuring that the remote and local state are equal

**Monitor | Systemd** 
* Read all data online and compare | download all files locally
  * If a file exists in that location it is renamed, preserving the existing local file
* Validates all local data and seeks out all *new* and *changed* files and uploads this data
* Performs a true-up ensuring that the remote and local state are equal
* Goes into loop where it reads and waits for inotify events from the local filesystem to process
  * This is where local edits are then uploaded post file modification

Lets step through a scenario for you:

1. You setup the client, configured the client to access SharePoint
2. The client downloaded all your SharePoint data, or you had this sitting somewhere locally already
    * Now in the case of the data being already local, the client would have validated the data residing locally rather than downloading the data
    * The local cache database now contains an accurate record of the files stored online and what is stored locally
3. You configured the client to run as a systemd service
4. The client started monitoring your local SharePoint Library and your local repository for changes

At some point the client stopped working for you

You then state that you restarted the application and that a file you had not touched was uploaded.

So - for the file to have been uploaded:
1. The application would have, on restart, first downloaded and synced all of the remote data first .... as that is *how* the client operates .....
2. It was never in sync to begin with - but then would have been uploaded as a new file .. but on restart should have been in-sync before it got to processing any systemd events ..... 

There is literally *zero* way for the application to just arbitrarily upload a file on its own without being given an instruction to do so.

So lets look at some other plausible scenarios - you are using ~~Crapbuntu~~ Ubuntu after all.

* In the past it has been proven that Baloo File Indexer and other such processes *modify* your files when they do their file indexing
  * How these ~~crap~~ not well thought out applications operate is that they modify the files date and timestamp to equal the time they were last indexed ... essentially 'touching the file' .... this triggers an inotify event - which, if you are running the application in systemd mode would cause the application to be uploaded .... you didnt modify the file - but the system you are using did
* Linux 'Office' applications - such as WPS Office will 'delete' and 'save' a new file, rather than saving the existing file. Even just opening and closing (no edits) can cause this issue to manefest when using WPS Office. This has not been seen with OpenOffice or LibreOffice.
  * Again, if using WPS Office - simply opening up the application and closing it causes WPS to delete the local file, re-write it - causing inotify events ... you didnt modify the file but the application you used did



As for your data - old copies of this document in the SharePoint Recycling Bin. Please search there for your file.

**Comment by abraunegg** [comment] 2023-03-25 18:53
> Also recommend placing a warning in the SharePoint setup documentation that this can happen. Happy to do a PR if you wish.

Feel free to raise any PR

**Comment by kendonB** [comment] 2023-03-26 00:08
The only plausible story above is the file indexer, as I wasn't using any other software. Baloo is not installed on Ubuntu 22.04 - I believe it's `tracker3`.

**Comment by kendonB** [comment] 2023-03-26 20:24
We looked in the Recycle Bin and the file strangely wasn't there, but over 100 files that the client deleted were there. We just restored all of those.

**Comment by abraunegg** [comment] 2023-04-04 01:44
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
