### ISSUE TITLE
A database statement execution error occurred: attempt to write a readonly database

### ISSUE THREAD

**Issue by Izanatos** [abraunegg/onedrive#609] opened 2019-07-31 12:24 UTC
### Bug Report Details ###
**Describe the bug**
Standalone run works fine but when I start the process it fails when it tries to sync.

Jul 31 13:14:16 server onedrive[14536]: A database statement execution error occurred: attempt to write a readonly database

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)
`Linux server 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed?
headless

*   OneDrive Account Type
Business

*   DMD  compiler version `DMD64 D Compiler v2.087.0`

*   Application configuration: 
```
onedrive version                    = v2.3.7-24-g8f71043
Config path                         = /home/administrator/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /sftp
Config option 'skip_dir'            = Documents|Download
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = true
Config option 'skip_symlinks'       = true
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
archive
```
*   Curl Version: 
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```
Application Log Output:
```
Jul 31 13:14:16 server onedrive[14536]: A database statement execution error occurred: attempt to write a readonly database
Jul 31 13:14:16 server  systemd[1510]: onedrive.service: Main process exited, code=exited, status=255/n/a
Jul 31 13:14:16 server  systemd[1510]: onedrive.service: Unit entered failed state.
Jul 31 13:14:16 server  systemd[1510]: onedrive.service: Failed with result 'exit-code'.
```

**Comment by abraunegg** [comment] 2019-07-31 19:40
@Izanatos 
This is indicative of:
* incorrect permissions
* multiple copies of the binaries running at the same time using the same configuration

**Comment by Izanatos** [comment] 2019-08-01 12:02
Hi,

Thanks for the reply.

I run onedrive as a service with systemctl --user start onedrive but looking in the process I can see that the process is not run a root but as my local admin.

is it why I am getting this issue?

Thanks,

**Comment by abraunegg** [comment] 2019-08-01 12:07
correct - when you are running as `systemctl --user start onedrive` this starts the service with 'root' permissions. If you are looking to use a specific user, you need to use `systemctl enable onedrive@<username>.service`

Refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd

**Comment by abraunegg** [comment] 2019-08-01 12:17
Closing issue, not a bug, service permissions based on how serivce is being started

**Closed by abraunegg** 2019-08-01 12:17 UTC
Labels: Answer Provided, Local Environment Issue, Not a bug, Question
