### ISSUE TITLE
Remote files get deleted for unknown reason

### ISSUE THREAD

**Issue by DorianScholz** [abraunegg/onedrive#1508] opened 2021-06-08 09:37 UTC
### Bug Report Details ###
**Describe the bug**
Files on a Sharepoint library (OneDrive Business 365) get deleted for unknown reason.
These are files I have not touched locally, not even viewed.
This happens in the background and I only noticed since my colleagues complained that I deleted their files.
They were in the online recycling bin marked as deleted by me.
This has now happend multiple times over the last 6 month, but only every few days or weeks...

**Application and Operating System Details:**
*   Ubuntu 18.x: Linux mylaptop 5.4.116-0504116-generic #202105021035 SMP Sun May 2 11:39:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
*   GUI: Gnome Shell
*   OneDrive Account Type: Business
*   Build from source: onedrive v2.4.12-7-g761cf3e, DMD64 D Compiler v2.094.0
*   curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
*   sync_dir is a local ext4 disk
*   I have multiple onedrive instances running for different sharepoint libraries all using the same account

**To Reproduce**
Can't reproduce as this happens at random intervals of mulitple days or weeks.
Only found 3 instances in my syslogs over the last two weeks.

**Logs**
Here are the normal syslog outputs (redacted for privacy):

Instance 1:
```
Jun  2 10:32:45 mylaptop onedrive[9594]: Moving General/subfolder/Old SubFolder to General/subfolder/New SubFolder
Jun  2 10:32:46 mylaptop onedrive[9594]: Trying to delete item General/subfolder/New SubFolder/sub subfolder/file name.numbers
Jun  2 10:32:46 mylaptop onedrive[9594]: Deleting item General/subfolder/New SubFolder/sub subfolder/file name.numbers
```

Instance 2:
```
Jun 08 09:10:47 mylaptop onedrive[27269]: Downloading file General/subfolder with&in it/subfolder/this&that.docx ...
Jun 08 09:10:47 mylaptop onedrive[27269]: ERROR: Microsoft OneDrive API returned an error with the following message:
Jun 08 09:10:47 mylaptop onedrive[27269]:   Error Message:    Timeout was reached on handle 565390BC4CC0
Jun 08 09:10:47 mylaptop onedrive[27269]:   Calling Function: download()
Jun 08 09:10:47 mylaptop onedrive[27269]: ERROR: File download size mis-match. Increase logging verbosity to determine why.
Jun 08 09:10:47 mylaptop onedrive[27269]: ERROR: File download hash mis-match. Increase logging verbosity to determine why.
Jun 08 09:10:47 mylaptop onedrive[27269]: ERROR: The local file system returned an error with the following message:
Jun 08 09:10:47 mylaptop onedrive[27269]:   Error Message:    General/subfolder with&in it/subfolder/this&that.docx: No such file or directory
Jun 08 09:10:47 mylaptop onedrive[27269]:   Calling Function: applyChangedItem()
Jun 08 09:10:48 mylaptop onedrive[27269]: Downloading file General/subfolder with&in it/subfolder/another file from same folder.pptx ...
Jun 08 09:10:54 mylaptop onedrive[27269]: [3.2K blob data]
Jun 08 09:10:54 mylaptop onedrive[27269]: done.
Jun 08 09:10:54 mylaptop onedrive[27269]: Deleting item from OneDrive: General/subfolder with&in it/subfolder/this&that.docx
Jun 08 09:10:55 mylaptop onedrive[27269]: Cannot upload file changes/creation: General/subfolder with&in it/subfolder/this&that.docx: No such file or directory
```

Instance 3:
(on this file luckily the deletion failed, because it was locked by someone else...)
```
Jun  1 12:16:26 mylaptop onedrive[16613]: Downloading file General/subfolder/sub_folder/file - name_asd.xlsx ... done.
Jun  1 12:16:26 mylaptop onedrive[16613]: Uploading differences of General/subfolder/sub_folder/file - name_asd.xlsx
Jun  1 12:16:26 mylaptop onedrive[16613]: Uploading new items of General/subfolder/sub_folder/file - name_asd.xlsx
Jun  1 12:17:29 mylaptop onedrive[16613]: WARNING: OneDrive quota information is being restricted or providing a zero value. Please fix by speaking to your OneDrive / Office 365 Administrator.
Jun  1 12:17:59 mylaptop onedrive[16613]: Starting a sync with OneDrive
Jun  1 12:17:59 mylaptop onedrive[16613]: Syncing changes from OneDrive ...
Jun  1 12:18:00 mylaptop onedrive[16613]: Sync with OneDrive is complete
Jun  1 12:23:32 mylaptop onedrive[16613]: Downloading file General/subfolder/sub_folder/file - name_asd.xlsx ...
Jun  1 12:23:32 mylaptop onedrive[16613]: ERROR: OneDrive returned an error with the following message:
Jun  1 12:23:32 mylaptop onedrive[16613]:   Error Message: Timeout was reached on handle 55A15A424E00
Jun  1 12:23:32 mylaptop onedrive[16613]: ERROR: File download size mis-match. Increase logging verbosity to determine why.
Jun  1 12:23:32 mylaptop onedrive[16613]: ERROR: File download hash mis-match. Increase logging verbosity to determine why.
Jun  1 12:23:32 mylaptop onedrive[16613]: ERROR: The local file system returned an error with the following message:
Jun  1 12:23:32 mylaptop onedrive[16613]:   Error Message: General/subfolder/sub_folder/file - name_asd.xlsx: No such file or directory
Jun  1 12:23:32 mylaptop onedrive[16613]: Deleting item from OneDrive: General/subfolder/sub_folder/file - name_asd.xlsx
Jun  1 12:23:33 mylaptop onedrive[16613]: ERROR: OneDrive returned an error with the following message:
Jun  1 12:23:33 mylaptop onedrive[16613]:   Error Message: HTTP request returned status code 423 (Locked)
Jun  1 12:23:33 mylaptop onedrive[16613]:   Error Reason:  The resource you are attempting to access is locked
```

### Bug Report Checklist ###
*   [x] Detailed description
*   [x] Application and Operating System Details provided in full
*   [n/a] Reproduction steps (if applicable)
*   [n/a] Verbose Log Output from your error
*   [n/a] Debug Log generated and submitted

**Comment by abraunegg** [comment] 2021-06-08 10:07
@DorianScholz 
There are a number of things going on here:

1. You are using SharePoint. This means that you are being hit by this issue: https://github.com/OneDrive/onedrive-api-docs/issues/935
   
   What this issue means to you is, from Linux, each and *every* time you upload a file, Microsoft will be modifying this file. How this gets done, and how you keep in-sync, involves deletion of files. This *could* be what you are seeing. The deletes - even if you are not doing them, could be done by background application processes - see https://github.com/abraunegg/onedrive/issues/824

2. What office application are you using on Linux? WPS Office & the way it handles file writes - it *deletes* the file and re-creates it - see https://github.com/abraunegg/onedrive/issues/712

For point 1, suggest you modify your application configuration to use `--verbose` and see what additional messaging is being outputted to assist here.

For point 2 - if you are using WPS Office on Linux .. dont. Find an alternative or file a bug with them.

I also suggest you run the application in `--verbose --verbose` for a while to capture verbose debug logs. This will assist in tracking down if this a bug or other issue.

**Comment by DorianScholz** [comment] 2021-06-09 00:04
Thanks for the quick response!

For point 1:
Sad to hear about this SharePoint issue!
I have enabled more verbose logging, but since it can't reproduce easily it might take some time until I have more info.

For point 2:
I'm not using any Office in Linux, only the browser based MS Office.
And as stated, the files in question were never edited or even viewed by me and still got deleted somehow in the sync process...

**Comment by abraunegg** [comment] 2021-06-09 00:15
@DorianScholz 
> And as stated, the files in question were never edited or even viewed by me and still got deleted somehow in the sync process...

OK .. this is 100% concerning.

I suspect that 'something' on your Linux system is performing those actions. If you are not deleting the file, then 'something' is creating those actions on those files on your behalf somehow.

If you are only using browser based MS Office, from the browser, saving the file locally somehow (unsure if this is possible, have not checked) - it 'could' be that process that is triggering it unwittingly from the browser - but again, you really will need to look at all actions being taken to understand what is going on.

Also the systemd logging you have provided this far, does not show the inotify activity for these events. I 'think' these will only be shown in normal logging to terminal / log file .. but not the systemd logs - thus, I think you also need to enable logging to a separate file rather than relying on systemd logging and make sure that you are capturing all events.

If you can capture the inotify events - this will show that maybe a deletion event was caught - meaning, a process on your system performed that action, which the client then acted upon if you are certain you did not perform that action.

If this is what is occurring, and this is not you doing this, you have some process on your system that is doing this - and this is not this clients issue.

As you are using Ubuntu 18.x ... maybe also consider using something other than Ubuntu .....

**Comment by DorianScholz** [comment] 2021-06-11 12:14
MS Office in the browser is not saving anything locally, only directly to sharepoint.
Also, files that I'm actively working with have not affected so far, only files that I never touched with any program myself, neither in browser or locally...

I'm now using the audit framework to monitor the directory for unlink and rename events:
https://wiki.archlinux.org/title/Audit_framework
Let's see what I can find...

Additionally I'm logging onedrive debug events to a separate file.
Any hints on how to prevent onedrive debug logging also going into my syslog?
(this is filling up my root partition rather quickly...)

**Comment by abraunegg** [comment] 2021-06-11 21:16
@DorianScholz 
> I'm now using the audit framework to monitor the directory for unlink and rename events

Great - hopefully it will show what is deleting the file on your behalf. This onedrive client will not be the source of those events - it is merely processing the inotify event that it receives. Once you do find that source, you will have to lodge a bug against that application - and hopefully then close this one as the cause of deletion will be found.

> Any hints on how to prevent onedrive debug logging also going into my syslog?

You will need to create a rsyslog configuration so that the logging to syslog is reduced or rejected. This is not something I can assist with.

**Comment by abraunegg** [comment] 2021-06-16 20:33
@DorianScholz 
Any update in regards to your auditing of your systems activities?

**Comment by DorianScholz** [comment] 2021-06-20 13:15
Sorry for the late reply.
Still collecting logs.
Got one instance so far where the onedrive client tried to delete a file from onedrive, which I did not delete locally.
I will gather the onedrive logs and audit logs for this and post them here soon.

**Comment by abraunegg** [comment] 2021-06-23 22:52
@DorianScholz 
Any update here regarding your investigations?

**Comment by abraunegg** [comment] 2021-06-26 22:07
@DorianScholz
Any update here regarding your investigations?

**Comment by abraunegg** [comment] 2021-06-29 07:31
@DorianScholz
Any update here regarding your investigations?

**Comment by abraunegg** [comment] 2021-06-29 21:24
@DorianScholz 
Closing issue for the following reasons:
* Lack of response
* Most likely the cause of your issue is some external application triggering a inotify event that is causing the deletion of the file - this is the *only* plausible explanation I can give without evidence.

Actions for development:
* Double check debug statements around delete event, and ensure there are debug logging details written out to ensure it can be clearly seen as to the 'source' of the delete action to assist in further inquiries

**Closed by abraunegg** 2021-06-29 21:24 UTC
Labels: More Information Needed, Waiting on Response

**Comment by abraunegg** [comment] 2021-06-29 23:42
> Actions for development:
> 
> * Double check debug statements around delete event, and ensure there are debug logging details written out to ensure it can be clearly seen as to the 'source' of the delete action to assist in further inquiries

Double checked code to be sure, when using debug mode, all received inotify events are written out to the verbose log file, including any deletion activities - for example:
```
[DEBUG] inotify event wd: 2
[DEBUG] inotify event mask: 512
[DEBUG] inotify event cookie: 0
[DEBUG] inotify event len: 16
[DEBUG] inotify event name: 
[DEBUG] inotify event flag: IN_DELETE
[DEBUG] inotify event flag: IN_ALL_EVENTS
[DEBUG] inotify path event for: notes/todo.txt
[DEBUG] skip_file evaluation for: notes/todo.txt
[DEBUG] event IN_DELETE: notes/todo.txt
[M] Item deleted: notes/todo.txt
```

**Comment by DorianScholz** [comment] 2021-06-30 15:07
Sorry, my responses are taking so long.

I was really hoping I could give you more helpful insights into what is happening.
Over the last two weeks this issue has appeared about 20 times, but fortunately none of the files was actually deleted from Sharepoint, because this seems to happen mostly when someone else is editing the file and it is therefore locked on Sharepoint preventing the deletion.
So the case where the file actually gets deleted from Sharepoint is even more seldom and I have yet to catch an instance with the debug logs...
But I would say already the deletion attempt by the sync client is not supposed to happen. 

The auditd rule that I set up has not caught any unlink or rename events of the files the sync client detects as missing and want to delete from Sharepoint.
The auditd rule seems to be working in general though, as it logs when I delete a file the relevant directory in the terminal or with a file manager.

So all I can supply at the moment to hopefully shed some more light onto this are the debug logs from the sync client itself.
Here is an example of a file "relevant_file.pptx" which the sync client tries to delete from Sharepoint, but fortunately fails, since the file was being worked on by a colleague and was therefore locked by Sharepoint.

There were two attempts to delete this file.
This is attempt 1:
```
2021-Jun-14 14:14:15.2038904    [DEBUG] Attempting to calculate local filesystem path for b!bPuoBEqlM0eE_51840vPvZgb6s8S53RNs5bWldptzHUxzcNI-vjkSpUc-WWolK7C and 01G474SYDUAD562QPQHNFZRL4G7JRJQ36J
2021-Jun-14 14:14:15.2042015    Processing General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:15.2043036    [DEBUG] skip_file evaluation for: relevant_file.pptx
2021-Jun-14 14:14:15.2044717    The file appears to have been deleted locally .. but we are running in --monitor mode. This may have been 'moved' on the local filesystem rather than being 'deleted'
2021-Jun-14 14:14:15.2045006    [DEBUG] Most likely cause - 'inotify' event was missing for whatever action was taken locally or action taken when application was stopped
2021-Jun-14 14:14:15.2045221    Deleting item from OneDrive: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:15.2048364    [DEBUG] Number of items to delete: 0
2021-Jun-14 14:14:15.2049018    [DEBUG] Attempting to delete item from drive: b!bPuoBEqlM0eE_51840vPvZgb6s8S53RNs5bWldptzHUxzcNI-vjkSpUc-WWolK7C
2021-Jun-14 14:14:15.2049212    [DEBUG] Attempting to delete this item id: 01G474SYDUAD562QPQHNFZRL4G7JRJQ36J
2021-Jun-14 14:14:15.3979561    [DEBUG] onedrive.deleteById generated an error response when attempting to delete object by item id
2021-Jun-14 14:14:15.3982854
ERROR: Microsoft OneDrive API returned an error with the following message:
2021-Jun-14 14:14:15.3983095      Error Message:    HTTP request returned status code 423 (Locked)
2021-Jun-14 14:14:15.398363     [DEBUG] Raw Error Data: HTTP request returned status code 423 (Locked)
{
    "error": {
        "code": "notAllowed",
        "innerError": {
            "client-request-id": "47e8b7fa-9c19-4b6d-a97c-4883b69ced42",
            "date": "2021-06-14T12:14:15",
            "request-id": "47e8b7fa-9c19-4b6d-a97c-4883b69ced42"
        },
        "message": "The resource you are attempting to access is locked"
    }
}
2021-Jun-14 14:14:15.3986851    [DEBUG] JSON Message: {"error":{"code":"notAllowed","innerError":{"client-request-id":"47e8b7fa-9c19-4b6d-a97c-4883b69ced42","date":"2021-06-14T12:14:15","request-id":"47e8b7fa-9c19-4b6d-a97c-4883b69ced42"}
2021-Jun-14 14:14:15.3987477      Error Reason:     The resource you are attempting to access is locked
2021-Jun-14 14:14:15.3987657      Error Timestamp:  2021-06-14T12:14:15
2021-Jun-14 14:14:15.3987792      API Request ID:   47e8b7fa-9c19-4b6d-a97c-4883b69ced42
2021-Jun-14 14:14:15.3987926      Calling Function: uploadDeleteItem()
```
This is attempt 2 a second later:
```
021-Jun-14 14:14:16.4698729    [DEBUG] Attempting to calculate local filesystem path for b!bPuoBEqlM0eE_51840vPvZgb6s8S53RNs5bWldptzHUxzcNI-vjkSpUc-WWolK7C and 01G474SYBK674TF4PAJZAJ5L4AUAJXUHVZ
2021-Jun-14 14:14:16.4700279    Processing path/to/other/file/other_irrelevant_file.pdf
2021-Jun-14 14:14:16.4700516    [DEBUG] skip_file evaluation for: other_irrelevant_file.pdf
2021-Jun-14 14:14:16.4701293    The file has not changed
2021-Jun-14 14:14:16.4701516    [DEBUG] inotify event wd: 11
2021-Jun-14 14:14:16.4701682    [DEBUG] inotify event mask: 8
2021-Jun-14 14:14:16.4701826    [DEBUG] inotify event cookie: 0
2021-Jun-14 14:14:16.4701976    [DEBUG] inotify event len: 64
2021-Jun-14 14:14:16.4702119    [DEBUG] inotify event name:
2021-Jun-14 14:14:16.4702262    [DEBUG] inotify event flag: IN_CLOSE_WRITE
2021-Jun-14 14:14:16.4702382    [DEBUG] inotify event flag: IN_CLOSE
2021-Jun-14 14:14:16.4702513    [DEBUG] inotify event flag: IN_ALL_EVENTS
2021-Jun-14 14:14:16.470268     [DEBUG] inotify path event for: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4702819    [DEBUG] skip_file evaluation for: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4703235    [DEBUG] event IN_CLOSE_WRITE and ...: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4703372    [M] File changed: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4729717    Cannot upload file changes/creation: General/path/to/file/relevant_file.pptx: No such file or directory
2021-Jun-14 14:14:16.4730387    [DEBUG] inotify event wd: 11
2021-Jun-14 14:14:16.4730663    [DEBUG] inotify event mask: 512
2021-Jun-14 14:14:16.4730902    [DEBUG] inotify event cookie: 0
2021-Jun-14 14:14:16.4731134    [DEBUG] inotify event len: 64
2021-Jun-14 14:14:16.4731377    [DEBUG] inotify event name:
2021-Jun-14 14:14:16.4731636    [DEBUG] inotify event flag: IN_DELETE
2021-Jun-14 14:14:16.473183     [DEBUG] inotify event flag: IN_ALL_EVENTS
2021-Jun-14 14:14:16.4732108    [DEBUG] inotify path event for: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4732352    [DEBUG] skip_file evaluation for: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4732999    [DEBUG] event IN_DELETE: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.473325     [M] Item deleted: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4736137    Deleting item from OneDrive: General/path/to/file/relevant_file.pptx
2021-Jun-14 14:14:16.4737443    [DEBUG] Number of items to delete: 0
2021-Jun-14 14:14:16.4737787    [DEBUG] Attempting to delete item from drive: b!bPuoBEqlM0eE_51840vPvZgb6s8S53RNs5bWldptzHUxzcNI-vjkSpUc-WWolK7C
2021-Jun-14 14:14:16.4738146    [DEBUG] Attempting to delete this item id: 01G474SYDUAD562QPQHNFZRL4G7JRJQ36J
2021-Jun-14 14:14:16.7464027    [DEBUG] onedrive.deleteById generated an error response when attempting to delete object by item id
2021-Jun-14 14:14:16.7468882
ERROR: Microsoft OneDrive API returned an error with the following message:
2021-Jun-14 14:14:16.7469411      Error Message:    HTTP request returned status code 423 (Locked)
2021-Jun-14 14:14:16.7470046    [DEBUG] Raw Error Data: HTTP request returned status code 423 (Locked)
{
    "error": {
        "code": "notAllowed",
        "innerError": {
            "client-request-id": "2fb23116-1fd7-4136-8f1f-f1d822e4336c",
            "date": "2021-06-14T12:14:16",
            "request-id": "2fb23116-1fd7-4136-8f1f-f1d822e4336c"
        },
        "message": "The resource you are attempting to access is locked"
    }
}
2021-Jun-14 14:14:16.74736      [DEBUG] JSON Message: {"error":{"code":"notAllowed","innerError":{"client-request-id":"2fb23116-1fd7-4136-8f1f-f1d822e4336c","date":"2021-06-14T12:14:16","request-id":"2fb23116-1fd7-4136-8f1f-f1d822e4336c"}
2021-Jun-14 14:14:16.747432       Error Reason:     The resource you are attempting to access is locked
2021-Jun-14 14:14:16.7474527      Error Timestamp:  2021-06-14T12:14:16
2021-Jun-14 14:14:16.7474703      API Request ID:   2fb23116-1fd7-4136-8f1f-f1d822e4336c
2021-Jun-14 14:14:16.7474867      Calling Function: uploadDeleteItem()

2021-Jun-14 14:14:16.7475152    Uploading new items of /media/data/dorian/OneDrive/sharepoint_lib
```

**Comment by abraunegg** [comment] 2021-06-30 21:20
@DorianScholz 
This clearly shows that the 'actions' are coming from outside the this application - this application is *not* the cause or source of this activity. 

Some options for you to think about:
* Find the source of this activity and raise a bug against that application or raise a bug against Ubuntu itself
* Stop using Ubuntu as your Linux OS - use something that is *not* based on Ubuntu
* Use the correct distribution kernel package for your OS as you appear to potentially be using your own kernel ... introducing maybe some sort of kernel bug ... 
* Use a better file system for your data such as ZFS on Linux to ensure some sort of weird file system issue is not the root cause here

This issue is *not* a bug or issue with this client.
