### ISSUE TITLE
ERROR: The local file system returned an error with the following message

### ISSUE THREAD

**Issue by CKingX** [abraunegg/onedrive#1906] opened 2022-04-01 01:00 UTC
### Describe the bug

While downloading files, I get errors like these for some files:
```
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/tcltk2/tklibs/ttktheme_aquablue/aquablue/scaletrough-v.gif: No such file or directory
  Calling Function: downloadFileItem()
```

### Operating System Details

```shell
`uname -a` gave me this:
`Linux skydrive 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

while running lsb_release -a gave me this:

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
I have been running this on Ubuntu Server (with ZFS as the storage backend), but even on full Desktop insall, it has the same issue
```


### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

onedrive v2.4.16-1~np1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                       = v2.4.16-1~np1
Config path                            = /home/chirag/.config/onedrive
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/chirag/onedrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```

### What is your 'curl' version

```shell
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=937068k,nr_inodes=234267,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=196412k,mode=755)
/dev/mapper/ubuntu--vg-ubuntu--lv on / type ext4 (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15758)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on /boot type ext4 (rw,relatime)
/dev/sda1 on /boot/efi type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
onedrive on /home/chirag/onedrive type zfs (rw,xattr,posixacl)
/var/lib/snapd/snaps/core20_1328.snap on /snap/core20/1328 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snapd_14978.snap on /snap/snapd/14978 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/lxd_21835.snap on /snap/lxd/21835 type squashfs (ro,nodev,relatime,x-gdu.hide)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=196412k,mode=755)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=196408k,mode=700,uid=1000,gid=1000)
/var/lib/snapd/snaps/core20_1405.snap on /snap/core20/1405 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/snapd_15177.snap on /snap/snapd/15177 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/lxd_22753.snap on /snap/lxd/22753 type squashfs (ro,nodev,relatime,x-gdu.hide)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
```

### What are all your local file system partition types

```shell
NAME                      FSTYPE      LABEL    UUID                                   FSAVAIL FSUSE% MOUNTPOINT
loop0                     squashfs                                                          0   100% /snap/core20/1328
loop1                     squashfs                                                          0   100% /snap/snapd/14978
loop2                     squashfs                                                          0   100% /snap/lxd/21835
loop3                     squashfs                                                          0   100% /snap/core20/1405
loop4                     squashfs                                                          0   100% /snap/snapd/15177
loop5                     squashfs                                                          0   100% /snap/lxd/22753
sda                                                                                                  
├─sda1                    vfat                 3D88-219B                               531.7M     1% /boot/efi
├─sda2                    ext4                 710d2042-a192-4cdf-b1bb-a1b04592e6a9    578.4M    15% /boot
└─sda3                    LVM2_member          3BWLod-Yuw9-qbUP-X8Ds-6GdL-115z-Bi9YNx                
  └─ubuntu--vg-ubuntu--lv ext4                 1cf73479-0c9b-4c9b-a6fb-9fc7b6d69711   1017.8M    73% /
sdb                                                                                                  
├─sdb1                    zfs_member  onedrive 18263902214144971873                                  
└─sdb9                                                                                               
sr0
```

### How do you use 'onedrive'

I installed it using the OpenSUSE package as per the install instructions here. I then changed the configuration to use onedrive rather than OneDrive and use download-only option and set it up with my personal email (Previously, the error still showed up when I used this without download-only option, but some of the folder started deleting so I had to start from scratch, recover files from OneDrive website in the Recycling Bin and recreate the VM from scratch). The onedrive folder itself is hosted on ZFS

### Steps to reproduce the behaviour

Install OneDrive on Ubuntu using the opensuse repository as per instructions. Log in and start syncronization (with or without download-only option). Some of these files will get the error

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /home/chirag/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/chirag/onedrive
Application version: v2.4.16-1~np1
Account Type: personal
Default Drive ID: 3ae0e262bc74e151
Default Root ID: 3AE0E262BC74E151!107
Remaining Free Space: 3298385724
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 3AE0E262BC74E151!107
Updated Remaining Free Space: 3298385724
Processing 259 OneDrive items to ensure consistent local state
The database is currently locked by another process - cannot sync
The database is currently locked by another process - cannot sync
Processing 354 OneDrive items to ensure consistent local state
Downloading file Documents/R/win-library/4.1/pillar/help/figures/lifecycle-maturing.svg ... 
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/pillar/help/figures/lifecycle-maturing.svg: No such file or directory
  Calling Function: downloadFileItem()

Downloading file Documents/R/win-library/4.1/pillar/help/figures/lifecycle-experimental.svg ... done.
Downloading file Documents/R/win-library/4.1/pillar/help/figures/lifecycle-deprecated.svg ... done.
Downloading file Documents/R/win-library/4.1/nloptr/libs/i386/nloptr.dll ... 
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/nloptr/libs/i386/nloptr.dll: No such file or directory
  Calling Function: downloadFileItem()

Downloading file Documents/R/win-library/4.1/munsell/help/figures/README-manipulate-blue-1.png ... 
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/munsell/help/figures/README-manipulate-blue-1.png: No such file or directory
  Calling Function: downloadFileItem()

Downloading file Documents/R/win-library/4.1/pillar/help/figures/lifecycle-archived.svg ... done.
Downloading file Documents/R/win-library/4.1/png/libs/i386/symbols.rds ... done.
Downloading file Documents/R/win-library/4.1/munsell/help/figures/README-complement-slice-1.png ... 
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/munsell/help/figures/README-complement-slice-1.png: No such file or directory
  Calling Function: downloadFileItem()

Downloading file Documents/R/win-library/4.1/png/libs/x64/symbols.rds ... done.
Downloading file Documents/R/win-library/4.1/processx/libs/i386/symbols.rds ... done.
Downloading file Documents/R/win-library/4.1/nloptr/libs/x64/nloptr.dll ... done.
Downloading file Documents/R/win-library/4.1/processx/libs/i386/processx.dll ... done.
Downloading file Documents/R/win-library/4.1/processx/libs/i386/client.dll ...
```

### Screenshots

![image](https://user-images.githubusercontent.com/13824156/161174141-ec4950e8-a124-4195-993d-2a2a6d7111d9.png)

**Comment by abraunegg** [comment] 2022-04-01 02:31
@CKingX 
```
ERROR: The local file system returned an error with the following message:
  Error Message:    Documents/R/win-library/4.1/pillar/help/figures/lifecycle-maturing.svg: No such file or directory
  Calling Function: downloadFileItem()
```


This particular error is coming from your actual filesystem - meaning that, when the client has attempted to update the timestamp and/or set the file permissions on your file, your filesystem - told the client that the file does not exist.

Can you check and actually see if there is *any* file or data in that location for the file? .partial or otherwise.

I would also check your disks for any physical errors (bad sectors, pending sectors) or if this a SSD or similar - check all the FS Trim values to ensure there are no issues.

> I have been running this on Ubuntu Server (with ZFS as the storage backend), but even on full Desktop insall, it has the same issue

When you had this running on ZFS - was it actually a ZFS volume or was it ZFS backend with some other filesystem format over the top?

**Comment by CKingX** [comment] 2022-04-01 02:47
> This particular error is coming from your actual filesystem - meaning that, when the client has attempted to update the timestamp and/or set the file permissions on your file, your filesystem - told the client that the file does not exist.
> 
> Can you check and actually see if there is _any_ file or data in that location for the file? .partial or otherwise.
> 
> I would also check your disks for any physical errors (bad sectors, pending sectors) or if this a SSD or similar - check all the FS Trim values to ensure there are no issues.

There are files in the directory:
![image](https://user-images.githubusercontent.com/13824156/161184975-832b65bf-b3ef-45fc-ad84-e60d888c616d.png)

The disk on host is fine and the whole setup for now is running in a VM (with over 5 GB disk (technically an vhdx image but to a VM it looks like a disk?) for boot with Ubuntu server, and a separate disk that is ~70 GB for OneDrive)


> When you had this running on ZFS - was it actually a ZFS volume or was it ZFS backend with some other filesystem format over the top?

So the boot is entirely ext4 on top of LVM (that's how Ubuntu Server sets it up). The 70 GB disk is ZFS mounted at `/home/chirag/onedrive`. 

Here is the VM setup for harddrive:
![image](https://user-images.githubusercontent.com/13824156/161185355-521b499d-ce65-4e03-9095-fc3d308ef759.png)

**Comment by abraunegg** [comment] 2022-04-01 03:00
@CKingX 
> The disk on host is fine and the whole setup for now is running in a VM (with over 5 GB disk (technically an vhdx image but to a VM it looks like a disk?) for boot with Ubuntu server, and a separate disk that is ~70 GB for OneDrive (which in Hyper-V is another disk image that it creates) but with copies=2 set up)

OK .. this will be your problem. Hyper-V is *not* a good choice for a hypervisor. How the virtual disk is being presented + how the underlying Windows OS handles all the disk write requests. You are probably being bitten by write hole issues.

I 100% suspect that your issue is related to your setup and nothing related to this client.

**Comment by CKingX** [comment] 2022-04-01 08:04
> OK .. this will be your problem. Hyper-V is _not_ a good choice for a hypervisor. How the virtual disk is being presented + how the underlying Windows OS handles all the disk write requests. You are probably being bitten by write hole issues.
> 
> I 100% suspect that your issue is related to your setup and nothing related to this client.

So I decided to rule out both hypervisor, ZFS and any extra files. I dualbooted to Ubuntu this time, shrunk the Ubuntu partition down and created a new ext4 (5 GB) partition. Then, I set up OneDrive according to install.md (this time using Ubuntu 21.10). I used a different account where I just installed R and synced up that folder. This same message happened here (![image](https://user-images.githubusercontent.com/13824156/161221324-f31e803d-93aa-426d-8e8b-838175994d47.png)

Here's a way to reproduce it. Inside the Documents folder in OneDrive, copy these files (using the website or on Windows) (share link to it here)

https://1drv.ms/u/s!Au2grZ5nWTbdgSKBdC32vjR_mTgE?e=ZrcnJ7

Then set up OneDrive on linux and have it synchronize. It should create the "The local file system returned an error with the following message" for some of the files.

**Comment by abraunegg** [comment] 2022-04-01 08:20
@CKingX 
I am unable to reproduce this at all ...

Please can you have a think about the following:
* There is *something* potentially up with your physical hardware - even though you say there is no issue ........ subtle errors may exist
  * Check that your power cables / cables are correctly seated
  * Make sure you have no drive | cabling errors
  * Make sure you have no power issues going to the drive
* Disk *writes* are not being reflected quickly enough to the OS you are running
* Some obscure Ubuntu issue due to how they manage their ecosystem
  * Try and replicate *without* using Ubuntu
* Try and replicate on some totally *different* hardware

This application is extensively tested and used. If this was an application issue, there would be hundreds if not thousands of reports of an issue.

Will try with your data set shortly - as it is not adding to my OneDrive account at present - so need to rework some stuff to make it available.

**Comment by CKingX** [comment] 2022-04-01 09:13
I will try this on another computer this weekend using Fedora (although I will likely have to do it using live usb as I don't want to install another OS or dualboot on that machine.)

If you can't add it to your account, just download the folder win-library folder using the website. It will create a zip file. Extract that somewhere and upload that using the OneDrive website (it gives the option to upload a folder). However, make sure to create the win-library folder inside R folder and extract there as zip extraction just seems to extract everything inside of win-library rather than create the folder win-library and extract everything inside it. Also be warned there is a risk of data deletion (I think of files that it couldn't download due to this error, but you can prevent it by using downloading only option)

**Comment by abraunegg** [comment] 2022-04-01 19:35
@CKingX 
I downloaded your R data archive, extracted, uploaded to a test account and replicated your OneDrive directory structure based on your logs thus far:

![directory_structure](https://user-images.githubusercontent.com/4956234/161328197-7a4f862c-8573-41b6-b3a2-2ba65064da38.JPG)

![directory_structure_2](https://user-images.githubusercontent.com/4956234/161328209-732eaeaa-28a3-473d-897d-27a32b80affd.JPG)

I have then installed Ubuntu 21.10, ensured this was updated, then installed the client as per: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md

I authorised the client, enabled logging via the configuration file, then started a download of all the data using the command: `onedrive --synchronize --verbose`

**In Progress:**
![In_Progress](https://user-images.githubusercontent.com/4956234/161327199-b9781691-02dd-4a86-9023-6e6d9e7fca2e.JPG)

**Completed without any file access errors:**
![Completed](https://user-images.githubusercontent.com/4956234/161328536-5aa52fcb-82bb-47f8-8bc2-7ce5ede61197.JPG)

**Log File:**
 [onedrive.log](https://github.com/abraunegg/onedrive/files/8400437/onedrive.log)

As you can see - zero issue downloading the data or writing this to disk.

When I look specifically for files that you have had issues with:
![issue_files](https://user-images.githubusercontent.com/4956234/161329703-d47884f3-9916-47b5-ac5e-92d47997ab20.JPG)

These were downloaded without issue.

I *did* however get a OneDrive 503 error attempting to download one file - however a 503 is generated by OneDrive API - meaning internally the OneDrive platform had a problem ... and this error was gracefully handled by the client. Why the 503 error was generated by the OneDrive API - who knows .... that error comes from deep inside their platform.

The error you are receiving is coming from your Operating System - and it is telling you that the file is not there (but it is) .. this tells me you have some sort of issue with your platform, your hardware, storage devices or something else - some sort of file system issue - but it is *not* this client that is causing this .. it is simply reporting what the Operating System is advising.

**Comment by abraunegg** [comment] 2022-04-02 00:16
Closing this issue as the most likely cause will be:
* Some sort of hardware issue
* Potentially power supply related
* Operating System related

This is not a bug or issue with this client.

**Closed by abraunegg** 2022-04-02 00:16 UTC
Labels: Not a bug, Local Environment Issue

**Comment by CKingX** [comment] 2022-04-02 20:44
Thanks! I tested Fedora which had no problem. Ubuntu live-usb on another computer also worked. On the computer where the downloadFileItem reported local file system error, I built the onedrive following instructions on install.md and using that version, I do not get any errors. Thanks for the help though!
