### ISSUE TITLE
Bug: Folders are renamed despite using --dry-run

### ISSUE THREAD

**Issue by marmeladapk** [abraunegg/onedrive#2341] opened 2023-03-17 09:07 UTC
### Describe the bug

When running `onedrive --confdir="~/.config/<config_dir>" --synchronize --dry-run` folder was renamed on disk despite --dry-run flag. No other changes happened.

```
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Moving General/<folder a> to General/<folder b>
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of <sharepoint dir>
Uploading new items of <sharepoint dir>
```

### Operating System Details

```shell
Linux LB-18-22 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Elementary
Description:	elementary OS 6.1 Jólnir
Release:	6.1
Codename:	jolnir
```
(system is based on ubuntu 20.04)

### Client Installation Method

From 3rd Party Source (PPA, OpenSuSE Build Service etc)

### OneDrive Account Type

SharePoint

### What is your OneDrive Application Version

onedrive v2.4.23-1+np1

### What is your OneDrive Application Configuration

```shell
Configuration file successfully loaded
onedrive version                             = v2.4.23-1+np1
Config path                                  = <config_path>
Config file found in config path             = true
Config option 'drive_id'                     = <id>
Config option 'sync_dir'                     = /media/<user>/DATA/SharePoint/sync_folder
Config option 'enable_logging'               = false
Config option 'log_dir'                      = /var/log/onedrive/
Config option 'disable_notifications'        = false
Config option 'min_notify_changes'           = 5
Config option 'skip_dir'                     = 
Config option 'skip_dir_strict_match'        = false
Config option 'skip_file'                    = ~*|.~*|*.tmp
Config option 'skip_dotfiles'                = false
Config option 'skip_symlinks'                = false
Config option 'monitor_interval'             = 300
Config option 'monitor_log_frequency'        = 6
Config option 'monitor_fullscan_frequency'   = 12
Config option 'read_only_auth_scope'         = false
Config option 'dry_run'                      = false
Config option 'upload_only'                  = false
Config option 'download_only'                = false
Config option 'local_first'                  = false
Config option 'check_nosync'                 = true
Config option 'check_nomount'                = true
Config option 'resync'                       = false
Config option 'resync_auth'                  = false
Config option 'cleanup_local_files'          = false
Config option 'classify_as_big_delete'       = 1000
Config option 'disable_upload_validation'    = false
Config option 'bypass_data_preservation'     = false
Config option 'no_remote_delete'             = false
Config option 'remove_source_files'          = false
Config option 'sync_dir_permissions'         = 700
Config option 'sync_file_permissions'        = 600
Config option 'space_reservation'            = 52428800
Config option 'application_id'               = 
Config option 'azure_ad_endpoint'            = 
Config option 'azure_tenant_id'              = common
Config option 'user_agent'                   = 
Config option 'force_http_11'                = false
Config option 'debug_https'                  = false
Config option 'rate_limit'                   = 0
Config option 'operation_timeout'            = 3600
Config option 'sync_root_files'              = false
Selective sync 'sync_list' configured        = false
Config option 'sync_business_shared_folders' = false
Business Shared Folders configured           = false
Config option 'webhook_enabled'              = false
```

### What is your 'curl' version

```shell
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=16216304k,nr_inodes=4054076,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3256992k,mode=755,inode64)
rpool/ROOT/ubuntu_<id> on / type zfs (rw,relatime,xattr,posixacl)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755,inode64)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/misc type cgroup (rw,nosuid,nodev,noexec,relatime,misc)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=24451)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
rpool/ROOT/ubuntu_<id>/tmp on /tmp type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/srv on /srv type zfs (rw,relatime,xattr,posixacl)
rpool/USERDATA/root_<id> on /root type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib on /var/lib type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/usr/local on /usr/local type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/log on /var/log type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/mail on /var/mail type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/games on /var/games type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/snap on /var/snap type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/spool on /var/spool type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/www on /var/www type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib/AccountService on /var/lib/AccountService type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib/NetworkManager on /var/lib/NetworkManager type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib/dpkg on /var/lib/dpkg type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib/docker on /var/lib/docker type zfs (rw,relatime,xattr,posixacl)
rpool/ROOT/ubuntu_<id>/var/lib/apt on /var/lib/apt type zfs (rw,relatime,xattr,posixacl)
/dev/sda2 on /media/<user>/data2 type ext4 (rw,noatime,errors=remount-ro)
bpool/BOOT/ubuntu_<id> on /boot type zfs (rw,nodev,relatime,xattr,posixacl)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/nvme0n1p1 on /boot/grub type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
rpool/USERDATA/<user> on /home/<user> type zfs (rw,relatime,xattr,posixacl)
dislocker on /media/<user>/bitlocker type fuse.dislocker (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
/media/<user>/bitlocker/dislocker-file on /media/<user>/DATA type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3256988k,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

### What are all your local file system partition types

```shell
NAME          FSTYPE     LABEL    UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0         ntfs                <id>                       61,2G    79% /media/<user>/DATA
sda                                                                                   
├─sda1        BitLocker                                                               
├─sda2        ext4                <id>    /media/<user>/data2
└─sda3        swap                <id>                
  └─cryptswap swap                <id>                [SWAP]
nvme0n1                                                                               
├─nvme0n1p1   vfat       BOOT     <id>                             429,1M    14% /boot/efi
├─nvme0n1p2                                                                           
├─nvme0n1p3   zfs_member bpool    <id>                                
├─nvme0n1p4   zfs_member rpool    <id>                                
├─nvme0n1p5   ntfs                <id>                                    
└─nvme0n1p6   ntfs       Recovery <id>
```

### How do you use 'onedrive'

Windows also has access to this folder (not at the same time) but is not configured to sync this sharepoint. Folder resides on bitlocker encrypted partition.

### Steps to reproduce the behaviour

Change folder name in sharepoint (e.g. online). Perform sync with --dry-run.

### Complete Verbose Log Output

```shell
Using 'user' Config Dir: /home/<user>/.config/<config_dir>
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
Opening the item database ...
All operations will be performed in: /media/<user>/DATA/SharePoint/sync_dir
ERROR: OneDrive quota information is being restricted. Please fix by speaking to your OneDrive / Office 365 Administrator.
Application version: v2.4.23-1+np1
Account Type: documentLibrary
Default Drive ID: <id>
Default Root ID: <id>
Remaining Free Space: Not Available
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Applying changes of Path ID: <id>
Processing 5 OneDrive items to ensure consistent local state
Moving General/<folder a> to General/<folder b>
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of /media/<user>/DATA/SharePoint/sync_dir
Processing .
The directory has not changed
Processing General
The directory has not changed
<ommited, files and folders have not changed>
Uploading new items of /media/<user>/DATA/SharePoint/sync_dir
Applying changes of Path ID: <id>
Sync with OneDrive is complete
```

**Comment by abraunegg** [comment] 2023-03-17 10:32
@marmeladapk 
That output is 100% normal for dry run operation

The actual local move is a 'no operation' .. that is the whole purpose of dry run. The logging output indicates what would have occured.

Can you please validate, with debug log evidence and local file system evidence that an actual change of directory occured.

**Comment by marmeladapk** [comment] 2023-03-17 11:34
> Can you please validate, with debug log evidence and local file system evidence that an actual change of directory occured.

Folder was renamed on disk during dry-run.

**Comment by abraunegg** [comment] 2023-03-19 01:38
@marmeladapk 

Please can you test the following PR to potentially resolve your issue:

```
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/2343/head:pr2343
git checkout pr2343
```

To run the PR, you need to run the client from the PR build directory:
```
./onedrive <any options needed>
```

To install the PR, you will need to perform `sudo make install` to install the PR version. 

When running the PR, your version should be: `onedrive v2.4.23-12-g957e1cb` or greater

**Comment by abraunegg** [comment] 2023-03-21 18:44
@marmeladapk 
Please can you respond.

**Comment by marmeladapk** [comment] 2023-03-21 20:35
I need a moment to set up sharepoint for testing.

**Comment by abraunegg** [comment] 2023-03-22 21:06
@marmeladapk 
Any progress ?

**Comment by marmeladapk** [comment] 2023-03-24 22:23
@abraunegg Thanks for the fix! Unfortunately it seems that it doesn't handle files gracefully. I renamed a file on the remote and while using --dry-run onedrive doesn't change the name of the file locally (which is correct) it shows an error message:

```
/tmp/onedrive/onedrive --confdir=`pwd` --synchronize --dry-run
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Moving Nowy plik to ./Nowyplik
Downloading file ./Nowyplik ... done.

ERROR: The local file system returned an error with the following message:
  Error Message:    ./Nowyplik: No such file or directory
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of /DATA/SharePoint/SITest
Uploading new items of l/DATA/SharePoint/SITest
Sync with OneDrive is complete
```

Proper sync is fine:

```
/tmp/onedrive/onedrive --confdir=`pwd` --synchronize
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes and items from OneDrive ...
Moving Nowy plik to ./Nowyplik
Downloading file ./Nowyplik ... done.
Performing a database consistency and integrity check on locally stored data ... 
Uploading differences of /DATA/SharePoint/SITest
Uploading new items of /DATA/SharePoint/SITest
Sync with OneDrive is complete
```

This doesn't happen with directories.

**Comment by abraunegg** [comment] 2023-03-24 23:12
@marmeladapk 
> Unfortunately it seems that it doesn't handle files gracefully.

That might be a regression. As that appears to be a new issue, please open a new bug report.

If the folder issue is resolved, can you double confirm - thus the fix can be merged into 'master'

**Closed** 2023-03-27 06:22 UTC
Labels: Bug, Fixed

**Comment by abraunegg** [comment] 2023-04-04 01:44
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
