### ISSUE TITLE
Cannot connect to Microsoft OneDrive Service - Network Connection Issue upon trying to Initialise

### ISSUE THREAD

**Issue by Karthik-Dulam** [abraunegg/onedrive#1238] opened 2021-01-24 18:35 UTC
### Bug Report Details ###
Upon initialising for authentication using

```
 ~$ onedrive


Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 55B20994D1E0
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service, unable to initialize application
```

**Application and Operating System Details:**
*   Linux Mint 20 `Linux cathy-mint-Inspiron-5570 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

*   Are you using a headless system (no gui) or with a gui installed? Gui 
*   OneDrive Account Type - School
*   Did you build from source or install from a package? PPI package available for Ubuntu.
*   OneDrive Application Version: Output of `onedrive --version`:` onedrive v2.4.9-0~202012270043~ubuntu20.04.1`
*   OneDrive Application Configuration: Output of `onedrive --display-config`: 
```
onedrive version                       = v2.4.9-0~202012270043~ubuntu20.04.1
Config path                            = /home/karthik/.config/onedrive
Config file found in config path       = false
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/karthik/OneDrive
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = false
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = false
```
*   Provide the version of curl you are using: Output of `curl --version`:
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```
*   Is your configured 'sync_dir' a local directory or a network mount point?
*   If *not* local, provide all the mountpoints in your system: Output of: `mount`
*   What partition format type does your configured 'sync_dir' reside on? Output of: `lsblk -f` 
```
NAME   FSTYPE LABEL       UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda                                                                           
├─sda1 vfat   ESP         B0E3-9485                             575.1M    11% /boot/efi
├─sda2                                                                        
├─sda3 ntfs   OS          F886DE3B86DDFA58                                    
├─sda4 ntfs   WINRETOOLS  A2C69777C6974A85                                    
├─sda5 ntfs   Image       644098194097EFD2                                    
├─sda6 ntfs   DELLSUPPORT 98CE64FFCE64D752                                    
└─sda7 ext4               966ee5a0-a95d-4784-8b7e-b73856c360c3  302.6G     8% /run/timeshift/backup

```
*   Explain your entire configuration setup - is the OneDrive folder shared with any other system, shared with any other platform at the same time, is the OneDrive account you use shared across multiple systems / platforms / Operating Systems and in use at the same time NA

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Install PPA of Ubuntu on Mint
2.  Type $ onedrive

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose

Using 'user' Config Dir: /home/karthik/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
No user or system config file found, using application defaults
Cannot connect to Microsoft OneDrive Service - Network Connection Issue

ERROR: Microsoft OneDrive API returned an error with the following message:
  Error Message:    Timeout was reached on handle 56304F462500
  Calling Function: testNetwork()

Unable to reach Microsoft OneDrive API service, unable to initialize application

```

**Comment by abraunegg** [comment] 2021-01-24 20:35
@Karthik-Dulam 
>```
>Unable to reach Microsoft OneDrive API service, unable to initialize application
>```

You most likely have a firewall blocking HTTPS / DNS requests or have slow DNS responses. The client cannot resolve or connect to the required services that it needs to use, to determine if the service is reachable.

This is not a bug or issue with the client, but an issue with your Linux system, your local network, your local security policies.

To diagnose your issue further, you can use:
```
curl -I --connect-timeout 5 --max-time 5 https://login.microsoftonline.com
```
If the site is reachable, something like the following will be returned:
```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Length: 149018
Content-Type: text/html; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Link: <https://aadcdn.msauth.net>; rel=preconnect; crossorigin
Link: <https://aadcdn.msauth.net>; rel=dns-prefetch
Link: <https://aadcdn.msftauth.net>; rel=dns-prefetch
X-DNS-Prefetch-Control: on
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 9e4014b7-d7ab-4b3c-b9e8-90cd15d30100
x-ms-ests-server: 2.1.11397.10 - SEASLR1 ProdSlices
Set-Cookie: fpc=Ag3BdGWv6h5Hhyj3iQ9XZ-4; expires=Thu, 11-Feb-2021 19:13:04 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: esctx=AQABAAAAAABeStGSRwwnTq2vHplZ9KL4ytg81iXsrrQ1yUHVGZXn5WvXq2FBtm_sC1rpeDQrfGMRmBdFwMUmqJZMJxx1mzRMGbZKwV9AF9E0r6j1RdCs2aum2Ery7qMcxpTuHQU7XOkLXZAKz8yQ9x_1JLWuXEmVS3ZzGOjYQjGcf6MoIvcnaR6AMpjfuOWs9qA6FrDR764gAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Tue, 12 Jan 2021 19:13:04 GMT
```

If HTTPS is blocked, the curl response will be similar to the following:
```
curl: (7) Failed connect to login.microsoftonline.com:443; Operation now in progress
```

If DNS is blocked or has slow response, the curl response will be similar to the following:
```
curl: (6) Could not resolve host: login.microsoftonline.com; Unknown error
```

**Comment by abraunegg** [comment] 2021-01-24 23:19
Issue listed now in FAQ including resolution steps: https://github.com/abraunegg/onedrive/wiki/Frequently-Asked-Questions#cannot-connect-to-microsoft-onedrive-service---network-connection-issue

Closing issue as this is not a bug or issue with client, issue is with users local environment.

**Closed by abraunegg** 2021-01-24 23:19 UTC
Labels: Answer Provided, Local Environment Issue, Not a bug

**Comment by NandanS-git** [comment] 2021-02-16 11:55
Hi I am also facing a similar issue, I have found that the issue is at timeout=5 sec at util.d file. Can you please increase the timeout from to 10 (or any number, at my location and connection minimum 6 sec is required for connection to take place). Currently using a direct compile version using timeout 10 sec, but the one from AUR doesnot.

**Comment by abraunegg** [comment] 2021-02-16 11:59
@NandanS-git 

> Hi I am also facing a similar issue, I have found that the issue is at timeout=5 sec at util.d file. Can you please increase the timeout from to 10 (or any number, at my location and connection minimum 6 sec is required for connection to take place). Currently using a direct compile version using timeout 10 sec, but the one from AUR doesnot.


You need to fix your DNS. a 5 second timeout is long enough - sorry.
