### ISSUE TITLE
sync_list does not exclude remote dirs/files

### ISSUE THREAD

**Issue by gaeeronimo** [abraunegg/onedrive#1782] opened 2022-01-06 23:43 UTC
### Bug Report Details ###
My OneDrive already contains a lot of files and is several GB big. On one PC I just want to sync one specific folder with a couple of files. I created a `sync_list` file in my config dir that only includes this folder. Still when I start syncing, the client starts downloading all other files.

Seems sync_list is only processed for uploads?

**Application and Operating System Details:**
OS: Kubuntu 20.04
uname -a: `Linux XXXXX 5.11.0-44-generic #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
GUI: KDE
Account: Private
Install: Package
Version: `onedrive v2.4.15-1~np1`
Config:
```
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.15-1~np1
Config path                            = .config/onedrive_private
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/andreas/OneDrive/Private
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 300
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /home/andreas/OneDrive/log/private/
Config option 'classify_as_big_delete' = 1000
Config option 'upload_only'            = false
Config option 'no_remote_delete'       = true
Config option 'remove_source_files'    = false
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
# sync_list supports comments
#
# The ordering of entries is highly recommended - exclusions before inclusions
#

# Sync only Testfolder
/Testfolder/*
Business Shared Folders configured     = false
```
sync_dir: local
fstype: ext4

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1. Have a OneDrive account with multiple folder
2. Create a new, empty sync_dir and a fresh config
3. Add only 1 folder to sync_list
4. `onedrive --syncdir ~/.config/fresh_config --synchronize --dry-run
5. Observe all other folder get downloaded, too

**Comment by abraunegg** [comment] 2022-01-07 00:01
@gaeeronimo 
Because you have installed via package on a Ubuntu platform - have you read and fully understood this: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#known-issues-with-installing-from-the-above-packages

You folders are being probably downloaded in the background because of this issue.

Steps to resolve:
1. Read the above URL and take the appropriate action
2. Reboot your system to ensure that there is no lurking systemd process enabled for 'onedrive'
3. Perform your testing again

**Comment by gaeeronimo** [comment] 2022-01-07 00:34
I already read the document, I double checked that the link is removed and no onedrive process is running. I never authenticated with the default confdir location. I tested with a new config in a new dir, problem stays the same.

**Comment by abraunegg** [comment] 2022-01-07 00:52
@abraunegg 
Please provide a verbose debug log as per support requirements

**Comment by abraunegg** [comment] 2022-01-07 00:53
@gaeeronimo
Please provide a verbose debug log as per support requirements

**Comment by gaeeronimo** [comment] 2022-01-07 01:11
Sorry, the full log contains huge amounts of sensitive information. Can't provide that.

I looked a little bit deeper in the log. While `onedrive -v -v --confdir .config/onedrive_test3 --display-config` clearly shows a configured sync_list:
```
onedrive version                       = v2.4.15-1~np1
Config path                            = .config/onedrive_test3
Selective sync 'sync_list' configured  = true
sync_list contents:
/Testfolder/
Business Shared Folders configured     = false
```

The verbose output during `onedrive -v -v --confdir .config/onedrive_test3 --synchronize --dry-run` says:

```
2022-Jan-07 02:05:51.7738353    [DEBUG] syncListConfigured = false
```

So it seems the sync_list wasn't loaded during sync.

**Comment by gaeeronimo** [comment] 2022-01-07 01:15
AH! Checked a little more. If I use the default config dir `.config/onedrive` the `sync_list` get's loaded and the behaviour is as expected. If I use a `--confdir` the `sync_list` does not get loaded.

**Comment by abraunegg** [comment] 2022-01-07 01:15
@gaeeronimo 
> So it seems the sync_list wasn't loaded during sync.

This is because your path passed in as the alternate configuration directory is invalid

**Comment by abraunegg** [comment] 2022-01-07 01:17
@gaeeronimo 
You need to pass in the correct path for the configuration directory - not `.config/<folder_name>` .. please follow the usage correctly for this parameter option.

**Comment by gaeeronimo** [comment] 2022-01-07 01:18
It finds the `config` file, so didn't expect the path to be incorrect.

**Comment by abraunegg** [comment] 2022-01-07 01:21
@gaeeronimo 
You must specify the path as:
```
onedrive -v -v --confdir '~/.config/onedrive_test3' --display-config
```


Closing issue, not a bug or issue. Documentation needs to be updated to reflect this parameter usage.

**Closed by abraunegg** 2022-01-07 01:21 UTC
Labels: More Information Needed, Local Environment Issue, Waiting on Response

**Comment by gaeeronimo** [comment] 2022-01-07 01:27
@abraunegg
Sorry, but the changed argument you suggested does **not** fix the issue. The `sync_list` still is ignored. And as I said, `--display-config` does display the correct (!) config and sync_list. But `--synchronize` does not use it.

**Comment by gaeeronimo** [comment] 2022-01-07 01:49
Confirm this fixed the problem. Thanks!
