### ISSUE TITLE
Download of large files (> 8 GB) fails (most of the time) due to 'OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104'

### ISSUE THREAD

**Issue by tm-89** [abraunegg/onedrive#884] opened 2020-04-22 18:48 UTC
### Bug Report Details ###
I have several large files (> 8 GB, usually below 10 GB) on my OneDrive. The download fails most of the time. E.g. the client was downloading a file that has about 9 GB, according to the progress it was at 95%, while the file only had 3.7 GB on the HDD. A bit later the client said 100%, then stopped (without any error and many files left to download). The file on the HDD has 4.1 GB. Yesterday I managed to download a file with about 8 GB after about 20 attempts. 

The log file below is for another attempt. In the end the file had 3.3 GB (out of 9 GB) and the client claimed that it was at 85%.

**Application and Operating System Details:**
*   OS: Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
*   GUI installed
*   OneDrive for Business
*   Application configuration: 
```
onedrive version = v2.4.0
Config path = /home/pi/.config/onedrive
Config file found in config path = true
Config option 'check_nosync'  = false
Config option 'skip_dir' = 
Config option 'skip_file'  = ~*|.~*|*.tmp
Config option 'skip_dotfiles'  = false
Config option 'skip_symlinks'  = false
Config option 'monitor_interval'  = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir' = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files' = false
Selective sync configured  = false
```
*   Curl Version: curl 7.64.0 (arm-unknown-linux-gnueabihf) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06

**Verbose Log Output**
```
[DEBUG] OneDrive change is a new local item
The local item has a different modified time 2020-Apr-22 13:57:14Z remote is 2020-Mar-04 23:39:29Z
The local item has a different hash
Local item does not exist in local database - replacing with file from OneDrive - failed download?
Downloading file my_data_folder/my_large_file.zip ... 

                                                                                
Downloading   5% |oo                                      |   ETA   --:--:--:
                                                                                
Downloading  10% |oooo                                    |   ETA   00:13:48 
                                                                                
Downloading  15% |oooooo                                  |   ETA   00:18:53 
                                                                                
Downloading  20% |oooooooo                                |   ETA   00:19:12 
                                                                                
Downloading  25% |oooooooooo                              |   ETA   00:19:24 
                                                                                
Downloading  30% |oooooooooooo                            |   ETA   00:18:35 
                                                                                
Downloading  35% |oooooooooooooo                          |   ETA   00:17:55 
                                                                                
Downloading  40% |oooooooooooooooo                        |   ETA   00:16:43 
                                                                                
Downloading  45% |oooooooooooooooooo                      |   ETA   00:15:33 
                                                                                
Downloading  50% |oooooooooooooooooooo                    |   ETA   00:14:37 
                                                                                
Downloading  55% |oooooooooooooooooooooo                  |   ETA   00:13:13 
                                                                                
Downloading  60% |oooooooooooooooooooooooo                |   ETA   00:11:51 
                                                                                
Downloading  65% |oooooooooooooooooooooooooo              |   ETA   00:10:27 
                                                                                
Downloading  70% |oooooooooooooooooooooooooooo            |   ETA   00:08:57 
                                                                                
Downloading  75% |oooooooooooooooooooooooooooooo          |   ETA   00:07:27 
                                                                                
Downloading  80% |oooooooooooooooooooooooooooooooo        |   ETA   00:05:56 
                                                                                
Downloading  85% |oooooooooooooooooooooooooooooooooo      |   ETA   00:04:26 
```

**Comment by abraunegg** [comment] 2020-04-22 20:13
@tm-89 
As I am unable to reproduce this due to:
* Business Account
* File Sizes involved

Please can you provide a HTTPS Debug Log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support

Please email this debug log, if possible without any file redaction other than the instructions given in the wiki.

**Comment by tm-89** [comment] 2020-04-22 23:47
> @tm-89
> As I am unable to reproduce this due to:
> 
> * Business Account
> * File Sizes involved
> 
> Please can you provide a HTTPS Debug Log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support
> 
> Please email this debug log, if possible without any file redaction other than the instructions given in the wiki.

I'm 

> @tm-89
> As I am unable to reproduce this due to:
> 
> * Business Account
> * File Sizes involved
> 
> Please can you provide a HTTPS Debug Log as per https://github.com/abraunegg/onedrive/wiki/Generate-https-debug-log-for-support
> 
> Please email this debug log, if possible without any file redaction other than the instructions given in the wiki.

I just tried to create the Debug Log. However, using the command given in the wiki (to remove the 'Authorization: bearer') doesn't really change anything apart from inserting a few spaces?

**Comment by abraunegg** [comment] 2020-04-22 23:54
@tm-89 
The sed command removes your authorization code in the log file - if I had that, I could access your account.

**Comment by tm-89** [comment] 2020-04-22 23:59
> @tm-89
> The sed command removes your authorization code in the log file - if I had that, I could access your account.

Yes, I got that. But as said, comparing the log file before and after removing the authorization code I don't find any differences (apart from a few spaces).

To be on the safe side:
The authorization code is written somewhere in the file after "authorization: " and stuff like root and drive id alone are useless?

**Comment by abraunegg** [comment] 2020-04-23 00:13
@tm-89 
That sed command 'should' be removing all instances of the auth code when present .. so long as your debug log does not have that - no issue.

knowing the drive id / account id are useless without that

**Comment by tm-89** [comment] 2020-04-23 00:15
> @tm-89
> That sed command 'should' be removing all instances of the auth code when present .. so long as your debug log does not have that - no issue.
> 
> knowing the drive id / account id are useless without that

Noted, thanks. You'll get the file soon.

**Comment by abraunegg** [comment] 2020-04-23 21:16
@tm-89 
Thanks for the log file. In the log file there is the following which is the reason why it is failing:
```
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
* Closing connection 2
```
Please can you read the following: 
https://github.com/abraunegg/onedrive/wiki/Debugging-SSL-TLS-Issues-when-the-client-stops-syncing-with-no-crash

Please review best course of actions for yourself, and how to debug your SSL/TLS problem.

**Comment by tm-89** [comment] 2020-04-23 21:20
> @tm-89
> Thanks for the log file. In the log file there is the following which is the reason why it is failing:
> 
> ```
> * OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
> * Closing connection 2
> ```
> 
> Please can you read the following:
> https://github.com/abraunegg/onedrive/wiki/Debugging-SSL-TLS-Issues-when-the-client-stops-syncing-with-no-crash
> 
> Please review best course of actions for yourself, and how to debug your SSL/TLS problem.

Thank you. Would it be possible to make the client show that error? It is/was really annoying that the client seemingly just stopped without any error.

**Comment by abraunegg** [comment] 2020-04-23 21:31
@tm-89 
> Thank you. Would it be possible to make the client show that error? It is/was really annoying that the client seemingly just stopped without any error.

Unfortunately this is not possible (I have tried in the past) - as Curl / OpenSSL just silently drops / crashes with zero return information. To fix this - Curl / OpenSSL team need to fix their code to handle such situations better.

**Comment by abraunegg** [comment] 2020-04-25 00:47
Closing issue as not an issue with this client. Most likely cause is user version of Curl or OpenSSL.

**Closed by abraunegg** 2020-04-25 00:47 UTC
Labels: Local Environment Issue, Not a bug
