### ISSUE TITLE
I want to set onedrive to always monitor, but it fails.

### ISSUE THREAD

**Issue by yuusakuri** [abraunegg/onedrive#1199] opened 2020-12-24 22:10 UTC
# environment
Ubuntu 20.04 (wsl2)

run:
```
onedrive --version
```
result:
```
onedrive v2.4.8-11-g62a2b4f
```

# problems
## Option 1: OneDrive service running as root user via init.d
run:
```
 chkconfig onedrive on
```
result:
```
chkconfig: command not found
```

run:
```
service onedrive start
```
result:
```
onedrive: unrecognized service
```

## Option 2: OneDrive service running as root user via systemd (Arch, Ubuntu, Debian, OpenSuSE, Fedora)
run:
```
systemctl --user enable onedrive
```
result:
```

```
run:
```
systemctl --user start onedrive
```
result:
```
Failed to connect to bus: No such file or directory
```

# my install bash script for onedrive
```bash
    # Install dependencies
    sudo apt install -y build-essential
    sudo apt install -y libcurl4-openssl-dev
    sudo apt install -y libsqlite3-dev
    sudo apt install -y pkg-config
    sudo apt install -y git
    sudo apt install -y curl
    curl -fsS https://dlang.org/install.sh | bash -s dmd
    source "$(find ~/dlang -maxdepth 2 -mindepth 2 -name 'activate')"
    # Install OneDrive
    mkdir -p ~/apps
    cd ~/apps
    if [ ! -d "onedrive" ]; then
        git clone https://github.com/abraunegg/onedrive.git
    fi
    cd onedrive
    ./configure
    make clean
    make
    sudo make install
    deactivate
    # Configure OneDrive
    mkdir -p ~/.config/onedrive
    cp ./config ~/.config/onedrive/config
    mkdir -p ~/OneDrive
    systemctl --user enable onedrive
    systemctl --user start onedrive
    onedrive
```

**Comment by abraunegg** [comment] 2020-12-25 02:34
@yuusakuri 
Closing issue for the following reasons:
1. Not following the correct support procedure
2. Not using the bug report template

Additionally, your systemd issue is related to wsl2, which does not support systemd. Refer to: https://github.com/microsoft/WSL/issues/4202 

This is not a bug or issue with this client.

**Closed by abraunegg** 2020-12-25 02:34 UTC
