### ISSUE TITLE
Can't sync more than one SharePoint library

### ISSUE THREAD

**Issue by ranyc2000** [abraunegg/onedrive#917] opened 2020-05-12 00:49 UTC
**Note:** Before submitting a bug report, please ensure you are running the latest 'onedrive' client as built from 'master' and by using the latest available DMD compiler. Refer to the readme on building the client for your system.

onedrive v2.3.13-1build2 - installed from repo on Ubuntu 20.04

### Bug Report Details ###
**Describe the bug**

Followed abraunegg Office365.md instructions and was able to sync one SharePoint library. However, for this library, named 'XYZ', it dumps all the files directly into the sync_dir, without creating an XYZ directory under sync_dir.

Also, I see only one option for drive_id

So, there are two issues:

1. I see no way to separate the SharePoint Library files (XYZ) from the general OneDrive folder. 
2. I see no way to sync more than one SharePoint library (say XYZ and ABC) (i.e., to use two or more drive_ids, and having separate folders for XYZ and ABC).

**Application and Operating System Details:**
*   OS: Output of `uname -a` & provide your OS & version (CentOS 6.x, Ubuntu 18.x etc)

Linux [Machine Name] 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*   Are you using a headless system (no gui) or with a gui installed?
Running headless but GUI is installed

*   OneDrive Account Type
Office 365 (OneDrive for Business and SharePoint)

*   DMD or LDC compiler version `dmd --version` or `ldmd2 --version`
None - using precompiled from Ubuntu 20.04 repo

*   Application configuration: Output of `onedrive --display-config`

onedrive version                    = v2.3.13-1build2
Config path                         = /home/ron/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /bigpool/OneDrive
Config option 'skip_dir'            =
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'drive_id'            = [REDACTED]
Config option 'sync_root_files'     = false
Selective sync configured           = false

*   Curl Version: Output of `curl --version`
Not installed 

**Note:** Please generate a full debug log as per [https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support](https://github.com/abraunegg/onedrive/wiki/Generate-debug-log-for-support) and email to support@mynas.com.au

Not applicable - not a 'crash'

**To Reproduce**
Steps to reproduce the behavior if not causing an application crash:
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

Follow the instructions to sync a first SharePoint library and note that all the files go into the root of the sync_dir

Try to do with a second SharePoint library, and not that you get a different drive_id with noplace to put it becuase there is already a drive_id for the first library.

If issue is replicated by a specific 'file' or 'path' please archive the file and path tree & email to support@mynas.com.au 

**Complete Verbose Log Output**
A clear and full log of the problem when running the application in the following manner (ie, not in monitor mode):
```bash
onedrive --synchronize --verbose <any of your other needed options>
```

N/A

Run the application in a separate terminal window or SSH session and provide the entire application output including the error & crash. When posing the logs, Please format log output to make it easier to read. See [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for more details.

Application Log Output:
```bash
Verbose console log output goes here
```

N/A

**Screenshots**

N/A

**Additional context**

### Bug Report Checklist ###
*   [] Detailed description
*   [] Reproduction steps (if applicable)
*   [] Verbose Log Output

**Comment by abraunegg** [comment] 2020-05-12 00:58
@ranyc2000 
There are many issues with your initial post above.
1. You are using Ubuntu and using old Ubuntu packages. **Dont do this.** Build from source. Ubuntu packages are broken.
2. This is not a bug. You can only use 1 x Sharepoint Library per application configuration because of the way that Sharepoint works.

To solve this you need to:
1. Have multiple application configurations that are for each SharePoint Library
2. Have this 'unique' configuration store the data in it's right 'sync_dir' location eg: 'sync_dir = ~/OneDrive/SharedLibraries/<ABC>/

Refer to https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#using-multiple-onedrive-accounts for more details.

**Comment by ranyc2000** [comment] 2020-05-12 01:14
Yup, that all makes sense.

**Comment by abraunegg** [comment] 2020-05-12 22:23
@ranyc2000 
Before closing this case - can you please clarify - 'Yup, that all makes sense' .. you have the details now on how to solve this or you need further assistance ... ??

**Comment by ranyc2000** [comment] 2020-05-12 23:27
Thanks, it will take me a couple of days to see what happens with a couple of large SharePoint libraries, but what you said makes sense. Well verify and post.

**Comment by ranyc2000** [comment] 2020-05-14 19:43
So far so good. Compiled the application from source as documented. Created separate config directories, one each for personal OneDrive, as well as for each of several SharePoint libraries, with separate authorizations and separate O365 drive_ids for the respective SharePoint libraries. It is still initially syncing, but it appears to be working.

**Comment by abraunegg** [comment] 2020-05-15 00:19
@ranyc2000 
Sounds like you have things now setup correctly. 

As you are using Ubuntu, and there is no package for Ubuntu due to the absurdity around how Ubuntu accepts 'application updates',  be sure to watch the application releases to ensure your application is kept up-to-date. Release cycle is typically at the moment every 1-2 months for a new release.

**Comment by abraunegg** [comment] 2020-05-16 23:06
Closing issue as answer provided and working as expected

**Closed by abraunegg** 2020-05-16 23:06 UTC
Labels: Answer Provided, Invalid - Old Code Version, Not a bug, Question
